src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_Ultimate_Parent_Account_ID_Formula__c</fullName>
        <formula>IF(ISBLANK(FC_Ultimate_Parent_Account__c),  CASESAFEID(Id), CASESAFEID(FC_Ultimate_Parent_Account__c))</formula>
        <label>(FC) Ultimate Parent Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account_Synced__c</fullName>
        <formula>(ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c == Account__c) ||
(!ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c ==  Account__r.FC_Ultimate_Parent_Account__c)</formula>
        <label>(FC) Ultimate Parent Account Synced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Metrostudy_Account_Product_Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_MapgUltimateParentAccountSyncBatch.cls
public without sharing class FC_MapgUltimateParentAccountSyncBatch implements Database.Batchable<sObject> {

    public FC_MapgUltimateParentAccountSyncBatch() {
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
                select Id, FC_Ultimate_Parent_Account__c, Account__r.FC_Ultimate_Parent_Account_ID_Formula__c
                from MetroclientAccountProductGeography__c
                where FC_Ultimate_Parent_Account_Synced__c = false
        ]);
    }

    public void execute(Database.BatchableContext context, List<MetroclientAccountProductGeography__c> scope) {
        if (scope != null && !scope.isEmpty()) {
            for (MetroclientAccountProductGeography__c record : scope) {
                record.FC_Ultimate_Parent_Account__c = record.Account__r.FC_Ultimate_Parent_Account_ID_Formula__c;
            }
            update scope;
        }
    }

    public void finish(Database.BatchableContext context) {
        FC_UpdateUltimateParentMapgStatusBatch batchable = new FC_UpdateUltimateParentMapgStatusBatch();
        Database.executeBatch(batchable);
    }

}