src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_MAPG_Status__c</fullName>
        <label>(FC) MAPG Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date the subscription ends  (SubscriptionEndDate).  This value is blank (NULL) for evergreen subscriptions.</description>
        <inlineHelpText>The date access to the product expires and can no longer be accessed.  This field is blank when a subscription is evergreen.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account_Synced__c</fullName>
        <formula>(ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c == Account__c) ||
(!ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c ==  Account__r.FC_Ultimate_Parent_Account__c)</formula>
        <label>(FC) Ultimate Parent Account Synced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Metrostudy_Account_Product_Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date that the subscription starts (SubscriptionStartDate)</description>
        <inlineHelpText>The date that the access to the product starts.  This date is determined by the subscription or amendment start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status can be Active, Future, Expired, On Hold</description>
        <formula>IF(Deleted__c  = True, &apos;Expired&apos;, 
  IF(EndDate__c &lt;   TODAY(), &apos;Expired&apos;, 
    IF(OnHold__c = True, &apos;On Hold&apos;,
    IF(StartDate__c &gt;  TODAY() , &apos;Future&apos;,

&apos;Active&apos;
)
)
)
)</formula>
        <inlineHelpText>Active, Future, Expired, or On Hold</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestUpdateUltimateMapgStatusBatch.cls
@isTest
private class FC_TestUpdateUltimateMapgStatusBatch {

    @isTest
    private static void testBatchableCurrent() {

        MetroclientAccountProductGeography__c testMetroclientAccountProductGeography = [
                select Id, Account__c,
                        FC_Ultimate_Parent_Account__c, FC_Ultimate_Parent_Account_Synced__c, Status__c
                from
                        MetroclientAccountProductGeography__c
                where Name = 'MAPG-1'
                limit 1
        ];
        System.assertEquals(true, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account_Synced__c);
        System.assertEquals(testMetroclientAccountProductGeography.Account__c, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account__c);
        System.assertEquals('Active', testMetroclientAccountProductGeography.Status__c);

        Account testAccount = [select Id, ParentId, FC_MAPG_Status__c from Account where Name = 'Test Account' limit 1];
        System.assertEquals(null, testAccount.ParentId);
        System.assertEquals(null, testAccount.FC_MAPG_Status__c);

        Test.startTest();
        FC_UpdateUltimateParentMapgStatusBatch batchable = new FC_UpdateUltimateParentMapgStatusBatch();
        Database.executeBatch(batchable);
        Test.stopTest();

        testAccount = [select Id, ParentId, FC_MAPG_Status__c from Account where Name = 'Test Account' limit 1];
        System.assertEquals('Current', testAccount.FC_MAPG_Status__c);

    }


    @isTest
    private static void testBatchableFuture() {

        MetroclientAccountProductGeography__c testMetroclientAccountProductGeography = [
                select Id, Account__c,
                        FC_Ultimate_Parent_Account__c, FC_Ultimate_Parent_Account_Synced__c, Status__c
                from
                        MetroclientAccountProductGeography__c
                where Name = 'MAPG-2'
                limit 1
        ];
        System.assertEquals(true, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account_Synced__c);
        System.assertEquals(testMetroclientAccountProductGeography.Account__c, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account__c);
        System.assertEquals('Future', testMetroclientAccountProductGeography.Status__c);

        Account testAccount = [select Id, ParentId, FC_MAPG_Status__c from Account where Name = 'Test Account' limit 1];
        System.assertEquals(null, testAccount.ParentId);
        System.assertEquals(null, testAccount.FC_MAPG_Status__c);

        delete [select Id from MetroclientAccountProductGeography__c where Name = 'MAPG-1'];

        Test.startTest();
        FC_UpdateUltimateParentMapgStatusBatch batchable = new FC_UpdateUltimateParentMapgStatusBatch();
        Database.executeBatch(batchable);
        Test.stopTest();

        testAccount = [select Id, ParentId, FC_MAPG_Status__c from Account where Name = 'Test Account' limit 1];
        System.assertEquals('Future', testAccount.FC_MAPG_Status__c);

    }

    @testSetup
    private static void setup() {
        Account testAccount = new Account(Name = 'Test Account', BillingPostalCode = '12345');
        insert testAccount;

        MetroclientAccountProductGeography__c[] testMetroclientAccountProductGeographies = new MetroclientAccountProductGeography__c[]{
                new MetroclientAccountProductGeography__c(Name = 'MAPG-1', Account__c = testAccount.Id,
                        FC_Ultimate_Parent_Account__c = testAccount.Id, StartDate__c = Date.today() - 30, EndDate__c = Date.today() + 30),
                new MetroclientAccountProductGeography__c(Name = 'MAPG-2', Account__c = testAccount.Id,
                        FC_Ultimate_Parent_Account__c = testAccount.Id, StartDate__c = Date.today() + 30, EndDate__c = Date.today() + 60)
        };
        insert testMetroclientAccountProductGeographies;
    }

}