src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UltimateParentAccountId__c</fullName>
        <formula>if( CONTAINS( ParentId , &quot;0&quot;), 
  if( CONTAINS( Parent.ParentId , &quot;0&quot;), 
    if( CONTAINS( Parent.Parent.ParentId , &quot;0&quot;),
      if( CONTAINS( Parent.Parent.Parent.ParentId , &quot;0&quot;),
        &quot;MAXIMUM_ALLOWABLE_HIERARCHY_DEPTH_EXCEEDED&quot; ,
      Parent.Parent.Parent.Id ),
    Parent.Parent.Id ), 
    Parent.Id ), 
Id
)</formula>
        <label>Ultimate Parent Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box makes the contact a Metrostudy User.  This box must be checked in order for the contact to be able to access their products from Metrostudy Central.</inlineHelpText>
        <label>Metrostudy User?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Subscription is no longer active and product cannot be accessed. Record exists for reference only.</description>
        <inlineHelpText>When checked, product cannot be accessed. Record exists for reference only.</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date the subscription ends  (SubscriptionEndDate).  This value is blank (NULL) for evergreen subscriptions.</description>
        <inlineHelpText>The date access to the product expires and can no longer be accessed.  This field is blank when a subscription is evergreen.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MetroclientContactProvisioningByAccount.cls
public class MetroclientContactProvisioningByAccount{

    private final Account acct;
    
    // The extension constructor initializes the private member variable acct by using the getRecord method from the standard controller.
    public MetroclientContactProvisioningByAccount(ApexPages.StandardController stdController) {
        this.acct = (Account)stdController.getRecord();
    }
    
    public Boolean getRenderIframe() {
        Boolean metrostudyUserExists = getMetrostudyUserExists();
        Boolean invalidHierarchyDepth = getInvalidHierarchyDepth();
        Boolean validProductsExist = getValidProductsExist();
        
        return (metrostudyUserExists && !invalidHierarchyDepth && validProductsExist);
    }

    public Boolean getMetrostudyUserExists() {
        Boolean metrostudyUserExists = false;
        
        Account account = [SELECT Id, (SELECT Metrostudy_User__c FROM Contacts) FROM Account WHERE Id = :acct.Id];
        
        // Loop through all the contacts for the account
        for (Contact contact : account.Contacts)
        {
            if (contact.Metrostudy_User__c) {
                metrostudyUserExists = true;
                break;
            }
        }   
        return metrostudyUserExists;
    }
    
    public Boolean getInvalidHierarchyDepth() {
        return (acct.UltimateParentAccountId__c == 'MAXIMUM_ALLOWABLE_HIERARCHY_DEPTH_EXCEEDED');
    }     
    
    public Boolean getValidProductsExist() {        
        Map<Id,Account> accounts = new Map<Id,Account>([SELECT Id FROM Account WHERE UltimateParentAccountId__c = :acct.UltimateParentAccountId__c]);
        Set<Id> accountIdSet = accounts.keySet();
        
        List<MetroclientAccountProductGeography__c> accountProductGeographyList = [SELECT Id FROM MetroclientAccountProductGeography__c WHERE Account__r.Id IN :accountIdSet AND Deleted__c = false AND (EndDate__c = NULL OR EndDate__c > :system.now().date())];     //
                
        return (accountProductGeographyList.size() > 0) ;
    }    
}