src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_Ultimate_Parent_Account_ID_Formula__c</fullName>
        <formula>IF(ISBLANK(FC_Ultimate_Parent_Account__c),  CASESAFEID(Id), CASESAFEID(FC_Ultimate_Parent_Account__c))</formula>
        <label>(FC) Ultimate Parent Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <description>Zuora Subscription Charge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Charge Number (Zuora)</inlineHelpText>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>Metrostudy_Account_Product_Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Metrostudy_Account_Product_Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Term_Type__c</fullName>
        <label>Subscription Term Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__TermSettingType__c</fullName>
        <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
        <label>Term Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_MetroclientAccountProductGeoHandler.cls
global without sharing class FC_MetroclientAccountProductGeoHandler extends fcf.TriggerAdapter {

    Map<String, Zuora__SubscriptionProductCharge__c> chargeLookupMap = new Map<String, Zuora__SubscriptionProductCharge__c>();
    Map<ID, Account> accountLookupMap = new Map<ID, Account>();

    global override void bulkBefore() {
        if (Trigger.isInsert || Trigger.isUpdate) {
            Set<String> chargeNumbersToLookup = new Set<String>();
            Set<ID> accountIdsToLookup = new Set<ID>();
            for (SObject so : Trigger.new) {
                MetroclientAccountProductGeography__c metroclientAccountProductGeographyRecord =
                        (MetroclientAccountProductGeography__c) so;
                if (String.isNotBlank(metroclientAccountProductGeographyRecord.ChargeNumber__c)) {
                    chargeNumbersToLookup.add(metroclientAccountProductGeographyRecord.ChargeNumber__c);
                }
                if (metroclientAccountProductGeographyRecord.Account__c != null) {
                    accountIdsToLookup.add(metroclientAccountProductGeographyRecord.Account__c);
                }
            }
            if (!chargeNumbersToLookup.isEmpty()) {
                chargeLookupMap.putAll(FC_SubscriptionProductChargeCache.findByChargeNumbers(chargeNumbersToLookup));
            }
            if (!accountIdsToLookup.isEmpty()) {
                accountLookupMap.putAll(FC_AccountCache.findByIds(accountIdsToLookup));
            }
        }
    }

    global override void beforeInsert(SObject so) {
        MetroclientAccountProductGeography__c newMetroclientAccountProductGeography =
                (MetroclientAccountProductGeography__c) so;
        populateFields(newMetroclientAccountProductGeography);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        MetroclientAccountProductGeography__c newMetroclientAccountProductGeography =
                (MetroclientAccountProductGeography__c) so;
        populateFields(newMetroclientAccountProductGeography);
    }

    private void populateFields(MetroclientAccountProductGeography__c metroclientAccountProductGeographyRecord) {
        metroclientAccountProductGeographyRecord.Charge__c = null;
        if (String.isNotBlank(metroclientAccountProductGeographyRecord.ChargeNumber__c)) {
            if (chargeLookupMap.containsKey(metroclientAccountProductGeographyRecord.ChargeNumber__c)) {
                metroclientAccountProductGeographyRecord.Charge__c = chargeLookupMap.get(metroclientAccountProductGeographyRecord.ChargeNumber__c).Id;
                metroclientAccountProductGeographyRecord.Subscription_Term_Type__c = chargeLookupMap.get(metroclientAccountProductGeographyRecord.ChargeNumber__c).Zuora__Subscription__r.Zuora__TermSettingType__c;
            }
        }

        Account accountRecord = accountLookupMap.get(metroclientAccountProductGeographyRecord.Account__c);
        if (accountRecord != null) {
            if (String.isNotBlank(accountRecord.FC_Ultimate_Parent_Account_ID_Formula__c)) {
                try {
                    metroclientAccountProductGeographyRecord.FC_Ultimate_Parent_Account__c = Id.valueOf(accountRecord.FC_Ultimate_Parent_Account_ID_Formula__c);
                } catch (Exception e) {
                    // Do nothing.
                }
            }
        }
    }

}