src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_Opportunity_Last_Sent_To_Zuora__c</fullName>
        <label>(FC) Opportunity Last Sent To Zuora</label>
        <summarizedField>Opportunity.FC_Last_Sent_To_Zuora__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SBQQ__SubscriptionConsumptionSchedule__c.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>SBQQ__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Consumption Schedules</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Consumption Schedule</label>
    <nameField>
        <label>Subscription Consumption Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Consumption Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_MetroclientAccountProvisionBatchable.cls
public class FC_MetroclientAccountProvisionBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts,
        Database.Stateful {

    public Id parentTransactionId = null;

    private Set<Id> accountIdsToProvision;

    private Date lastSentToZuoraStartDate;
    private Date lastSentToZuoraEndDate;

    @testVisible
    private static Integer insertedRecordCount = 0;

    @testVisible
    private static Integer updatedRecordCount = 0;

    private static final String SOQL_BASE = 'select Id, ' +
            '(select Id, Zuora__External_Id__c from Zuora__Subscriptions__r) ' +
            'from Account ';

    public FC_MetroclientAccountProvisionBatchable() {
        this(null);
    }

    public FC_MetroclientAccountProvisionBatchable(Set<Id> accountIdsToProvision) {
        this.accountIdsToProvision = accountIdsToProvision;
    }

    public FC_MetroclientAccountProvisionBatchable(Date lastSentToZuoraStartDate, Date lastSentToZuoraEndDate) {
        this.lastSentToZuoraStartDate = lastSentToZuoraStartDate;
        this.lastSentToZuoraEndDate = lastSentToZuoraEndDate;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        String soql = SOQL_BASE;
        if (this.lastSentToZuoraStartDate != null) {
            soql += 'where FC_Opportunity_Last_Sent_To_Zuora__c >= :lastSentToZuoraStartDate ';
            if (this.lastSentToZuoraEndDate != null) {
                soql += 'and FC_Opportunity_Last_Sent_To_Zuora__c <= :lastSentToZuoraEndDate';
            }
        } else if (this.accountIdsToProvision != null && !this.accountIdsToProvision.isEmpty()) {
            soql += 'where Id in :accountIdsToProvision';
        } else {
            soql += 'where FC_Opportunity_Last_Sent_To_Zuora__c >= LAST_N_DAYS:2';
        }

        System.debug('******* SOQL: ' + soql);
        return Database.getQueryLocator(soql);
    }

    public void execute(Database.BatchableContext context, List<Account> scope) {
        if (scope != null && !scope.isEmpty()) {

            Map<Id, Account> accountsInScope = new Map<Id, Account>(scope);

            FC_MetroclientAccountProvisioningUtil.buildProvisioningRecords(
                    new List<Id>(accountsInScope.keySet()), parentTransactionId);

            insertedRecordCount += FC_MetroclientAccountProvisioningUtil.getProvisioningRecordsToInsert().size();
            updatedRecordCount += FC_MetroclientAccountProvisioningUtil.getProvisioningRecordsToUpdate().size();
            FC_MetroclientAccountProvisioningUtil.commitProvisioningRecords();

        }
    }

    public void finish(Database.BatchableContext context) {
    }

}