src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_MAPG_Status__c</fullName>
        <label>(FC) MAPG Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FC_UpdateDescendantAcctMapgStatusBatch.cls
public without sharing class FC_UpdateDescendantAcctMapgStatusBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
                select Id, FC_Ultimate_Parent_Account__r.FC_MAPG_Status__c
                from Account
                where ParentId != null
        ]);
    }

    public void execute(Database.BatchableContext context, List<Account> scope) {
        if (scope != null && !scope.isEmpty()) {
            for (Account record : scope) {
                record.FC_MAPG_Status__c = record.FC_Ultimate_Parent_Account__r.FC_MAPG_Status__c;
            }
            update scope;
        }
    }

    public void finish(Database.BatchableContext context) {
    }

}