src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Contact.Account.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Billing Contact)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Media_Account_Type__c</fullName>
        <label>Media Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ADVERTISER</fullName>
                    <default>true</default>
                    <label>ADVERTISER</label>
                </value>
                <value>
                    <fullName>AGENCY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AB2__AB_Contact_Type_new__c</fullName>
        <description>What AdBook Contact Types can this Contact be used for?</description>
        <inlineHelpText>What AdBook Contact Types can this Contact be used for?</inlineHelpText>
        <label>AB Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Materials</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Media_Account_Type__c</fullName>
        <formula>TEXT(Account.Media_Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Account Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AB2__ABBillingContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AB Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (AB Billing Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB2__AB_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AB Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AB2__ABAccountType__c</field>
                <operation>equals</operation>
                <value>Agency</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HW Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (HW Agency Name)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Billing Contact_2)</relationshipLabel>
        <relationshipName>Opportunities5</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Media</fullName>
        <active>true</active>
        <businessProcess>Media</businessProcess>
        <label>HW_Media</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>AB2__ABEndDate__c</fullName>
        <inlineHelpText>Enter the End Date of the drop here.</inlineHelpText>
        <label>AB End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AB2__ABStartDate__c</fullName>
        <inlineHelpText>Enter the Start Date of the drop here.</inlineHelpText>
        <label>AB Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HW_Line_Item_End_Date__c</fullName>
        <label>HW Line Item End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HW_Line_Item_Start_Date__c</fullName>
        <label>HW Line Item Start Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src/classes/AdBookIntegration.cls
public class AdBookIntegration {
        
    // Set the AdBook [AB Contact Type] based on the parent Accounts [Media Account Type]
    public void handleContactTrigger(List<Contact> triggerNew) {
        for(Contact c : triggerNew) {
            if(c.Media_Account_Type__c == 'ADVERTISER') {
                appendContactType(c, 'Client');
            } else if(c.Media_Account_Type__c == 'Agency') {
                appendContactType(c, 'Agency');
            }
        }
    }
    
    // Called from FC_OpportunityTrigger on insert/update of an Opportunity
    public static void handleOpportunityTriggerPopulateFields(Opportunity oldOpportunityRecord, Opportunity newOpportunityRecord){
        //System.debug('handleOpportunityTriggerPopulateFields() ' + newOpportunityRecord);
        
        // Copy the local Billing Contact custom field to the AdBook Billing Contact Id
        if(oldOpportunityRecord == null || oldOpportunityRecord.Billing_Contact__c != newOpportunityRecord.Billing_Contact__c) {
            newOpportunityRecord.AB2__ABBillingContact__c = newOpportunityRecord.Billing_Contact__c;
        }
        
        // Copy the Double Click custom field to the AdBook Agency Name
        if(oldOpportunityRecord == null || oldOpportunityRecord.Agency_Name__c != newOpportunityRecord.Agency_Name__c) {
            // The field is a Lookup(Account), so it doesn't need to be converted to the Account.Name
            newOpportunityRecord.AB2__AB_Agency__c = newOpportunityRecord.Agency_Name__c;
        }
    }
    
    public static void handleOpportunityLineItemTriggerPopulateFields(OpportunityLineItem opportunityLineItemRecord) {
        // Create DateTimes in the current users TimeZone at midnight so that they appear to be on the same Date in the UI.
        // Note, if there are users in various timezones they will naturally see different values.
        
        // Copy the value from the AB2__ABStartDate__c (Date) to HW_Line_Item_Start_Date__c (Date/Time)
        // Allow for the current users timezone
        if(opportunityLineItemRecord.AB2__ABStartDate__c != null) {
            opportunityLineItemRecord.HW_Line_Item_Start_Date__c = 
                DateTime.newInstance(opportunityLineItemRecord.AB2__ABStartDate__c.year(), 
                                     opportunityLineItemRecord.AB2__ABStartDate__c.month(), 
                                     opportunityLineItemRecord.AB2__ABStartDate__c.day(),
                                     0,0,0);
        }
        
        // Copy the value from the AB2__ABEndDate__c (Date) to HW_Line_Item_End_Date__c (Date/Time)
        if(opportunityLineItemRecord.AB2__ABEndDate__c != null) {
            opportunityLineItemRecord.HW_Line_Item_End_Date__c = 
                DateTime.newInstance(opportunityLineItemRecord.AB2__ABEndDate__c.year(), 
                                     opportunityLineItemRecord.AB2__ABEndDate__c.month(), 
                                     opportunityLineItemRecord.AB2__ABEndDate__c.day(),
                                     0,0,0);
        }
    }
    
    /**
     * Called when the refresh from AdBook process is completed.
     * Check for changes from AdBook and update mapped fields.
     */
    @future
    public static void updateOpportunityDetails(Id oppId) {
        updateOpportunityDetailsSync(oppId);
    }
        
    /**
     * Called when the refresh from AdBook process is completed.
     * Check for changes from AdBook and update mapped fields.
     */
    public static void updateOpportunityDetailsSync(Id oppId) {
        List<Opportunity> opps = [Select Id, AB2__ABBillingContact__c, Billing_Contact__c, AB2__AB_Agency__c, Agency_Name__c from Opportunity where Id = :oppId];
        if(opps.isEmpty()) {
            System.debug(LoggingLevel.Error, 'Unable to find Opportunity with ID: ' + oppId);
            return;
        }
        Opportunity opp = opps[0];
        
        boolean updatedRequired = false;
        if(opp.Agency_Name__c != opp.AB2__AB_Agency__c) {
            opp.Agency_Name__c = opp.AB2__AB_Agency__c;
            updatedRequired = true;
        }
        
        if(opp.Billing_Contact__c != opp.AB2__ABBillingContact__c) {
            opp.Billing_Contact__c = opp.AB2__ABBillingContact__c;
            updatedRequired = true;
        }
        
        if(updatedRequired) {
            update opp;
        }
    }
    
    private void appendContactType(Contact c, string typeToAppend) {
        if(c == null) { return; }
        
        if(string.isBlank(c.AB2__AB_Contact_Type_new__c)) {
            c.AB2__AB_Contact_Type_new__c = typeToAppend;    
        } else if (c.AB2__AB_Contact_Type_new__c.contains(typeToAppend)) {
            //Noop - already present
        } else {
            // Merge
            c.AB2__AB_Contact_Type_new__c += ';' + typeToAppend;
        }
        
    }
}