src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Has_Active_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Active Subscription?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>FC_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Subscription_Number__c</fullName>
        <externalId>true</externalId>
        <label>(FC) Subscription Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestContractHandler.cls
@isTest
private class FC_TestContractHandler {

    @isTest
    private static void testInsert() {

        Account testAccount = [select Id from Account where Name = 'Test Account' limit 1];

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_ContractHandler'
        });

        Test.startTest();

        Contract testContract = new Contract(AccountId = testAccount.Id, FC_Subscription_Number__c = 'S-2',
                FC_Price_Book__c = Test.getStandardPricebookId());
        insert testContract;

        Test.stopTest();

        testContract = [
                select Id, AccountId, FC_Subscription_Number__c, FC_Subscription__c, FC_Subscription__r.Name,
                        FC_Price_Book__c
                from Contract
                where FC_Subscription_Number__c = 'S-2'
                limit 1
        ];

        System.assertNotEquals(null, testContract.FC_Subscription__c);
        System.assertEquals('S-2', testContract.FC_Subscription__r.Name);

    }

    @isTest
    private static void testUpdate() {

        Contract testContract = [
                select Id, AccountId, FC_Subscription_Number__c, FC_Subscription__c, FC_Subscription__r.Name,
                        FC_Price_Book__c
                from Contract
                where FC_Subscription_Number__c = 'S-1'
                limit 1
        ];

        System.assertEquals(null, testContract.FC_Subscription__c);
        System.assertEquals(null, testContract.FC_Subscription__r.Name);

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_ContractHandler'
        });

        Test.startTest();

        update testContract;

        Test.stopTest();

        testContract = [
                select Id, AccountId, FC_Subscription_Number__c, FC_Subscription__c, FC_Subscription__r.Name,
                        FC_Price_Book__c
                from Contract
                where FC_Subscription_Number__c = 'S-1'
                limit 1
        ];

        System.assertNotEquals(null, testContract.FC_Subscription__c);
        System.assertEquals('S-1', testContract.FC_Subscription__r.Name);

    }

    @testSetup
    private static void setup() {

        Account testAccount = new Account(Name = 'Test Account', Has_Active_Subscription__c = false, BillingPostalCode = '12345');
        insert testAccount;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account',
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;

        Zuora__Subscription__c[] testSubscriptions = new Zuora__Subscription__c[]{
                new Zuora__Subscription__c(Name = 'S-1',
                        Zuora__Account__c = testAccount.Id, Zuora__CustomerAccount__c = testCustomerAccount.Id,
                        Zuora__Status__c = 'Active', Zuora__SubscriptionNumber__c = 'S-1'),
                new Zuora__Subscription__c(Name = 'S-2',
                        Zuora__Account__c = testAccount.Id, Zuora__CustomerAccount__c = testCustomerAccount.Id,
                        Zuora__Status__c = 'Active', Zuora__SubscriptionNumber__c = 'S-2')
        };
        insert testSubscriptions;

        Contract testContract = new Contract(AccountId = testAccount.Id, FC_Subscription_Number__c = 'S-1',
                FC_Price_Book__c = Test.getStandardPricebookId());
        insert testContract;

    }

}