src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Active_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Active Subscription?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Term_Status__c</fullName>
        <formula>IF(Zuora__Status__c == &quot;Cancelled&quot; &amp;&amp; Zuora__CancelledDate__c &gt;= TODAY(),
            &quot;Active&quot;, /* future dated cancellations */
            IF(Zuora__Status__c == &quot;Cancelled&quot;,&quot;Cancelled&quot;,
            IF(FC_One_Time_Charge_Count__c &gt; 0 &amp;&amp; FC_Recurring_Charge_Count__c == 0,
            IF(Zuora__TermStartDate__c &gt; TODAY(), &quot;Future&quot;,
            IF(FC_Latest_Charge_Effective_Date__c &lt; TODAY(), &quot;Expired&quot;,
            &quot;Active&quot;
            )
            ),
            IF(FC_Recurring_Charge_Count__c &gt; 0,
            IF(Zuora__TermStartDate__c &gt; TODAY(),
            &quot;Future&quot;,
            IF(TEXT(Zuora__TermSettingType__c) == &quot;TERMED&quot;,
            IF(Zuora__TermEndDate__c &lt; TODAY(), &quot;Expired&quot;, &quot;Active&quot;),
            Zuora__Status__c
            )
            ),
            Zuora__Status__c
            )
            )
            )
)</formula>
        <label>Term Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_AccountHandler.cls
global without sharing class FC_AccountHandler extends fcf.TriggerAdapter {

    private Map<ID, Account> accountLookupMap = new Map<ID, Account>();
    private Map<ID, Integer> accountIdToActiveSubscriptionCountMap = new Map<ID, Integer>();

    global override void bulkBefore() {

        if (Trigger.isInsert || Trigger.isUpdate) {

            Set<ID> accountIdsToLookup = new Set<ID>();
            for (SObject so : Trigger.new) {
                Account accountRecord = (Account) so;
                if (accountRecord.ParentId != null) {
                    accountIdsToLookup.add(accountRecord.ParentId);
                }
            }
            accountLookupMap.putAll(FC_AccountCache.findByIds(accountIdsToLookup));
        }

        if (Trigger.isUpdate) {

            for (SObject so : Trigger.new) {
                accountIdToActiveSubscriptionCountMap.put(so.Id, 0);
            }
            for (AggregateResult ar : [
                    select Zuora__Account__c, count(Id) recordCount
                    from Zuora__Subscription__c
                    where Zuora__Account__c in :Trigger.newMap.keySet()
                    and Term_Status__c = 'Active'
                    group by Zuora__Account__c
            ]) {
                accountIdToActiveSubscriptionCountMap.put((ID) ar.get('Zuora__Account__c'),
                        (Integer) ar.get('recordCount'));
            }

        }
    }

    global override void beforeInsert(SObject so) {
        Account newAccountRecord = (Account) so;

        populateFields(newAccountRecord);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        Account newAccountRecord = (Account) so;

        populateFields(newAccountRecord);
    }

    private void populateFields(Account accountRecord) {
        Integer activeSubscriptionCount =
                accountIdToActiveSubscriptionCountMap.get(accountRecord.Id);
        accountRecord.Has_Active_Subscription__c =
                activeSubscriptionCount != null && activeSubscriptionCount > 0;

        ID ultimateParentId = null;
        if (accountRecord.ParentId != null) {
            ultimateParentId = accountRecord.ParentId;
            Account parentAccountRecord = accountLookupMap.get(accountRecord.ParentId);
            if (parentAccountRecord != null) {
                if (parentAccountRecord.ParentId != null) {
                    ultimateParentId = parentAccountRecord.ParentId;
                    if (parentAccountRecord.Parent.ParentId != null) {
                        ultimateParentId = parentAccountRecord.Parent.ParentId;
                        if (parentAccountRecord.Parent.Parent.ParentId != null) {
                            ultimateParentId = parentAccountRecord.Parent.Parent.ParentId;
                            if (parentAccountRecord.Parent.Parent.Parent.ParentId != null) {
                                ultimateParentId = parentAccountRecord.Parent.Parent.Parent.ParentId;
                                if (parentAccountRecord.Parent.Parent.Parent.Parent.ParentId != null) {
                                    ultimateParentId = parentAccountRecord.Parent.Parent.Parent.Parent.ParentId;
                                    if (parentAccountRecord.Parent.Parent.Parent.Parent.Parent.ParentId != null) {
                                        ultimateParentId = parentAccountRecord.Parent.Parent.Parent.Parent.Parent.ParentId;
                                    }
                                }
                            }
                        }

                    }
                }
            }
        }
        accountRecord.FC_Ultimate_Parent_Account__c = ultimateParentId;

    }

}