src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account_Synced__c</fullName>
        <formula>(ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c == Account__c) ||
(!ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c ==  Account__r.FC_Ultimate_Parent_Account__c)</formula>
        <label>(FC) Ultimate Parent Account Synced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Metrostudy_Account_Product_Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestMapgUltimateParentAcctSyncBatch.cls
@isTest
private class FC_TestMapgUltimateParentAcctSyncBatch {

    @isTest
    private static void testBatchable() {

        MetroclientAccountProductGeography__c testMetroclientAccountProductGeography = [
                select Id, Account__c,
                        FC_Ultimate_Parent_Account__c, FC_Ultimate_Parent_Account_Synced__c
                from
                        MetroclientAccountProductGeography__c
                where Name = 'MAPG-1'
                limit 1
        ];
        System.assertEquals(false, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account_Synced__c);
        System.assertEquals(null, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account__c);

        Test.startTest();
        FC_MapgUltimateParentAccountSyncBatch batchable = new FC_MapgUltimateParentAccountSyncBatch();
        Database.executeBatch(batchable);
        Test.stopTest();

        testMetroclientAccountProductGeography = [
                select Id, Account__c,
                        FC_Ultimate_Parent_Account__c, FC_Ultimate_Parent_Account_Synced__c
                from
                        MetroclientAccountProductGeography__c
                where Name = 'MAPG-1'
                limit 1
        ];
        System.assertEquals(true, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account_Synced__c);
        System.assertEquals(testMetroclientAccountProductGeography.Account__c, testMetroclientAccountProductGeography.FC_Ultimate_Parent_Account__c);

    }

    @testSetup
    private static void setup() {
        Account testAccount = new Account(Name = 'Test Account', BillingPostalCode = '12345');
        insert testAccount;

        MetroclientAccountProductGeography__c testMetroclientAccountProductGeography = new MetroclientAccountProductGeography__c(Name = 'MAPG-1', Account__c = testAccount.Id);
        insert testMetroclientAccountProductGeography;
    }
}