src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Override_Billing_Address_Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Billing Address Information</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FC_Charge_Monthly_Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Number__c</fullName>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Plan_Charge__c</fullName>
        <label>Rate Plan Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>(FC) Charge Monthly Revenues</relationshipLabel>
        <relationshipName>FC_Charge_Monthly_Revenues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>(FC) Charge Monthly Revenue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Charge Monthly Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Charge Monthly Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionChargeNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestFcChargeMonthlyRevenueHandler.cls
@IsTest
private class FC_TestFcChargeMonthlyRevenueHandler {

    @IsTest
    private static void testInsert() {

        fcf.TriggerHandlerSettings.enable('FC_FcChargeMonthlyRevenueHandler');
        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [
                select Id
                from Zuora__SubscriptionProductCharge__c
                where Zuora__ChargeNumber__c = 'SPC-1'
                limit 1
        ];

        Test.startTest();
        FC_Charge_Monthly_Revenue__c testChargeMonthlyRevenue = new FC_Charge_Monthly_Revenue__c(Charge_Number__c = 'SPC-1');
        insert testChargeMonthlyRevenue;
        Test.stopTest();

        System.assertEquals(testSubscriptionProductCharge.Id, [
                select Rate_Plan_Charge__c
                from FC_Charge_Monthly_Revenue__c
                where Id = :testChargeMonthlyRevenue.Id
        ].Rate_Plan_Charge__c);
    }

    @IsTest
    private static void testUpdate() {
        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [
                select Id
                from Zuora__SubscriptionProductCharge__c
                where Zuora__ChargeNumber__c = 'SPC-1'
                limit 1
        ];

        FC_Charge_Monthly_Revenue__c testChargeMonthlyRevenue = new FC_Charge_Monthly_Revenue__c(Charge_Number__c = 'SPC-1',
                Rate_Plan_Charge__c = testSubscriptionProductCharge.Id);
        insert testChargeMonthlyRevenue;


        fcf.TriggerHandlerSettings.enable('FC_FcChargeMonthlyRevenueHandler');
        Test.startTest();
        testChargeMonthlyRevenue.Charge_Number__c = 'SPC-1';
        update testChargeMonthlyRevenue;
        Test.stopTest();

        System.assertEquals(testSubscriptionProductCharge.Id, [
                select Rate_Plan_Charge__c
                from FC_Charge_Monthly_Revenue__c
                where Id = :testChargeMonthlyRevenue.Id
        ].Rate_Plan_Charge__c);
    }


    @TestSetup
    private static void setup() {
        Account testAccount = new Account(Name = 'Test Account', BillingPostalCode = '10069', Override_Billing_Address_Information__c = true);
        insert testAccount;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account',
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;

        Zuora__Subscription__c testSubscription = new Zuora__Subscription__c(Name = 'S-1',
                Zuora__Account__c = testAccount.Id, Zuora__CustomerAccount__c = testCustomerAccount.Id,
                Zuora__External_Id__c = 'S-1');
        insert testSubscription;

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = new Zuora__SubscriptionProductCharge__c(
                Name = 'SPC-1', Zuora__Account__c = testAccount.Id, Zuora__Subscription__c = testSubscription.Id,
                Zuora__ChargeNumber__c = 'SPC-1', Zuora__External_Id__c = 'SPC-1', Zuora__SubscriptionChargeNumber__c = 'SPC-1');
        insert testSubscriptionProductCharge;
    }

}