src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_MAPG_Status__c</fullName>
        <label>(FC) MAPG Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>FC_One_If_Active__c</fullName>
        <formula>IF(Status__c == &quot;Active&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) One If Active</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_One_If_Future__c</fullName>
        <formula>IF(Status__c == &quot;Future&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) One If Future</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account_Synced__c</fullName>
        <formula>(ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c == Account__c) ||
(!ISBLANK(Account__r.ParentId) &amp;&amp; FC_Ultimate_Parent_Account__c ==  Account__r.FC_Ultimate_Parent_Account__c)</formula>
        <label>(FC) Ultimate Parent Account Synced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Metrostudy_Account_Product_Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_UpdateUltimateParentMapgStatusBatch.cls
public without sharing class FC_UpdateUltimateParentMapgStatusBatch implements Database.Batchable<AggregateResult> {

    public FC_UpdateUltimateParentMapgStatusBatch() {
    }

    public Iterable<AggregateResult> start(Database.BatchableContext context) {
        return [
                select FC_Ultimate_Parent_Account__c, SUM(FC_One_If_Active__c) activeCount,
                        SUM(FC_One_If_Future__c) futureCount
                from MetroclientAccountProductGeography__c
                where FC_Ultimate_Parent_Account_Synced__c = true and FC_Ultimate_Parent_Account_Synced__c != null
                group by FC_Ultimate_Parent_Account__c
        ];
    }

    public void execute(Database.BatchableContext context, List<AggregateResult> scope) {
        System.debug('**** SCOPE: ' + scope);
        if (scope != null && !scope.isEmpty()) {
            Account[] accountsToUpdate = new List<Account>();
            for (AggregateResult ar : scope) {
                String mapgStatus = 'Past';
                if ((Decimal) ar.get('activeCount') > 0) {
                    mapgStatus = 'Current';
                } else if ((Decimal) ar.get('futureCount') > 0) {
                    mapgStatus = 'Future';
                }
                accountsToUpdate.add(new Account(Id = (ID) ar.get('FC_Ultimate_Parent_Account__c'),
                        FC_MAPG_Status__c = mapgStatus));
            }
            update accountsToUpdate;
        }
    }

    public void finish(Database.BatchableContext context) {
        FC_UpdateDescendantAcctMapgStatusBatch batchable = new FC_UpdateDescendantAcctMapgStatusBatch();
        Database.executeBatch(batchable);
    }

}