src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry_Category__c</fullName>
        <label>Industry Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry_Description__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment Owners and Managers</fullName>
                </value>
                <value>
                    <fullName>Builders and Developers</fullName>
                </value>
                <value>
                    <fullName>Building Product Manufacturers</fullName>
                </value>
                <value>
                    <fullName>Hanley Wood</fullName>
                </value>
                <value>
                    <fullName>Industry Associates</fullName>
                </value>
                <value>
                    <fullName>Lenders and Investors</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Code__c</fullName>
        <label>Industry Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry_Description__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ACCT</fullName>
                </value>
                <value>
                    <fullName>ADVR</fullName>
                </value>
                <value>
                    <fullName>APPL</fullName>
                </value>
                <value>
                    <fullName>APPR</fullName>
                </value>
                <value>
                    <fullName>APTM</fullName>
                </value>
                <value>
                    <fullName>APTO</fullName>
                </value>
                <value>
                    <fullName>ARCH</fullName>
                </value>
                <value>
                    <fullName>ASSOC</fullName>
                </value>
                <value>
                    <fullName>ATTY</fullName>
                </value>
                <value>
                    <fullName>BLDR</fullName>
                </value>
                <value>
                    <fullName>BPM</fullName>
                </value>
                <value>
                    <fullName>BROK</fullName>
                </value>
                <value>
                    <fullName>CABI</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>DEVC</fullName>
                </value>
                <value>
                    <fullName>DEVL</fullName>
                </value>
                <value>
                    <fullName>DOOR</fullName>
                </value>
                <value>
                    <fullName>ELEC</fullName>
                </value>
                <value>
                    <fullName>ENGR</fullName>
                </value>
                <value>
                    <fullName>FAUC</fullName>
                </value>
                <value>
                    <fullName>FLOOR</fullName>
                </value>
                <value>
                    <fullName>GOVT</fullName>
                </value>
                <value>
                    <fullName>HVAC</fullName>
                </value>
                <value>
                    <fullName>HW</fullName>
                </value>
                <value>
                    <fullName>INSUL</fullName>
                </value>
                <value>
                    <fullName>INSUR</fullName>
                </value>
                <value>
                    <fullName>INTD</fullName>
                </value>
                <value>
                    <fullName>INVB</fullName>
                </value>
                <value>
                    <fullName>LEND</fullName>
                </value>
                <value>
                    <fullName>LUMB</fullName>
                </value>
                <value>
                    <fullName>MISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Description__c</fullName>
        <label>Industry Description</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACCOUNTING FIRMS</fullName>
                </value>
                <value>
                    <fullName>ADVERTISING</fullName>
                </value>
                <value>
                    <fullName>APARTMENT MANAGER</fullName>
                </value>
                <value>
                    <fullName>APARTMENT OWNERS</fullName>
                </value>
                <value>
                    <fullName>APPLIANCE COMPANY</fullName>
                </value>
                <value>
                    <fullName>APPRAISER</fullName>
                </value>
                <value>
                    <fullName>ARCHITECT</fullName>
                </value>
                <value>
                    <fullName>ATTORNEY</fullName>
                </value>
                <value>
                    <fullName>BUILDING INDUSTRY ASSOCIATION AND COUNCIL</fullName>
                </value>
                <value>
                    <fullName>CABINETS</fullName>
                </value>
                <value>
                    <fullName>DEVELOPER-COMMERCIAL</fullName>
                </value>
                <value>
                    <fullName>DEVELOPER-RESIDENTIAL LAND</fullName>
                </value>
                <value>
                    <fullName>DOORS MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>ELECTRICAL</fullName>
                </value>
                <value>
                    <fullName>ENGINEER</fullName>
                </value>
                <value>
                    <fullName>FAUCET MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>FLOORING MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>GOVERNMENT/CITY/COUNTY</fullName>
                </value>
                <value>
                    <fullName>HANLEY WOOD</fullName>
                </value>
                <value>
                    <fullName>HEATING, VENILATION, AIR CONDITIONING</fullName>
                </value>
                <value>
                    <fullName>INSULATION</fullName>
                </value>
                <value>
                    <fullName>INSURANCE</fullName>
                </value>
                <value>
                    <fullName>INTERIOR DESIGNER</fullName>
                </value>
                <value>
                    <fullName>INVESTMENT BANKER (EQUITY)</fullName>
                </value>
                <value>
                    <fullName>LAND BROKER</fullName>
                </value>
                <value>
                    <fullName>LAND PLANNER</fullName>
                </value>
                <value>
                    <fullName>LENDER/BANK</fullName>
                </value>
                <value>
                    <fullName>LUMBER</fullName>
                </value>
                <value>
                    <fullName>MORTGAGE COMPANY</fullName>
                </value>
                <value>
                    <fullName>OTHER BUILDING PRODUCT MANUFACTURERS</fullName>
                </value>
                <value>
                    <fullName>OTHER INDUSTRY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used isn the Parent Account look up to restrict the lookup to Parent Accounts only</description>
        <inlineHelpText>This checkbox identifies this Account as a Parent Account</inlineHelpText>
        <label>Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strategic_Account_Owner__c</fullName>
        <description>10K Legacy Strategic Account Exec Sponsor</description>
        <inlineHelpText>Do not use - Legacy Strategic Account Exec Sponsor</inlineHelpText>
        <label>Legacy Strategic Account Exec Sponsor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>La Femina, Catherine</fullName>
                </value>
                <value>
                    <fullName>Macintosh, David</fullName>
                </value>
                <value>
                    <fullName>Norris, Wayne</fullName>
                </value>
                <value>
                    <fullName>Rassel, Phillip</fullName>
                </value>
                <value>
                    <fullName>Sage, Ben</fullName>
                </value>
                <value>
                    <fullName>Hunter, Brad</fullName>
                </value>
                <value>
                    <fullName>Brown, David</fullName>
                </value>
                <value>
                    <fullName>Ackley, Brooke Burns</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/StategicAccount.cls
public with sharing class StategicAccount {
    
    public static void PreProcess(Account[] accounts)
    {
        List<Account> parentUpdate = new List<Account>();
        List<Account> childrenUpdate = new List<Account>();
        
        //modified code (single query)
        
        Set<Id> parentIDs = new Set<Id>();
        for(Account thisAct : accounts)
        {
            if(thisAct.ParentId != null)
            {
                parentIDs.add(thisAct.ParentId);
            }
        }
        
        List<Account> parents = [SELECT Id, Strategic_Account_Owner__c 
                                    FROM Account WHERE id in :parentIDs];

        for(Account childAcc : accounts)
        {
            for(Account parentAcc : parents)
            {
                if(childAcc.parentId == parentAcc.Id)
                {
                    childAcc.Strategic_Account_Owner__c = parentAcc.Strategic_Account_Owner__c;
                }
            }
        }
        
        //original code
        
        /*for (Account a:accounts)
        {
            //Need to determine if this account has an associated Parent Account
            if (a.ParentId != null) //process as a child account
            {
                //Get the parent account's Stategic Account
                Account parent = [SELECT
                Account.Id,
                Account.Strategic_Account_Owner__c
                FROM Account 
                WHERE Account.Id = :a.ParentId];
                //Now that we have the parent account Stategic Account Owner, update this Account with the same information
                a.Strategic_Account_Owner__c = parent.Strategic_Account_Owner__c;
            }
        }*/
    }
    public static void PostProcess(Account[] accounts)
    {
        List<Account> childrenUpdate = new List<Account>();
        
        //modified code (single query)

        Set<Id> accIds = new Set<Id>();
        for(Account acc : accounts)
        {
            accIds.add(acc.id);
        }
        List<Account> children = [SELECT parentId, Id, Strategic_Account_Owner__c 
                                        FROM Account WHERE ParentId in :accIds];
        if(children.size() > 0)
        {
            for(Account child : children)
            {
                for(Account parent : accounts)
                {
                    if(child.ParentId == parent.id)
                    {
                        child.Strategic_Account_Owner__c = parent.Strategic_Account_Owner__c;
                        childrenUpdate.add(child);
                    }
                }
            }
        }
        if (childrenUpdate.size()>0)
        {
            update(childrenUpdate);
        }
        
        //original code
        /*for (Account a:accounts)
        {
            //This could be a parent account, see if there are any childern associated
            List<Account> children = [SELECT
            Account.Id,
            Account.Strategic_Account_Owner__c
            FROM Account
            WHERE Account.ParentId = :a.id];
            if (children.size() > 0)
            {
                //Update all of the childern accounts
                for (Account c:children)
                {
                    c.Strategic_Account_Owner__c = a.Strategic_Account_Owner__c;
                    childrenUpdate.add(c);
                }
            }
        }
        if (childrenUpdate.size()>0)
        {
            update(childrenUpdate);
        }*/
    }
    public class CustomException extends Exception {}
    
    public static testMethod void testAccount()
    {
        GoogleIntegrationHelper.disableAsync = true;
        //Create an Account as a Parent
        Account parent = new Account();
        parent.Name = 'Test Parent';
        parent.Strategic_Account_Owner__c = 'Local';
        parent.Industry_Code__c = 'MISC';
        parent.Industry_Category__c = 'Other';
        parent.Industry_Description__c = 'OTHER INDUSTRY';
        parent.BillingPostalCode = '12345';
        parent.Parent__c = true;
        insert(parent);
        List<Account> test = new List<Account>();
        test.add(parent);
        PreProcess(test);
        //Now create a child Account
        Account child = new Account();
        child.Name = 'Test Child';
        child.BillingPostalCode = '12345';
        child.Strategic_Account_Owner__c = 'Local';
        child.Industry_Code__c = 'MISC';
        child.Industry_Category__c = 'Other';
        child.Industry_Description__c = 'OTHER INDUSTRY';
        child.ParentId = parent.Id;
        test.add(child);
        PreProcess(test);
        insert(child);
        //Now change the parent Stategic_Account_Owner and update (Should test child change also)
        parent.Strategic_Account_Owner__c = 'Local';
        update(parent);
        PostProcess(test);
    }
}