src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_MAPG_Status__c</fullName>
        <label>(FC) MAPG Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status can be Active, Future, Expired, On Hold</description>
        <formula>IF(Deleted__c  = True, &apos;Expired&apos;, 
  IF(EndDate__c &lt;   TODAY(), &apos;Expired&apos;, 
    IF(OnHold__c = True, &apos;On Hold&apos;,
    IF(StartDate__c &gt;  TODAY() , &apos;Future&apos;,

&apos;Active&apos;
)
)
)
)</formula>
        <inlineHelpText>Active, Future, Expired, or On Hold</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_AccountUpdateBatchable.cls
global class FC_AccountUpdateBatchable implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('select Id from Account');
    }

    global void execute(Database.BatchableContext context, List<SObject> scope) {
        if (scope != null && !scope.isEmpty()) {

//            // Initialize maps
//            Map<ID, Integer> accountIdToTotalMapgCountMap = new Map<ID, Integer>();
//            Map<ID, Integer> accountIdToActiveMapgCountMap = new Map<ID, Integer>();
//            Map<ID, Integer> accountIdToExpiredMapgCountMap = new Map<ID, Integer>();
//            for (SObject record : scope) {
//                accountIdToTotalMapgCountMap.put(record.Id, 0);
//                accountIdToActiveMapgCountMap.put(record.Id, 0);
//                accountIdToExpiredMapgCountMap.put(record.Id, 0);
//            }
//
//            // Calculate totals
//            for (AggregateResult result : [select Account__c, count(Id) totalMapgCount
//                    from MetroclientAccountProductGeography__c where Account__c in :scope
//                    group by Account__c]) {
//                accountIdToTotalMapgCountMap.put((ID) result.get('Account__c'), (Integer) result.get('totalMapgCount'));
//            }
//            for (AggregateResult result : [select Account__c, count(Id) activeMapgCount
//                    from MetroclientAccountProductGeography__c where Account__c in :scope and Status__c = 'Active'
//                    group by Account__c]) {
//                accountIdToActiveMapgCountMap.put((ID) result.get('Account__c'), (Integer) result.get('activeMapgCount'));
//            }
//            for (AggregateResult result : [select Account__c, count(Id) expiredMapgCount
//                    from MetroclientAccountProductGeography__c where Account__c in :scope and Status__c = 'Expired'
//                    group by Account__c]) {
//                accountIdToExpiredMapgCountMap.put((ID) result.get('Account__c'), (Integer) result.get('expiredMapgCount'));
//            }
//
//            // Update accounts
//            Account[] accountsToUpdate = new List<Account>();
//            for (SObject record : scope) {
//                String mapgStatus = null;
//                Integer totalMapgCount = accountIdToTotalMapgCountMap.get(record.Id);
//                Integer activeMapgCount = accountIdToActiveMapgCountMap.get(record.Id);
//                Integer expiredMapgCount = accountIdToExpiredMapgCountMap.get(record.Id);
//                if (totalMapgCount > 0) {
//                    if (activeMapgCount > 0) {
//                        mapgStatus = 'Current';
//                    } else if (expiredMapgCount == totalMapgCount) {
//                        mapgStatus = 'Past';
//                    }
//                }
//                accountsToUpdate.add(new Account(Id = record.Id, FC_MAPG_Status__c = mapgStatus));
//            }
//
//            update accountsToUpdate;

            update scope;
        }
    }

    global void finish(Database.BatchableContext context) {
    }

}