src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hard_Copy_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Invoice Delivery Preference is Hard Copy</inlineHelpText>
        <label>Hard Copy Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hold_Past_Due_Emails__c</fullName>
        <label>Hold Past Due Emails</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoices_Sent_on_10th__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked then, Email Notifications sent on 10th of this month to all pending invoices of the account.</inlineHelpText>
        <label>Invoices Sent on 10th</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoices_Sent_on_20th__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked then, Email Notifications sent on 20th of this month to all pending invoices of the account.</inlineHelpText>
        <label>Invoices Sent on 20th</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due on receipt</fullName>
                    <default>true</default>
                    <label>Due on receipt</label>
                </value>
                <value>
                    <fullName>Net 15</fullName>
                </value>
                <value>
                    <fullName>Net 30</fullName>
                </value>
                <value>
                    <fullName>Net 45</fullName>
                </value>
                <value>
                    <fullName>Net 60</fullName>
                </value>
                <value>
                    <fullName>Net 90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Meyers</fullName>
        <active>true</active>
        <label>Meyers</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/blng__FinanceBook__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>To deactivate the finance book, clear the checkbox. This won&apos;t affect existing transactions
        that reference the book.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__PeriodType__c</fullName>
        <inlineHelpText>Select whether to base the finance book on revenue transactions or accounting transactions.</inlineHelpText>
        <label>Period Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__FinanceBookPeriodType</valueSetName>
        </valueSet>
    </fields>
    <label>Finance Book</label>
    <nameField>
        <label>Finance Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/blng__FinancePeriod__c.object
<CustomObject>
    <fields>
        <fullName>blng__FinanceBook__c</fullName>
        <label>Finance Book</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>blng__FinanceBook__c.blng__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__FinanceBook__c</referenceTo>
        <relationshipLabel>Finance Periods</relationshipLabel>
        <relationshipName>FinancePeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__PeriodEndDate__c</fullName>
        <inlineHelpText>Select an end date for the finance period.</inlineHelpText>
        <label>Period End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__PeriodStartDate__c</fullName>
        <inlineHelpText>Select the beginning of the finance period.</inlineHelpText>
        <label>Period Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__PeriodStatus__c</fullName>
        <inlineHelpText>Select Open to capture all transactions or Closed to prevent further transactions.</inlineHelpText>
        <label>Period Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__FinancialPeriodStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__PeriodType__c</fullName>
        <formula>Text(blng__FinanceBook__r.blng__PeriodType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Refers to the period type selected in the finance book.</inlineHelpText>
        <label>Period Type</label>
        <type>Text</type>
    </fields>
    <label>Finance Period</label>
    <nameField>
        <label>Financial Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>Hard_Copy_Invoice_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hard Copy Invoice set via Process Builder if the Hard Copy field changes on the account and the invoice has not been Posted</description>
        <label>Hard Copy Invoice Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hard_Copy_Invoice__c</fullName>
        <formula>Hard_Copy_Invoice_Account__c</formula>
        <inlineHelpText>Invoice Delivery Preference is Hard Copy -- From Account</inlineHelpText>
        <label>Hard Copy Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__PaymentTerm</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <formula>LOWER( Text( Payment_Term__c ) )</formula>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSD_Auto_Set__c</fullName>
        <label>RSD (Auto Set)</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__Account__c</fullName>
        <inlineHelpText>Lookup to the Account this invoice is billed to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>AccountInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Bill To contact for this invoice</inlineHelpText>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (BillToContact)</relationshipLabel>
        <relationshipName>BillToContactInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__DueDate__c</fullName>
        <description>When is the last date of invoice to be paid.</description>
        <inlineHelpText>The date when payment for the invoice is due.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__InvoiceStatus__c</fullName>
        <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>Invoice total (including tax). Equals SubTotal + Tax.</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <summarizedField>blng__InvoiceLine__c.blng__TotalAmount__c</summarizedField>
        <summaryForeignKey>blng__InvoiceLine__c.blng__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/blng__InvoiceLine__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>blng__InvoiceLineStatus__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>blng__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>InvoiceInvoiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>SubTotal + Tax</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountInvoicesScheduler_Test.cls
@isTest(SeeAllData = false)
public class AccountInvoicesScheduler_Test {
    
    public static testMethod void testAccountInvschedule() {
        Account accnt = new Account();
        accnt.name='test1';
        accnt.type='prospect';
        accnt.Industry='Banking';
        accnt.BillingPostalCode='590009';
        accnt.Invoices_Sent_on_20th__c = true;
        accnt.Invoices_Sent_on_10th__c = true;
        accnt.Hard_Copy_Invoice__c = true;
        accnt.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Meyers').getRecordTypeId();
        accnt.Payment_Terms__c = 'Net 30';
        accnt.Hold_Past_Due_Emails__c = NULL;
        insert accnt;
              
        Test.StartTest();
        
              
        AccountPastDueInvoices10th20thScheduler testsche = new AccountPastDueInvoices10th20thScheduler();
        String sch = '0 0 23 10 * ?';
        system.schedule('Test Invoice Check', sch, testsche );
        
        AccountPastDueInvoices10th20thScheduler testsche1 = new AccountPastDueInvoices10th20thScheduler();
        String sch1 = '0 0 23 20 * ?';
        system.schedule('Test Invoice Check1', sch1, testsche1 );
        
        AccountInvoicesScheduler9th testsche2 = new AccountInvoicesScheduler9th();
        String sch2 = '0 0 23 25 * ?';
        system.schedule('Test uncheck 10th checkbox', sch2, testsche2 );
        
        AccountInvoicesScheduler19th testsche3 = new AccountInvoicesScheduler19th();
        String sch3 = '0 0 23 15 * ?';
        system.schedule('Test uncheck 20th checkbox', sch3, testsche3 );
        
        AccountPastDueInvoices10thScheduler testsche4 = new AccountPastDueInvoices10thScheduler();
        String sch4 = '0 0 23 10 * ?';
        system.schedule('Test check 10th', sch4, testsche4 );
        
        AccountPastDueInvoices20thScheduler testsche5 = new AccountPastDueInvoices20thScheduler();
        String sch5 = '0 0 23 20 * ?';
        system.schedule('Test check 20th', sch5, testsche5 );
        
        Test.stopTest();
    }
    
    public static testMethod void testAccountInvschedule2() {
        list<blng__Invoice__c> invoice1 =  new list<blng__Invoice__c>();
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User usr = new User(LastName = 'LIVESTON',
                            FirstName='JASON',
                            Alias = 'jliv',
                            Email = 'jason.liveston@asdf.com',
                            Username = 'jason.liveston@asdf.com123',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US');
       // insert usr;

        Account accnt = new Account();
        accnt.name='test1';
        accnt.Ownerid = usr.id;
        accnt.type='prospect';
        accnt.Industry='Banking';
        accnt.BillingPostalCode='590009';
        accnt.Invoices_Sent_on_20th__c = true;
        accnt.Invoices_Sent_on_10th__c = true;
        accnt.Hard_Copy_Invoice__c = true;
        accnt.Payment_Terms__c = 'Net 30';
        accnt.Hold_Past_Due_Emails__c = NULL;
       // insert accnt;
        
        Contact con = new Contact();
        con.Lastname = 'Test';
        con.email = 'abc@abc.com';
        con.AccountId = accnt.Id;
     //   insert con;
        
        blng__Invoice__c inv1 = new blng__Invoice__c();
        inv1.blng__Account__c = accnt.Id;
        inv1.blng__InvoiceStatus__c = 'Posted';
        inv1.Hard_Copy_Invoice_Account__c = accnt.Hard_Copy_Invoice__c;
        inv1.Payment_Term__c = accnt.Payment_Terms__c;
        inv1.RSD_Auto_Set__c = usr.Id;
        inv1.blng__BillToContact__c = con.id;
        inv1.blng__DueDate__c = system.Today()-41;
       // insert inv1;
        
        blng__FinanceBook__c fBook = new blng__FinanceBook__c();
        fBook.Name = 'sdf';
        fBook.blng__Active__c = true;
        fBook.blng__PeriodType__c = 'Revenue';
      //  insert fBook;
        
        blng__FinancePeriod__c fPer = new blng__FinancePeriod__c();
        fPer.Name = 'Test';
        fPer.blng__FinanceBook__c = fBook.Id;
       // fPer.blng__PeriodStartDate__c = system.today();
        fPer.blng__PeriodStartDate__c =  date.newInstance(2018,05,01) ;
       // fPer.blng__PeriodEndDate__c = system.today()+30;
        fPer.blng__PeriodEndDate__c = date.newInstance(2018,05,31);
        fPer.blng__PeriodStatus__c = 'Open';
       // insert fPer;
        
        blng__InvoiceLine__c invline = new blng__InvoiceLine__c();
        invline.Name = 'test invoice line';
        invline.blng__Invoice__c = inv1.Id ; 
        invline.blng__InvoiceLineStatus__c = 'Posted';
        invline.blng__TotalAmount__c = 45;
      //  insert invline;
      
        Test.StartTest();
        AccountPastDueInvoices10th20thScheduler testsche = new AccountPastDueInvoices10th20thScheduler();
        String sch = '0 0 23 10 * ?';
        system.schedule('Test Invoice Check', sch, testsche );
        AccountPastDueInvoices10th20thScheduler testsche1 = new AccountPastDueInvoices10th20thScheduler();
        String sch1 = '0 0 23 20 * ?';
        system.schedule('Test Invoice Check1', sch1, testsche1 );
        Test.StopTest();
    }

            
}