src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_Sales_Region_Assignment_RD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Region Assignment RD</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>Accounts (Metrostudy Sales Region Assignment RD)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegion__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Available sales regions to assign to geographies</description>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_DNU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Emp DNU</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MSRATriggerHandler_test.cls
@isTest
class MSRATriggerHandler_test {
    static testMethod void m1(){
        MetrostudySalesRegion__c msr=new MetrostudySalesRegion__c(Abbreviation__c='test',User_DNU__c=userinfo.getUserId());
        insert msr;
        MetrostudySalesRegionAssignment__c msra=new MetrostudySalesRegionAssignment__c(SalesRegion__c=msr.id);
        insert msra;
        Account a=new Account(name='test',Metrostudy_Sales_Region_Assignment_RD__c=msra.id, BillingPostalCode = '12345');
        insert a;
        msra.User__c=userinfo.getUserId();
        upsert msra;
        MSRATriggerHandler msrat=new MSRATriggerHandler();
        msrat.bulkBefore();
        msrat.bulkAfter();
        msrat.beforeInsert();
        msrat.beforeUpdate();
        msrat.beforeDelete();
        msrat.afterInsert();
        msrat.afterDelete();
        msrat.afterUnDelete();
        msrat.andFinally();
    }
}