src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_MAPG_Status__c</fullName>
        <label>(FC) MAPG Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used isn the Parent Account look up to restrict the lookup to Parent Accounts only</description>
        <inlineHelpText>This checkbox identifies this Account as a Parent Account</inlineHelpText>
        <label>Parent</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date the subscription ends  (SubscriptionEndDate).  This value is blank (NULL) for evergreen subscriptions.</description>
        <inlineHelpText>The date access to the product expires and can no longer be accessed.  This field is blank when a subscription is evergreen.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Metrostudy_Account_Product_Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date that the subscription starts (SubscriptionStartDate)</description>
        <inlineHelpText>The date that the access to the product starts.  This date is determined by the subscription or amendment start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestUpdateDescendantMapgStatusBatch.cls
@isTest
private class FC_TestUpdateDescendantMapgStatusBatch {

    @isTest
    private static void testBatchable() {

        Account testAccount = [select Id, ParentId, FC_MAPG_Status__c from Account where Name = 'Test Account' limit 1];
        System.assertEquals(null, testAccount.ParentId);
        System.assertEquals('Current', testAccount.FC_MAPG_Status__c);

        Account testAccount1 = [select Id, ParentId, FC_MAPG_Status__c from Account where Name = 'Test Account 1' limit 1];
        System.assertEquals(testAccount.Id, testAccount1.ParentId);
        System.assertEquals(null, testAccount1.FC_MAPG_Status__c);

        Test.startTest();
        FC_UpdateDescendantAcctMapgStatusBatch batchable = new FC_UpdateDescendantAcctMapgStatusBatch();
        Database.executeBatch(batchable);
        Test.stopTest();

        testAccount1 = [select Id, ParentId, FC_MAPG_Status__c from Account where Name = 'Test Account 1' limit 1];
        System.assertEquals('Current', testAccount1.FC_MAPG_Status__c);

    }

    @testSetup
    private static void setup() {
        Account testAccount = new Account(Name = 'Test Account', FC_MAPG_Status__c = 'Current', BillingPostalCode = '12345', Parent__c = true);
        insert testAccount;

        Account testAccount1 = new Account(Name = 'Test Account 1', FC_Ultimate_Parent_Account__c = testAccount.Id, ParentId = testAccount.Id, BillingPostalCode = '12345');
        insert testAccount1;

        MetroclientAccountProductGeography__c[] testMetroclientAccountProductGeographies = new MetroclientAccountProductGeography__c[]{
                new MetroclientAccountProductGeography__c(Name = 'MAPG-1', Account__c = testAccount.Id,
                        FC_Ultimate_Parent_Account__c = testAccount.Id, StartDate__c = Date.today() - 30, EndDate__c = Date.today() + 30),
                new MetroclientAccountProductGeography__c(Name = 'MAPG-2', Account__c = testAccount.Id,
                        FC_Ultimate_Parent_Account__c = testAccount.Id, StartDate__c = Date.today() + 30, EndDate__c = Date.today() + 60)
        };
        insert testMetroclientAccountProductGeographies;
    }

}