src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metrostudy Market</label>
        <referenceTo>MetrostudyMarket__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metrostudy_Sales_Region_Assignment_DBD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Region Assignment DBD</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metrostudy_Sales_Region_Assignment_RD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Region Assignment RD</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>Accounts (Metrostudy Sales Region Assignment RD)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RD_Name_for_Dashboard_Filter__c</fullName>
        <label>RD Name for Dashboard Filter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strategic Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipName>MetroclientGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <fields>
        <fullName>GeographyTypeId__c</fullName>
        <label>Geography Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metrostudy_ZIP_Code__c.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_Market__c</fullName>
        <label>Metrostudy Market</label>
        <referenceTo>MetrostudyMarket__c</referenceTo>
        <relationshipLabel>Metrostudy ZIP Codes</relationshipLabel>
        <relationshipName>Metrostudy_ZIP_Codes1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Metrostudy ZIP Code</label>
    <nameField>
        <label>Metrostudy ZIP Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy ZIP Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetrostudyMarket__c.object
<CustomObject>
    <description>Metrostudy Survey Markets</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metroclient Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Markets</relationshipLabel>
        <relationshipName>MetrostudyMarkets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegion__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Available sales regions to assign to geographies</description>
    <label>Metrostudy Sales Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FC_TestAccountRD_DBDUpdate.cls
@isTest
private class FC_TestAccountRD_DBDUpdate {

    @isTest
    private static void testStrategicAccount() {

        MetrostudySalesRegionAssignment__c[] testSalesRegionAssignments = [
                select Id, Name, Role__c, User__c, User__r.Name
                from MetrostudySalesRegionAssignment__c
                where Name in ('Test Other', 'Test RD', 'Test DBD')
        ];
        Map<String, MetrostudySalesRegionAssignment__c> testSalesRegionAssignmentsByNameMap =
                new Map<String, MetrostudySalesRegionAssignment__c>();
        for (MetrostudySalesRegionAssignment__c testSalesRegionAssignment : testSalesRegionAssignments) {
            testSalesRegionAssignmentsByNameMap.put(testSalesRegionAssignment.Name, testSalesRegionAssignment);
        }

        Test.startTest();
        Account testAccount = new Account(Name = 'Test Account', Strategic_Account__c = true,
                ShippingPostalCode = '12345', BillingPostalCode = '12345',
                Metrostudy_Sales_Region_Assignment_DBD__c = testSalesRegionAssignmentsByNameMap.get('Test Other').Id,
                Metrostudy_Sales_Region_Assignment_RD__c = testSalesRegionAssignmentsByNameMap.get('Test Other').Id,
                RD_Name_for_Dashboard_Filter__c = testSalesRegionAssignmentsByNameMap.get('Test Other').User__r.Name);
        insert testAccount;
        Test.stopTest();

        testAccount = [
                select Id, Metrostudy_Sales_Region_Assignment_DBD__c, Metrostudy_Sales_Region_Assignment_RD__c,
                        RD_Name_for_Dashboard_Filter__c
                from Account
                where Id = :testAccount.Id
                limit 1
        ];
        System.assertEquals(testAccount.Metrostudy_Sales_Region_Assignment_DBD__c, testSalesRegionAssignmentsByNameMap.get('Test Other').Id);
        System.assertEquals(testAccount.Metrostudy_Sales_Region_Assignment_RD__c, testSalesRegionAssignmentsByNameMap.get('Test RD').Id);
        System.assertEquals(testAccount.RD_Name_for_Dashboard_Filter__c, testSalesRegionAssignmentsByNameMap.get('Test RD').User__r.Name);

    }

    @isTest
    private static void testNonStrategicAccount() {

        MetrostudySalesRegionAssignment__c[] testSalesRegionAssignments = [
                select Id, Name, Role__c, User__c, User__r.Name
                from MetrostudySalesRegionAssignment__c
                where Name in ('Test Other', 'Test RD', 'Test DBD')
        ];
        Map<String, MetrostudySalesRegionAssignment__c> testSalesRegionAssignmentsByNameMap =
                new Map<String, MetrostudySalesRegionAssignment__c>();
        for (MetrostudySalesRegionAssignment__c testSalesRegionAssignment : testSalesRegionAssignments) {
            testSalesRegionAssignmentsByNameMap.put(testSalesRegionAssignment.Name, testSalesRegionAssignment);
        }

        Test.startTest();
        Account testAccount = new Account(Name = 'Test Account', Strategic_Account__c = false,
                ShippingPostalCode = '12345', BillingPostalCode = '12345',
                Metrostudy_Sales_Region_Assignment_DBD__c = testSalesRegionAssignmentsByNameMap.get('Test Other').Id,
                Metrostudy_Sales_Region_Assignment_RD__c = testSalesRegionAssignmentsByNameMap.get('Test Other').Id,
                RD_Name_for_Dashboard_Filter__c = testSalesRegionAssignmentsByNameMap.get('Test Other').User__r.Name);
        insert testAccount;
        Test.stopTest();

        testAccount = [
                select Id, Metrostudy_Sales_Region_Assignment_DBD__c, Metrostudy_Sales_Region_Assignment_RD__c,
                        RD_Name_for_Dashboard_Filter__c
                from Account
                where Id = :testAccount.Id
                limit 1
        ];
        System.assertEquals(testAccount.Metrostudy_Sales_Region_Assignment_DBD__c, testSalesRegionAssignmentsByNameMap.get('Test DBD').Id);
        System.assertEquals(testAccount.Metrostudy_Sales_Region_Assignment_RD__c, testSalesRegionAssignmentsByNameMap.get('Test RD').Id);
        System.assertEquals(testAccount.RD_Name_for_Dashboard_Filter__c, testSalesRegionAssignmentsByNameMap.get('Test RD').User__r.Name);

    }


    @testSetup
    private static void setup() {

        Profile testProfile = [select Id from Profile where Name = 'Media - Sales Rep' limit 1];

        User[] testUsers = new User[]{
                new User(FirstName = 'Test', LastName = 'User', ProfileId = testProfile.Id,
                        Username = FC_UuidUtil.uuidV4() + '@example.com', Email = FC_UuidUtil.uuidV4() + '@example.com',
                        Alias = FC_UuidUtil.uuidV4().left(8), CommunityNickname = FC_UuidUtil.uuidV4(),
                        TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8',
                        LanguageLocaleKey = 'en_US'),
                new User(FirstName = 'Test', LastName = 'DBD', ProfileId = testProfile.Id,
                        Username = FC_UuidUtil.uuidV4() + '@example.com', Email = FC_UuidUtil.uuidV4() + '@example.com',
                        Alias = FC_UuidUtil.uuidV4().left(8), CommunityNickname = FC_UuidUtil.uuidV4(),
                        TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8',
                        LanguageLocaleKey = 'en_US'),
                new User(FirstName = 'Test', LastName = 'RD', ProfileId = testProfile.Id,
                        Username = FC_UuidUtil.uuidV4() + '@example.com', Email = FC_UuidUtil.uuidV4() + '@example.com',
                        Alias = FC_UuidUtil.uuidV4().left(8), CommunityNickname = FC_UuidUtil.uuidV4(),
                        TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8',
                        LanguageLocaleKey = 'en_US')
        };
        insert testUsers;

        MetrostudySalesRegion__c testSalesRegion = new MetrostudySalesRegion__c(Name = 'Test Sales Region');
        insert testSalesRegion;

        MetrostudySalesRegionAssignment__c[] testSalesRegionAssignments = new MetrostudySalesRegionAssignment__c[]{
                new MetrostudySalesRegionAssignment__c(Name = 'Test Other', User__c =
                        testUsers[0].Id, Role__c = 'Other', SalesRegion__c = testSalesRegion.Id),
                new MetrostudySalesRegionAssignment__c(Name = 'Test DBD', User__c =
                        testUsers[1].Id, Role__c = 'DBD', SalesRegion__c = testSalesRegion.Id),
                new MetrostudySalesRegionAssignment__c(Name = 'Test RD', User__c =
                        testUsers[2].Id, Role__c = 'RD', SalesRegion__c = testSalesRegion.Id)
        };
        insert testSalesRegionAssignments;

        MetroclientGeographyType__c testGeographyType = new MetroclientGeographyType__c(Name = 'Test Geography Type',
                GeographyTypeId__c = 1);
        insert testGeographyType;

        MetroclientGeography__c testGeography = new MetroclientGeography__c(Name = 'Test Geography',
                GeographyType__c = testGeographyType.Id, SalesRegion__c = testSalesRegion.Id);
        insert testGeography;

        MetrostudyMarket__c testMarket = new MetrostudyMarket__c(Name = 'Test Market',
                Geography__c = testGeography.Id, ZipCode__c = '12345');
        insert testMarket;

        Metrostudy_ZIP_Code__c testZipCode = new Metrostudy_ZIP_Code__c(Name = '12345', Metrostudy_Market__c = testMarket.Id);
        insert testZipCode;

    }

}