src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Has_Active_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Active Subscription?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>FC_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Subscription_Number__c</fullName>
        <externalId>true</externalId>
        <label>(FC) Subscription Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Term_End_Date__c</fullName>
        <label>(FC) Term End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>FC_One_Time_Charge_Count__c</fullName>
        <label>(FC) One-Time Charge Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpportunityID__c</fullName>
        <label>Opportunity ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveStartDate__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionChargeNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestZuoraSubscriptionHandler.cls
@isTest
private class FC_TestZuoraSubscriptionHandler {

    @isTest
    private static void testInsert() {

        Account testAccount = [select Id from Account where Name = 'Test Account' limit 1];

        Zuora__CustomerAccount__c testCustomerAccount = [
                select Id
                from Zuora__CustomerAccount__c
                where Name = 'Test Account'
                limit 1
        ];

        Opportunity testOpportunity = [select Id from Opportunity where Name = 'Test Opportunity' limit 1];

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_ZuoraSubscriptionHandler'
        });

        Test.startTest();

        Zuora__Subscription__c testSubscription = new Zuora__Subscription__c(Name = 'S-2',
                OpportunityID__c = testOpportunity.Id, Zuora__Account__c = testAccount.Id,
                Zuora__CustomerAccount__c = testCustomerAccount.Id, Zuora__TermEndDate__c = Date.today() + 365,
                Zuora__TermStartDate__c = Date.today());
        insert testSubscription;

        Test.stopTest();

        testSubscription = [
                select Id, Opportunity__c, FC_One_Time_Charge_Count__c
                from Zuora__Subscription__c
                where Name = 'S-2'
                limit 1
        ];

        System.assertEquals(testOpportunity.Id, testSubscription.Opportunity__c);
        System.assertEquals(0, testSubscription.FC_One_Time_Charge_Count__c);

    }

    @isTest
    private static void testUpdate() {

        Opportunity testOpportunity = [select Id from Opportunity where Name = 'Test Opportunity' limit 1];

        Zuora__Subscription__c testSubscription = [
                select Id, Opportunity__c, FC_One_Time_Charge_Count__c
                from Zuora__Subscription__c
                where Name = 'S-1'
                limit 1
        ];

        System.assertEquals(null, testSubscription.Opportunity__c);
        System.assertNotEquals(1, testSubscription.FC_One_Time_Charge_Count__c);

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_ZuoraSubscriptionHandler'
        });

        Test.startTest();

        testSubscription.OpportunityID__c = testOpportunity.Id;
        update testSubscription;

        Test.stopTest();

        testSubscription = [
                select Id, Opportunity__c, FC_One_Time_Charge_Count__c
                from Zuora__Subscription__c
                where Id = :testSubscription.Id
                limit 1
        ];

        System.assertEquals(testOpportunity.Id, testSubscription.Opportunity__c);
        System.assertEquals(1, testSubscription.FC_One_Time_Charge_Count__c);

    }

    @isTest
    private static void testDelete() {

        Account testAccount = [select Id, Has_Active_Subscription__c from Account where Name = 'Test Account' limit 1];

        System.assertEquals(true, testAccount.Has_Active_Subscription__c);

        Zuora__Subscription__c testSubscription = [
                select Id
                from Zuora__Subscription__c
                where Name = 'S-1'
                limit 1
        ];

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_AccountHandler',
                'FC_ZuoraSubscriptionHandler'
        });

        Test.startTest();

        delete testSubscription;

        Test.stopTest();

        testAccount = [select Id, Has_Active_Subscription__c from Account where Id = :testAccount.Id limit 1];

        System.assertEquals(false, testAccount.Has_Active_Subscription__c);

    }

    @isTest
    private static void testUndelete() {

        Account testAccount = [select Id, Has_Active_Subscription__c from Account where Name = 'Test Account' limit 1];

        System.assertEquals(true, testAccount.Has_Active_Subscription__c);

        Zuora__Subscription__c testSubscription = [
                select Id
                from Zuora__Subscription__c
                where Name = 'S-1'
                limit 1
        ];

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_AccountHandler',
                'FC_ZuoraSubscriptionHandler'
        });

        update testSubscription;

        fcf.TriggerRunStatus.unblockAll();

        delete testSubscription;

        testAccount = [select Id, Has_Active_Subscription__c from Account where Id = :testAccount.Id limit 1];

        System.assertEquals(false, testAccount.Has_Active_Subscription__c);

        fcf.TriggerRunStatus.unblockAll();

        Test.startTest();

        undelete testSubscription;

        Test.stopTest();

        testAccount = [select Id, Has_Active_Subscription__c from Account where Id = :testAccount.Id limit 1];

        System.assertEquals(true, testAccount.Has_Active_Subscription__c);

    }

    @testSetup
    private static void setup() {

        Account testAccount = new Account(Name = 'Test Account', Has_Active_Subscription__c = true, BillingPostalCode = '12345');
        insert testAccount;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account',
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;

        Zuora__Subscription__c testSubscription = new Zuora__Subscription__c(Name = 'S-1',
                Zuora__Account__c = testAccount.Id, Zuora__CustomerAccount__c = testCustomerAccount.Id,
                Zuora__TermEndDate__c = Date.today() + 365, Zuora__TermStartDate__c = Date.today());
        insert testSubscription;

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge =
                new Zuora__SubscriptionProductCharge__c(Name = 'C-1',
                        Zuora__Subscription__c = testSubscription.Id, Zuora__Type__c = 'One-Time',
                        Zuora__SubscriptionChargeNumber__c = 'C-1', Zuora__EffectiveStartDate__c = Date.today());
        insert testSubscriptionProductCharge;

        Contract testContract = new Contract(AccountId = testAccount.Id, FC_Subscription_Number__c = 'S-1',
                FC_Price_Book__c = Test.getStandardPricebookId());
        insert testContract;

        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity',
                AccountId = testAccount.Id, Amount = 100, ContractId = testContract.Id,
                StageName = 'New Opportunity', CloseDate = Date.today(), FC_Term_End_Date__c = Date.today() + 30);
        insert testOpportunity;

    }
}