src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Has_Active_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Active Subscription?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Billing_Address_Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Billing Address Information</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/fcf__Exception_Log__c.object
<CustomObject>
    <description>The Exception Log object stores exception data caught in real-time by the ExceptionLogUtil class.</description>
    <fields>
        <fullName>fcf__Message__c</fullName>
        <description>The error message that displays for the user.</description>
        <inlineHelpText>The error message that displays for the user.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fcf__Related_To_ID__c</fullName>
        <description>This ID can be used to relate this exception log to a specific object or job ID.</description>
        <externalId>true</externalId>
        <label>Related To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fcf__Type__c</fullName>
        <description>The type of exception, such as DmlException, ListException, MathException, and so on.</description>
        <inlineHelpText>The type of exception, such as DmlException, ListException, MathException, and so on.</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestAmendmentJobStatusController.cls
@isTest
private class FC_TestAmendmentJobStatusController {

    @isTest
    public static void testController() {

        Opportunity testOpportunity = [select Id from Opportunity where Name = 'Test Opportunity' limit 1];

        Id asyncJobId = Database.executeBatch(new FC_ZuoraAmendmentProcessorBatchable(testOpportunity.Id, false), 1);
        System.assertNotEquals(null, asyncJobId);

        Test.setMock(HttpCalloutMock.class, new FC_ZuoraCalloutMock());
        Test.startTest();

        FC_AmendmentJobStatusController controller = new FC_AmendmentJobStatusController();
        controller.amendmentJobId = asyncJobId;

        System.assertNotEquals(null, controller.job);
        System.assertEquals(true, controller.isJobRunning);
        System.assertNotEquals('Error', controller.jobStatus);

        fcf__Exception_Log__c testExceptionLog = new fcf__Exception_Log__c(fcf__Message__c = 'Test Message',
                fcf__Related_To_ID__c = asyncJobId, fcf__Type__c = 'TestException');
        insert testExceptionLog;

        controller.refresh();

        System.assertEquals('TestException: Test Message', controller.jobExtendedStatus);

        Test.stopTest();

    }

    @testSetup
    public static void setup() {

        Account testAccount = new Account(Name = 'Test Account', Has_Active_Subscription__c = false, BillingPostalCode = '10069', Override_Billing_Address_Information__c = true);
        insert testAccount;

        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity', Amount = 100,
                CloseDate = Date.today() + 30, StageName = 'New Opportunity', AccountId = testAccount.Id);
        insert testOpportunity;

    }

}