src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metrostudy Market</label>
        <referenceTo>MetrostudyMarket__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipName>MetroclientGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <fields>
        <fullName>GeographyTypeId__c</fullName>
        <label>Geography Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metrostudy_ZIP_Code__c.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_Market__c</fullName>
        <label>Metrostudy Market</label>
        <referenceTo>MetrostudyMarket__c</referenceTo>
        <relationshipLabel>Metrostudy ZIP Codes</relationshipLabel>
        <relationshipName>Metrostudy_ZIP_Codes1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Metrostudy ZIP Code</label>
    <nameField>
        <label>Metrostudy ZIP Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy ZIP Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetrostudyMarket__c.object
<CustomObject>
    <description>Metrostudy Survey Markets</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metroclient Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Markets</relationshipLabel>
        <relationshipName>MetrostudyMarkets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MarketCode__c</fullName>
        <inlineHelpText>Legacy Metrostudy Market Code</inlineHelpText>
        <label>Market Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegion__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Available sales regions to assign to geographies</description>
    <label>Metrostudy Sales Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MetrostudyTest.cls
@isTest
class MetrostudyTest{
    @testSetup
    static void creatingTest(){
        MetroclientGeographyType__c mgt=new MetroclientGeographyType__c(name='Market',GeographyTypeId__c=4392);
        insert mgt;
        /*---------------record chain 1--------------------------------------*/
             
        MetrostudySalesRegion__c msr=new MetrostudySalesRegion__c(name='test');
        insert msr;
        MetrostudySalesRegionAssignment__c msraRD=new MetrostudySalesRegionAssignment__c(Name='testRD',Role__c='RD',SalesRegion__c=msr.id,User__c=userinfo.getUserId());
        insert msraRD;
        MetrostudySalesRegionAssignment__c msraDBD=new MetrostudySalesRegionAssignment__c(Name='testDBD',Role__c='DBD',SalesRegion__c=msr.id,User__c=userinfo.getUserId());
        insert msraDBD;
        MetroclientGeography__c mg=new MetroclientGeography__c(name='test',GeographyType__c=mgt.id,SalesRegion__c=msr.id);
        insert mg;
        MetrostudyMarket__c mm=new MetrostudyMarket__c(name='test',Geography__c=mg.id,MarketCode__c='IND');
        insert mm;
        Metrostudy_ZIP_Code__c mzip=new Metrostudy_ZIP_Code__c(Metrostudy_Market__c=mm.id,name='302004');
        insert mzip;
        
        /*---------------record chain 2 --------------------------------------*/
        
        MetrostudySalesRegion__c msr1=new MetrostudySalesRegion__c(name='test1');
        insert msr1;
        MetrostudySalesRegionAssignment__c msraRD1=new MetrostudySalesRegionAssignment__c(Name='test1RD',Role__c='RD',SalesRegion__c=msr1.id,User__c=userinfo.getUserId());
        insert msraRD1;
        MetrostudySalesRegionAssignment__c msraDBD1=new MetrostudySalesRegionAssignment__c(Name='test1DBD',Role__c='DBD',SalesRegion__c=msr1.id,User__c=userinfo.getUserId());
        insert msraDBD1;
        MetroclientGeography__c mg1=new MetroclientGeography__c(name='test1',GeographyType__c=mgt.id,SalesRegion__c=msr1.id);
        insert mg1;
        MetrostudyMarket__c mm1=new MetrostudyMarket__c(name='test1',Geography__c=mg1.id,MarketCode__c='INI');
        insert mm1;
        Metrostudy_ZIP_Code__c mzip1=new Metrostudy_ZIP_Code__c(Metrostudy_Market__c=mm1.id,name='302005');
        insert mzip1;
        
        
    }
    static testMethod void StrategicAccountTrigger_Test(){
        Account a=new Account(name='test',shippingpostalcode='302004', BillingPostalCode = '12345');
        insert a;
    }
    static testMethod void MetroStudyZipCodeTrigger_Test(){
        Account a=new Account(name='test',shippingpostalcode='302004', BillingPostalCode = '12345');
        insert a;
        List<Metrostudy_ZIP_Code__c> mzc=[select id from Metrostudy_ZIP_Code__c ];
        update mzc;
        MetroStudyZipCodeTriggerHandler mzcth=new MetroStudyZipCodeTriggerHandler();
        mzcth.bulkBefore();
        mzcth.beforeInsert();
        mzcth.beforeUpdate();
        mzcth.beforeDelete();
        mzcth.afterDelete();
        mzcth.afterUnDelete();
    }
    static testMethod void MetroStudyZipCodeBatch_Test(){
        Account a=new Account(name='test',shippingpostalcode='302004', BillingPostalCode = '12345');
        insert a;
        Account a1=new Account(name='test',shippingpostalcode='302005', BillingPostalCode = '12345');
        insert a1;
        Database.executeBatch(new MetroStudyZipCodeBatch([select createddate from Metrostudy_ZIP_Code__c][0].createddate),100);
    }
    
}