src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FC_Ultimate_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Ultimate Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts ((FC) Ultimate Parent Account)</relationshipLabel>
        <relationshipName>Related_Accounts_by_Ultimate_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Active_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Active Subscription?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used isn the Parent Account look up to restrict the lookup to Parent Accounts only</description>
        <inlineHelpText>This checkbox identifies this Account as a Parent Account</inlineHelpText>
        <label>Parent</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestAccountHandler.cls
@isTest
private class FC_TestAccountHandler {

    @isTest
    private static void testInsert() {

        Account testAccount6 = [select Id, FC_Ultimate_Parent_Account__c from Account where Name = 'Test Account 6' limit 1];
        Account testAccount = [select Id, FC_Ultimate_Parent_Account__c from Account where Name = 'Test Account' limit 1];

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_AccountHandler'
        });

        Test.startTest();

        Account testAccount7 = new Account(Name = 'Test Account 7', ParentId = testAccount6.Id, Parent__c = true, BillingPostalCode = '12345');
        insert testAccount7;

        Test.stopTest();

        testAccount7 = [select Id, FC_Ultimate_Parent_Account__c from Account where Name = 'Test Account 7' limit 1];
        System.assertNotEquals(null, testAccount7.FC_Ultimate_Parent_Account__c);
        System.assertEquals(testAccount6.FC_Ultimate_Parent_Account__c, testAccount7.FC_Ultimate_Parent_Account__c);
        System.assertEquals(testAccount.Id, testAccount7.FC_Ultimate_Parent_Account__c);

    }

    @isTest
    private static void testUpdate() {

        Account testAccount = [select Id, Has_Active_Subscription__c from Account where Name = 'Test Account' limit 1];

        System.assertEquals(false, testAccount.Has_Active_Subscription__c);

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_AccountHandler'
        });

        Test.startTest();

        update testAccount;

        Test.stopTest();

        testAccount = [select Id, Has_Active_Subscription__c from Account where Name = 'Test Account' limit 1];

        System.assertEquals(true, testAccount.Has_Active_Subscription__c);

    }

    @testSetup
    private static void setup() {

        Account testAccount = new Account(Name = 'Test Account', Has_Active_Subscription__c = false, BillingPostalCode = '12345', Parent__c = true);
        insert testAccount;

        Account testAccount1 = new Account(Name = 'Test Account 1', FC_Ultimate_Parent_Account__c = testAccount.Id,
                Has_Active_Subscription__c = false, ParentId = testAccount.Id, BillingPostalCode = '12345', Parent__c = true);
        insert testAccount1;

        Account testAccount2 = new Account(Name = 'Test Account 2', FC_Ultimate_Parent_Account__c = testAccount.Id,
                Has_Active_Subscription__c = false, ParentId = testAccount1.Id, BillingPostalCode = '12345', Parent__c = true);
        insert testAccount2;

        Account testAccount3 = new Account(Name = 'Test Account 3', FC_Ultimate_Parent_Account__c = testAccount.Id,
                Has_Active_Subscription__c = false, ParentId = testAccount2.Id, BillingPostalCode = '12345', Parent__c = true);
        insert testAccount3;

        Account testAccount4 = new Account(Name = 'Test Account 4', FC_Ultimate_Parent_Account__c = testAccount.Id,
                Has_Active_Subscription__c = false, ParentId = testAccount3.Id, BillingPostalCode = '12345', Parent__c = true);
        insert testAccount4;

        Account testAccount5 = new Account(Name = 'Test Account 5', FC_Ultimate_Parent_Account__c = testAccount.Id,
                Has_Active_Subscription__c = false, ParentId = testAccount4.Id, BillingPostalCode = '12345', Parent__c = true);
        insert testAccount5;

        Account testAccount6 = new Account(Name = 'Test Account 6', FC_Ultimate_Parent_Account__c = testAccount.Id,
                Has_Active_Subscription__c = false, ParentId = testAccount5.Id, BillingPostalCode = '12345', Parent__c = true);
        insert testAccount6;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account',
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;

        Zuora__Subscription__c testSubscription = new Zuora__Subscription__c(Name = 'S-1',
                Zuora__Account__c = testAccount.Id, Zuora__CustomerAccount__c = testCustomerAccount.Id,
                Zuora__Status__c = 'Active');
        insert testSubscription;

    }

}