src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hold_Past_Due_Emails__c</fullName>
        <label>Hold Past Due Emails</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoices_Sent_on_10th__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked then, Email Notifications sent on 10th of this month to all pending invoices of the account.</inlineHelpText>
        <label>Invoices Sent on 10th</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoices_Sent_on_20th__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked then, Email Notifications sent on 20th of this month to all pending invoices of the account.</inlineHelpText>
        <label>Invoices Sent on 20th</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Days_Open__c</fullName>
        <formula>TODAY() - Oldest_Invoice_Due_Date__c</formula>
        <label>Max Days Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary_of_Invoices_Balance__c</fullName>
        <inlineHelpText>Summary of all Invoices Balance of this account.</inlineHelpText>
        <label>Summary of Invoices Balance</label>
        <summarizedField>blng__Invoice__c.blng__Balance__c</summarizedField>
        <summaryFilterItems>
            <field>blng__Invoice__c.blng__InvoiceStatus__c</field>
            <operation>equals</operation>
            <value>Posted, Rebilled</value>
        </summaryFilterItems>
        <summaryForeignKey>blng__Invoice__c.blng__Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>blng__Account__c</fullName>
        <inlineHelpText>Lookup to the Account this invoice is billed to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>AccountInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__Balance__c</fullName>
        <formula>blng__TotalAmount__c - blng__Payments__c - blng__Credits__c + blng__Debits__c + blng__NegativeLineConversion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Balance = Total Amount - Total Net Payments - Credit Notes Applied + Debit Notes Applied + Negative Line Conversions</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__InvoiceStatus__c</fullName>
        <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountPastDueInvoicesBatch10th20th.cls
global class AccountPastDueInvoicesBatch10th20th implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC){
        string query = 'select id,Invoices_Sent_on_20th__c,Invoices_Sent_on_10th__c,Max_Days_Open__c from Account where Max_Days_Open__c > 44 AND Summary_of_Invoices_Balance__c > 0 AND Hold_Past_Due_Emails__c = NULL';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope){
        list<account> acclist = [select id,Invoices_Sent_on_10th__c,Invoices_Sent_on_20th__c,Max_Days_Open__c,(select id,blng__Account__c from blng__AccountInvoices__r where blng__InvoiceStatus__c IN ('Posted','Rebilled') AND blng__Balance__c > 10) from Account where Max_Days_Open__c > 44 AND Summary_of_Invoices_Balance__c > 0 AND Hold_Past_Due_Emails__c = NULL AND ID IN:scope];
        for(Account acc : acclist){
            //if(acc.blng__AccountInvoices__r.size() >0 && acc.Invoices_Sent_on_20th__c == False){
            //    acc.Invoices_Sent_on_10th__c = true;
            //}
            //else 
                if(acc.blng__AccountInvoices__r.size() >0 && acc.Invoices_Sent_on_10th__c == False){
                acc.Invoices_Sent_on_20th__c = true;
            } 
        }
        if(acclist.size()>0)
            update acclist;
    }
    
    global void finish(Database.BatchableContext BC){
    }
}