src/objects/Builder__c.object
<CustomObject>
    <description>MG_Builder</description>
    <label>Builder</label>
    <nameField>
        <label>Builder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zonda_Contract__c.object
<CustomObject>
    <description>MG_Zonda Contract</description>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                    <isActive>false</isActive>
                    <label>A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Coverage_String__c</fullName>
        <label>Coverage String</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <defaultValue>DATE(2999,12,31)</defaultValue>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <label>Zonda Contract</label>
    <nameField>
        <label>Zonda Contract</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zonda Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZondaContractCoverage.cls
public without sharing class ZondaContractCoverage {
    
	//public Id selectedContract {get; set;}

	//if (null != fBuilder && '' != fBuilder.getValue()) {
	//	selectedContract = (Id)fBuilder.getValue();
 //          Zonda_Contract__c b = [SELECT Id, Name FROM Zonda_Contract__c WHERE Id = :selectedContract];
 //          searchTerm = b.Name;

	//public void clearFilter() {
 //       selectedContract = null;
	//fBuilder = new Cookie('fBuilder',selectedContract,null,-1,false);

	//String soqlFilter = '';
 //       if (null != selectedContract && String.valueOf(selectedContract) != '') {
 //           soqlFilter += ' AND Zonda_Contract__c = \''+String.valueOf(selectedContract)+'\'';




//    public Id selectedBuilder {get; set;}

//        if (null != fBuilder && '' != fBuilder.getValue()) {
//            selectedBuilder = (Id)fBuilder.getValue();
//            Builder__c b = [SELECT Id, Name FROM Builder__c WHERE Id = :selectedBuilder];
//            searchTerm = b.Name;

//public void clearFilter() {
//        selectedBuilder = null;
//fBuilder = new Cookie('fBuilder',selectedBuilder,null,-1,false);

//String soqlFilter = '';
//        if (null != selectedBuilder && String.valueOf(selectedBuilder) != '') {
//            soqlFilter += ' AND Builder__c = \''+String.valueOf(selectedBuilder)+'\'';


 //   public Static void 

 //   public Id theZondaContract {get; set;}
 //   public List <zondaContract> getContract
 //   public Zonda_Contract__c theContract;

 //   //Zonda Contract data
 //   public Zonda_Contract__c z {get; set;}
 //   public List<Zonda_Contract__c> theContractCoverage {get; set;}
 //   //public id zid {get; set;}
 //   //Lists

 //   //public contractCoverage(){
 //   //	z = [	SELECT id, Contract_Name__c, Coverage_String__c, Contract_Status__c, Subscription_End_Date__c 
 //   //			FROM Zonda_Contract__c
 //   //			WHERE id = : ApexPages.currentPage().getParameters().get('id')
 //   //			];
 //   //} 
	//if (null != ApexPages.currentPage().getParameters().get('id')) {
 //           pageMode = 'zondaContract';
 //           this.theContract = (Zonda_Contract__c)stdController.getRecord();
 //           theContractCoverage = [SELECT Id, Contract_Name__c, Contract_Status__c, Coverage_String__c, FROM Zonda_Contract__c WHERE Zonda_Contract__c = :theContract.Id];
 //       } else {
 //           pageMode = 'dataUser';
 //           filterProjects();
 //       }



    //public String contractCoverage {get; set;}

    
    //theZondaContract = [SELECT Id FROM Zonda_Contract__c]
    //contractCoverage = [SELECT Id FROM Zonda_Contract__c]
}