src/objects/Builder__c.object
<CustomObject>
    <description>MG_Builder</description>
    <label>Builder</label>
    <nameField>
        <label>Builder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Data_User__c.object
<CustomObject>
    <description>MG_Data User</description>
    <label>Data User</label>
    <nameField>
        <label>Data User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>MG_Plan</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To assign a Project to a specific Data User record so it will appear in their queue.</inlineHelpText>
        <label>Data User</label>
        <referenceTo>Data_User__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Contact__c.object
<CustomObject>
    <description>MG_Project Contact</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Contacts</relationshipLabel>
        <relationshipName>Project_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project Contact</label>
    <nameField>
        <label>Project Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatchJobs.cls
@isTest
private class TestBatchJobs { 
	static void setupTestData() {
		Account a1 = new Account(
			Name = 'the account'
		,	Industry = 'Other'
		, BillingPostalCode='560028'
			);
		insert a1;
		 
		Builder__c b1 = new Builder__c(
			Name = 'the builder'
		);
		insert b1;

		Data_User__c du1 = new Data_User__c(
			Name = 'test user'
			);
		insert du1;

		Project__c p1 = new Project__c(
			Name = 'the project'
		,	Builder__c = b1.Id
		,	Data_User__c = du1.Id
		,	Open_Date__c = Date.newInstance(2015, 1, 1)
		,	Total_Units_Planned__c = 90
		,	Total_Units_Sold__c = 20
			);
		insert p1;

		Project__c p2 = new Project__c(
			Name = 'the other project'
		,	Builder__c = b1.Id
		,	Data_User__c = du1.Id
			);
		insert p2;

		Project_Contact__c pc1 = new Project_Contact__c(
			Name = 'the guy'
		,	Project__c = p1.Id
			);
		insert pc1;

		Plan__c plan1 = new Plan__c(
			Name = 'the plan'
		,	Project__c = p1.Id
			);
		insert plan1;

		p1.Total_Units_Sold__c = 25;
		update p1;
	}
	
	
	@isTest static void testBatchDeleteSusbcriberActivity() {
		BatchDeleteSubscriberActivity theBatch = new BatchDeleteSubscriberActivity();
		Database.executeBatch(theBatch);
	}
	
	@isTest static void testBatchMaintProjectFields() {
        
		setupTestData();
		Project__c p1 = [SELECT Id, Total_Units_Planned__c, Total_Units_Sold__c FROM Project__c LIMIT 1];
		p1.Total_Units_Sold__c = 30;
		update p1;
		BatchMaintProjectFields theBatch = new BatchMaintProjectFields();
		Database.executeBatch(theBatch);
	}
    public static testMethod void testschedule() {
         Test.StartTest();
             BatchMaintProjectFields testsche = new BatchMaintProjectFields();
             String sch = '0 0 23 * * ?';
             system.schedule('Test status Check', sch, testsche );
       Test.stopTest();
    }
	
}