src/objects/Builder__c.object
<CustomObject>
    <description>MG_Builder</description>
    <fields>
        <fullName>Builder_Logo_URL__c</fullName>
        <inlineHelpText>Provide the URL of the logo image to be used in Zonda. Paste shared dropbox link here.  Update dl=0 at the end of the link to raw=1.</inlineHelpText>
        <label>Builder Logo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Builder_Website__c</fullName>
        <label>Builder Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Builder</label>
    <nameField>
        <label>Builder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Community__c.object
<CustomObject>
    <description>MG_Community</description>
    <fields>
        <fullName>Open_Date__c</fullName>
        <inlineHelpText>This is an estimated value.</inlineHelpText>
        <label>Oldest Project Open Date</label>
        <type>Date</type>
    </fields>
    <label>Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>MG_Plan</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Snapshot__c.object
<CustomObject>
    <description>MG_Plan Snapshot</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plan Snapshots</relationshipLabel>
        <relationshipName>Plan_Snapshots</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Plan Snapshot</label>
    <nameField>
        <displayFormat>PLS{0000} {MM}-{DD}-{YYYY}</displayFormat>
        <label>Plan Snapshot Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Builder_Logo_URL__c</fullName>
        <formula>Builder__r.Builder_Logo_URL__c</formula>
        <inlineHelpText>Displayed from Builder</inlineHelpText>
        <label>Builder Logo URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State (legacy)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Update_Request__c.object
<CustomObject>
    <description>MG_Project Update Request</description>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Project Update Request</label>
    <nameField>
        <displayFormat>PUR-{000000}</displayFormat>
        <label>Project Update Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BackupPlanTest.cls
/*
* Test for BackupPlanTest
* @since           : 30 Jan 2019
* @date            : 30 Jan 2019 - Navin: created initial version
* @see      
*/ 

@isTest
public class BackupPlanTest {
	
    // Create testsetup records
    @TestSetup
    public static void createTestRecord(){
        Builder__c builderRecord = new  Builder__c(); 
        builderRecord.Name = 'TestBuilder';
        builderRecord.Builder_Website__c = 'http://www.test.com/';
        builderRecord.State__c = 'CA';
        builderRecord.Builder_Logo_URL__c ='https://kennedywilson.box.com/shared/static/d2dvbd8nz72wt7e44jxpuv9qcas0odhy.jpg';    
        INSERT builderRecord;
        
        Schema.DescribeSObjectResult communitObjectDescribe = Community__c.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> communityRecordTypeInfo = communitObjectDescribe.getRecordTypeInfos();
        
        Community__c communityRecord = new Community__c();
        communityRecord.RecordTypeId = communityRecordTypeInfo[0].getRecordTypeId();
        communityRecord.name = 'mTestCommu1';
        communityRecord.Open_Date__c = system.today();
        INSERT communityRecord;
        
        
        
        Project__c projectRecord = new Project__c();
        projectRecord.Name = 'mTestProject';
        projectRecord.Builder__c = builderRecord.id;
        projectRecord.Status__c = 'Active';
        projectRecord.open_Date__c = system.today()-1;
        projectRecord.Total_Units_Planned__c = 10;
        projectRecord.Total_Units_Sold__c = 5;
        projectRecord.Website__c = 'http://www.test.com/';
        projectRecord.Location__Latitude__s = 40.731;
        projectRecord.Location__Longitude__s = -73.997;
        projectRecord.Master_Plan_Community__c = communityRecord.id;
        INSERT projectRecord;  
        
        List<Project_Update_Request__c> projectUpdateRequestRecordList = new List<Project_Update_Request__c>();
        for(Integer i=0; i<10; i++) {
            projectUpdateRequestRecordList.add(new Project_Update_Request__c(Builder__c = builderRecord.Id,
                                                                             Project__c = projectRecord.Id));
        }
        
        INSERT projectUpdateRequestRecordList;
        
        for(Project_Update_Request__c pur : projectUpdateRequestRecordList) {
           Test.setCreatedDate(pur.Id, System.today().addDays(-3));
        }
        
        System.assertEquals(System.today().addDays(-3), [SELECT Id, createdDate FROM Project_Update_Request__c][0].createdDate);
        
        Opportunity opportunityRecord = new Opportunity(name = 'test opp 1',
                                                        StageName = 'Oferecer projeto/orçamento',
                                                        LeadSource = 'Google',
                                                        CloseDate = system.today()) ;
        
        insert opportunityRecord;
        
        List<Task> taskList = new List<Task>();
        for(Integer i=0; i<10; i++) {
            taskList.add(new Task(WhatID = opportunityRecord.id,
                                  Subject='Test '+i,
                                  Status='Completed',
                                  Priority='Normal',
                                  ActivityDate = (System.today().addMonths(-8)))); 
        }
        INSERT taskList;  
        
        Plan__c  planRecord = new Plan__c();
        planRecord.Name     ='testPln';
        planRecord.Project__c = projectRecord.id;
        INSERT planRecord;
        
        List<Plan_Update_Request__c> planUpdateRequestList = new List<Plan_Update_Request__c>();
        for(Integer i=0; i<10; i++){
            planUpdateRequestList.add(new Plan_Update_Request__c(Project__c = projectRecord.id,
                                                                 Plan__c = planRecord.id,
                                                                 Project_Update_Request__c = projectUpdateRequestRecordList[0].id,
                                                                 Plan_Name__c = 'testPlan',
                                                                 Previous_Price__c = NULL,
                                                                 Price__c = 1,
                                                                 Previous_Square_Footage__c = NULL,
                                                                 Square_Footage__c = 1));
        }
        INSERT planUpdateRequestList;
        
        List<Plan_Snapshot__c> planSnapShotList = new List<Plan_Snapshot__c>();
        for(Integer i=0; i<10; i++) {
            planSnapShotList.add(new Plan_Snapshot__c(Plan__c = planRecord.Id,
                                                      Project__c = projectRecord.Id));
        }
        INSERT planSnapShotList;
        
        List<Plan_Image__c> planImageList = new List<Plan_Image__c>();
        for(Integer i=0; i<10; i++) {
            planImageList.add(new Plan_Image__c(Name = 'Test Plan Image '+i,
                                                Plan__c = planRecord.Id));
        }
        INSERT planImageList;
    }
    
    // Test for BackupProjectUpdateRequests batch class
    @isTest
    public static void backupProjectUpdateRequestsTest() {
        Test.startTest(); 
        BackupProjectUpdateRequests backupProjectUpdateObject = new BackupProjectUpdateRequests(System.today()+1);
        Database.executeBatch(backupProjectUpdateObject);
        Test.stopTest();
    }
    
    // Test for BackupTasksBatch batch class
    @isTest
    public static void backupTasksBatchTest() {
        Test.startTest(); 
        BackupTasksBatch backupTasksBatchObject = new BackupTasksBatch();
        Database.executeBatch(backupTasksBatchObject);
        Test.stopTest();
    }
    
    // Test for BackupPlanUpdateRequestsBatch batch class
    @isTest
    public static void backupPlanUpdateRequestsTest() {
        Test.startTest(); 
        BackupPlanUpdateRequestsBatch BackupPlanUpdateRequestsObject = new BackupPlanUpdateRequestsBatch(System.today()+1);
        Database.executeBatch(BackupPlanUpdateRequestsObject);
        Test.stopTest();
    }
}