src/objects/Builder__c.object
<CustomObject>
    <description>MG_Builder</description>
    <label>Builder</label>
    <nameField>
        <label>Builder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Data_User__c.object
<CustomObject>
    <description>MG_Data User</description>
    <label>Data User</label>
    <nameField>
        <label>Data User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To assign a Project to a specific Data User record so it will appear in their queue.</inlineHelpText>
        <label>Data User</label>
        <referenceTo>Data_User__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Contact__c.object
<CustomObject>
    <description>MG_Project Contact</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Contacts</relationshipLabel>
        <relationshipName>Project_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project Contact</label>
    <nameField>
        <label>Project Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestMapNearbyProjects.cls
@isTest
private class TestMapNearbyProjects {
	
	@isTest static void createTestData() {
		Builder__c b1 = new Builder__c(
			Name = 'the builder'
		);
		insert b1;

		Data_User__c du1 = new Data_User__c(
			Name = 'test user'
			);
		insert du1;

		Project__c p1 = new Project__c(
			Name = 'the project'
		,	Builder__c = b1.Id
		,	Data_User__c = du1.Id
			);
		insert p1;

		Project_Contact__c pc1 = new Project_Contact__c(
			Name = 'the guy'
		,	Project__c = p1.Id
			);
		insert pc1;
	}
	
	@isTest static void testMapNearbyProjectsPage() {
		createTestData();

		PageReference mapNearbyProjects = Page.MapNearbyProjects;
		Test.setCurrentPage(mapNearbyProjects);
		MapNearbyProjectsExt contExt = new MapNearbyProjectsExt(new ApexPages.Standardcontroller(new Project__c()));

		MapNearbyProjectsExt.getNearby('','');
	}
	
}