src/objects/Builder__c.object
<CustomObject>
    <description>MG_Builder</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Builder Records</relationshipLabel>
        <relationshipName>Builders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Builder</label>
    <nameField>
        <label>Builder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Data_User__c.object
<CustomObject>
    <description>MG_Data User</description>
    <label>Data User</label>
    <nameField>
        <label>Data User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Land_Listing__c.object
<CustomObject>
    <description>MG_Land Listing</description>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing_URL__c</fullName>
        <label>Listing URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Land Listing</label>
    <nameField>
        <label>Land Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Land Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>MG_Plan</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County (legacy)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To assign a Project to a specific Data User record so it will appear in their queue.</inlineHelpText>
        <label>Data User</label>
        <referenceTo>Data_User__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State (legacy)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Cycle__c</fullName>
        <description>Update cycle needs to default to 0 for all new projects so they can be immediately reviewed.  The PUR flow will set the Update Cycle to 27.</description>
        <label>Update Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Contact__c.object
<CustomObject>
    <description>MG_Project Contact</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Contacts</relationshipLabel>
        <relationshipName>Project_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project Contact</label>
    <nameField>
        <label>Project Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestTriggers.cls
@isTest
private class TestTriggers {
	static void setupTestData() { 
		
        Account a1 = new Account(
			Name = 'the account'
		,	Industry = 'Other'
		,	BillingPostalCode ='560029'
			);
		insert a1;
        
        Account a2 = new Account(
			Name = 'the other account'
		,	Industry = 'Other'
		,	BillingPostalCode ='560029'
			);
		insert a2;
        
		Builder__c b1 = new Builder__c(
			Name = 'the builder'
		);
		insert b1;

		Data_User__c du1 = new Data_User__c(
			Name = 'test user'
			);
		insert du1;

		Project__c p1 = new Project__c(
			Name = 'the project'
		,	Builder__c = b1.Id
		,	Data_User__c = du1.Id
		,	Total_Units_Planned__c = 40
		,	Total_Units_Sold__c = 0
			);
		insert p1;

		Project__c p2 = new Project__c(
			Name = 'the other project'
		,	Builder__c = b1.Id
		,	Data_User__c = du1.Id
		,	Total_Units_Planned__c = 40
		,	Total_Units_Sold__c = 0
			);
		insert p2;

		Project_Contact__c pc1 = new Project_Contact__c(
			Name = 'the guy'
		,	Project__c = p1.Id
			);
		insert pc1;

		Plan__c plan1 = new Plan__c(
			Name = 'the plan'
		,	Project__c = p1.Id
			);
		insert plan1;

		Land_Listing__c listing1 = new Land_Listing__c(
			Name = 'the listing'
		,	County__c = 'San Diego'
		,	Location__Latitude__s = 33
		,	Location__Longitude__s = -78
		,	State__c = 'CA'
		,	Zip__c = '92129'
			);
		insert listing1;

		Land_Listing__c listing2 = new Land_Listing__c(
			Name = 'the listing'
		,	County__c = 'San Diego'
		,	Location__Latitude__s = 33
		,	Location__Longitude__s = -78
		,	State__c = 'CA'
		,	Zip__c = '92129'
			);
		insert listing2;

		Land_Listing__c listing3 = new Land_Listing__c(
			Name = 'the listing'
		,	County__c = 'San Diego'
		,	Location__Latitude__s = 33
		,	Location__Longitude__s = -78
		,	State__c = 'CA'
		,	Zip__c = '92129'
			);
		insert listing3;
	}
	
	@isTest static void TestProjectTrigger() {
		setupTestData();
		Project__c theProject = [SELECT Id, Website__c, Name, Total_Units_Planned__c, Total_Units_Sold__c FROM Project__c LIMIT 1];
		theProject.Name = 'updated!!!!!';
		theProject.Website__c = 'http://www.google.com';
		theProject.Total_Units_Sold__c = 2;
        theProject.Update_Cycle__c = '27';
		update theProject;
		List<Project__c> allTheProjects = [SELECT Id, Website__c, Name FROM Project__c];
		update allTheProjects;

		theProject = [SELECT Id, Website__c, Name FROM Project__c WHERE Name = 'the other project' LIMIT 1];
		delete theProject;
	}
    
	@isTest static void TestProjectTriggerGoogleBatch() {
        // Create test accounts to be updated by batch
        List<Project__c> lstProject = new List<project__c>();
        for(Integer i=0; i<10; i++){
            Project__c p = new Project__c();
            p.Name = 'Name'+i;
            p.Website__c = 'http://www.google.com';
            p.Location__Latitude__s = 33;
            p.Location__Longitude__s = -78;
            lstProject.add(p);
        }
        Test.startTest();
        	insert lstProject;
        Test.stopTest();
    }

	@isTest static void TestPlanTrigger() {
		setupTestData();
		Project__c theProject = [SELECT Id, Name FROM Project__c LIMIT 1];
		Plan__c thePlan = [SELECT Id, Name, Price__c FROM Plan__c LIMIT 1];
		thePlan.Name = 'updated!!!!!';
		thePlan.Price__c = 500;
		update thePlan;
	}

	@isTest static void TestBuilderTrigger() {
		setupTestData();
		Builder__c theBuilder = [SELECT Id, Name, Account__c FROM Builder__c LIMIT 1];
		update theBuilder;
		Account theAccount = [SELECT Id FROM Account LIMIT 1];
		theBuilder.Account__c = theAccount.Id;
		update theBuilder;

		delete theBuilder;
	}

	@isTest static void TestLandListingTrigger() {
		setupTestData();
		Land_Listing__c theListing = [SELECT Id, Listing_URL__c, Name FROM Land_Listing__c LIMIT 1];
		theListing.Name = 'updated!!!!!';
		theListing.Listing_URL__c = 'http://www.google.com';
		update theListing;
		List<Land_Listing__c> allTheListings = [SELECT Id, Listing_URL__c, Name FROM Land_Listing__c];
		update allTheListings;
	}

    @isTest static void TestAccountTrigger() {
		setupTestData();
		Account theAccount = [SELECT Id, Name, Industry, BillingPostalCode FROM Account LIMIT 1];
		theAccount.Name = 'Updated Account';
        theAccount.Industry = 'Other';
        theAccount.BillingPostalCode = '02474';
		update theAccount;
        
        List<Account> allTheAccounts = [SELECT Id, Name, Industry, BillingPostalCode FROM Account];
        update allTheAccounts;
	}
    
	@isTest static void TestAccountTriggerGoogleBatch() {
        // Create test accounts to be updated by batch
        List<Account> lstAccount = new List<Account>();
        for(Integer i=0; i<10; i++){
            Account a = new Account();
            a.Name = 'Name'+i;
            a.Industry = 'Other';
            a.BillingPostalCode ='10123';
            lstAccount.add(a);
        }
        Test.startTest();
        	insert lstAccount;
        Test.stopTest();
    }
    
}