src/objects/Builder__c.object
<CustomObject>
    <description>MG_Builder</description>
    <label>Builder</label>
    <nameField>
        <label>Builder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Update_Request__c.object
<CustomObject>
    <description>MG_Project Update Request</description>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_Request_Status__c</fullName>
        <label>Update Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Update Request</label>
    <nameField>
        <displayFormat>PUR-{000000}</displayFormat>
        <label>Project Update Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectStatusBoardController.cls
public without sharing class ProjectStatusBoardController {
	public ProjectStatusBoardController() {
		
	}

	public String getPendingUpdateCount() {
		Integer pendingUpdateCount = [SELECT COUNT() FROM Project_Update_Request__c WHERE Update_Request_Status__c = 'Pending'];
		String pendingUpdateCountText = pendingUpdateCount.format();
		return pendingUpdateCountText;
	}

	public String getInProgressUpdateCount() {
		Integer inProgressUpdateCount = [SELECT COUNT() FROM Project_Update_Request__c WHERE Update_Request_Status__c = 'In Progress'];
		String inProgressUpdateCountText = inProgressUpdateCount.format();
		return inProgressUpdateCountText;
	}

	public String getTotalBuilderCount() {
		Integer totalBuilderCount = [SELECT COUNT() FROM Builder__c WHERE Id IN (SELECT Builder__c FROM Project__c)];
		String totalBuilderCountText = totalBuilderCount.format();
		return totalBuilderCountText;
	}

	public String getTotalProjectCount() {
		Integer totalProjectCount = [SELECT COUNT() FROM Project__c];
		String totalProjectCountText = totalProjectCount.format();
		return totalProjectCountText;
	}
}