src/objects/Community__c.object
<CustomObject>
    <description>MG_Community</description>
    <fields>
        <fullName>Open_Date__c</fullName>
        <inlineHelpText>This is an estimated value.</inlineHelpText>
        <label>Oldest Project Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Sold Out</fullName>
                </value>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleIntegrationHelperSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GoogleIntegrationHelperSettings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Master_Plan_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Master Plan (Community)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Community__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Master Plan</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Projects - Master Plan</relationshipLabel>
        <relationshipName>Projects_Master_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Neighborhood</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Community__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Neighborhood</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Projects - Neighborhood</relationshipLabel>
        <relationshipName>Projects_Neighborhood</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Sold Out</fullName>
                </value>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>--Other--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Village_Community__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Village</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Community__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Village</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Projects - Village</relationshipLabel>
        <relationshipName>Projects_Village</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityProjectsMapExtnTest.cls
@isTest 
public class CommunityProjectsMapExtnTest {
    static testMethod void testMethod1() 
    {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        GoogleIntegrationHelperSetting__c AddressEndpoint = new GoogleIntegrationHelperSetting__c(Name='AddressEndpoint', Value__c = 'https://maps.googleapis.com/maps/api/geocode/json');
        insert AddressEndpoint;
        GoogleIntegrationHelperSetting__c AddressApiKey = new GoogleIntegrationHelperSetting__c(Name='AddressApiKey', Value__c = 'AIzaSyAMCeNu4PTVrFpBNqNRzl7-s6YnXI_vPpM');
        insert AddressApiKey;  
        GoogleIntegrationHelperSetting__c ClientId = new GoogleIntegrationHelperSetting__c(Name='ClientId', Value__c = 'gme-meyersresearch');
        insert ClientId;        
        GoogleIntegrationHelperSetting__c CryptoKey = new GoogleIntegrationHelperSetting__c(Name='CryptoKey', Value__c = 'PAIt9ZFY6hUf6t33fsilLI2TGRM=');
        insert CryptoKey;  
        GoogleIntegrationHelperSetting__c UrlEndpoint = new GoogleIntegrationHelperSetting__c(Name='UrlEndpoint', Value__c = 'https://www.googleapis.com/urlshortener/v1/url');
        insert UrlEndpoint;
        
        Schema.DescribeSObjectResult R = Community__c.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
        
        Community__c mcomm = new Community__c();
        mcomm.RecordTypeId = RT[0].getRecordTypeId();
        mcomm.name = 'TestCommu1';
        mcomm.Open_Date__c = system.today();
        insert mcomm;
        Community__c ncomm = new Community__c();
        ncomm.RecordTypeId = RT[1].getRecordTypeId();
        ncomm.name = 'TestCommu1';
        ncomm.Open_Date__c = system.today();
        insert ncomm;
        Community__c vcomm = new Community__c();
        vcomm.RecordTypeId = RT[2].getRecordTypeId();
        vcomm.name = 'TestCommu1';
        vcomm.Open_Date__c = system.today();
        insert vcomm;
        
        Project__c p = new Project__c();
        p.Name = 'TestProject';
        p.Status__c = 'Active';
        p.open_Date__c = system.today()-1;
        p.Total_Units_Planned__c = 10;
        p.Total_Units_Sold__c = 5;
        p.Website__c = 'http://www.test.com/';
        p.Location__Latitude__s = 40.731;
        p.Location__Longitude__s = -73.997;
        p.Village_Community__c = vcomm.id;
        insert p;
        
        Project__c p2 = new Project__c();
        p2.Name = 'TestProject';
        p2.Status__c = 'Active';
        p2.open_Date__c = system.today()-1;
        p2.Total_Units_Planned__c = 10;
        p2.Total_Units_Sold__c = 5;
        p2.Website__c = 'http://www.test.com/';
        p2.Location__Latitude__s = 40.731;
        p2.Location__Longitude__s = -73.997;
        p2.Neighborhood_Community__c = ncomm.id;
        insert p2;
        
        Project__c p3 = new Project__c();
        p3.Name = 'TestProject2';
        p3.Status__c = 'Active';
        p3.open_Date__c = system.today()-1;
        p3.Total_Units_Planned__c = 10;
        p3.Total_Units_Sold__c = 5;
        p3.Website__c = 'http://www.test.com/';
        p3.Location__Latitude__s = 40.731;
        p3.Location__Longitude__s = -73.997;
        p3.Master_Plan_Community__c = mcomm.id;
        insert p3;
        
        PageReference pageRef = Page.CommunityProjectsMap;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(mcomm.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(mcomm);
        CommunityProjectsMapExtn testCommuCtl = new CommunityProjectsMapExtn(sc);
        
        pageRef.getParameters().put('Id', String.valueOf(vcomm.Id));
        ApexPages.StandardController sc2 = new ApexPages.StandardController(vcomm);
        CommunityProjectsMapExtn testCommuCt2 = new CommunityProjectsMapExtn(sc);
        
        pageRef.getParameters().put('Id', String.valueOf(ncomm.Id));
        ApexPages.StandardController sc3 = new ApexPages.StandardController(ncomm);
        CommunityProjectsMapExtn testCommuCt3 = new CommunityProjectsMapExtn(sc);
    }
}