src/objects/Community__c.object
<CustomObject>
    <description>MG_Community</description>
    <fields>
        <fullName>Open_Date__c</fullName>
        <inlineHelpText>This is an estimated value.</inlineHelpText>
        <label>Oldest Project Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Sold Out</fullName>
                </value>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Community</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Data_User__c.object
<CustomObject>
    <description>MG_Data User</description>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meyers Temp</fullName>
                    <default>true</default>
                    <label>Meyers Temp</label>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data User</label>
    <nameField>
        <label>Data User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Assessments__c</fullName>
        <inlineHelpText>An overall tax rate, including a base tax rate</inlineHelpText>
        <label>Total Tax Rate (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To assign a Project to a specific Data User record so it will appear in their queue.</inlineHelpText>
        <label>Data User</label>
        <referenceTo>Data_User__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HOA_2__c</fullName>
        <inlineHelpText>This is a secondary HOA monthly fee.</inlineHelpText>
        <label>Monthly HOA #2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <label>Monthly HOA #1</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lot_Dimension__c</fullName>
        <label>Lot Dimension</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meyers_Disposition_calc__c</fullName>
        <formula>IF(NOT(ISNULL(Open_Date__c)) 
&amp;&amp; NOT(ISNULL(Total_Units_Sold__c)) 
&amp;&amp; NOT(ISNULL(Total_Units_Planned__c)) 
&amp;&amp; NOT(ISNULL(Min_Unit_Size_display__c)) 
&amp;&amp; Min_Price_display__c &gt; 0
    , &apos;Baselined&apos;
    , &apos;Follow Up&apos;)</formula>
        <inlineHelpText>Baselines are triggered when open date, total units sold, total units planned, unit size display and min price display are populated.</inlineHelpText>
        <label>Meyers Disposition (calc)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min_Price__c</fullName>
        <label>Min Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attached</fullName>
                </value>
                <value>
                    <fullName>Detached</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sold_Out_Date__c</fullName>
        <label>Sold Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Sold Out</fullName>
                </value>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>--Other--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Typical_Lot_Size__c</fullName>
        <label>Typical Lot Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ZIC_Date__c</fullName>
        <description>Date Project will be added to the ZIC site for review</description>
        <inlineHelpText>Date Project will be added to the ZIC site for review</inlineHelpText>
        <label>ZIC Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Update_Request__c.object
<CustomObject>
    <description>MG_Project Update Request</description>
    <fields>
        <fullName>Builder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Builder</label>
        <referenceTo>Builder__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data User</label>
        <referenceTo>Data_User__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HOA_2__c</fullName>
        <label>Monthly HOA #2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <label>Monthly HOA #1</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lot_Dimension__c</fullName>
        <label>Lot Dimension</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meyers_Disposition_calc__c</fullName>
        <label>Meyers Disposition (calc)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min_Price__c</fullName>
        <label>Min Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_HOA_2__c</fullName>
        <label>Previous Monthly HOA #2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_HOA__c</fullName>
        <label>Previous Monthly HOA #1</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_Lot_Dimension__c</fullName>
        <label>Previous Lot Dimension</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Meyers_Disposition_calc__c</fullName>
        <label>Previous Meyers Disposition (calc)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Open_Date__c</fullName>
        <label>Previous Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_Product_Type__c</fullName>
        <label>Previous Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attached</fullName>
                </value>
                <value>
                    <fullName>Detached</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Sold_Out_Date__c</fullName>
        <label>Previous Sold Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_Status__c</fullName>
        <label>Previous Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Sold Out</fullName>
                </value>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>--Other--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Typical_Lot_Size__c</fullName>
        <label>Previous Typical Lot Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attached</fullName>
                </value>
                <value>
                    <fullName>Detached</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Out_Date__c</fullName>
        <label>Sold Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Sold Out</fullName>
                </value>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>--Other--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Typical_Lot_Size__c</fullName>
        <label>Typical Lot Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Project Update Request</label>
    <nameField>
        <displayFormat>PUR-{000000}</displayFormat>
        <label>Project Update Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrgProjectsHandlerTest.cls
/*
* @Description : Test Class for TrgProjectsHandler and trgProjects
* @CreatedDate  : 05 March 2019
*/
@isTest
public class TrgProjectsHandlerTest {

/*
* @Description : Setup Method to create data
*/    
    @testSetup
    public static void setup(){
       
        //Create Builder__c record
        Builder__c buliderOne = new Builder__c();
        buliderOne.Name='Pulte';
        insert buliderOne;
        
         //Create Community__c record
        Schema.DescribeSObjectResult R = Community__c.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
        
        Community__c mcomm = new Community__c();
        mcomm.RecordTypeId = RT[0].getRecordTypeId();
        mcomm.name = 'mTestCommu1';
        mcomm.Open_Date__c = system.today();
        insert mcomm;
    }


/*
* @Description : Test Method for trgProjects
*/    
    public static testMethod void beforeInsertTest(){
        test.startTest();
            Builder__c buliderOne = [Select Id From Builder__c LIMIT 1];
            Community__c mcomm  = [Select Id From Community__c LIMIT 1];
            
            //Insert Project records
            Project__c project = createProject(buliderOne, mcomm);
            List<Project_Update_Request__c> PURList = createPURList(project, buliderOne);
            
            //Create Data_User__c Record 
            Data_User__c du = new Data_User__c();
            du.Name            ='TestUser';
            du.Organization__c ='Meyers Temp';
            insert du;
            
            
            //update project
            project.Total_Units_Sold__c = 20;
            project.Total_Units_Planned__c = 20;
            project.Min_Price__c = 1000;
            project.Data_User__c = du.Id;
            project.Website__c = 'www.tesing.com';
            project.ZIC_Date__c = system.today()-8;
            update project;
            
            //delete project
            delete project;
            
            
            //Insert Multiple Project__c
            List<Project__c> projectsToUpdate = new List<Project__c>(); 
            projectsToUpdate.add(createProject(buliderOne, mcomm));
            projectsToUpdate.add(createProject(buliderOne, mcomm));
            projectsToUpdate.add(createProject(buliderOne, mcomm));
            
            //update 
            for( Project__c pro : projectsToUpdate ){
                pro.Total_Units_Sold__c = 20;
                pro.Total_Units_Planned__c = 20;
                pro.Min_Price__c = 1000;
                pro.Data_User__c = du.Id;
                pro.Website__c = 'www.tesing.com';
                pro.ZIC_Date__c = system.today()-8;
            }
            update projectsToUpdate;
        test.stopTest();
    }
    
/*
* @Description : Method to create Project_Update_Request__c record
* @Param : Project__c pro, Builder__c buliderOne 
* @Return Value : List<Project_Update_Request__c> PURList
*/    
    private static List<Project_Update_Request__c> createPURList(Project__c pro, Builder__c buliderOne ){
        List<Project_Update_Request__c> PURList = new List<Project_Update_Request__c>();
       
            Project_Update_Request__c pur1 = new Project_Update_Request__c();
            pur1.Builder__c = buliderOne.Id;
            pur1.Project__c = pro.Id;
            pur1.Status__c = 'Active'; 
            pur1.Previous_Status__c = 'Active';
            pur1.Previous_Meyers_Disposition_calc__c = 'Follow Up';
            pur1.Meyers_Disposition_calc__c = 'Baselined';
            pur1.Previous_Status__c = 'Upcoming';
            pur1.Product_Type__c =  'Attached';
            pur1.Previous_Product_Type__c = 'Detached';
            pur1.Lot_Dimension__c = 'test1';
            pur1.Previous_Lot_Dimension__c ='test2';
            pur1.Open_Date__c = system.today();
            pur1.Previous_Open_Date__c = system.today()-1;
            pur1.Sold_Out_Date__c = system.today();
            pur1.Previous_Sold_Out_Date__c = system.today()-1;
            pur1.Previous_Typical_Lot_Size__c = 1;
            pur1.Typical_Lot_Size__c = 210; 
            pur1.Previous_HOA__c = 1;
            pur1.HOA__c = 210;
            pur1.Previous_HOA_2__c =1;
            pur1.HOA_2__c = 210;
            pur1.Assessments__c = 4;
            pur1.Total_Units_Sold__c = 11;
            pur1.Previous_Total_Units_Sold__c = 1;
            pur1.Update_Request_Status__c = 'In Progress';
            PURList.add(pur1);

        Insert PURList;
        return PURList;
    }

/*
* @Description : Method to create Project__c record
* @Param : Builder__c buliderOne, Community__c mcomm
* @Return Value : Project__c masp
*/      
    private static Project__c createProject(Builder__c buliderOne, Community__c mcomm){
        Project__c masp = new Project__c();
        masp.Name = 'mTestProject';
        masp.Builder__c = buliderOne.id;
        masp.Status__c = 'Active';
        masp.open_Date__c = system.today()-1;
        masp.Total_Units_Planned__c = 10;
        masp.Total_Units_Sold__c = 5;
        masp.Website__c = 'http://www.test.com/';
        masp.Location__Latitude__s = 40.731;
        masp.Location__Longitude__s = -73.997;
        masp.Master_Plan_Community__c = mcomm.id;
        masp.Min_Price__c = 200;
        masp.Location__Latitude__s =56.47;
        masp.ZIC_Date__c = system.today()-2;
        Insert masp;
        return masp;
    }
}