src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>FC_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Subscription_Number__c</fullName>
        <externalId>true</externalId>
        <label>(FC) Subscription Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__RenewalTerm__c</fullName>
        <label>Renewal Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ContractCache.cls
public class FC_ContractCache {

    private static String[] CONTRACT_FIELDS = new String[]{
            'Id', 'FC_Price_Book__c', 'FC_Subscription_Number__c', 'FC_Subscription__c',
            'FC_Subscription__r.Zuora__CustomerAccount__c', 'FC_Subscription__r.Zuora__RenewalTerm__c',
            'FC_Subscription__r.Zuora__TermEndDate__c', 'FC_Subscription__r.Zuora__TermStartDate__c'
    };

    private static final Map<ID, Contract> BY_ID_MAP = new Map<ID, Contract>();
    private static final Map<String, Contract> BY_SUBSCRIPTION_NUMBER_MAP = new Map<String, Contract>();

    private static final String SOQL_BASE;

    static {
        SOQL_BASE = String.format('select {0} from Contract',
                new String[]{
                        String.join(CONTRACT_FIELDS, ', ')
                });
    }

    public static void clearCache() {
        BY_ID_MAP.clear();
        BY_SUBSCRIPTION_NUMBER_MAP.clear();
    }


    public static Map<ID, Contract> findByIds(Set<ID> recordIds) {
        Map<ID, Contract> results = new Map<ID, Contract>();
        Set<ID> recordIdsToQuery = new Set<ID>();
        for (ID recordId : recordIds) {
            if (BY_ID_MAP.containsKey(recordId)) {
                results.put(recordId, BY_ID_MAP.get(recordId));
            } else {
                recordIdsToQuery.add(recordId);
            }
        }
        if (!recordIdsToQuery.isEmpty()) {
            String soql = SOQL_BASE + ' where Id in :recordIdsToQuery';
            for (Contract record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                results.put(record.Id, record);
            }
        }
        return results;
    }

    public static Map<String, Contract> findBySubscriptionNumbers(Set<String> subcriptionNumbers) {
        Map<String, Contract> results = new Map<String, Contract>();
        Set<String> recordNumbersToQuery = new Set<String>();
        for (String subscriptionNumber : subcriptionNumbers) {
            if (BY_SUBSCRIPTION_NUMBER_MAP.containsKey(subscriptionNumber)) {
                results.put(subscriptionNumber, BY_SUBSCRIPTION_NUMBER_MAP.get(subscriptionNumber));
            } else {
                recordNumbersToQuery.add(subscriptionNumber);
            }
        }
        if (!recordNumbersToQuery.isEmpty()) {
            String soql = SOQL_BASE + ' where FC_Subscription_Number__c in :recordNumbersToQuery';
            for (Contract record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                BY_SUBSCRIPTION_NUMBER_MAP.put(record.FC_Subscription_Number__c, record);
                results.put(record.FC_Subscription_Number__c, record);
            }
        }
        return results;


    }

}