src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>How_May_We_Help_You__c</fullName>
        <label>How May We Help You?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Become a Member</fullName>
                </value>
                <value>
                    <fullName>Purchase Information</fullName>
                </value>
                <value>
                    <fullName>Consulting/Market Study</fullName>
                </value>
                <value>
                    <fullName>Training Request</fullName>
                </value>
                <value>
                    <fullName>Media Request</fullName>
                </value>
                <value>
                    <fullName>Customer Support/Training</fullName>
                </value>
                <value>
                    <fullName>Billing Questions</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Join eList</fullName>
                </value>
                <value>
                    <fullName>Download White Paper</fullName>
                </value>
                <value>
                    <fullName>Speakers Bureau Information</fullName>
                </value>
                <value>
                    <fullName>Contact your Local Expert</fullName>
                </value>
                <value>
                    <fullName>Technical Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Attendee - Private Consultation</fullName>
                </value>
                <value>
                    <fullName>Attendee - Quarterly Briefing</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Bill to</fullName>
                </value>
                <value>
                    <fullName>Bill to (Legacy)</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Decision Maker - All Aspects</fullName>
                </value>
                <value>
                    <fullName>Decision Maker – CRM</fullName>
                </value>
                <value>
                    <fullName>Decision Maker - Data and Analytics</fullName>
                </value>
                <value>
                    <fullName>Decision Maker – Events</fullName>
                </value>
                <value>
                    <fullName>Decision Maker – Marketing Services</fullName>
                </value>
                <value>
                    <fullName>Decision Maker – Media</fullName>
                </value>
                <value>
                    <fullName>Decision Maker – Sales Enablement</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Influencer – All Aspects</fullName>
                </value>
                <value>
                    <fullName>Influencer – CRM</fullName>
                </value>
                <value>
                    <fullName>Influencer - Data and Analytics</fullName>
                </value>
                <value>
                    <fullName>Influencer – Events</fullName>
                </value>
                <value>
                    <fullName>Influencer – Marketing Services</fullName>
                </value>
                <value>
                    <fullName>Influencer – Media</fullName>
                </value>
                <value>
                    <fullName>Influencer – Sales Enablement</fullName>
                </value>
                <value>
                    <fullName>Location Contact - Non-user</fullName>
                </value>
                <value>
                    <fullName>Location Contact - User</fullName>
                </value>
                <value>
                    <fullName>Media Creative Contact</fullName>
                </value>
                <value>
                    <fullName>Purchaser</fullName>
                </value>
                <value>
                    <fullName>Sold to</fullName>
                </value>
                <value>
                    <fullName>Technical Support</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Default_LeadOwner_MetroStudy__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>UserID__c</fullName>
        <label>User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Default LeadOwner MetroStudy</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>How_may_we_help_you__c</fullName>
        <label>How may we help you?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Become a Member</fullName>
                </value>
                <value>
                    <fullName>Purchase Information/Reports</fullName>
                </value>
                <value>
                    <fullName>Consulting/Market Study</fullName>
                </value>
                <value>
                    <fullName>Training Request</fullName>
                </value>
                <value>
                    <fullName>Media Request</fullName>
                </value>
                <value>
                    <fullName>Customer Support/Training Request</fullName>
                </value>
                <value>
                    <fullName>Billing Questions</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Join eList</fullName>
                </value>
                <value>
                    <fullName>Download White Paper</fullName>
                </value>
                <value>
                    <fullName>Speakers Bureau Information</fullName>
                </value>
                <value>
                    <fullName>Contact a Local Market Expert</fullName>
                </value>
                <value>
                    <fullName>Technical Support</fullName>
                </value>
                <value>
                    <fullName>Have a Sales Representative Contact Me</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Key Influencer</fullName>
                </value>
                <value>
                    <fullName>Purchaser</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Purchasing Agent</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Market_Intelligence_Lead_Record_Type</fullName>
        <active>true</active>
        <businessProcess>Market Intelligence Lead Process</businessProcess>
        <label>MS_Market Intelligence Lead Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Media</fullName>
        <active>true</active>
        <businessProcess>Media</businessProcess>
        <label>HW_Media</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metrostudy_ZIP_Code__c.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_Market__c</fullName>
        <label>Metrostudy Market</label>
        <referenceTo>MetrostudyMarket__c</referenceTo>
        <relationshipLabel>Metrostudy ZIP Codes</relationshipLabel>
        <relationshipName>Metrostudy_ZIP_Codes1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Metrostudy ZIP Code</label>
    <nameField>
        <label>Metrostudy ZIP Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy ZIP Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetrostudyMarket__c.object
<CustomObject>
    <description>Metrostudy Survey Markets</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metroclient Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Markets</relationshipLabel>
        <relationshipName>MetrostudyMarkets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MetroStudyLeadAssignmentTriggerHandler.cls
/*******************************************************************************************************************
** Module Name   : MetroStudyLeadAssignmentTriggerHandler
** Description   : Handler class for MSLeadAssignment trigger
** Throws        : NA
** Calls         : NA
** Test Class    : MetroStudyLeadAssignmentTH_test
** 
** Organization  : Rainmaker
**
** Revision History:-
** Version             Date            Author           Description of Action
** 1.0                 06/20/16        Rainmaker             
******************************************************************************************************************/

public with sharing class MetroStudyLeadAssignmentTriggerHandler implements ITrigger{
    
    public MetroStudyLeadAssignmentTriggerHandler(){}
    public void bulkBefore(){}
    public void bulkAfter(){}
    public void beforeInsert(){
       
        
    }
    public void beforeUpdate(){
        /* Commented as we only need to check this on Insert 
        if(Utility.IsLeadUpdate){
            updateLeadAssignment();
        }
        */
    }
    public void beforeDelete(){}
    public void afterInsert(){
    
     // use Utility.IsFromLeadInsert in update logic and set this to false
       if(Utility.IsFromLeadInsert){
            updateLeadAssignment();
        }
        
    }
    public void afterUpdate(){
    
        
       
    }
    public void afterDelete(){}
    public void afterUnDelete(){}
    public void andFinally(){}
    
    
/*-----------Service Methods-------------*/    
    
    public void updateLeadAssignment(){
        try{
            Set<String> zipCodeSet = new Set<String>();
            List<Lead> leadDBDList = new List<Lead>();
            List<Lead> leadRDList = new List<Lead>();
            //Map<String,Lead> zipCodesDBD=new Map<String,Lead>();
            //Map<String,Lead> zipCodesRD=new Map<String,Lead>();
            Map<String,Lead> LeadMap = new Map<String,Lead>();
            
            List<RecordType> MktIntelRecordType = [select id from RecordType where sObjecttype = 'Lead' AND  DeveloperName = 'Market_Intelligence_Lead_Record_Type' limit 1];
            Default_LeadOwner_MetroStudy__c defaultLeadOwner = Default_LeadOwner_MetroStudy__c.getValues('DefaultLeadOwner');        
            
           for(Lead L : (List<Lead>)trigger.new){
                LeadMap.put(L.Id, null);
            }
            
            if(LeadMap.size()>0){
                for(Lead L : [select Id, Name, RecordTypeId, How_may_we_help_you__c, LeadSource, Industry, postalCode, OwnerId FROM Lead WHERE Id in: LeadMap.keyset()]){
                    LeadMap.put(L.Id, L);
                }
            }
            
            if(LeadMap.size() > 0){
                for(Lead leadObj : LeadMap.values()){
                    system.debug('The how we may help you is ' + leadObj.How_may_we_help_you__c + 'Industry ' + leadObj.Industry + 'Lead Source ' + leadObj.leadsource);
                    if(MktIntelRecordType != null && MktIntelRecordType[0] != null && leadObj.RecordTypeId == MktIntelRecordType[0].id && leadObj.LeadSource != null && (leadObj.LeadSource.startsWith('MS_') ||leadObj.LeadSource == 'Jigsaw')  && (leadObj.LeadSource != 'MS_Marketing_Newsletter')  && leadObj.Industry != 'Building Product Manufacturer'){
                        //if(leadObj.How_may_we_help_you__c != 'Training Request' && leadObj.How_may_we_help_you__c != 'Media Request' && leadObj.How_may_we_help_you__c != 'Customer Support/Training Request' && leadObj.How_may_we_help_you__c != 'Billing Questions' && leadObj.How_may_we_help_you__c != 'Speakers Bureau Information' && leadObj.How_may_we_help_you__c != 'Contact a Local Market Expert' && leadObj.How_may_we_help_you__c != 'Technical Support'){
                        system.debug('The how we may help you is ' + leadObj.How_may_we_help_you__c + 'Industry ' + leadObj.Industry );
                        if(leadObj.How_may_we_help_you__c == null || leadObj.How_may_we_help_you__c == 'Purchase Information/Reports' || leadObj.How_may_we_help_you__c == 'Consulting/Market Study' || leadObj.How_may_we_help_you__c == 'Have a Sales Representative Contact Me' || leadObj.How_may_we_help_you__c == 'General Information' || leadObj.How_may_we_help_you__c == 'Other' || leadObj.How_may_we_help_you__c == 'Become a Member'){
                            zipCodeSet.add(leadobj.postalCode.substringBefore('-'));
                            leadDBDList.add(leadObj);
                            //zipCodesDBD.put(leadobj.postalCode.substringBefore('-'),leadObj);
                            
                        }
                        else if(leadObj.How_may_we_help_you__c == 'Training Request' || leadObj.How_may_we_help_you__c == 'Billing Questions' || leadObj.How_may_we_help_you__c == 'Speakers Bureau Information' || leadObj.How_may_we_help_you__c == 'Contact a Local Market Expert' || leadObj.How_may_we_help_you__c == 'Technical Support'){
                            //zipCodesRD.put(leadobj.postalCode.substringBefore('-'),leadObj);
                            zipCodeSet.add(leadobj.postalCode.substringBefore('-'));
                            leadRDList.add(leadObj);
                        }
                    }
                }
            }
            
            Map<String,List<String>> serviceMap1=new Map<String,List<String>>();
            if(zipCodeSet.size()>0){
                for(Metrostudy_ZIP_Code__c mzc:[select Name,Metrostudy_Market__r.Geography__c,Metrostudy_Market__r.Geography__r.SalesRegion__c from Metrostudy_ZIP_Code__c where name in:zipcodeSet]){
                    if(mzc.Metrostudy_Market__c!=null && mzc.Metrostudy_Market__r.Geography__c!=null && mzc.Metrostudy_Market__r.Geography__r.SalesRegion__c!=null){
                        if(!serviceMap1.containsKey(mzc.Metrostudy_Market__r.Geography__r.SalesRegion__c))
                            serviceMap1.put(mzc.Metrostudy_Market__r.Geography__r.SalesRegion__c,new List<String>());
                        serviceMap1.get(mzc.Metrostudy_Market__r.Geography__r.SalesRegion__c).add(mzc.name);
                    }
                }
            }
            Map<String,List<MetrostudySalesRegionAssignment__c>> finalServiceMap=new Map<String,List<MetrostudySalesRegionAssignment__c>>(); 
            if(serviceMap1.size()>0){
                for(MetrostudySalesRegionAssignment__c msra:[select id,SalesRegion__c,User__c,Role__c from MetrostudySalesRegionAssignment__c  where SalesRegion__c in:serviceMap1.keySet()]){
                    if(serviceMap1.containsKey(msra.SalesRegion__c)){
                        for(String key:serviceMap1.get(msra.SalesRegion__c)){
                            if(!finalServiceMap.containsKey(key)){
                                finalServiceMap.put(key,new List<MetrostudySalesRegionAssignment__c>());
                            }
                            finalServiceMap.get(key).add(msra);
                        }
                    }
                }
            }
            List<Lead> updateLeadList = new List<Lead>();
            if(finalServiceMap.size()>0){
                for(Lead leadObj: leadDBDList){
                    if(leadObj.PostalCode != null){
                        if(finalServiceMap.containsKey(leadObj.PostalCode.substringBefore('-'))){
                            for(MetrostudySalesRegionAssignment__c msra:finalServiceMap.get(leadObj.PostalCode.substringBefore('-'))){
                                if(msra.Role__c=='DBD'){
                                    if(msra.User__c != null)
                                        leadObj.OwnerId = msra.User__c;
                                    else{
                                        if(defaultLeadOwner != null && defaultLeadOwner.UserID__c !=null)
                                            leadObj.OwnerId = defaultLeadOwner.UserID__c; 
                                    }
                                    updateLeadList.add(leadObj);
                                }
                            }
                        }
                    }  
                }
                for(Lead leadObj: leadRDList){
                    if(leadObj.PostalCode != null){
                        if(finalServiceMap.containsKey(leadObj.PostalCode.substringBefore('-'))){
                            for(MetrostudySalesRegionAssignment__c msra:finalServiceMap.get(leadObj.PostalCode.substringBefore('-'))){
                                if(msra.Role__c=='RD'){
                                    if(msra.User__c != null)
                                        leadObj.OwnerId = msra.User__c;
                                    else{
                                        if(defaultLeadOwner != null && defaultLeadOwner.UserID__c !=null)
                                            leadObj.OwnerId = defaultLeadOwner.UserID__c; 
                                    }
                                    updateLeadList.add(leadObj);
                                }
                            }
                        }
                    }  
                }
            }
            
            if(updateLeadList.size() > 0){
                Utility.IsFromLeadInsert = false;
                update updateLeadList;
            }
        }
        catch(Exception e){
            system.debug(' ==== MetroStudyLeadAssignmentTriggerHandler ====> '+e.getLineNumber()+' == '+e.getMessage());
        }
    }  
}