src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>FC_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/echosign_dev1__SIGN_Agreement__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchosignHelp</customHelpPage>
    <fields>
        <fullName>echosign_dev1__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>R00N70000001hM2REAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pre-Send</fullName>
                </value>
                <value>
                    <fullName>Out for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Signature</fullName>
                </value>
                <value>
                    <fullName>Send in Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Approval</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>What channel does the deal belong to?</description>
        <inlineHelpText>What channel does the deal belong to?</inlineHelpText>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BPM</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>REE</fullName>
                </value>
                <value>
                    <fullName>Strategic Account</fullName>
                </value>
                <value>
                    <fullName>Templeton</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Annualize_New_Revenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Annualize New Revenue?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Initial_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <label>(FC) Initial Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Renew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Term_Type__c</fullName>
        <defaultValue>&quot;TERMED&quot;</defaultValue>
        <label>(FC) Term Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                    <default>true</default>
                    <label>TERMED</label>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MS_Segments__c</fullName>
        <label>MS Segments</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BPM</fullName>
                </value>
                <value>
                    <fullName>Builder</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Emerging Builder</fullName>
                </value>
                <value>
                    <fullName>Finance/AD&amp;C</fullName>
                </value>
                <value>
                    <fullName>Finance/Institutional</fullName>
                </value>
                <value>
                    <fullName>Finance/Mortgage</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Templeton</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Type__c</fullName>
        <label>Purchase Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>One-time</fullName>
                </value>
                <value>
                    <fullName>Price Increase Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_For_Postponement__c</fullName>
        <label>Change in Status Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a renewal?</description>
        <label>Renewal?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>AppStage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Approved</fullName>
        <active>true</active>
        <label>Approved</label>
    </recordTypes>
    <recordTypes>
        <fullName>Signed</fullName>
        <active>true</active>
        <label>Signed</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__TermSettingType__c</fullName>
        <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
        <label>Term Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_OpportunityCache.cls
public class FC_OpportunityCache {

    private static String[] OPPORTUNITY_FIELDS = new String[]{
            'Id', 'Amount', 'ContractId', 'Contract.FC_Subscription__c',
            'Contract.FC_Subscription__r.Zuora__TermSettingType__c', 'Channel_Type__c', 'FC_Annualize_New_Revenue__c',
            'FC_Initial_Term__c', 'FC_Renew__c', 'FC_Term_Type__c', 'Purchase_Type__c', 'Reason_For_Postponement__c',
            'MS_Segments__c', 'Pricebook2Id', 'RecordTypeId', 'RecordType.DeveloperName', 'RecordType.Name',
            'Renewal__c', 'StageName',
            '(select Id, echosign_dev1__Status__c from echosign_dev1__R00N70000001hM2REAU__r where echosign_dev1__Status__c = \'Signed\')',
            '(select Id from zqu__Quotes__r where Approval_Status__c = \'Approved\')'
    };

    private static final Map<ID, Opportunity> BY_ID_MAP = new Map<ID, Opportunity>();

    private static final String SOQL_BASE;

    static {
        SOQL_BASE = String.format('select {0} from Opportunity',
                new String[]{
                        String.join(OPPORTUNITY_FIELDS, ', ')
                });
    }

    public static void clearCache() {
        BY_ID_MAP.clear();
    }

    public static Map<ID, Opportunity> findByIds(Set<ID> opportunityIds) {
        Map<ID, Opportunity> results = new Map<ID, Opportunity>();
        Set<ID> opportunityIdsToQuery = new Set<ID>();
        for (ID opportunityId : opportunityIds) {
            if (BY_ID_MAP.containsKey(opportunityId)) {
                results.put(opportunityId, BY_ID_MAP.get(opportunityId));
            } else {
                opportunityIdsToQuery.add(opportunityId);
            }
        }
        if (opportunityIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Id in :opportunityIdsToQuery';
            for (Opportunity opportunityRecord : Database.query(soql)) {
                BY_ID_MAP.put(opportunityRecord.Id, opportunityRecord);
                results.put(opportunityRecord.Id, opportunityRecord);
            }
        }
        return results;
    }

}