src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>FC_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FC_Billing_Instruction_Step__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Instruction_Set__c</fullName>
        <label>Billing Instruction Set</label>
        <referenceTo>FC_Billing_Instruction_Set__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Steps</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contract_Effective_Date__c</fullName>
        <label>Contract Effective Date</label>
        <type>Date</type>
    </fields>
    <label>(FC) Billing Instruction Step</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Billing Instruction Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Steps</pluralLabel>
    <recordTypes>
        <fullName>Subscribe</fullName>
        <active>true</active>
        <label>Subscribe</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>OneTime</fullName>
                    <label>One-Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography_Type__c</fullName>
        <formula>Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name</formula>
        <label>Geography Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <formula>Product_Geography__r.Geography__r.Name</formula>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Geography__c</fullName>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Annualize_New_Revenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Annualize New Revenue?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Initial_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <label>(FC) Initial Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_New_Revenue__c</fullName>
        <label>(FC) New Revenue</label>
        <summarizedField>OpportunityLineItem.FC_New_Revenue_Formula__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>FC_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Renew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Term_Type__c</fullName>
        <defaultValue>&quot;TERMED&quot;</defaultValue>
        <label>(FC) Term Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                    <default>true</default>
                    <label>TERMED</label>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a renewal?</description>
        <label>Renewal?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Skip_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Validation</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>MS_Opportunity_BPM</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <label>MS - Opportunity BPM</label>
    </recordTypes>
    <recordTypes>
        <fullName>MS_Opportunity_Zuora_Duplicates</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <description>Created to manage duplicate opportunities created during the CPQ pilot Q2&apos;19</description>
        <label>MS Opportunity - Zuora Duplicates</label>
    </recordTypes>
    <recordTypes>
        <fullName>Market_Intelligence_Opportunity_Record_Type</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <description>Use this for Revenue Opps</description>
        <label>MS Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Metrostudy_Opportunity_REE</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <label>MS_Metrostudy Opportunity - REE</label>
    </recordTypes>
    <recordTypes>
        <fullName>Metrostudy_Opportunity_Record_Type_Admin</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <description>for admin only</description>
        <label>MS_Metrostudy Opportunity Record Type Admin</label>
    </recordTypes>
    <recordTypes>
        <fullName>Metrostudy_Opportunity_Record_Type_Consult</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <description>Use for MS Consulting Opps</description>
        <label>MS_Metrostudy Opportunity Record Type Consult</label>
    </recordTypes>
    <recordTypes>
        <fullName>Metrostudy_Renewal_Oppty_Record_Type</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <description>Used for MS cancellations</description>
        <label>MS_Metrostudy Renewal Oppty Record Type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Network_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Media</businessProcess>
        <label>MS_Media - Network</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Billing_Frequency__c</fullName>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Subscription_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Annually</fullName>
                    <default>true</default>
                    <label>Annually</label>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Annualize_New_Revenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Annualize New Revenue?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Billing_Instruction_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Billing Instruction Set</label>
        <referenceTo>FC_Billing_Instruction_Set__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Deal_Length__c</fullName>
        <label>(FC) Deal Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Do_Not_Annualize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Do Not Annualize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Effective_Date__c</fullName>
        <label>Eff. Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_End_Date__c</fullName>
        <label>(FC) End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Line_Description__c</fullName>
        <label>Line Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_New_Revenue__c</fullName>
        <label>xx_(FC) New Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Opportunity_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Opportunity Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Product_Geography_Seg3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Metrostudy Product Geography Seg3</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_RD_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) RD Assignment</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Seg3_Text__c</fullName>
        <label>(FC) Seg3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Term_Type__c</fullName>
        <formula>IF(ISBLANK(Opportunity.ContractId), TEXT(Opportunity.FC_Term_Type__c),
            TEXT(Opportunity.Contract.FC_Subscription__r.Zuora__TermSettingType__c))</formula>
        <label>Term Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_UUID__c</fullName>
        <externalId>true</externalId>
        <label>(FC) UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FC_Zuora_Action__c</fullName>
        <label>(FC) Zuora Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Action</fullName>
                </value>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__TermSettingType__c</fullName>
        <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
        <label>Term Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_OpportunityLineItemHandler.cls
global without sharing class FC_OpportunityLineItemHandler extends fcf.TriggerAdapter {

    global static final String TRIGGER_RUN_STATUS_ID = 'FC_OpportunityLineItemHandler';

    private final static Set<String> ACT_ONLY_FOR_OPPORTUNITY_RECORD_TYPES = new Set<String>{
            'Metrostudy_Renewal_Oppty_Record_Type',
            'Metrostudy_Opportunity_Record_Type_Consult',
            'Metrostudy_Opportunity_Record_Type_Admin',
            'Metrostudy_Opportunity_REE',
            'Market_Intelligence_Opportunity_Record_Type',
            'MS_Opportunity_BPM',
            'Network_Opportunity',
            'MS_Opportunity_Zuora_Duplicates'
    };

    // Before and after phase
    private static Map<Id, Opportunity> opportunityLookupMap = new Map<Id, Opportunity>();

    // Before phase
    private Map<Id, FC_Metroclient_Product_Geography_Seg3__c> fcMetroclientProductGeographySeg3LookupMap =
            new Map<Id, FC_Metroclient_Product_Geography_Seg3__c>();
    private Map<Id, FC_Billing_Instruction_Set__c> fcBillingInstructionSetLookupMap = new Map<Id, FC_Billing_Instruction_Set__c>();
    private Map<Id, FC_Billing_Instruction_Set__c> opportunityLineItemIdToFcBillingInstructionSetMap =
            new Map<Id, FC_Billing_Instruction_Set__c>();
    private Map<Id, Set<FC_Billing_Instruction_Step__c>> fcBillingInstructionSetIdToFcBillingInstructionStepsMap =
            new Map<Id, Set<FC_Billing_Instruction_Step__c>>();
    private Map<Id, Set<String>> fcBillingInstructionStepIdToTagsMap = new Map<Id, Set<String>>();
    private Map<Id, Set<MetrostudySalesRegionAssignment__c>> salesRegionIdToSalesRegionAssignmentsMap =
            new Map<Id, Set<MetrostudySalesRegionAssignment__c>>();
    private Map<Id, Integer> opportunityLineItemIdToSubscribeBillingStepCountMap = new Map<Id, Integer>();

    // After phase
    private Set<Id> billingInstructionSetIdsToDelete = new Set<Id>();
    private Set<Opportunity> opportunitiesToUpdate = new Set<Opportunity>();

    global override void bulkBefore() {

        if (Trigger.isInsert || Trigger.isUpdate) {

            Set<Id> fcMetroclientProductGeographySeg3IdsToLookup = new Set<Id>();
            Set<Id> opportunityIdsToLookup = new Set<Id>();
            Set<Id> fcBillingInstructionSetIdsToLookup = new Set<Id>();
            for (SObject so : Trigger.new) {
                OpportunityLineItem opportunityLineItemRecord = (OpportunityLineItem) so;
                if (opportunityLineItemRecord.FC_Product_Geography_Seg3__c != null) {
                    fcMetroclientProductGeographySeg3IdsToLookup.add(opportunityLineItemRecord.FC_Product_Geography_Seg3__c);
                }
                if (opportunityLineItemRecord.OpportunityId != null) {
                    opportunityIdsToLookup.add(opportunityLineItemRecord.OpportunityId);
                }
                if (opportunityLineItemRecord.FC_Billing_Instruction_Set__c != null) {
                    fcBillingInstructionSetIdsToLookup.add(opportunityLineItemRecord.FC_Billing_Instruction_Set__c);
                }
            }

            fcMetroclientProductGeographySeg3LookupMap.putAll(FC_FcMetroclientProductGeoSeg3Cache.findByIds(fcMetroclientProductGeographySeg3IdsToLookup));
            opportunityLookupMap.putAll(FC_OpportunityCache.findByIds(opportunityIdsToLookup));
            fcBillingInstructionSetLookupMap.putAll(FC_FcBillingInstructionSetCache.findByIds(fcBillingInstructionSetIdsToLookup));
            fcBillingInstructionSetIdToFcBillingInstructionStepsMap.putAll(FC_FcBillingInstructionStepCache.findByBillingInstructionSetIds(fcBillingInstructionSetIdsToLookup));

            // Populate Billing Instruction Step Tags map
            for (Set<FC_Billing_Instruction_Step__c> fcBillingInstructionStepRecords : fcBillingInstructionSetIdToFcBillingInstructionStepsMap.values()) {
                for (FC_Billing_Instruction_Step__c fcBillingInstructionStepRecord : fcBillingInstructionStepRecords) {
                    Set<String> fcBillingInstructionSetTags = fcBillingInstructionStepIdToTagsMap.get(fcBillingInstructionStepRecord.Id);
                    if (fcBillingInstructionSetTags == null) {
                        fcBillingInstructionSetTags = new Set<String>();
                        fcBillingInstructionStepIdToTagsMap.put(fcBillingInstructionStepRecord.Id, fcBillingInstructionSetTags);
                    }
                    for (FC_Billing_Instruction_Step__Tag tagRecord : fcBillingInstructionStepRecord.Tags) {
                        fcBillingInstructionSetTags.add(tagRecord.Name);
                    }
                }
            }

            Set<Id> salesRegionIdsToLookup = new Set<Id>();
            for (FC_Metroclient_Product_Geography_Seg3__c seg3Record : fcMetroclientProductGeographySeg3LookupMap.values()) {
                if (seg3Record.Product_Geography__r.Geography__r.SalesRegion__c != null) {
                    salesRegionIdsToLookup.add(seg3Record.Product_Geography__r.Geography__r.SalesRegion__c);
                }
            }
            salesRegionIdToSalesRegionAssignmentsMap.putAll(FC_MetrostudySalesRegionAssignmentCache.findBySalesRegionIds(salesRegionIdsToLookup));

        }


        if (Trigger.isUpdate) {
            opportunityLineItemIdToFcBillingInstructionSetMap.putAll(FC_FcBillingInstructionSetCache.findByOpportunityLineItemIds(Trigger.newMap.keySet()));

            // Calculate subscribe billing step counts for each opportunity line item.
            for (SObject so : Trigger.new) {
                opportunityLineItemIdToSubscribeBillingStepCountMap.put(so.Id, 0);
            }
            for (SObject so : Trigger.new) {
                OpportunityLineItem opportunityLineItemRecord = (OpportunityLineItem) so;
                FC_Billing_Instruction_Set__c billingInstructionSetRecord = opportunityLineItemIdToFcBillingInstructionSetMap.get(opportunityLineItemRecord.Id);
                if (billingInstructionSetRecord != null) {
                    Set<FC_Billing_Instruction_Step__c> billingInstructionSteps = fcBillingInstructionSetIdToFcBillingInstructionStepsMap.get(billingInstructionSetRecord.Id);
                    Integer subscribeCount = 0;
                    if (billingInstructionSteps != null) {
                        for (FC_Billing_Instruction_Step__c billingInstructionStepRecord : billingInstructionSteps) {
                            if (billingInstructionStepRecord.RecordType.DeveloperName == 'Subscribe') {
                                subscribeCount++;
                            }
                        }
                    }
                    opportunityLineItemIdToSubscribeBillingStepCountMap.put(opportunityLineItemRecord.Id, subscribeCount);
                }
            }

        }


    }

    global override void beforeInsert(SObject so) {
        OpportunityLineItem newOpportunityLineItem = (OpportunityLineItem) so;
        populateFields(newOpportunityLineItem);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        OpportunityLineItem newOpportunityLineItem = (OpportunityLineItem) so;
        populateFields(newOpportunityLineItem);
    }

    global override void finallyBefore() {

        // Initialize fields
        Set<Id> billingInstructionSetIdsToSummarize = new Set<Id>();
        for (SObject so : Trigger.new) {
            OpportunityLineItem opportunityLineItemRecord = (OpportunityLineItem) so;
            opportunityLineItemRecord.FC_Deal_Length__c = 1;
            if (opportunityLineItemRecord.FC_Billing_Instruction_Set__c != null) {
                billingInstructionSetIdsToSummarize.add(opportunityLineItemRecord.FC_Billing_Instruction_Set__c);
            }
        }


        Map<Id, AggregateResult> billingInstructionSetIdToSummaryMap = new Map<Id, AggregateResult>();
        if (Trigger.isUpdate && !billingInstructionSetIdsToSummarize.isEmpty()) {
            for (AggregateResult row : [
                    select Billing_Instruction_Set__c, min(Contract_Effective_Date__c) minContractEffectiveDate,
                            max(Contract_Effective_Date__c) maxContractEffectiveDate
                    from FC_Billing_Instruction_Step__c
                    where Billing_Instruction_Set__c in :billingInstructionSetIdsToSummarize
                    group by Billing_Instruction_Set__c
            ]) {
                Id billingInstructionSetId = (Id) row.get('Billing_Instruction_Set__c');
                billingInstructionSetIdToSummaryMap.put(billingInstructionSetId, row);
            }
        }

        for (SObject so : Trigger.new) {
            OpportunityLineItem opportunityLineItemRecord = (OpportunityLineItem) so;
            if (opportunityLineItemRecord.FC_Billing_Instruction_Set__c != null) {
                AggregateResult ar = billingInstructionSetIdToSummaryMap.get(opportunityLineItemRecord.FC_Billing_Instruction_Set__c);
                if (ar != null) {
                    Date minContractEffectiveDate = (Date) ar.get('minContractEffectiveDate');
                    Date maxContractEffectiveDate = (Date) ar.get('maxContractEffectiveDate');
                    opportunityLineItemRecord.FC_Deal_Length__c = Math.max(1, minContractEffectiveDate.monthsBetween(maxContractEffectiveDate));
                }
            }
        }

    }

    global override void afterInsert(SObject so) {
        OpportunityLineItem opportunityLineItemRecord = (OpportunityLineItem) so;
        prepareOpportunityRecordForUpdate(opportunityLineItemRecord);
    }

    global override void afterUpdate(SObject oldSo, SObject so) {
        OpportunityLineItem opportunityLineItemRecord = (OpportunityLineItem) so;
        prepareOpportunityRecordForUpdate(opportunityLineItemRecord);
    }

    global override void afterDelete(SObject so) {

        OpportunityLineItem opportunityLineItemRecord = (OpportunityLineItem) so;
        if (opportunityLineItemRecord.FC_Billing_Instruction_Set__c != null) {
            billingInstructionSetIdsToDelete.add(opportunityLineItemRecord.FC_Billing_Instruction_Set__c);
        }

        prepareOpportunityRecordForUpdate(opportunityLineItemRecord);

    }

    global override void finallyAfter() {

        // Prevent after phase from recursively executing
        if (!fcf.TriggerRunStatus.isRunnable(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID))) {
            return;
        }
        fcf.TriggerRunStatus.block(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID));

        if (Trigger.isDelete) {

            if (!billingInstructionSetIdsToDelete.isEmpty()) {
                Database.delete(new List<Id>(billingInstructionSetIdsToDelete));
                billingInstructionSetIdsToDelete.clear();
            }

        }

        if (!opportunitiesToUpdate.isEmpty()) {
            update new List<Opportunity>(opportunitiesToUpdate);
            opportunitiesToUpdate.clear();
        }

    }

    private void prepareOpportunityRecordForUpdate(OpportunityLineItem opportunityLineItemRecord) {

        Opportunity opportunityRecord = opportunityLookupMap.get(opportunityLineItemRecord.OpportunityId);

        /* Do not continue if opportunity is not one of the record types listed in
         * ACT_ONLY_FOR_OPPORTUNITY_RECORD_TYPES.
         */
        if (!(opportunityRecord != null &&
                ACT_ONLY_FOR_OPPORTUNITY_RECORD_TYPES.contains(opportunityRecord.RecordType.DeveloperName))) {
            return;
        }

        opportunitiesToUpdate.add(new Opportunity(Id = opportunityLineItemRecord.OpportunityId, Skip_Validation__c = true));
    }

    private void populateFields(OpportunityLineItem opportunityLineItemRecord) {

        // Assign AdBook Start and End Date fields to local Double Click fields
        AdBookIntegration.handleOpportunityLineItemTriggerPopulateFields(opportunityLineItemRecord);

        Opportunity opportunityRecord = opportunityLookupMap.get(opportunityLineItemRecord.OpportunityId);

        /* Do not continue if opportunity is not one of the record types listed in
         * ACT_ONLY_FOR_OPPORTUNITY_RECORD_TYPES.
         */
        if (!(opportunityRecord != null &&
                ACT_ONLY_FOR_OPPORTUNITY_RECORD_TYPES.contains(opportunityRecord.RecordType.DeveloperName))) {
            return;
        }

        opportunityLineItemRecord.FC_Line_Description__c = null;
        FC_Metroclient_Product_Geography_Seg3__c fcMetroclientProductGeographySeg3Record =
                fcMetroclientProductGeographySeg3LookupMap.get(opportunityLineItemRecord.FC_Product_Geography_Seg3__c);

        if (opportunityRecord != null) {

            opportunityLineItemRecord.FC_Annualize_New_Revenue__c = opportunityRecord.FC_Annualize_New_Revenue__c;

            // Populate Opportunity Renewal
            opportunityLineItemRecord.FC_Opportunity_Renewal__c = opportunityRecord.FC_Renew__c;

            if (opportunityLineItemRecord.FC_Product_Geography_Seg3__c != null &&
                    fcMetroclientProductGeographySeg3Record != null) {

                opportunityLineItemRecord.FC_Seg3_Text__c = fcMetroclientProductGeographySeg3Record.Seg3__c;

                opportunityLineItemRecord.FC_RD_Assignment__c = null;
                Set<MetrostudySalesRegionAssignment__c> possibleSalesRegionAssignments =
                        salesRegionIdToSalesRegionAssignmentsMap.get(fcMetroclientProductGeographySeg3Record.Product_Geography__r.Geography__r.SalesRegion__c);
                if (possibleSalesRegionAssignments != null) {
                    for (MetrostudySalesRegionAssignment__c salesRegionAssignmentRecord : possibleSalesRegionAssignments) {
                        if (salesRegionAssignmentRecord.Role__c == 'RD') {
                            opportunityLineItemRecord.FC_RD_Assignment__c = salesRegionAssignmentRecord.Id;
                            break;
                        }
                    }
                }

                if (opportunityLineItemRecord.FC_Effective_Date__c != null && opportunityLineItemRecord.FC_Zuora_Action__c != 'Remove') {
                    if (fcMetroclientProductGeographySeg3Record.Charge_Type__c == 'Recurring') {
                        if (opportunityRecord.FC_Initial_Term__c != null &&
                                ((opportunityRecord.ContractId == null && opportunityRecord.FC_Term_Type__c == 'TERMED') ||
                                        (opportunityRecord.ContractId != null &&
                                                opportunityRecord.Contract.FC_Subscription__r.Zuora__TermSettingType__c == 'TERMED'))) {
                            opportunityLineItemRecord.FC_End_Date__c =
                                    opportunityLineItemRecord.FC_Effective_Date__c.addMonths(
                                            Integer.valueOf(opportunityRecord.FC_Initial_Term__c));
                        } else {
                            opportunityLineItemRecord.FC_End_Date__c = opportunityLineItemRecord.FC_Effective_Date__c.addMonths(12);
                        }
                    } else {
                        opportunityLineItemRecord.FC_End_Date__c = opportunityLineItemRecord.FC_Effective_Date__c;
                    }
                }

                opportunityLineItemRecord.FC_Line_Description__c = String.format('{0} | {1} | {2} | {3}',
                        new String[]{
                                fcMetroclientProductGeographySeg3Record.Geography_Type__c,
                                fcMetroclientProductGeographySeg3Record.Geography__c,
                                fcMetroclientProductGeographySeg3Record.Charge_Type__c == 'Recurring' ?
                                        opportunityLineItemRecord.Billing_Frequency__c : 'One-Time',
                                fcMetroclientProductGeographySeg3Record.Seg3__c
                        });
            }

            if (String.isBlank(opportunityLineItemRecord.FC_UUID__c)) {
                opportunityLineItemRecord.FC_UUID__c = FC_UuidUtil.uuidV4();
            }

            if (String.isNotBlank(opportunityLineItemRecord.FC_Zuora_Action__c)) {

                Decimal lessThan12MonthsMultiplier = 1;
                if (opportunityRecord.FC_Term_Type__c == 'TERMED' && opportunityRecord.FC_Initial_Term__c != null &&
                        opportunityRecord.FC_Initial_Term__c < 12 && opportunityLineItemRecord.Billing_Frequency__c != 'One-Time') {
                    lessThan12MonthsMultiplier = opportunityRecord.FC_Initial_Term__c / 12;
                } else if (opportunityRecord.FC_Term_Type__c == 'EVERGREEN' && opportunityLineItemRecord.FC_Do_Not_Annualize__c) {
                    Map<String, Decimal> billingFrequencyToMultiplierMap = new Map<String, Decimal>{
                            'Monthly' => 1.0 / 12.0,
                            'Quarterly' => 3.0 / 12.0,
                            'Semi-Annually' => 6.0 / 12.0,
                            'Annually' => 12.0 / 12.0
                    };
                    if (String.isNotBlank(opportunityLineItemRecord.Billing_Frequency__c) &&
                            billingFrequencyToMultiplierMap.containsKey(opportunityLineItemRecord.Billing_Frequency__c)) {
                        lessThan12MonthsMultiplier = billingFrequencyToMultiplierMap.get(opportunityLineItemRecord.Billing_Frequency__c);
                    }
                }

                if (opportunityLineItemRecord.FC_Zuora_Action__c == 'Remove') {
                    opportunityLineItemRecord.FC_New_Revenue__c = 0;
                    opportunityLineItemRecord.FC_Renewal_Revenue__c = 0;
                    opportunityLineItemRecord.FC_Cancellation_Revenue__c = opportunityLineItemRecord.FC_Original_Sale_Price__c * -1;
                    opportunityLineItemRecord.UnitPrice = opportunityLineItemRecord.FC_Sale_Price__c * lessThan12MonthsMultiplier * -1;
                    opportunityLineItemRecord.Quantity = 1;
                    if (opportunityLineItemRecord.FC_Purchase_Type__c == 'Restructure') {
                        opportunityLineItemRecord.UnitPrice = 0;
                    }
                } else if (opportunityLineItemRecord.FC_Zuora_Action__c == 'No Action') {
                    opportunityLineItemRecord.FC_New_Revenue__c = 0;
                    opportunityLineItemRecord.FC_Renewal_Revenue__c = opportunityRecord.Renewal__c ? opportunityLineItemRecord.FC_Original_Sale_Price__c : 0;
                    opportunityLineItemRecord.FC_Cancellation_Revenue__c = 0;
                    opportunityLineItemRecord.UnitPrice = opportunityRecord.Renewal__c ? opportunityLineItemRecord.FC_Sale_Price__c * lessThan12MonthsMultiplier : 0;
                    opportunityLineItemRecord.Quantity = 1;
                } else if (opportunityLineItemRecord.FC_Zuora_Action__c == 'Add') {
                    opportunityLineItemRecord.FC_New_Revenue__c = opportunityLineItemRecord.FC_Sale_Price__c;
                    opportunityLineItemRecord.FC_Renewal_Revenue__c = 0;
                    opportunityLineItemRecord.FC_Cancellation_Revenue__c = 0;
                    opportunityLineItemRecord.UnitPrice = opportunityLineItemRecord.FC_Sale_Price__c * lessThan12MonthsMultiplier;
                    opportunityLineItemRecord.Quantity = 1;
                } else if (opportunityLineItemRecord.FC_Zuora_Action__c == 'Update') {
                    Decimal deltaPrice = opportunityLineItemRecord.FC_Sale_Price__c - opportunityLineItemRecord.FC_Original_Sale_Price__c;
                    opportunityLineItemRecord.FC_New_Revenue__c = deltaPrice;
                    opportunityLineItemRecord.FC_Renewal_Revenue__c = 0;
                    opportunityLineItemRecord.FC_Cancellation_Revenue__c = 0;
                    if (opportunityRecord.Renewal__c) {
                        if (deltaPrice > 0) {
                            opportunityLineItemRecord.FC_New_Revenue__c = 0;
                            opportunityLineItemRecord.FC_Renewal_Revenue__c = opportunityLineItemRecord.FC_Original_Sale_Price__c;
                            opportunityLineItemRecord.FC_Cancellation_Revenue__c = 0;
                        } else if (deltaPrice < 0) {
                            opportunityLineItemRecord.FC_New_Revenue__c = 0;
                            opportunityLineItemRecord.FC_Renewal_Revenue__c = opportunityLineItemRecord.FC_Original_Sale_Price__c + deltaPrice;
                            opportunityLineItemRecord.FC_Cancellation_Revenue__c = deltaPrice;
                        } else {
                            opportunityLineItemRecord.FC_New_Revenue__c = 0;
                            opportunityLineItemRecord.FC_Renewal_Revenue__c = opportunityLineItemRecord.FC_Original_Sale_Price__c;
                            opportunityLineItemRecord.FC_Cancellation_Revenue__c = 0;
                        }
                    }
                    opportunityLineItemRecord.UnitPrice = (opportunityLineItemRecord.FC_Sale_Price__c - (opportunityRecord.Renewal__c ? 0 : opportunityLineItemRecord.FC_Original_Sale_Price__c)) * lessThan12MonthsMultiplier;
                    opportunityLineItemRecord.Quantity = 1;
                    if (!opportunityLineItemRecord.FC_Override_Purchase_Type__c) {
                        opportunityLineItemRecord.FC_Purchase_Type__c = opportunityRecord.Renewal__c ? 'Renewal' : 'Price Change';
                    }
                }
            }
        }

        if (Trigger.isUpdate) {
            if (opportunityLineItemIdToFcBillingInstructionSetMap.containsKey(opportunityLineItemRecord.Id)) {
                opportunityLineItemRecord.FC_Billing_Instruction_Set__c = opportunityLineItemIdToFcBillingInstructionSetMap.get(opportunityLineItemRecord.Id).Id;
            }
        }

        FC_Billing_Instruction_Set__c fcBillingInstructionSetRecord = null;
        if (opportunityLineItemRecord.FC_Billing_Instruction_Set__c != null) {
            if (fcBillingInstructionSetLookupMap.containsKey(opportunityLineItemRecord.FC_Billing_Instruction_Set__c)) {
                fcBillingInstructionSetRecord = fcBillingInstructionSetLookupMap.get(opportunityLineItemRecord.FC_Billing_Instruction_Set__c);
            } else if (Trigger.isUpdate && opportunityLineItemIdToFcBillingInstructionSetMap.containsKey(opportunityLineItemRecord.Id)) {
                fcBillingInstructionSetRecord = opportunityLineItemIdToFcBillingInstructionSetMap.get(opportunityLineItemRecord.Id);
            }
        }


        Map<String, Object> parsedInstructionParameters = null;
        String billCaseString = '';
        if (fcBillingInstructionSetRecord != null) {

            // Bill Case should default to Billing Instruction Set Template Name
            billCaseString = fcBillingInstructionSetRecord.Template__r.Name;

            // Parse Instruction Parameters if possible
            if (String.isNotBlank(fcBillingInstructionSetRecord.Instruction_Parameters__c)) {
                try {
                    parsedInstructionParameters = (Map<String, Object>) JSON.deserializeUntyped(fcBillingInstructionSetRecord.Instruction_Parameters__c);
                } catch (JSONException e) {
                    // Do nothing.
                }
            }
        }

        if ((opportunityLineItemIdToSubscribeBillingStepCountMap.get(opportunityLineItemRecord.Id) != null &&
                opportunityLineItemIdToSubscribeBillingStepCountMap.get(opportunityLineItemRecord.Id) > 0) ||
                opportunityRecord.ContractId == null) {

            /* If this opportunity is for a new subscription and the billing instruction set is using a Free Months
             * template, then extend the End Date by the number of free months.
             */
            if (fcBillingInstructionSetRecord != null) {

                if (fcBillingInstructionSetRecord.Template__r.Name == 'Free Months') {

                    if (parsedInstructionParameters != null && parsedInstructionParameters.containsKey('numberOfFreeMonths')) {
                        String numberOfFreeMonthsString = (String) parsedInstructionParameters.get('numberOfFreeMonths');
                        if (String.isNotBlank(numberOfFreeMonthsString)) {
                            opportunityLineItemRecord.FC_End_Date__c = opportunityLineItemRecord.FC_End_Date__c.addMonths(Integer.valueOf(numberOfFreeMonthsString));
                        }
                    }

                } else if (fcBillingInstructionSetRecord.Template__r.Name == 'Opt Out') {

                    if (parsedInstructionParameters != null && parsedInstructionParameters.containsKey('duration')) {
                        String durationString = (String) parsedInstructionParameters.get('duration');
                        if (String.isNotBlank(durationString)) {
                            opportunityLineItemRecord.FC_End_Date__c = opportunityLineItemRecord.FC_End_Date__c.addMonths(Integer.valueOf(durationString));
                        }
                    }

                }

            }

        } else {

            // If this opportunity is for an existing subscription, default the Bill Case to the Zuora Action.
            if (opportunityLineItemRecord.FC_Zuora_Action__c == 'No Action') {
                billCaseString = 'No Change';
            } else {
                billCaseString = String.format('Amend ({0})', new String[]{
                        opportunityLineItemRecord.FC_Zuora_Action__c
                });
            }
        }

        /* If the Billing Instruction Set is using a Template of Free Months or Opt Out, then the Bill Case is set
         * to the template name followed by the number of free months or opt out duration, respectively.
         */
        if (fcBillingInstructionSetRecord != null) {
            if (fcBillingInstructionSetRecord.Template__r.Name == 'Free Months') {

                if (parsedInstructionParameters != null && parsedInstructionParameters.containsKey('numberOfFreeMonths')) {
                    String numberOfFreeMonthsString = (String) parsedInstructionParameters.get('numberOfFreeMonths');
                    if (String.isNotBlank(numberOfFreeMonthsString)) {
                        billCaseString = String.format('{0} ({1})', new String[]{
                                fcBillingInstructionSetRecord.Template__r.Name,
                                (String) parsedInstructionParameters.get('numberOfFreeMonths')
                        });
                    }
                }

            } else if (fcBillingInstructionSetRecord.Template__r.Name == 'Opt Out') {

                if (parsedInstructionParameters != null && parsedInstructionParameters.containsKey('duration')) {
                    billCaseString = String.format('{0} ({1})', new String[]{
                            fcBillingInstructionSetRecord.Template__r.Name,
                            (String) parsedInstructionParameters.get('duration')
                    });
                }

            }
        }
        opportunityLineItemRecord.FC_Bill_Case__c = billCaseString;


        if (fcMetroclientProductGeographySeg3Record != null &&
                fcMetroclientProductGeographySeg3Record.Seg3__c == 'CONS' &&
                fcBillingInstructionSetRecord != null &&
                fcBillingInstructionSetIdToFcBillingInstructionStepsMap.containsKey(fcBillingInstructionSetRecord.Id)) {

            Set<FC_Billing_Instruction_Step__c> fcBillingInstructionStepRecords =
                    fcBillingInstructionSetIdToFcBillingInstructionStepsMap.get(fcBillingInstructionSetRecord.Id);

            for (FC_Billing_Instruction_Step__c fcBillingInstructionStepRecord : fcBillingInstructionStepRecords) {
                Set<String> fcBillingInstructionStepTags = fcBillingInstructionStepIdToTagsMap.get(fcBillingInstructionStepRecord.Id);
                if (fcBillingInstructionStepTags != null && fcBillingInstructionStepTags.contains('Expenses')) {
                    opportunityLineItemRecord.FC_Consulting_Expenses__c = fcBillingInstructionStepRecord.Price__c;
                    break;
                }
            }

        }

    }

}