src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>Field to understand the status of the contact (whether active or not)</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Land Listing</fullName>
                </value>
                <value>
                    <fullName>NO LONGER AT COMPANY</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Inactive (non-qualified)</fullName>
                    <isActive>false</isActive>
                    <label>Inactive (non-qualified)</label>
                </value>
                <value>
                    <fullName>Open-Need to Review</fullName>
                    <isActive>false</isActive>
                    <label>Open-Need to Review</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zonda_User_Group__c</fullName>
        <label>Zonda User Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zonda_User__c.object
<CustomObject>
    <description>MG_Zonda User</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Zonda Users</relationshipLabel>
        <relationshipName>Zonda_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zonda_User_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is an internal field - used for look up and coverage association</inlineHelpText>
        <label>Zonda User Group</label>
        <referenceTo>Zonda_User_Group__c</referenceTo>
        <relationshipLabel>Zonda Users</relationshipLabel>
        <relationshipName>Zonda_Users</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Zonda User</label>
    <nameField>
        <displayFormat>ZU-{00000}</displayFormat>
        <label>Zonda User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zonda Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zonda_User_Group__c.object
<CustomObject>
    <description>MG_Zonda User Group: This object links with m_customer_master</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zonda_Customer_Name__c</fullName>
        <inlineHelpText>This is the Customer name that will be displayed in Zonda.  If this is left blank then the User Group Name will be used</inlineHelpText>
        <label>Zonda Customer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Zonda User Group</label>
    <nameField>
        <label>Zonda User Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zonda User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestZondaUserTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestZondaUserTrigger {

    static testMethod void myZondauser() {
        // TO DO: implement unit test
                       
        Account act = new Account();
        act.Name='xyz';
        act.Industry='BPM';
        act.Type='Prospect';
        act.BillingPostalCode='5600098';
        
        insert act;
        
        Contact con = new Contact();
        con.LastName= 'test';
        con.Email='abc@xyz.com';
        con.AccountId= act.id;
        con.Contact_Status__c='prospect';
        
        insert con;
        
        Zonda_User_Group__c zug = new Zonda_User_Group__c();
        zug.Zonda_Customer_Name__c='Test';
        
        insert zug;
        
        Zonda_User__c zu = new Zonda_User__c();
        zu.Contact__c = con.Id;
        zu.Zonda_User_Group__c =zug.Id;
        zu.status__c='Active';
        
        insert zu;
        
        zu.status__c='Disabled';
        
        update zu;
    

    }
}