src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box makes the contact a Metrostudy User.  This box must be checked in order for the contact to be able to access their products from Metrostudy Central.</inlineHelpText>
        <label>Metrostudy User?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <description>Zuora Subscription Charge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Charge Number (Zuora)</inlineHelpText>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metroclient_cl_prod_id_TEMP_DNU__c</fullName>
        <description>DNU - for migration only</description>
        <inlineHelpText>For migration from Metroclient.  DNU.</inlineHelpText>
        <label>Metroclient Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubscriptionName__c</fullName>
        <description>Zuora Subscription Name</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Name (Zuora)</inlineHelpText>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientContactProductGeography__c.object
<CustomObject>
    <description>Metrostudy  Provisioning - Metrostudy User (Contact) Level</description>
    <fields>
        <fullName>MetroclientAccountProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Product Geography</label>
        <referenceTo>MetroclientAccountProductGeography__c</referenceTo>
        <relationshipName>AccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography Type</label>
        <referenceTo>MetroclientProductGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MetroclientProductGeography__c.ProductGeographyType__c</field>
                <operation>equals</operation>
                <valueField>$Source.MetroclientProductGeographyType__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Contact Product Geography</label>
    <nameField>
        <label>Contact Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Contact Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geography_FIPS__c</fullName>
        <label>Geography FIPS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <fields>
        <fullName>GeographyTypeId__c</fullName>
        <label>Geography Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProduct__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Metrostudy Products</description>
    <fields>
        <fullName>ProductAbbreviation__c</fullName>
        <label>Product Abbreviation</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProvisionFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is not in use at this time</description>
        <inlineHelpText>This field is not in use at this time</inlineHelpText>
        <label>Provision?</label>
        <type>Checkbox</type>
    </fields>
    <label>Metrostudy Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if the product-geography is currently available for sale.</description>
        <inlineHelpText>Indicates if the product-geography is currently available for sale. Inactive product geographies will not be included in the product selector&apos;s tiered selections (when applicable).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography Type</label>
        <referenceTo>MetroclientProductGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestDataGenerator.cls
@isTest
public class FC_TestDataGenerator {
    public static Contact[] generateContacts(Integer count) {
        Contact[] contacts = new List<Contact>();
        for (Integer i = 0; i < count; i++) {
            contacts.add(new Contact(FirstName = 'Test ' + i, 
                LastName = 'Last ' + i,
                Metrostudy_User__c = true));
        }
        return contacts;
    }
    
    public static Account[] generateAccounts(Integer count) {
        Account[] accounts = new List<Account>();
        for (Integer i = 0; i < count; i++) {
            accounts.add(new Account(Name = 'Test Account ' + i, BillingPostalCode = '12345'));
        }
        return accounts;
    }
    
    // Count is the number of contact product geographies PER contact
    public static MetroclientContactProductGeography__c[] 
            generateContactProductGeographies(Contact[] contacts, 
            MetroclientProductGeography__c[] prodGeos,
            MetroclientAccountProductGeography__c[] accProdGeos,
            MetroclientProductGeographyType__c[] prodGeoTypes) {
                
        MetroclientContactProductGeography__c[] cpGeos = new List<MetroclientContactProductGeography__c>();
        
        Account metrostudyAccount = loadMetrostudyAccount();
        
        for (Contact cont : contacts) {
            for (Integer i = 0; i < prodGeos.size(); i++) {
                cpGeos.add(new MetroclientContactProductGeography__c(
                    Name = cont.Name,
                    MetroclientAccountProductGeography__c = accProdGeos[i].Id,
                    MetroclientProductGeographyType__c = prodGeoTypes[i].Id,
                    MetroclientProductGeography__c = prodGeos[i].Id));
            }
        }
        return cpGeos;
    }
    
    public static MetroclientAccountProductGeography__c generateAccProdGeo(Account acc, MetroclientProductGeography__c prodGeo) {
        String randomStr = generateRandomString(5);
        MetroclientAccountProductGeography__c accProdGeo = new MetroclientAccountProductGeography__c(
            Account__c = acc.Id,
            ChargeNumber__c = 'CN-' + randomStr,
            SubscriptionName__c = 'S-' + randomStr,
            MetroclientProductGeography__c = prodGeo.Id,
            Metroclient_cl_prod_id_TEMP_DNU__c = randomStr);
        return accProdGeo;
    }
    
    public static MetroclientProductGeography__c generateProdGeo(MetroclientProductGeographyType__c prodGeoType) {
        MetroclientProductGeography__c prodGeo = new MetroclientProductGeography__c(Name = 'Test',
            Active__c = true,
            Geography__c = generateGeo(generateGeoTypes(1)[0]).Id,
            ProductGeographyType__c = prodGeoType.Id);
        return prodGeo;
    }
    
    public static MetroclientProductGeographyType__c generateProdGeoType() {
        MetroclientGeographyType__c geoType = generateGeoTypes(1)[0];
        insert geoType;
        
        MetroclientProduct__c product = generateMetroclientProducts(1)[0];
        insert product;
        
        MetroclientProductGeographyType__c prodGeoType = new MetroclientProductGeographyType__c(Name = 'test',
            GeographyType__c = geoType.Id,
            Product__c = product.Id);
        return prodGeoType;
    }
    
    public static MetroclientGeography__c generateGeo(MetroclientGeographyType__c geoType) {
        MetroclientGeography__c geo = new MetroclientGeography__c(Name = geoType.Name,
            GeographyType__c = geoType.Id,
            Geography_FIPS__c = '1');
        return geo;
    }
    
    public static MetroclientGeographyType__c[] generateGeoTypes(Integer count) {
        MetroclientGeographyType__c[] geoTypes = new List<MetroclientGeographyType__c>();
        for (Integer i = 0; i < count; i++) {
            geoTypes.add(new MetroclientGeographyType__c(Name = 'Geo Type ' + i, GeographyTypeId__c = i));
        }
        return geoTypes;
    }
    
    public static MetroclientProduct__c[] generateMetroclientProducts(Integer count) {
        MetroclientProduct__c[] mcProducts = new List<MetroclientProduct__c>();
        for (Integer i = 0; i < count; i++) {
            mcProducts.add(new MetroclientProduct__c(Name = 'product name ' + i,
                ProductAbbreviation__c = 'pm' + i,
                ProvisionFlag__c = true));
        }
        return mcProducts;
    }
    
    // contact product geography
        // MetroclientProductGeographyType__c
        // MetroclientAccountProductGeography__c
        // MetroclientProductGeography__c
    
    // product geography types
        // Product
        // Geography Type
    
    // product geography
        // Geography
    
    // account product geography
        // account
    
    public static Account loadMetrostudyAccount() {
        Account acc = new Account(Name = 'Metrostudy, a Hanleywood Company', BillingPostalCode = '12345');
        insert acc;
        return acc;
    }
    
    public static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
           Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), 62);
           randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
}