src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>FC_Subscription_Number__c</fullName>
        <externalId>true</externalId>
        <label>(FC) Subscription Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ContractHandler.cls
global without sharing class FC_ContractHandler extends fcf.TriggerAdapter {

    private Map<String, Zuora__Subscription__c> subscriptionNumberToSubscriptionMap = new Map<String, Zuora__Subscription__c>();

    global override void bulkBefore() {

        Set<String> subscriptionNumbersToLookup = new Set<String>();
        if (Trigger.isInsert || Trigger.isUpdate) {

            for (SObject so : Trigger.new) {
                Contract newContractRecord = (Contract) so;
                subscriptionNumbersToLookup.add(newContractRecord.FC_Subscription_Number__c);
            }

            subscriptionNumberToSubscriptionMap.putAll(FC_SubscriptionCache.findBySubscriptionNumber(subscriptionNumbersToLookup));

        }

    }

    global override void beforeInsert(Sobject so) {
        Contract newContractRecord = (Contract) so;
        populateFields(newContractRecord);
    }

    global override void beforeUpdate(SObject oldSo, Sobject so) {
        Contract newContractRecord = (Contract) so;
        populateFields(newContractRecord);
    }

    private void populateFields(Contract contractRecord) {
        contractRecord.FC_Subscription__c = null;
        if (String.isNotBlank(contractRecord.FC_Subscription_Number__c) &&
                subscriptionNumberToSubscriptionMap.containsKey(contractRecord.FC_Subscription_Number__c)) {
            contractRecord.FC_Subscription__c = subscriptionNumberToSubscriptionMap.get(contractRecord.FC_Subscription_Number__c).Id;
        }
    }

}