src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Status__c</fullName>
        <label>Customer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Past</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Geographies__c</fullName>
        <label>Product Geographies</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date the subscription ends  (SubscriptionEndDate).  This value is blank (NULL) for evergreen subscriptions.</description>
        <inlineHelpText>The date access to the product expires and can no longer be accessed.  This field is blank when a subscription is evergreen.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date that the subscription starts (SubscriptionStartDate)</description>
        <inlineHelpText>The date that the access to the product starts.  This date is determined by the subscription or amendment start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status can be Active, Future, Expired, On Hold</description>
        <formula>IF(Deleted__c  = True, &apos;Expired&apos;, 
  IF(EndDate__c &lt;   TODAY(), &apos;Expired&apos;, 
    IF(OnHold__c = True, &apos;On Hold&apos;,
    IF(StartDate__c &gt;  TODAY() , &apos;Future&apos;,

&apos;Active&apos;
)
)
)
)</formula>
        <inlineHelpText>Active, Future, Expired, or On Hold</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientContactProductGeography__c.object
<CustomObject>
    <description>Metrostudy  Provisioning - Metrostudy User (Contact) Level</description>
    <fields>
        <fullName>ContactAccountName__c</fullName>
        <description>Name of the account and site the contact belongs to.</description>
        <formula>Contact__r.Account.Name + &quot; (&quot; + Contact__r.Account.Site__c + &quot;)&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Contact&apos;s account and site</inlineHelpText>
        <label>Contact Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Metrostudy_User__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroclientAccountProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Product Geography</label>
        <referenceTo>MetroclientAccountProductGeography__c</referenceTo>
        <relationshipName>AccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography Type</label>
        <referenceTo>MetroclientProductGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MetroclientProductGeography__c.ProductGeographyType__c</field>
                <operation>equals</operation>
                <valueField>$Source.MetroclientProductGeographyType__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGeographyAccount__c</fullName>
        <description>The account the product geography belongs to</description>
        <formula>MetroclientAccountProductGeography__r.Account__r.Name + &quot; (&quot; + MetroclientAccountProductGeography__r.Account__r.Site__c + &quot;)&quot;</formula>
        <inlineHelpText>The account that owns the product geography.  (formula field)</inlineHelpText>
        <label>Product Geography Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>MetroclientAccountProductGeography__r.Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Metrostudy Contact Product Geography</label>
    <nameField>
        <label>Contact Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Contact Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <fields>
        <fullName>GeographyTypeId__c</fullName>
        <label>Geography Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProduct__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Metrostudy Products</description>
    <fields>
        <fullName>ProductAbbreviation__c</fullName>
        <label>Product Abbreviation</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if the product-geography is currently available for sale.</description>
        <inlineHelpText>Indicates if the product-geography is currently available for sale. Inactive product geographies will not be included in the product selector&apos;s tiered selections (when applicable).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography Type</label>
        <referenceTo>MetroclientProductGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestContactUpdaterBatchable.cls
@isTest
private class FC_TestContactUpdaterBatchable {
    private static final Date SCHEDULED_DATE = Date.newInstance(2022, 9, 3);
    
    static testMethod void testCurrentAndNullCustomerStatus() {
        loadSetupData();
        Contact inactiveContact = [select Id from Contact limit 1];
        delete [select Id from MetroclientContactProductGeography__c where Contact__c = :inactiveContact.Id];
        
        Test.startTest();
        scheduleContactUpdater();
        // Database.executeBatch(new FC_ContactUpdaterBatchable()); 
        Test.stopTest();
        
        for (Contact cont : [select Customer_Status__c from Contact]) {
            if (cont.Id == inactiveContact.Id) {
                System.assert(String.isBlank(cont.Customer_Status__c));
            } else {
                System.assertEquals('Current', cont.Customer_Status__c);
            }
        }
    }
    
    static testMethod void testPastCustomerStatus() {
        loadSetupData();
        Contact inactiveContact = [select Id from Contact limit 1];
        delete [select Id from MetroclientContactProductGeography__c where Contact__c = :inactiveContact.Id];
        
        MetroclientAccountProductGeography__c[] accProdGeos = [select EndDate__c from MetroclientAccountProductGeography__c];
        for (MetroclientAccountProductGeography__c accProdGeo : accProdGeos) {
            // this will set the start date to something in the future which will cause the customer to be a 'Past' customer
            accProdGeo.StartDate__c = Date.today().addDays(-10);
            accProdGeo.EndDate__c = Date.today().addDays(-1);
        }
        update accProdGeos;
        
        MetroclientContactProductGeography__c[] contProdGeos = 
            [select Name, Contact__c, ContactAccountName__c, MetroclientProductGeography__c, ProductGeographyAccount__c, 
                MetroclientProductGeographyType__c, Status__c from MetroclientContactProductGeography__c];
        for (MetroclientContactProductGeography__c cpg : contProdGeos) {
            if (cpg.Contact__c != inactiveContact.Id) {
                System.debug(logginglevel.error, 'cpg: ' + cpg.Status__c);
            }
        }
        
        Test.startTest();
        scheduleContactUpdater();
        // Database.executeBatch(new FC_ContactUpdaterBatchable()); 
        Test.stopTest();
        
        for (Contact cont : [select Customer_Status__c from Contact]) {
            if (cont.Id == inactiveContact.Id) {
                System.assert(String.isBlank(cont.Customer_Status__c));
            } else {
                System.assertEquals('Past', cont.Customer_Status__c);
            }
        }
    }
    
    static testMethod void testProdGeoRollup() {
        loadSetupData();
        Contact firstContact = [select Id from Contact limit 1];
        MetroclientProductGeography__c[] prodGeos = [select Name from MetroclientProductGeography__c];
        for (MetroclientProductGeography__c prodGeo : prodGeos) {
            prodGeo.Name = 'aaaa | bbbb | ccc ccc';
        }
        update prodGeos;
        
        Test.startTest();
        Database.executeBatch(new FC_ContactUpdaterBatchable()); 
        Test.stopTest();
        
        firstContact = [select Product_Geographies__c from Contact where Id = :firstContact.Id];
        System.assertEquals('aaaa|bbbb|ccc ccc', firstContact.Product_Geographies__c);
    }
    
    private static void loadSetupData() {
        MetroclientGeographyType__c geoType = new MetroclientGeographyType__c(Name = 'some geo type', GeographyTypeId__c = 123);
        insert geoType;
        MetroclientGeography__c geography = new MetroclientGeography__c(Name = 'Country', GeographyType__c = geoType.Id);
        insert geography;
        MetroclientProduct__c product = new MetroclientProduct__c(Name = 'Product', ProductAbbreviation__c = 'abc');
        insert product;
        MetroclientProductGeographyType__c prodGeoType = new MetroclientProductGeographyType__c(Name = 'some geo type',
            GeographyType__c = geoType.Id, Product__c = product.Id);
        insert prodGeoType;
        
        MetroclientProductGeography__c[] prodGeos = new List<MetroclientProductGeography__c>();
        prodGeos.add(generateProductGeography('All HWMI Reports | Country | United States', geography, prodGeoType));
        prodGeos.add(generateProductGeography('Insight, Analytics & PA | Country | United States', geography, prodGeoType));
        prodGeos.add(generateProductGeography('Shaw Report | Country | United States', geography, prodGeoType));
        insert prodGeos;
        
        
        Account msAccount = FC_TestDataGenerator.loadMetroStudyAccount();
        MetroclientAccountProductGeography__c[] accProdGeos = loadAccountProductGeographies(msAccount, prodGeos);
        
        Map<Id, MetroclientAccountProductGeography__c> prodGeoToAccProdGeo = new Map<Id, MetroclientAccountProductGeography__c>();
        for (MetroclientAccountProductGeography__c accProdGeo : accProdGeos) {
            prodGeoToAccProdGeo.put(accProdGeo.MetroclientProductGeography__c, accProdGeo);
        }
        
        Contact[] contacts = FC_TestDataGenerator.generateContacts(5);
        insert contacts;
        MetroclientContactProductGeography__c[] contProdGeos = loadContactProductGeographies(contacts, prodGeos, prodGeoToAccProdGeo);
		
	}
	
	private static void scheduleContactUpdater() {
	    FC_ContactUpdaterSchedulable schedulable = new FC_ContactUpdaterSchedulable();
        String cronExp = '0 0 0 ' + SCHEDULED_DATE.day() + ' ' + SCHEDULED_DATE.month() + ' ? ' + SCHEDULED_DATE.year();
        Id jobId = System.schedule('test batch process', cronExp, schedulable);
        doScheduledJobAsserts(jobId);
        
        Database.executeBatch(new FC_ContactUpdaterBatchable());
	}
	
	private static void doScheduledJobAsserts(Id jobId) {
	    CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
	        FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(0, ct.TimesTriggered);

        System.assertEquals(SCHEDULED_DATE, ct.NextFireTime.date());
	}
	
	private static MetroclientProductGeography__c generateProductGeography(
	        String geoName, MetroclientGeography__c geography, MetroclientProductGeographyType__c geoType) {
	    return new MetroclientProductGeography__c(Name = geoName,
	        Active__c = true,
	        Geography__c = geography.Id, 
	        ProductGeographyType__c = geoType.Id);
	}
	
	private static MetroclientAccountProductGeography__c[] loadAccountProductGeographies(Account acc, MetroclientProductGeography__c[] prodGeos) {
	    MetroclientAccountProductGeography__c[] accProdGeos = new List<MetroclientAccountProductGeography__c>();
	    for (MetroclientProductGeography__c prodGeo : prodGeos) {
	        accProdGeos.add(new MetroclientAccountProductGeography__c(Name = prodGeo.Name,
	            MetroclientProductGeography__c = prodGeo.Id,
	            StartDate__c = Date.newInstance(2000, 1, 1)));
	    }
	    insert accProdGeos;
	    return accProdGeos;
	}
	
	private static MetroclientContactProductGeography__c[] loadContactProductGeographies(Contact[] contacts, 
	        MetroclientProductGeography__c[] prodGeos, 
	        Map<Id, MetroclientAccountProductGeography__c> prodGeoToAccProdGeo) {
	            
	    MetroclientContactProductGeography__c[] contProdGeos = new List<MetroclientContactProductGeography__c>();
	    for (Contact cont : contacts) {
    	    for (MetroclientProductGeography__c prodGeo : prodGeos) {
    	        contProdGeos.add(new MetroclientContactProductGeography__c(Name = cont.Name,
    	            Contact__c = cont.Id,
    	            MetroclientProductGeography__c = prodGeo.Id,
    	            MetroclientProductGeographyType__c = prodGeo.ProductGeographyType__c,
    	            MetroclientAccountProductGeography__c = prodGeoToAccProdGeo.get(prodGeo.Id).Id));
    	    }
	    }
	    insert contProdGeos;
	    return contProdGeos;
	}
}