src/objects/Contract_User_Group_Association__c.object
<CustomObject>
    <description>MG_Contract User Group Association</description>
    <fields>
        <fullName>Coverage_String__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coverage String</label>
        <referenceTo>Zonda_Contract__c</referenceTo>
        <relationshipLabel>Contract User Group Associations (Coverage String)</relationshipLabel>
        <relationshipName>Contract_User_Group_Associations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_s__c</fullName>
        <formula>IF( INCLUDES(Zonda_Contract__r.Role_s__c , &quot;Land Acquisition&quot;), &quot;Land Acquisition; &quot;,&quot;&quot;)
&amp;
IF( INCLUDES(Zonda_Contract__r.Role_s__c , &quot;Sales &amp; Marketing&quot;), &quot;Sales &amp; Marketing; &quot;,&quot;&quot;)</formula>
        <label>Role(s)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zonda_Contract__c</fullName>
        <label>Zonda Contract</label>
        <referenceTo>Zonda_Contract__c</referenceTo>
        <relationshipLabel>User Groups</relationshipLabel>
        <relationshipName>Contract_User_Group_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zonda_User_Group__c</fullName>
        <label>Zonda User Group</label>
        <referenceTo>Zonda_User_Group__c</referenceTo>
        <relationshipLabel>Zonda Contracts</relationshipLabel>
        <relationshipName>Contract_User_Group_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contract User Group Association</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Contract User Group Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract User Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zonda_Contract__c.object
<CustomObject>
    <description>MG_Zonda Contract</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Zonda Contracts</relationshipLabel>
        <relationshipName>Zonda_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Creation_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                    <isActive>false</isActive>
                    <label>A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Coverage_String__c</fullName>
        <label>Coverage String</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Zonda_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_s__c</fullName>
        <label>Role(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Land Acquisition</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <defaultValue>DATE(2999,12,31)</defaultValue>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <label>Zonda Contract</label>
    <nameField>
        <label>Zonda Contract</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zonda Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zonda_User_Group__c.object
<CustomObject>
    <description>MG_Zonda User Group: This object links with m_customer_master</description>
    <fields>
        <fullName>Coverage_String__c</fullName>
        <description>All coverage strings from related contracts combined</description>
        <label>Coverage String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role_s__c</fullName>
        <description>Pulled from the Zonda Contract(s)</description>
        <label>Role(s)</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Zonda User Group</label>
    <nameField>
        <label>Zonda User Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zonda User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestZondaContractsTrigger.cls
/**
 * Created by pete on 1/7/16.
 */

@IsTest
public class TestZondaContractsTrigger {

    @testSetup static void setUpData() {
        // Need some Zonda Contracts
        Account accnte = new Account();
        accnte.name='test1';
        accnte.type='prospect';
        accnte.Industry='Banking';
        accnte.BillingPostalCode='500029';
        insert accnte;
        
        List<Zonda_Contract__c> contracts = new List<Zonda_Contract__c>();
        for (Integer i = 0; i<5; i++) {
            contracts.add(new Zonda_Contract__c(
                    Name = 'Contract '+i
                   // Account__c=accnte.id
            ));
        }
        insert contracts;

        // Need some Zonda User Groups
        List<Zonda_User_Group__c> userGroups = new List<Zonda_User_Group__c>();
        for (Integer i = 0; i<5; i++) {
            userGroups.add(new Zonda_User_Group__c(
                    Name = 'User Group '+i,
                    Coverage_String__c= '06065'+i
               //   Coverage_String__c = 06065|06071;
            ));
           
        }
        insert userGroups;

        // Need some Contract/User Group Associations
        List<Contract_User_Group_Association__c> junctions = new List<Contract_User_Group_Association__c>();
        for (Integer i=0; i<5; i++) {
            junctions.add(new Contract_User_Group_Association__c(
                    Zonda_Contract__c = contracts[i].Id,
                    Zonda_User_Group__c = userGroups[i].Id
            ));
        }
        insert junctions;
        
      /*  Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        
        Account accnt = new Account();
        accnt.name='test1';
        accnt.type='prospect';
        accnt.Industry='Banking';
        insert accnt;
        
        Zonda_Contract__c zoncon = new Zonda_Contract__c();
        zoncon.Name='contracttest';
        zoncon.Subscription_End_Date__c = date.today()+30;
        zoncon.RSD__c=u.id;
        zoncon.Contract_Creation_Date__c = date.today()-5;
        zoncon.Account__c=accnt.id;
        zoncon.Role_s__c='Sales & Marketing';
        zoncon.contract_status__c='Expired';
        insert zoncon;*/
    }

    static testMethod void testExpiredContracts() {
        List<Zonda_User_Group__c> expiredUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c = 'Expired'];
        List<Zonda_User_Group__c> notExpiredUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c != 'Expired'];

        system.assertEquals(expiredUserGroups.size(), 0);
        system.assertEquals(notExpiredUserGroups.size(), 5);

        Test.startTest();
            List<Zonda_Contract__c> contracts = [SELECT Id, Contract_Status__c FROM Zonda_Contract__c];

            for (Zonda_Contract__c contract : contracts) {
                contract.Contract_Status__c = 'Expired';
            }

            update contracts;
        Test.stopTest();

        expiredUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c = 'Expired'];
        notExpiredUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c != 'Expired'];

        system.assertEquals(expiredUserGroups.size(), 5);
        system.assertEquals(notExpiredUserGroups.size(), 0);
    }

    static testMethod void testCanceledContracts() {
        List<Zonda_User_Group__c> canceledUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c = 'Canceled'];
        List<Zonda_User_Group__c> notCanceledUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c != 'Canceled'];

        system.assertEquals(canceledUserGroups.size(), 0);
        system.assertEquals(notCanceledUserGroups.size(), 5);

        Test.startTest();
        List<Zonda_Contract__c> contracts = [SELECT Id, Contract_Status__c FROM Zonda_Contract__c];

        for (Zonda_Contract__c contract : contracts) {
            contract.Contract_Status__c = 'Canceled';
        }

        update contracts;
        Test.stopTest();

        canceledUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c = 'Canceled'];
        notCanceledUserGroups = [SELECT Id,Coverage_String__c  FROM Zonda_User_Group__c WHERE Status__c != 'Canceled'];

        system.assertEquals(canceledUserGroups.size(), 5);
        system.assertEquals(notCanceledUserGroups.size(), 0);
    }
     static testMethod void testZondaContractCoverageManagerExt() {
         List<Zonda_Contract__c> contracts = [SELECT Id,Coverage_String__c, Contract_Status__c FROM Zonda_Contract__c];
         Zonda_Contract__c cont = [SELECT Id, Coverage_String__c,Contract_Status__c FROM Zonda_Contract__c limit 1];
         ApexPages.StandardController sc = new ApexPages.StandardController(cont);
        ZondaContractCoverageManagerExt de = new ZondaContractCoverageManagerExt(sc);
        de.apexUpdateCoverage();
     
     }
     
     static testMethod void testZondaContractCoverageManagerViewOnly() {
         List<Zonda_User_Group__c > contracts = [SELECT Id,Coverage_String__c FROM Zonda_User_Group__c];
         Zonda_User_Group__c cont = [SELECT Id,Coverage_String__c FROM Zonda_User_Group__c limit 1];
         ApexPages.StandardController scw = new ApexPages.StandardController(cont);
        ZondaContractCoverageManagerViewOnlyExt deonly = new ZondaContractCoverageManagerViewOnlyExt(scw);
        deonly.updatedCoverage='test';
        deonly.apexUpdateCoverage();
     
     }
     
     
     
}