src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>FC_Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__AccountNumber__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__AutoRenew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoRenew?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zuora__ContractEffectiveDate__c</fullName>
        <description>This is the date on which the contract becomes effective, and will trigger charges that have their trigger event set to Upon Contract Effective.</description>
        <label>Contract Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__InitialTerm__c</fullName>
        <label>Initial Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__RenewalTerm__c</fullName>
        <label>Renewal Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__ServiceActivationDate__c</fullName>
        <description>This is when the service was activated, and will trigger charges that have their trigger event set to Upon Service Activation.</description>
        <label>Service Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermSettingType__c</fullName>
        <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
        <label>Term Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>GeographyName__c</fullName>
        <label>GeographyName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zuora__ProductName_Product__c</fullName>
        <formula>IF( ISBLANK(Zuora__Product__c) ,  Zuora__ProductName__c,  HYPERLINK( Zuora__Product__r.Id , Zuora__Product__r.Name) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_OpportunityContractFormController.cls
public with sharing class FC_OpportunityContractFormController {

    private final Opportunity OPPORTUNITY_RECORD;

    private final ApexPages.StandardController STANDARD_CONTROLLER;

    public Map<Id, Zuora__SubscriptionProductCharge__c[]> subscriptionIdToChargesMap {

        get {
            if (subscriptionIdToChargesMap == null && subscriptionIds != null) {
                subscriptionIdToChargesMap = new Map<Id, Zuora__SubscriptionProductCharge__c[]>();
                for (Zuora__SubscriptionProductCharge__c chargeRecord : [
                        select Id, GeographyName__c, Name, Zuora__Subscription__c, Zuora__Description__c,
                                Zuora__ProductName_Product__c
                        from Zuora__SubscriptionProductCharge__c
                        where Zuora__Subscription__c in :subscriptionIds
                ]) {
                    Zuora__SubscriptionProductCharge__c[] charges = subscriptionIdToChargesMap.get(chargeRecord.Zuora__Subscription__c);
                    if (charges == null) {
                        charges = new List<Zuora__SubscriptionProductCharge__c>();
                        subscriptionIdToChargesMap.put(chargeRecord.Zuora__Subscription__c, charges);
                    }
                    charges.add(chargeRecord);
                }
            }
            return subscriptionIdToChargesMap;
        }

        private set;

    }

    public Set<Id> subscriptionIds {

        get {
            if (subscriptionIds == null && accountContracts != null) {
                subscriptionIds = new Set<Id>();
                for (Contract contractRecord : accountContracts) {
                    subscriptionIds.add(contractRecord.FC_Subscription__c);
                }
            }
            return subscriptionIds;
        }

        private set;

    }

    public Contract[] accountContracts {

        get {
            if (accountContracts == null) {
                accountContracts = [
                        select Id, FC_Subscription__c, FC_Price_Book__c, FC_Subscription__r.Name,
                                FC_Subscription__r.Opportunity__c,
                                FC_Subscription__r.Zuora__AutoRenew__c,
                                FC_Subscription__r.Zuora__ContractEffectiveDate__c,
                                FC_Subscription__r.Zuora__CustomerAccount__c,
                                FC_Subscription__r.Zuora__CustomerAccount__r.Name,
                                FC_Subscription__r.Zuora__CustomerAccount__r.Zuora__AccountNumber__c,
                                FC_Subscription__r.Zuora__InitialTerm__c,
                                FC_Subscription__r.Zuora__RenewalTerm__c,
                                FC_Subscription__r.Zuora__ServiceActivationDate__c,
                                FC_Subscription__r.Zuora__TermEndDate__c,
                                FC_Subscription__r.Zuora__TermStartDate__c,
                                FC_Subscription__r.Zuora__TermSettingType__c
                        from Contract
                        where AccountId = :this.OPPORTUNITY_RECORD.AccountId
                        and FC_Subscription__c != null
                        and FC_Subscription__r.Zuora__Status__c = 'Active'
                        order by FC_Subscription__r.Name desc
                ];
            }
            return accountContracts;
        }

        private set;

    }

    public ContractWrapper[] wrappedAccountContracts {

        get {
            if (wrappedAccountContracts == null && accountContracts != null) {
                wrappedAccountContracts = new List<ContractWrapper>();
                for (Contract contractRecord : accountContracts) {
                    Set<String> productSet = new Set<String>();
                    List<Zuora__SubscriptionProductCharge__c> charges = subscriptionIdToChargesMap.get(contractRecord.FC_Subscription__c);
                    String products = '';
                    if (charges != null) {
                        for (Zuora__SubscriptionProductCharge__c chargeRecord : charges) {
                            productSet.add(String.join(new String[]{
                                    chargeRecord.Zuora__ProductName_Product__c,
                                    chargeRecord.GeographyName__c
                            }, ' | ').stripHtmlTags());
                        }
                        List<String> productList = new List<String>(productSet);
                        productList.sort();
                        products = String.join(productList, '<br />');
                    }
                    wrappedAccountContracts.add(new ContractWrapper(contractRecord.Id, contractRecord.FC_Subscription__r.Name,
                            contractRecord.FC_Subscription__r.Opportunity__c,
                            contractRecord.FC_Subscription__r.Zuora__CustomerAccount__r.Name,
                            contractRecord.FC_Subscription__r.Zuora__CustomerAccount__r.Zuora__AccountNumber__c,
                            contractRecord.FC_Subscription__r.Zuora__TermStartDate__c,
                            contractRecord.FC_Subscription__r.Zuora__TermEndDate__c, products));
                }
            }
            return wrappedAccountContracts;
        }

        private set;

    }

    public Id selectedContractId { get; set; }

    public FC_OpportunityContractFormController(ApexPages.StandardController standardController) {
        this.STANDARD_CONTROLLER = standardController;
        this.OPPORTUNITY_RECORD = (Opportunity) standardController.getRecord();
    }

    public PageReference selectContract() {
        if (this.selectedContractId == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You must select a contract.'));
            return null;
        }

        FC_OpportunityContractUtil.associateOpportunitiesWithContracts(new Map<Id, Id>{
                this.OPPORTUNITY_RECORD.Id => this.selectedContractId
        });

        return this.STANDARD_CONTROLLER.view();
    }


    public class ContractWrapper {

        public Id contractId {
            get;
            set;
        }


        public String customerAccountName { get; set; }

        public String customerAccountNumber { get; set; }

        public Id opportunityId { get; set; }

        public String products {
            get;
            set;
        }

        public String subscriptionNumber { get; set; }

        public String termEndDate {
            get;
            set;
        }

        public String termStartDate {
            get;
            set;
        }

        public ContractWrapper(Id contractId, String subscriptionNumber, Id opportunityId, String customerAccountName,
                String customerAccountNumber, Date termStartDate, Date termEndDate, String products) {
            this.contractId = contractId;
            this.subscriptionNumber = subscriptionNumber;
            this.opportunityId = opportunityId;
            this.customerAccountName = customerAccountName;
            this.customerAccountNumber = customerAccountNumber;
            if (termStartDate != null) {
                this.termStartDate = termStartDate.format();
            }
            if (termEndDate != null) {
                this.termEndDate = termEndDate.format();
            }
            this.products = products;
        }

    }

}