src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Login_Date_Time__c</fullName>
        <label>Last Login Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Max_App_Version__c</fullName>
        <label>Max App Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSD_Email__c</fullName>
        <formula>$User.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RSD Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zonda_Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zonda Pro</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zonda_Role__c</fullName>
        <label>Zonda Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zonda_User_Group_RSD__c</fullName>
        <label>Zonda User Group RSD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zonda_User_Group__c</fullName>
        <label>Zonda User Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zonda_User_Status__c</fullName>
        <label>Zonda User Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zonda_User__c.object
<CustomObject>
    <description>MG_Zonda User</description>
    <fields>
        <fullName>App_Version__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>App Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Zonda Users</relationshipLabel>
        <relationshipName>Zonda_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Login_Date_Time__c</fullName>
        <label>Last Login Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Password_Sent_Date__c</fullName>
        <inlineHelpText>This is the date time that the reset password notification was sent.</inlineHelpText>
        <label>Date Password Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Plain_Text_Password__c</fullName>
        <label>Plain Text Password</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSD_Email__c</fullName>
        <formula>Zonda_User_Group__r.RSD_Email__c +&apos;;&apos;+ Contact__r.Owner.Email</formula>
        <label>RSD Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reset_Password__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This box will be unchecked after the user has updated his or her password</inlineHelpText>
        <label>Reset Password</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_s__c</fullName>
        <formula>Zonda_User_Group__r.Role_s__c</formula>
        <label>Role(s)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Group_read_only__c</fullName>
        <description>This field is used to pass the Zonda User Group name to the Contact</description>
        <formula>Zonda_User_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zonda_Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zonda Pro</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zonda_User_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is an internal field - used for look up and coverage association</inlineHelpText>
        <label>Zonda User Group</label>
        <referenceTo>Zonda_User_Group__c</referenceTo>
        <relationshipLabel>Zonda Users</relationshipLabel>
        <relationshipName>Zonda_Users</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Zonda User</label>
    <nameField>
        <displayFormat>ZU-{00000}</displayFormat>
        <label>Zonda User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zonda Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zonda_User_Group__c.object
<CustomObject>
    <description>MG_Zonda User Group: This object links with m_customer_master</description>
    <fields>
        <fullName>RSD_Email__c</fullName>
        <description>Pulled from the Zonda Contract(s)</description>
        <label>RSD Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_s__c</fullName>
        <description>Pulled from the Zonda Contract(s)</description>
        <label>Role(s)</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zonda_Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pulled from the Zonda Contract(s)</description>
        <label>Zonda Pro</label>
        <type>Checkbox</type>
    </fields>
    <label>Zonda User Group</label>
    <nameField>
        <label>Zonda User Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zonda User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/trgZondaUsersHandler.cls
public with sharing class trgZondaUsersHandler { 
    
    public static void resetPasswordIfNeeded(List<Zonda_User__c> triggerNew, Map<Id, Zonda_User__c> triggerOldMap) {
        Context.isTriggerContext = TRUE;
        for (Zonda_User__c zu : triggerNew) {
            if ((Trigger.isInsert && zu.Reset_Password__c == TRUE) || (Trigger.isUpdate && zu.Reset_Password__c == TRUE && triggerOldMap.get(zu.Id).Reset_Password__c == FALSE)) {
                // generate password
                String newPassword = generatePassword();
                // set into the plain text AND password fields
                zu.Password__c = newPassword;
                zu.Plain_Text_Password__c = newPassword;
                zu.Password_Sent_Date__c = Datetime.now();
                //zu.Reset_Password__c = false;
                // done
            }
        }
    }

    /**
        SFDC-52
        Accounting has requested that the Max Last Login Date and the Max App Version be added to the contact 
        so that it can be displayed on the related list on the account. Can this information be used to assist 
        with preventing the contact from being deleted and/or the email from being updated?
    */
    public static void updateContactMaxValues(List<Zonda_User__c> triggerNew) {
        Set<Id> contactIds = new Set<Id>();
        Map<Id, Contact> contactsToUpdate = new Map<Id, Contact>();
        for (Zonda_User__c zu : triggerNew) {
            contactIds.add(zu.Contact__c);
        }
        if (!contactIds.isEmpty()) {
            Map<Id, Contact> contactsFromZondaUsers = new Map<Id, Contact>([SELECT Id, Last_Login_Date_Time__c, Max_App_Version__c, Zonda_User_Status__c, Zonda_Role__c, Zonda_Pro__c, Zonda_User_Group__c, Zonda_User_Group_RSD__c FROM Contact WHERE Id IN :contactIds]);
            for (Zonda_User__c zu : triggerNew) {
                Boolean somethingChanged = false;
                if (null != zu.Contact__c && contactsFromZondaUsers.containsKey(zu.Contact__c)) {
                    Contact c = contactsFromZondaUsers.get(zu.Contact__c);
                    if (getNumericString(c.Max_App_Version__c) < getNumericString(zu.App_Version__c) ) {
                        c.Max_App_Version__c = zu.App_Version__c;
                        somethingChanged = true;
                    }
                    if (c.Last_Login_Date_Time__c == null || c.Last_Login_Date_Time__c < zu.Last_Login_Date_Time__c) {
                        c.Last_Login_Date_Time__c = zu.Last_Login_Date_Time__c;
                        somethingChanged = true;
                    }
                    // Passing values to Contact for Last Login Report for RSDs
                    // Role 
                    if (c.Zonda_User_Status__c == null || c.Zonda_User_Status__c != zu.Status__c) {
                        c.Zonda_User_Status__c = zu.Status__c;
                        somethingChanged = true;
                    }
                    // Role 
                    if (c.Zonda_Role__c == null || c.Zonda_Role__c != zu.Role_s__c) {
                        c.Zonda_Role__c = zu.Role_s__c;
                        somethingChanged = true;
                    }
                    // Pro 
                    if (c.Zonda_Pro__c == null || c.Zonda_Pro__c != zu.Zonda_Pro__c) {
                        c.Zonda_Pro__c = zu.Zonda_Pro__c;
                        somethingChanged = true;
                    }
                    //User Group Name
                    if (c.Zonda_User_Group__c == null || c.Zonda_User_Group__c != zu.User_Group_read_only__c) {
                        c.Zonda_User_Group__c = zu.User_Group_read_only__c;
                        somethingChanged = true;
                    }
                    //User Group Name
                    if (c.Zonda_User_Group_RSD__c == null || c.Zonda_User_Group_RSD__c != zu.RSD_Email__c) {
                        c.Zonda_User_Group_RSD__c = zu.RSD_Email__c;
                        somethingChanged = true;
                    }    
                    if (somethingChanged) {
                        contactsToUpdate.put(c.Id, c);
                    }
                }
            }
            if (!contactsToUpdate.values().isEmpty()) {
                update contactsToUpdate.values();
            }
        }
    }

    private static String generatePassword() {
        return String.valueOf(Math.random()).replace('0','').substring(2, 7);
    }

    private static String getNumericString(String s) {
        if (s != null) {
            return s.replaceAll('[^0-9]', '');
        } else {
            return '';
        }
    }
}