src/objects/Data_User__c.object
<CustomObject>
    <description>MG_Data User</description>
    <label>Data User</label>
    <nameField>
        <label>Data User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Data_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To assign a Project to a specific Data User record so it will appear in their queue.</inlineHelpText>
        <label>Data User</label>
        <referenceTo>Data_User__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Update_Request__c.object
<CustomObject>
    <description>MG_Project Update Request</description>
    <fields>
        <fullName>Data_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data User</label>
        <referenceTo>Data_User__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Update Request</label>
    <nameField>
        <displayFormat>PUR-{000000}</displayFormat>
        <label>Project Update Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectUpdateRequestCreateExt.cls
public with sharing class ProjectUpdateRequestCreateExt {
	private final Project_Update_Request__c thePUR;

    public ProjectUpdateRequestCreateExt(ApexPages.StandardController stdController) {
        thePUR = (Project_Update_Request__c)stdController.getRecord();
    }

    public PageReference goSomewhere() {
    	List<Project__c> theProjects = BuilderProjectMgmtCmn.getProjects(new Set<Id>(new Id[]{thePUR.Project__c}));
    	if (theProjects.isEmpty()) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Oops - you can only get here by clicking "New Project Update Request" from the Project you want to update. Sorry!'));
    		return null;
    	}
    	Project__c theProject = theProjects[0];

    	Set<String> projectFieldNames = BuilderProjectMgmtCmn.getProjectFields();
		Set<String> purFieldNames = BuilderProjectMgmtCmn.getProjectUpdateRequestFields();
		Map<String, String> mapProjectFieldsToPurPreviousFields = BuilderProjectMgmtCmn.getProjectToPURFieldMap();

		for (String fieldName : projectFieldNames) { // loop through all the project fields
			if (purFieldNames.contains(fieldName)) { // if the PUR has a field with the same name
				thePUR.put(fieldName, theProject.get(fieldName)); // set the value to the Project's value
			}
			if (mapProjectFieldsToPurPreviousFields.containsKey(fieldName)) { // if the PUR has a field called Previous_<fieldName>
				thePUR.put(mapProjectFieldsToPurPreviousFields.get(fieldName), theProject.get(fieldName)); // set the value to the Project's current value
			}
		}
		thePUR.Data_User__c = null;
    	insert thePUR;
    	PageReference whereToGo = new PageReference('/'+thePUR.Id+'/e?retURL=/'+thePUR.Project__c);
        return whereToGo;
    }

}