src/objects/Directory_Category__c.object
<CustomObject>
    <fields>
        <fullName>Directory_Brands__c</fullName>
        <label>Directory Brands</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aquatics International</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Architectural Lighting</fullName>
                </value>
                <value>
                    <fullName>Builder</fullName>
                </value>
                <value>
                    <fullName>Concrete Construction</fullName>
                </value>
                <value>
                    <fullName>Pool &amp; Spa News</fullName>
                </value>
                <value>
                    <fullName>Remodeling</fullName>
                </value>
                <value>
                    <fullName>Tools of the Trade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Directory Category</label>
    <nameField>
        <label>Directory Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Directory Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Directory_Categories__c</fullName>
        <label>Directory Categories</label>
        <length>3200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Premium_Directory_Categories__c</fullName>
        <label>Premium Directory Categories</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>This is a concatenation of the Product Name and marekt so that the Market displays on the Add Product to Opportunity window</description>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DirectoryCategoriesTest.cls
@isTest
private class DirectoryCategoriesTest {
    
    private static testmethod void test1() {
        Account a = new Account(name = 'test account', BillingPostalCode = '12345');
        insert a;
        
        Opportunity o = new Opportunity( name =' test opp', closedate = date.today(), stagename = 'Open', accountId = a.id);
        insert o;
        
        Pricebook2 pbk1 = new Pricebook2 (Name='Test Pricebook Entry 1',Description='Test Pricebook Entry 1', isActive=true);
        insert pbk1;
       
        Product2 prod = new Product2 (Product__c='test', Name='Concrete Construction | Directory Listing (Premium)', Description='Test Product Entry 1',productCode = 'ABC', isActive = true);
        insert prod;
        
        Id standardPb = Test.getStandardPricebookId();
        PricebookEntry pbe1 = new PricebookEntry (Product2ID=prod.id,Pricebook2ID=standardPb,UnitPrice=50, isActive=true);
        insert pbe1;
       
        Opportunitylineitem lineitem = new Opportunitylineitem(Directory_Categories__c ='test',  Premium_Directory_Categories__c= 'pc',
        opportunityId = o.id,PriceBookEntryID=pbe1.id, quantity=4, UnitPrice = 1);
        
        insert lineitem;
        
        Directory_Category__c dc1 = new Directory_Category__c(name = 'test', Directory_Brands__c='Concrete Construction');
        insert dc1;
        
                
        Test.startTest();
        Apexpages.standardController sc = new Apexpages.standardController(lineitem);
        
        DirectoryCategories dc = new DirectoryCategories(sc);
        dc.search();
        dc.search2();
        
        dc.save();
        Test.stopTest();
    }

}