src/objects/DSM_Products__c.object
<CustomObject>
    <fields>
        <fullName>Inactive_Product__c</fullName>
        <label>Inactive Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>IF( 
CONTAINS(Product_Type__c, &quot;Metrostudy&quot;), &quot;Metrostudy&quot;,
IF(
AND(CONTAINS(Product_Type__c, &quot;Marketing&quot;),Product_Type__c &lt;&gt; &quot;Strategic Marketing Services&quot;) , &quot;Marketing&quot;, 
IF( 
CONTAINS(Product_Type__c, &quot;Direct Mail List&quot;), &quot;Digital&quot;,

CASE ( Product_Type__c , 
&quot;White Paper (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Webinar (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Virtual Event&quot;, &quot;Digital&quot;, 
&quot;Video (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Strategic Marketing Services&quot;, &quot;Digital&quot;, 
&quot;Roadblock&quot;, &quot;Digital&quot;, 
&quot;Product Spotlight Blast&quot;, &quot;Digital&quot;, 
&quot;Print&quot;, &quot;Print&quot;, 
&quot;Newsletter&quot;, &quot;Digital&quot;, 
&quot;newsletter&quot;, &quot;Digital&quot;, 
&quot;HWTV (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Email Promo Blast/Marketi&quot;, &quot;Digital&quot;, 
&quot;Email List Blast&quot;, &quot;Digital&quot;, 
&quot;Education&quot;, &quot;Digital&quot;, 
&quot;Digital Edition&quot;, &quot;Digital&quot;, 
&quot;Demand Generation&quot;, &quot;Digital&quot;, 
&quot;Customer Engagement Progr&quot;, &quot;Digital&quot;, 
&quot;Event Sponsorship&quot;, &quot;Event&quot;, 
&quot;Branded Event&quot;,&quot;Event&quot;,
&quot;CPM&quot;,&quot;Digital&quot;, 
&quot;Standard CPM&quot;,&quot;Digital&quot;, 
&quot;Building Know-How JLC&quot;,&quot;Digital&quot;, 
&quot;Category Exclusive JLC&quot;,&quot;Digital&quot;, 
&quot;Consumer Specials&quot;,&quot;Digital&quot;, 
&quot;Dedicated Email&quot;,&quot;Digital&quot;, 
&quot;Newsletter Plus&quot;,&quot;Digital&quot;, 
&quot;Paid Promo Allocation&quot;,&quot;Digital&quot;, 
&quot;Run of Network&quot;,&quot;Digital&quot;, 
&quot;Targeted Sponsorship&quot;,&quot;Digital&quot;, 
&quot;SMS&quot;,&quot;Digital&quot;, 
&quot;Event&quot;,&quot;Event&quot;, 
&quot;Event Sponsorship (Custom)&quot;,&quot;Event&quot;,
&quot;Exhibitions Intercompany&quot;,&quot;Exhibitions&quot;, 
&quot;Events - Tradeshow&quot;,&quot;Event&quot;,
&quot;Events - Branded&quot;,&quot;Event&quot;,
&quot;Events - Corporate&quot;,&quot;Event&quot;,
&quot;Back Copy Sales&quot;,&quot;Print&quot;,
&quot; &quot; 
))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <externalId>true</externalId>
        <label>Product ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Full Product Name (DSM Product Name field is truncated at 80 characters)</inlineHelpText>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Subcategory__c</fullName>
        <formula>IF( 
CONTAINS( Name , &quot;Classified&quot;), &quot;Classified&quot;, 

IF( 
CONTAINS (Name, &quot;Profile Nurturing&quot;), &quot;Demand Generation&quot;, 

IF( 
CONTAINS (Name, &quot;SMS Demand Generation&quot;), &quot;Demand Generation&quot;, 

IF(
CONTAINS (Name, &quot;Corner&quot;), &quot;Classified&quot;, 

IF(
AND(
CONTAINS (Name, &quot;Surfaces&quot;), 
NOT(CONTAINS(Name, &quot;Newsletter&quot;))),&quot;Classified&quot;,

IF( 
CONTAINS(Product_Type__c, &quot;Metrostudy&quot;), &quot;Metrostudy&quot;, 
IF(
AND(CONTAINS(Product_Type__c, &quot;Marketing&quot;),Product_Type__c &lt;&gt; &quot;Strategic Marketing Services&quot;) , &quot;Marketing&quot;,
IF( 
CONTAINS(Product_Type__c, &quot;Direct Mail List&quot;), &quot;Impressions/Branding&quot;, 

CASE ( Product_Type__c , 
&quot;White Paper (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Webinar (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Virtual Event&quot;,&quot;Demand Generation&quot;, 
&quot;Video (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Run of Network&quot;,&quot;Impressions/Branding&quot;,
&quot;Stragetic Marketing Servi&quot;,&quot;SMS&quot;, 
&quot;Strategic Marketing Services&quot;,&quot;SMS&quot;, 
&quot;Roadblock&quot;,&quot;Impressions/Branding&quot;, 
&quot;Product Spotlight Blast&quot;,&quot;Impressions/Branding&quot;, 
&quot;Print&quot;,&quot;Print&quot;, 
&quot;Newsletter&quot;,&quot;Impressions/Branding&quot;, 
&quot;newsletter&quot;,&quot;Impressions/Branding&quot;, 
&quot;HWTV (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Email Promo Blast/Marketi&quot;,&quot;Impressions/Branding&quot;, 
&quot;Email List Blast&quot;,&quot;Impressions/Branding&quot;, 
&quot;Education&quot;,&quot;Demand Generation&quot;, 
&quot;Digital Edition&quot;,&quot;Impressions/Branding&quot;, 
&quot;Customer Engagement Progr&quot;,&quot;Demand Generation&quot;, 
&quot;Demand Generation&quot;,&quot;Demand Generation&quot;, 
&quot;CPM&quot;, &quot;Impressions/Branding&quot;, 
&quot;Standard CPM&quot;, &quot;Impressions/Branding&quot;, 
&quot;Consumer Specials&quot;,&quot;Impressions/Branding&quot;, 
&quot;Event Sponsorship&quot;,&quot;Events&quot;, 
&quot;Event Sponsorship (Custom)&quot;,&quot;Events&quot;,
&quot;Branded Event&quot;,&quot;Events&quot;,
&quot;Exhibitions Intercompany&quot;, &quot;Exhibitions&quot;,
&quot;Events - Tradeshow&quot;,&quot;Events&quot;,
&quot;Events - Branded&quot;,&quot;Events&quot;,
&quot;Events - Corporate&quot;,&quot;Events&quot;,
&quot;Back Copy Sales&quot;,&quot;Print&quot;,
 
&quot; &quot; 
) 
))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Subcategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_Template_ID__c</fullName>
        <label>WF Template ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSM Products</label>
    <nameField>
        <label>DSM Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSM Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>CASE (   Product_Type__c  ,
&quot;White Paper (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Webinar (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Virtual Event&quot;, &quot;Digital&quot;,
&quot;Video (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Stragetic Marketing Servi&quot;, &quot;Digital&quot;,
&quot;Roadblock&quot;, &quot;Digital&quot;,
&quot;Product Spotlight Blast&quot;, &quot;Digital&quot;,
&quot;Print&quot;, &quot;Print&quot;,
&quot;Newsletter&quot;, &quot;Digital&quot;,
&quot;HWTV (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Email Promo Blast/Marketi&quot;, &quot;Digital&quot;,
&quot;Email List Blast&quot;, &quot;Digital&quot;,
&quot;Education&quot;, &quot;Digital&quot;,
&quot;Digital Edition&quot;, &quot;Digital&quot;,
&quot;Demand Generation&quot;, &quot;Digital&quot;,
&quot;Customer Engagement Progr&quot;, &quot;Digital&quot;,
&quot;Event Sponsorship&quot;, &quot;Event&quot;,
&quot;CPM&quot;,&quot;Digital&quot;,
&quot;Direct Mail List&quot;,&quot;Digital&quot;,
&quot;Digital Field Guide Subscription&quot;,&quot;Digital&quot;,
&quot;PSNDE&quot;,&quot;Digital&quot;,
&quot; &quot;
)</description>
        <formula>IF( 
CONTAINS(Product_Type__c, &quot;Metrostudy&quot;), &quot;Metrostudy&quot;,
IF(
AND(CONTAINS(Product_Type__c, &quot;Marketing&quot;),Product_Type__c &lt;&gt; &quot;Strategic Marketing Services&quot;) , &quot;Marketing&quot;,
IF( 
CONTAINS(Product_Type__c, &quot;Direct Mail List&quot;), &quot;Digital&quot;,  

CASE (   Product_Type__c  ,
&quot;White Paper (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Webinar (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Virtual Event&quot;, &quot;Digital&quot;,
&quot;Video (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Strategic Marketing Services&quot;, &quot;Digital&quot;,
&quot;Roadblock&quot;, &quot;Digital&quot;,
&quot;Product Spotlight Blast&quot;, &quot;Digital&quot;,
&quot;Print&quot;, &quot;Print&quot;,
&quot;Newsletter&quot;, &quot;Digital&quot;,
&quot;newsletter&quot;, &quot;Digital&quot;,
&quot;HWTV (Sponsor Supplied)&quot;, &quot;Digital&quot;,
&quot;Email Promo Blast/Marketi&quot;, &quot;Digital&quot;,
&quot;Email List Blast&quot;, &quot;Digital&quot;,
&quot;Education&quot;, &quot;Digital&quot;,
&quot;Digital Edition&quot;, &quot;Digital&quot;,
&quot;Demand Generation&quot;, &quot;Digital&quot;,
&quot;Customer Engagement Progr&quot;, &quot;Digital&quot;,
&quot;Event Sponsorship&quot;, &quot;Event&quot;,
&quot;Branded Event&quot;, &quot;Event&quot;,
&quot;Custom Event&quot;, &quot;Event&quot;,
&quot;Event Sponsorship (Custom)&quot;, &quot;Event&quot;,
&quot;Education Event&quot;, &quot;Event&quot;,
&quot;CPM&quot;,&quot;Digital&quot;,
&quot;Standard CPM&quot;,&quot;Digital&quot;,
&quot;Building Know-How JLC&quot;,&quot;Digital&quot;,
&quot;Category Exclusive JLC&quot;,&quot;Digital&quot;,
&quot;Consumer Specials&quot;,&quot;Digital&quot;,
&quot;Dedicated Email&quot;,&quot;Digital&quot;,
&quot;Newsletter Plus&quot;,&quot;Digital&quot;,
&quot;Paid Promo Allocation&quot;,&quot;Digital&quot;,
&quot;Run of Network&quot;,&quot;Digital&quot;,
&quot;Targeted Sponsorship&quot;,&quot;Digital&quot;,
&quot;SMS&quot;,&quot;Digital&quot;,
&quot;Event&quot;,&quot;Event&quot;,
&quot;Exhibitions Intercompany&quot;,&quot;Exhibitions&quot;,
&quot;Direct Mail List&quot;,&quot;Digital&quot;,
&quot;Standard CPM&quot;,&quot;Digital&quot;,
&quot;Digital Field Guide Subscription&quot;,&quot;Digital&quot;,
&quot;Digital Subscription&quot;,&quot;Digital&quot;,
&quot;PSNDE&quot;,&quot;Digital&quot;,
&quot;Pool &amp; Spa News Digital&quot;,&quot;Digital&quot;,
&quot;Directory Listing&quot;,&quot;Digital&quot;,
&quot;Events - Tradeshow&quot;,&quot;Event&quot;,
&quot;Events - Branded&quot;,&quot;Event&quot;,
&quot;Events - Corporate&quot;,&quot;Event&quot;,
&quot;Back Copy Sales&quot;,&quot;Print&quot;,
&quot; &quot;
))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Subcategory__c</fullName>
        <formula>IF(
CONTAINS(DSM_Product_Name__c, &quot;CEU&quot;), &quot;Education&quot;, 

IF(
CONTAINS (DSM_Product_Name__c, &quot;Profile Nurturing&quot;), &quot;Demand Generation&quot;,

IF(
CONTAINS (DSM_Product_Name__c, &quot;SMS Demand Generation&quot;), &quot;Demand Generation&quot;,


IF( 
CONTAINS(Product_Type__c, &quot;Metrostudy&quot;), &quot;Metrostudy&quot;, 
IF(
AND(CONTAINS(Product_Type__c, &quot;Marketing&quot;),Product_Type__c &lt;&gt; &quot;Strategic Marketing Services&quot;) , &quot;Marketing&quot;, 
IF( 
CONTAINS(Product_Type__c, &quot;Direct Mail List&quot;), &quot;Impressions/Branding&quot;,

CASE ( Product_Type__c , 
&quot;White Paper (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Webinar (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Virtual Event&quot;,&quot;Demand Generation&quot;, 
&quot;Video (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;,
&quot;Run of Network&quot;,&quot;Impressions/Branding&quot;, 
&quot;Stragetic Marketing Servi&quot;,&quot;SMS&quot;, 
&quot;Strategic Marketing Services&quot;,&quot;SMS&quot;, 
&quot;Roadblock&quot;,&quot;Impressions/Branding&quot;, 
&quot;Product Spotlight Blast&quot;,&quot;Impressions/Branding&quot;, 
&quot;Print&quot;,&quot;Print&quot;, 
&quot;Newsletter&quot;,&quot;Impressions/Branding&quot;, 
&quot;newsletter&quot;,&quot;Impressions/Branding&quot;, 
&quot;HWTV (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Email Promo Blast/Marketi&quot;,&quot;Impressions/Branding&quot;, 
&quot;Email List Blast&quot;,&quot;Impressions/Branding&quot;, 
&quot;Education&quot;,&quot;Demand Generation&quot;, 
&quot;Digital Edition&quot;,&quot;Impressions/Branding&quot;, 
&quot;Customer Engagement Progr&quot;,&quot;Demand Generation&quot;, 
&quot;Demand Generation&quot;,&quot;Demand Generation&quot;,
&quot;CPM&quot;, &quot;Impressions/Branding&quot;, 
&quot;Standard CPM&quot;, &quot;Impressions/Branding&quot;,
&quot;Consumer Specials&quot;,&quot;Impressions/Branding&quot;, 
&quot;Branded Event&quot;,&quot;Events&quot;,
&quot;Custom Event&quot;,&quot;Events&quot;,
&quot;Event Sponsorship (Custom)&quot;,&quot;Events&quot;,
&quot;Education Event&quot;,&quot;Events&quot;,
&quot;Event Sponsorship&quot;,&quot;Events&quot;,
&quot;Event Sponsorship (Custom)&quot;,&quot;Events&quot;,
&quot;Exhibitions Intercompany&quot;, &quot;Exhibitions&quot;,
&quot;Paid Promo Allocation&quot;, &quot;Impressions/Branding&quot;,
&quot;Direct Mail List&quot;, &quot;Impressions/Branding&quot;,
&quot;Standard CPM&quot;, &quot;Impressions/Branding&quot;,
&quot;Digital Subscription&quot;, &quot;Impressions/Branding&quot;,
&quot;Directory Listing&quot;, &quot;Impressions/Branding&quot;,
&quot;Events - Tradeshow&quot;,&quot;Events&quot;,
&quot;Events - Branded&quot;,&quot;Events&quot;,
&quot;Events - Corporate&quot;,&quot;Events&quot;,
&quot;Back Copy Sales&quot;,&quot;Print&quot;,
&quot; &quot; 
) 
))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Subcategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_Project_ID__c</fullName>
        <label>WF Project ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ProductSearchController.cls
public without sharing class ProductSearchController {
    
    public String searchstr { get; set; }
    public String subcategory { get; set; }
    public String producttype { get; set; }
    public string productId{get;set;}
    
    public string WFProjectId{get;set;}
    public string displayMessage{get;set;}
    public Boolean showLoadError{get; set;}
    
    public List<DSMProductWrapper> productsWrapper{get;set;}
    
    public ProductSearchController() {
        WFProjectId = Apexpages.currentpage().getparameters().get('WFProjectId');
        showLoadError = false;
        displayMessage  = '';
        List<OpportunityLineItem> oltList = [Select Id,WF_Project_Id__c from OpportunityLineItem where WF_Project_Id__c =: WFProjectId];
        if(oltList.size() > 0){
            showLoadError = true;
            displayMessage = ' Products cannot be changed after project has been synced with SFDC ';
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,displayMessage);
            ApexPages.addMessage(myMsg);
        }
        
        productsWrapper = new List<DSMProductWrapper>();
        productId ='';
    }
    
    public List<Selectoption> getsubcategories() {
        List<Selectoption> options = new List<Selectoption>();
        options.add(new selectoption( 'All', 'All'));
        options.add(new selectoption( 'Classified', 'Classified'));
        options.add(new selectoption( 'Demand Generation', 'Demand Generation'));
        options.add(new selectoption( 'Events', 'Events'));
        options.add(new selectoption( 'Exhibitions', 'Exhibitions'));
        options.add(new selectoption( 'Impressions/Branding', 'Impressions/Branding'));
        options.add(new selectoption( 'Print', 'Print'));
        options.add(new selectoption( 'Marketing', 'Marketing'));
        options.add(new selectoption( 'Metrostudy', 'Metrostudy'));
        options.add(new selectoption( 'SMS', 'SMS'));
        
        return options;
    }

/*

*/
    
    public List<Selectoption> getProducttypes() {
        List<Selectoption> options = new List<Selectoption>();
        options.add(new selectoption( 'All', 'All'));
        options.add(new selectoption( 'Back Copy Sales', 'Back Copy Sales'));
        options.add(new selectoption( 'Branded Event', 'Branded Event'));
        options.add(new selectoption( 'Consumer Specials', 'Consumer Specials'));
        options.add(new selectoption( 'Customer Engagement Program', 'Customer Engagement Program'));
        options.add(new selectoption( 'Demand Generation', 'Demand Generation'));
        options.add(new selectoption( 'Digital Edition', 'Digital Edition'));
        options.add(new selectoption( 'Digital Subscription','Digital Subscription'));
        options.add(new selectoption( 'Direct Mail List','Direct Mail List'));
        options.add(new selectoption( 'Directory Listing','Directory Listing'));
        options.add(new selectoption( 'Education','Education'));
        options.add(new selectoption( 'Email List Blast','Email List Blast'));
        options.add(new selectoption( 'Event Sponsorship','Event Sponsorship'));
        options.add(new selectoption( 'Event Sponsorship (Custom)','Event Sponsorship (Custom)'));
        options.add(new selectoption( 'Exhibitions Intercompany','Exhibitions Intercompany'));
        options.add(new selectoption( 'Hanley Wood Marketing','Hanley Wood Marketing'));
        options.add(new selectoption( 'HWTV (Sponsor Supplied)','HWTV (Sponsor Supplied)'));
        options.add(new selectoption( 'Marketing','Marketing'));
        options.add(new selectoption( 'Metrostudy','Metrostudy'));
        options.add(new selectoption( 'Metrostudy Intercompany','Metrostudy Intercompany'));
        options.add(new selectoption( 'Newsletter','Newsletter'));
        options.add(new selectoption( 'Paid Promo Allocation','Paid Promo Allocation'));
        options.add(new selectoption( 'Print','Print'));
        options.add(new selectoption( 'Product Spotlight Blast','Product Spotlight Blast'));
        options.add(new selectoption( 'Roadblock','Roadblock'));
        options.add(new selectoption( 'Run of Network','Run of Network'));
        options.add(new selectoption( 'Sponsored Circulation','Sponsored Circulation'));
        options.add(new selectoption( 'Strategic Marketing Services','Strategic Marketing Services'));
        options.add(new selectoption( 'Virtual Event','Virtual Event'));
        
        return options;
    }
    
    public void search() {
        if (searchstr.trim() == '' || searchstr == null) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please specify search term.');
            ApexPages.addMessage(myMsg);
            return ;
        }
        
        productsWrapper = new List<DSMProductWrapper>();
        string str ='%' + searchstr + '%';
        
        string query = ' select id, Product_Name__c ,Product_Type__c,Product_ID__c, Product_Category__c,name, Product_Subcategory__c from DSM_Products__c ';
        string whereclause =  ' where Inactive_Product__c != \'Yes\' AND';
        
        if (subcategory != null ) {
            if (subcategory != 'All') {
                whereclause += ' Product_Subcategory__c = ' + '\'' + subcategory +'\'' + ' AND ';   
            }      
        }  
        if (producttype != null) {
            if (producttype != 'All') {
                whereclause += ' Product_Type__c = ' + '\'' + producttype +'\'' + ' AND ';   
            }    
        }  
        
        if (searchstr != null) {
            whereclause += ' (Product_Name__c like ' + '\'' + str +'\') AND ';       
        }  
        
        query = query + whereclause;
        
        query = query.trim().substring (0, query.length() - 5)+' limit 1000';
        if ( searchstr != null) {
            //system.assert(false, query);
            //[select id, Product_Type__c, Product_Category__c,name, Product_Subcategory__c from DSM_Products__c where name like: str]
            for (DSM_Products__c prod: database.query(query)) {
                productsWrapper.add(new DSMProductWrapper(prod));
            }
        }
        if(productsWrapper.size() == 0){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,'Result: Records not found.');
            ApexPages.addMessage(myMsg);
        }
        //return productsWrapper;
        //return null;
    }
    
    
    public PageReference updateProject() {
        //system.assert(false,productId);
        displayMessage ='';
        
        List<OpportunityLineItem> oltList = [Select Id,WF_Project_Id__c from OpportunityLineItem where WF_Project_Id__c =: WFProjectId];
        if(oltList.size() > 0 ) {
            displayMessage = ' Error occured : Products cannot be changed after project has been synced with SFDC ';
        }
        else{
            //WFProjectId ='576061de00c2e7445a35ae5901af2b9f';
            DSM_Products__c prod = [select id, Product_ID__c, name,Product_Name__c,WF_Template_ID__c,
            Product_Type__c, Product_Category__c, Product_Subcategory__c from DSM_Products__c where id=: productId];
            //Boolean b = WorkFrontService.updateProject(WFProjectId, prod);
            displayMessage = WorkFrontService.updateProject(WFProjectId, prod);
            if (displayMessage == '') {
                displayMessage = ' Product has been updated successfully ';
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,displayMessage);
                ApexPages.addMessage(myMsg);
            }
            else{
                List<String> lstMsg = displayMessage.split('"message":"');
                if(lstMsg.size() == 2){
                    if(lstMsg[1].split('"title"').size() == 2){
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,lstMsg[1].split('","title"')[0]);
                        ApexPages.addMessage(myMsg);
                    }
                    else{
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,displayMessage);
                        ApexPages.addMessage(myMsg);
                    }
                }
                else{
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error,displayMessage);
                    ApexPages.addMessage(myMsg);
                }
            }
        }
        
           
        
        return null;
    }
    
    public List<DSMProductWrapper> getProducts() {
        return productsWrapper;
    }
    
    public class DSMProductWrapper {
        public Boolean isSelected{get;set;}
        public DSM_Products__c product{get;set;}
        public DSMProductWrapper(DSM_Products__c product){
            this.product = product;
            isSelected = false;
        }
    }
    
    
}