src/objects/DSM_Products__c.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>IF( 
CONTAINS(Product_Type__c, &quot;Metrostudy&quot;), &quot;Metrostudy&quot;,
IF(
AND(CONTAINS(Product_Type__c, &quot;Marketing&quot;),Product_Type__c &lt;&gt; &quot;Strategic Marketing Services&quot;) , &quot;Marketing&quot;, 
IF( 
CONTAINS(Product_Type__c, &quot;Direct Mail List&quot;), &quot;Digital&quot;,

CASE ( Product_Type__c , 
&quot;White Paper (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Webinar (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Virtual Event&quot;, &quot;Digital&quot;, 
&quot;Video (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Strategic Marketing Services&quot;, &quot;Digital&quot;, 
&quot;Roadblock&quot;, &quot;Digital&quot;, 
&quot;Product Spotlight Blast&quot;, &quot;Digital&quot;, 
&quot;Print&quot;, &quot;Print&quot;, 
&quot;Newsletter&quot;, &quot;Digital&quot;, 
&quot;newsletter&quot;, &quot;Digital&quot;, 
&quot;HWTV (Sponsor Supplied)&quot;, &quot;Digital&quot;, 
&quot;Email Promo Blast/Marketi&quot;, &quot;Digital&quot;, 
&quot;Email List Blast&quot;, &quot;Digital&quot;, 
&quot;Education&quot;, &quot;Digital&quot;, 
&quot;Digital Edition&quot;, &quot;Digital&quot;, 
&quot;Demand Generation&quot;, &quot;Digital&quot;, 
&quot;Customer Engagement Progr&quot;, &quot;Digital&quot;, 
&quot;Event Sponsorship&quot;, &quot;Event&quot;, 
&quot;Branded Event&quot;,&quot;Event&quot;,
&quot;CPM&quot;,&quot;Digital&quot;, 
&quot;Standard CPM&quot;,&quot;Digital&quot;, 
&quot;Building Know-How JLC&quot;,&quot;Digital&quot;, 
&quot;Category Exclusive JLC&quot;,&quot;Digital&quot;, 
&quot;Consumer Specials&quot;,&quot;Digital&quot;, 
&quot;Dedicated Email&quot;,&quot;Digital&quot;, 
&quot;Newsletter Plus&quot;,&quot;Digital&quot;, 
&quot;Paid Promo Allocation&quot;,&quot;Digital&quot;, 
&quot;Run of Network&quot;,&quot;Digital&quot;, 
&quot;Targeted Sponsorship&quot;,&quot;Digital&quot;, 
&quot;SMS&quot;,&quot;Digital&quot;, 
&quot;Event&quot;,&quot;Event&quot;, 
&quot;Event Sponsorship (Custom)&quot;,&quot;Event&quot;,
&quot;Exhibitions Intercompany&quot;,&quot;Exhibitions&quot;, 
&quot;Events - Tradeshow&quot;,&quot;Event&quot;,
&quot;Events - Branded&quot;,&quot;Event&quot;,
&quot;Events - Corporate&quot;,&quot;Event&quot;,
&quot;Back Copy Sales&quot;,&quot;Print&quot;,
&quot; &quot; 
))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <externalId>true</externalId>
        <label>Product ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Full Product Name (DSM Product Name field is truncated at 80 characters)</inlineHelpText>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Subcategory__c</fullName>
        <formula>IF( 
CONTAINS( Name , &quot;Classified&quot;), &quot;Classified&quot;, 

IF( 
CONTAINS (Name, &quot;Profile Nurturing&quot;), &quot;Demand Generation&quot;, 

IF( 
CONTAINS (Name, &quot;SMS Demand Generation&quot;), &quot;Demand Generation&quot;, 

IF(
CONTAINS (Name, &quot;Corner&quot;), &quot;Classified&quot;, 

IF(
AND(
CONTAINS (Name, &quot;Surfaces&quot;), 
NOT(CONTAINS(Name, &quot;Newsletter&quot;))),&quot;Classified&quot;,

IF( 
CONTAINS(Product_Type__c, &quot;Metrostudy&quot;), &quot;Metrostudy&quot;, 
IF(
AND(CONTAINS(Product_Type__c, &quot;Marketing&quot;),Product_Type__c &lt;&gt; &quot;Strategic Marketing Services&quot;) , &quot;Marketing&quot;,
IF( 
CONTAINS(Product_Type__c, &quot;Direct Mail List&quot;), &quot;Impressions/Branding&quot;, 

CASE ( Product_Type__c , 
&quot;White Paper (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Webinar (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Virtual Event&quot;,&quot;Demand Generation&quot;, 
&quot;Video (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Run of Network&quot;,&quot;Impressions/Branding&quot;,
&quot;Stragetic Marketing Servi&quot;,&quot;SMS&quot;, 
&quot;Strategic Marketing Services&quot;,&quot;SMS&quot;, 
&quot;Roadblock&quot;,&quot;Impressions/Branding&quot;, 
&quot;Product Spotlight Blast&quot;,&quot;Impressions/Branding&quot;, 
&quot;Print&quot;,&quot;Print&quot;, 
&quot;Newsletter&quot;,&quot;Impressions/Branding&quot;, 
&quot;newsletter&quot;,&quot;Impressions/Branding&quot;, 
&quot;HWTV (Sponsor Supplied)&quot;,&quot;Impressions/Branding&quot;, 
&quot;Email Promo Blast/Marketi&quot;,&quot;Impressions/Branding&quot;, 
&quot;Email List Blast&quot;,&quot;Impressions/Branding&quot;, 
&quot;Education&quot;,&quot;Demand Generation&quot;, 
&quot;Digital Edition&quot;,&quot;Impressions/Branding&quot;, 
&quot;Customer Engagement Progr&quot;,&quot;Demand Generation&quot;, 
&quot;Demand Generation&quot;,&quot;Demand Generation&quot;, 
&quot;CPM&quot;, &quot;Impressions/Branding&quot;, 
&quot;Standard CPM&quot;, &quot;Impressions/Branding&quot;, 
&quot;Consumer Specials&quot;,&quot;Impressions/Branding&quot;, 
&quot;Event Sponsorship&quot;,&quot;Events&quot;, 
&quot;Event Sponsorship (Custom)&quot;,&quot;Events&quot;,
&quot;Branded Event&quot;,&quot;Events&quot;,
&quot;Exhibitions Intercompany&quot;, &quot;Exhibitions&quot;,
&quot;Events - Tradeshow&quot;,&quot;Events&quot;,
&quot;Events - Branded&quot;,&quot;Events&quot;,
&quot;Events - Corporate&quot;,&quot;Events&quot;,
&quot;Back Copy Sales&quot;,&quot;Print&quot;,
 
&quot; &quot; 
) 
))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Subcategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WF_Template_ID__c</fullName>
        <label>WF Template ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSM Products</label>
    <nameField>
        <label>DSM Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSM Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WorkFrontService.cls
public class WorkFrontService {
    public static string login_Url = 'https://hanleywood.attask-ondemand.com/attask/api/login';
    public static string Project_Url = 'https://hanleywood.attask-ondemand.com/attask/api/v4.0/project';
    
    
    static string username = 'rainmakeradmin%2Bhwworkfront@rainmakercloud.com';
    static string password = 'rain2020';
    
    public static string login() {
        string sessionId ;
        string url = login_Url + '?username='+ username +'&password='+ password;
        string jsonstr = getCalloutResponseContents(url, 'GET');
        
        system.debug('#######'+jsonstr);
        WF_Loginresponse loginresponse = WF_Loginresponse.parse(jsonstr);
        
        sessionId = loginresponse.data.sessionID;
        
        system.debug('sessionId' + sessionId);
        return sessionId;
    }
    
    public static String updateProject(string projectId, DSM_Products__c prod) {
        //Product_ID__c, name,Product_Type__c, Product_Category__c, Product_Subcategory__c 
        
        try {
            //projectId = '56f006ec00ac4e12df7549307c334fc6';
            string sessionId = login();
            string url = Project_Url + '?id='+ projectId +'&sessionID='+ sessionId+'&method=PUT';
            
            url += '&DE:Product%20ID='+prod.Product_ID__c;
            String prodName = '';
            if(prod.Product_Name__c != null){
                prodName = prod.Product_Name__c;
            }
            else{
                prodName = prod.Name;
        
            }
            if(prodName != ''){
                url += '&name='+EncodingUtil.urlEncode(prodName,'UTF-8');
                url += '&DE:Product%20Name='+EncodingUtil.urlEncode(prodName,'UTF-8');
            }
            if(prod.Product_Category__c != null){
                url += '&DE:DSM%20Product%20Category='+EncodingUtil.urlEncode(prod.Product_Category__c,'UTF-8');
            }
            if(prod.Product_Subcategory__c != null){
                url += '&DE:DSM%20Product%20Sub%20Category='+EncodingUtil.urlEncode(prod.Product_Subcategory__c,'UTF-8');
            }
            if(prod.Product_Type__c != null){
                url += '&DE:DSM%20Product%20Type='+EncodingUtil.urlEncode(prod.Product_Type__c,'UTF-8');
            }
            url += '&categoryID=57054be50005e22dc7f6fcf7b2826fc8';
            string jsonstr = getCalloutResponseContents(url, 'GET');
            if(jsonstr.indexOf('{"error":') != -1){
                return jsonstr;    
            }
            if(prod.WF_Template_ID__c != null){
                    string urlTemp = Project_Url + '/'+ projectId +'/attachTemplate?sessionID='+ sessionId+'&method=PUT';
                    urlTemp  += '&templateID='+prod.WF_Template_ID__c;
                    string jsonstrTemp = getCalloutResponseContents(urlTemp, 'GET');
            }
            
            return '';
        }
        catch(Exception e) {
            
            return e.getMessage();
        }
    }
    
    public static Boolean updateProject(string projectId, string productId) {
        try {
            //projectId = '56f006ec00ac4e12df7549307c334fc6';
            string sessionId = login();
            string url = Project_Url + '?id='+ projectId +'&sessionID='+ sessionId+'&method=PUT'+'&DE:Product%20ID='+productId;
            //system.assert(false,url);
            //Builder Test Product Line Item (Project)
            string jsonstr = getCalloutResponseContents(url, 'GET');
            return true;
        }
        catch(Exception e) {
            return false;
        }
    }
    //PUT /attask/api/project?id=4c7...&name=New Project Name
    //sessionID

    /*
    
    {"data":{"userID":"56b4d0bc0024d04ea8d5101d1f50925a","sessionID":"460cc40c1fda4ef09734216cd5c9d583","versionInformation":{"currentAPI":"v5.0","buildNumber":"963b2bed623a06c6aa2e3f21f6f451e7c6acb980","apiVersions":{"v1.0":"\/attask\/api\/v1.0\/","v2.0":"\/attask\/api\/v2.0\/","v3.0":"\/attask\/api\/v3.0\/","v4.0":"\/attask\/api\/v4.0\/","v5.0":"\/attask\/api\/v5.0\/"},"lastUpdated":"2016\/06\/06 20:18:35","release":"R16","version":"4.0"},"locale":"en_US","timeZone":"US\/Mountain","timeZoneName":"Mountain Standard Time","iso3Country":"USA","iso3Language":"eng","currency":{"useNegativeSign":false,"fractionDigits":2,"symbol":"$","ID":"USD","groupingSeparator":",","decimalSeparator":"."}}}
    */
    
    // Pass in the endpoint to be used using the string url
    public static String getCalloutResponseContents(String url, string method) {
    
        // Instantiate a new http object
        Http h = new Http();
        
         // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.settimeout(60000);
        /*if (method == 'POST') {
            req.setHeader('Content-Type','multipart/form-data;');
            req.setHeader('Content-Length', url.length() +'');
        }*/
        req.setMethod(method);
        
        // Send the request, and return a response
        HttpResponse res = h.send(req);
        return res.getBody();
    }
}