src/objects/echosign_dev1__SIGN_Agreement__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchosignHelp</customHelpPage>
    <fields>
        <fullName>FC_Manual_EchoSign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FC Manual Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__DateSigned__c</fullName>
        <label>Date Signed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>R00N70000001hM2REAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Recipient2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Recipient 1 (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__SignatureType__c</fullName>
        <label>Signature Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Written Signature</fullName>
                </value>
                <value>
                    <fullName>e-Signature</fullName>
                    <default>true</default>
                    <label>e-Signature</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>echosign_dev1__Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pre-Send</fullName>
                </value>
                <value>
                    <fullName>Out for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Signature</fullName>
                </value>
                <value>
                    <fullName>Send in Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Approval</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>AppStage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote template that is used to generate the Quote PDF or Word document.</description>
        <inlineHelpText>The Quote template that will be used to generate the Quote PDF or Word document.  If not selected, the user will select a quote template from a list of available quote templates when creating Quote PDF or Word document.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>zqu__Quote_Template__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Status__c</fullName>
        <description>The Status of the Quote.</description>
        <inlineHelpText>The Status of the Quote.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent to Z-Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Signed</fullName>
        <active>true</active>
        <label>Signed</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote_Template__c.object
<CustomObject>
    <description>Quote template for generate PDF or WORD</description>
    <fields>
        <fullName>zqu__IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate this template is the default one of the refer quote type</description>
        <inlineHelpText>Indicate this template is the default one of the refer quote type</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Quote_Type__c</fullName>
        <description>Quote types.</description>
        <inlineHelpText>Quote Type</inlineHelpText>
        <label>Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Subscription</fullName>
                    <default>true</default>
                    <label>New Subscription</label>
                </value>
                <value>
                    <fullName>Amend Subscription</fullName>
                </value>
                <value>
                    <fullName>Renew Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Template_Id__c</fullName>
        <description>The template Id in Zuora</description>
        <inlineHelpText>The template Id in Zuora</inlineHelpText>
        <label>Template Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Quote Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestEditManualAgreementController.cls
@isTest
private class FC_TestEditManualAgreementController {
	private static final String QUOTE_TEMPLATE_NAME = 'Test Quote Template';
	@testSetup
	static void setup(){

		 Account testAccount = new Account(Name = 'TestAccount', BillingPostalCode = '12345');
        insert testAccount;
        
        Opportunity[] testOpportunities = new Opportunity[] {
            	new Opportunity(Name = 'TestOpportunity', AccountId = testAccount.Id, 
                                StageName = 'New', CloseDate = Date.today())};
        insert testOpportunities;
        
        zqu__Quote_Template__c[] testQuoteTemplates = new zqu__Quote_Template__c[] {
            	new zqu__Quote_Template__c(Name = QUOTE_TEMPLATE_NAME, zqu__IsDefault__c = true, 
                                           zqu__Quote_Type__c = 'New Subscription', zqu__Template_Id__c = '12345') };
        upsert testQuoteTemplates;

        zqu__Quote__c[] testQuotes = new zqu__Quote__c[] { 
            	new zqu__Quote__c(Name = 'TestQuote', RecordTypeId = fcf.RecordTypeUtil.findByName('zqu__Quote__c.Default').Id, Approval_Status__c = '', 
                                  zqu__QuoteTemplate__c = testQuoteTemplates[0].Id, zqu__QuoteTemplate__r = testQuoteTemplates[0], zqu__Status__c = 'New',
                                  zqu__Opportunity__c = testOpportunities[0].Id)};
        insert testQuotes;

		echosign_dev1__SIGN_Agreement__c es = new echosign_dev1__SIGN_Agreement__c();

		es.FC_Manual_EchoSign__c = true;
		es.echosign_dev1__Account__c = testAccount.id;
		es.Name = 'agreement1';
		es.echosign_dev1__Status__c = 'Signed';
		es.echosign_dev1__Recipient2__c = null;
		es.echosign_dev1__Opportunity__c = testOpportunities[0].id;
		es.Quote__c = null;
		es.echosign_dev1__SignatureType__c = 'Written Signature';
		es.echosign_dev1__DateSigned__c = Date.today();

		insert es;



		echosign_dev1__SIGN_Agreement__c es2 = new echosign_dev1__SIGN_Agreement__c();

		es2.FC_Manual_EchoSign__c = true;
		es2.echosign_dev1__Account__c = testAccount.id;
		es2.Name = 'agreement2';
		es2.echosign_dev1__Status__c = 'Signed';
		es2.echosign_dev1__Recipient2__c = null;
		es2.echosign_dev1__Opportunity__c = null;
		es2.Quote__c = testQuotes[0].id;
		es2.echosign_dev1__SignatureType__c = 'Written Signature';
		es2.echosign_dev1__DateSigned__c = Date.today();

		insert es2;


	}

	@isTest 
	static void testEditAgreement() {
		
		test.startTest();
		List<echosign_dev1__SIGN_Agreement__c> eslist = [Select Id,echosign_dev1__Opportunity__c  from echosign_dev1__SIGN_Agreement__c where Name='agreement1'];
		System.assertEquals(1,eslist.size());
		ApexPages.StandardController sc = new ApexPages.StandardController(eslist[0]);


		PageReference pgRef = Page.FC_EditManualAgreement;
		pgRef.getParameters().put('id',eslist[0].id);
		String oppId = eslist[0].echosign_dev1__Opportunity__c;
		pgRef.getParameters().put('retURL', oppId);
		
		test.SetCurrentPage(pgRef);
		FC_EditManualAgreementController fce = new FC_EditManualAgreementController(sc);

		PageReference pr = fce.SelectPage();
		System.assertEquals(null,pr);
		PageReference pr1 = fce.Save();
		System.assertNotEquals(null,pr1);
		PageReference pr2 = fce.Cancel();
		System.assertNotEquals(null,pr2);



		test.stopTest();


	}
	
}