src/objects/echosign_dev1__SIGN_Agreement__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchosignHelp</customHelpPage>
    <fields>
        <fullName>FC_Manual_EchoSign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FC Manual Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__AgreementLocale__c</fullName>
        <description>Select the language of the recipients.</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chinese (China)</fullName>
                </value>
                <value>
                    <fullName>Chinese (Taiwan)</fullName>
                </value>
                <value>
                    <fullName>Danish (Denmark)</fullName>
                </value>
                <value>
                    <fullName>Dutch (Netherlands)</fullName>
                </value>
                <value>
                    <fullName>English (United Kingdom)</fullName>
                </value>
                <value>
                    <fullName>English (United States)</fullName>
                    <default>true</default>
                    <label>English (United States)</label>
                </value>
                <value>
                    <fullName>Finnish (Finland)</fullName>
                </value>
                <value>
                    <fullName>French (France)</fullName>
                </value>
                <value>
                    <fullName>German (Germany)</fullName>
                </value>
                <value>
                    <fullName>Icelandic (Iceland)</fullName>
                </value>
                <value>
                    <fullName>Indonesian (Indonesia)</fullName>
                </value>
                <value>
                    <fullName>Italian (Italy)</fullName>
                </value>
                <value>
                    <fullName>Japanese (Japan)</fullName>
                </value>
                <value>
                    <fullName>Korean (South Korea)</fullName>
                </value>
                <value>
                    <fullName>Malay (Malaysia)</fullName>
                </value>
                <value>
                    <fullName>Norwegian (Norway)</fullName>
                </value>
                <value>
                    <fullName>Polish (Poland)</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Portugal)</fullName>
                </value>
                <value>
                    <fullName>Russian (Russia)</fullName>
                </value>
                <value>
                    <fullName>Spanish (Spain)</fullName>
                </value>
                <value>
                    <fullName>Swedish (Sweden)</fullName>
                </value>
                <value>
                    <fullName>Thai (Thailand)</fullName>
                </value>
                <value>
                    <fullName>Vietnamese (Vietnam)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>echosign_dev1__DateSigned__c</fullName>
        <label>Date Signed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>R00N70000001hM2REAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Recipient2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Recipient 1 (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__SignatureType__c</fullName>
        <label>Signature Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Written Signature</fullName>
                </value>
                <value>
                    <fullName>e-Signature</fullName>
                    <default>true</default>
                    <label>e-Signature</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>echosign_dev1__Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pre-Send</fullName>
                </value>
                <value>
                    <fullName>Out for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Signature</fullName>
                </value>
                <value>
                    <fullName>Send in Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Approval</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_EditManualAgreementController.cls
public with sharing class FC_EditManualAgreementController {
    
    public echosign_dev1__SIGN_Agreement__c clientAgreement{get;set;}
    private ApexPages.StandardController scController;
    public String returnUrl {get;set;}

    public FC_EditManualAgreementController(ApexPages.StandardController stdController) {

        scController = stdController;
        Map<String, String> parameterListing = apexpages.currentpage().getparameters();
        Set<string> keys = parameterListing.keySet();
        if(keys.contains('retURL')){
            String parentId = apexpages.currentpage().getparameters().get('retURL');
            this.returnUrl = '/' + parentId;
        }

        echosign_dev1__SIGN_Agreement__c  ecdObject = (echosign_dev1__SIGN_Agreement__c) stdController.getRecord();

        this.clientAgreement = [Select Id, FC_Manual_EchoSign__c,echosign_dev1__Account__c, Name,echosign_dev1__Status__c,echosign_dev1__Recipient2__c,echosign_dev1__Opportunity__c,Quote__c,echosign_dev1__SignatureType__c,echosign_dev1__DateSigned__c,echosign_dev1__AgreementLocale__c From echosign_dev1__SIGN_Agreement__c where id = :ecdObject.Id];

    }

    public PageReference selectPage(){

        PageReference pgRef  = null;

        if(!this.clientAgreement.FC_Manual_EchoSign__c){

            String url = '/apex/echosign_dev1__EchoSignAgreementAdvanced?retURL=' + this.returnUrl;
            pgRef = new PageReference(url);
            pgRef.setRedirect(true);

        }

        return pgRef;

    }

    public PageReference save(){

        update this.clientAgreement;

        System.debug('-- ' + returnUrl);
        PageReference pgRef = new PageReference(this.returnUrl);

        pgRef.setRedirect(true);

        return pgRef;
    }

    public PageReference cancel(){

            return scController.cancel();

    }

}