src/objects/echosign_dev1__SIGN_Agreement__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchosignHelp</customHelpPage>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pre-Send</fullName>
                </value>
                <value>
                    <fullName>Out for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Signature</fullName>
                </value>
                <value>
                    <fullName>Send in Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Approval</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_EchosignAgreementCache.cls
public class FC_EchosignAgreementCache {

    private static String[] ECHOSIGN_AGREEMENT_FIELDS = new String[] {
            'Id', 'Quote__c', 'echosign_dev1__Status__c' };

    private static final Map<ID, echosign_dev1__SIGN_Agreement__c> BY_ID_MAP = new Map<ID, echosign_dev1__SIGN_Agreement__c>();

    private static final Map<ID, Set<echosign_dev1__SIGN_Agreement__c>> BY_QUOTE_ID_MAP = new Map<ID, Set<echosign_dev1__SIGN_Agreement__c>>();

    private static final String SOQL_BASE;
    
    static {
        SOQL_BASE = String.format('select {0} from echosign_dev1__SIGN_Agreement__c', 
                                  new String[] { String.join(ECHOSIGN_AGREEMENT_FIELDS, ', ') });              
    }
    
    public static void clearCache() {
        BY_ID_MAP.clear();
        BY_QUOTE_ID_MAP.clear();
    }
    
    public static Map<ID, Set<echosign_dev1__SIGN_Agreement__c>> findSignedAgreementsByQuoteIds(Set<ID> quoteIds) {
        Map<ID, Set<echosign_dev1__SIGN_Agreement__c>> results = new Map<ID, Set<echosign_dev1__SIGN_Agreement__c>>();
        Set<ID> quoteIdsToQuery = new Set<ID>();
        for (ID quoteId : quoteIds) {
            if (BY_QUOTE_ID_MAP.containsKey(quoteId)) {
                results.put(quoteId, BY_QUOTE_ID_MAP.get(quoteId));
            } else {
                quoteIdsToQuery.add(quoteId);
            }
        }
        if (quoteIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Quote__c in :quoteIdsToQuery and echosign_dev1__Status__c = \'Signed\'';
            for (echosign_dev1__SIGN_Agreement__c agreementRecord : Database.query(soql)) {
                Set<echosign_dev1__SIGN_Agreement__c> agreements = results.get(agreementRecord.Quote__c);
                if (agreements == null) {
                    agreements = new Set<echosign_dev1__SIGN_Agreement__c>();
                    results.put(agreementRecord.Quote__c, agreements);
                }
                agreements.add(agreementRecord);
                BY_QUOTE_ID_MAP.put(agreementRecord.Quote__c, agreements);                
                BY_ID_MAP.put(agreementRecord.Id, agreementRecord);
            }
        }
        return results;
    }
    
}