src/objects/echosign_dev1__SIGN_Agreement__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchosignHelp</customHelpPage>
    <fields>
        <fullName>FC_Manual_EchoSign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FC Manual Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__DateSigned__c</fullName>
        <label>Date Signed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>R00N70000001hM2REAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Recipient2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Recipient 1 (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__SignatureType__c</fullName>
        <label>Signature Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Written Signature</fullName>
                </value>
                <value>
                    <fullName>e-Signature</fullName>
                    <default>true</default>
                    <label>e-Signature</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>echosign_dev1__Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pre-Send</fullName>
                </value>
                <value>
                    <fullName>Out for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Signature</fullName>
                </value>
                <value>
                    <fullName>Send in Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Approval</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account associated with this Quote.</description>
        <inlineHelpText>The Account associated with this Quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact that is billed for this Quote.</description>
        <inlineHelpText>The Contact that is billed for this Quote.</inlineHelpText>
        <label>Bill to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Signed</fullName>
        <active>true</active>
        <label>Signed</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_NewManualAgreementController.cls
public with sharing class FC_NewManualAgreementController {

    public Boolean isOpportunity;

    public String returnUrl {get;set;}

    public echosign_dev1__SIGN_Agreement__c clientAgreement{get;set;}

    public Attachment agreementDocument {get; set;}

    public FC_NewManualAgreementController() {
    

        Map<String, String> parameterListing = apexpages.currentpage().getparameters();
        Set<string> keys = parameterListing.keySet();
        Id oppId, quoteId;
        this.clientAgreement = new  echosign_dev1__SIGN_Agreement__c();
        this.clientAgreement.echosign_dev1__SignatureType__c = 'Written Signature';
        this.clientAgreement.FC_Manual_EchoSign__c = true;
        this.clientAgreement.echosign_dev1__Status__c = 'Signed';
        this.clientAgreement.echosign_dev1__DateSigned__c = datetime.now();
        if(keys.contains('opportunityId')){
            this.isOpportunity = true;
            oppId = apexpages.currentpage().getparameters().get('opportunityId');
            this.clientAgreement.echosign_dev1__Opportunity__c = oppId;
            List<Opportunity> oppList = [Select Id, AccountId, Name from Opportunity where id = :oppId ];

            this.clientAgreement.echosign_dev1__Account__c = oppList[0].AccountId;
            //this.clientAgreement.Name =  oppList[0].Name;
            returnUrl = '/' + oppId;
        }
        if(keys.contains('quoteId')){
            this.isOpportunity = false;
            quoteId = apexpages.currentpage().getparameters().get('quoteId');
            List<zqu__Quote__c> quoteList = [Select Id, zqu__Opportunity__c, zqu__Account__c,zqu__BillToContact__c, Name from zqu__Quote__c where id = :quoteId ];
            this.clientAgreement.echosign_dev1__Account__c = quoteList[0].zqu__Account__c;
            //this.clientAgreement.Name =  quoteList[0].Name;
            this.clientAgreement.echosign_dev1__Opportunity__c = quoteList[0].zqu__Opportunity__c;
            this.clientAgreement.echosign_dev1__Recipient2__c = quoteList[0].zqu__BillToContact__c;

            this.clientAgreement.Quote__c = quoteId;
            returnUrl =  '/' + quoteId;
        }
        
    }

    public void createDocument(){
        Attachment att = new Attachment();
        att.OwnerId = UserInfo.getUserId();
        this.agreementDocument = att;
    } 

    public PageReference save(){

        if(String.isBlank(this.clientAgreement.Name) ){
            this.clientAgreement.Name =  this.agreementDocument.Name;
        }

        insert this.clientAgreement;

        this.agreementDocument.ParentId = this.clientAgreement.Id;
        insert this.agreementDocument;
        Attachment parentObjectAtt = this.agreementDocument.clone(false,true,false,false);

        parentObjectAtt.ParentId = this.isOpportunity ? this.clientAgreement.echosign_dev1__Opportunity__c : this.clientAgreement.Quote__c;
        
        insert parentObjectAtt;

        System.debug('-- ' + returnUrl);
        PageReference pgRef = new PageReference(this.returnUrl);

        pgRef.setRedirect(true);

        return pgRef;
    }

    public PageReference cancel(){

        PageReference pgRef = new PageReference(this.returnUrl);

        pgRef.setRedirect(true);

        return pgRef;
    }


}