src/objects/FC_Approval_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Bypass_DBD_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass DBD Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>(FC) Approval Settings</label>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Original_Record_Type_Name__c</fullName>
        <defaultValue>&quot;Default&quot;</defaultValue>
        <label>Original Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote template that is used to generate the Quote PDF or Word document.</description>
        <inlineHelpText>The Quote template that will be used to generate the Quote PDF or Word document.  If not selected, the user will select a quote template from a list of available quote templates when creating Quote PDF or Word document.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>zqu__Quote_Template__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote_Template__c.object
<CustomObject>
    <description>Quote template for generate PDF or WORD</description>
    <fields>
        <fullName>zqu__Template_Id__c</fullName>
        <description>The template Id in Zuora</description>
        <inlineHelpText>The template Id in Zuora</inlineHelpText>
        <label>Template Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Quote Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__QuoteCharge__c.object
<CustomObject>
    <description>The Charges that are related to a Quote.</description>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>Name from the catalog via product rate plan charge</description>
        <formula>zqu__ProductRatePlanCharge__r.zqu__ProductRatePlan__r.zqu__ZProduct__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__EffectivePrice__c</fullName>
        <description>The Effective Price of the Charge.</description>
        <inlineHelpText>The Effective Price of the Charge.</inlineHelpText>
        <label>Effective Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__ListPrice__c</fullName>
        <formula>IF(zqu__ListPriceDisplay__c  == 0, zqu__ProductRatePlanCharge__r.zqu__ListPrice__c, zqu__ListPriceDisplay__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <description>The Quote related to the Charges.</description>
        <inlineHelpText>The Quote related to the Charges.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Charges</relationshipLabel>
        <relationshipName>QuoteCharge</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Charge</label>
    <nameField>
        <label>Quote Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlan__c.object
<CustomObject>
    <description>A QuoteRatePlan is part of a Quote.</description>
    <fields>
        <fullName>zqu__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote Rate Plan associated with a Quote.</description>
        <label>Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quote Rate Plans</relationshipLabel>
        <relationshipName>Quote_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Rate Plan</label>
    <nameField>
        <label>Quote Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>ProductName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__EffectivePrice__c</fullName>
        <label>Effective Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__ListPrice__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteRatePlan__c</fullName>
        <description>The identification of the rate plan that this charge applies to.</description>
        <label>Quote Rate Plan</label>
        <referenceTo>zqu__QuoteRatePlan__c</referenceTo>
        <relationshipLabel>Quote Rate Plan Charges</relationshipLabel>
        <relationshipName>Quote_Rate_Plan_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FC_GenerateQuoteRedirectController.cls
public without sharing class FC_GenerateQuoteRedirectController {

    private final ApexPages.StandardController standardController;
    private final zqu__Quote__c quoteRecord;
    
    public FC_GenerateQuoteRedirectController(ApexPages.StandardController standardController) {
        this.standardController = standardController;
        this.quoteRecord = (zqu__Quote__c) standardController.getRecord();
    }
    
    public PageReference redirectPdf() {
        if (!isValid()) {
            return null;
        }
        return redirect('pdf');    
    }
    
    public PageReference redirectDoc() {
        if (!isValid()) {
            return null;
        }
        return redirect('doc');
    }
    
    private Boolean isValid() {
        FC_Approval_Settings__c fcApprovalSettings = FC_Approval_Settings__c.getInstance();
        if (quoteRecord.zqu__QuoteTemplate__c == null) {
            PageReference prEditQuoteDetail = Page.zqu__EditQuoteDetail;
            prEditQuoteDetail.getParameters().put('id', quoteRecord.Id);
            prEditQuoteDetail.setRedirect(true);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                                                       'Please select a quote template by editing the quote details. ' +
                                                       '<a href="' + prEditQuoteDetail.getUrl() + '">Take me there!</a>'));
            return false;
        }

        if (quoteRecord.Original_Record_Type_Name__c == 'Default' || quoteRecord.Original_Record_Type_Name__c == 'Amendment') {
            ID quoteId = quoteRecord.Id;
            String chargeSoqlTemplate = 'select Id, zqu__ListPrice__c, zqu__EffectivePrice__c ' +
                    'from {0} where ProductName__c = \'\'Residential Economic Report\'\' and {1} = :quoteId';
            String chargeSoql = String.format(chargeSoqlTemplate, 
                    new String[] { quoteRecord.Original_Record_Type_Name__c == 'Amendment' ? 'zqu__QuoteRatePlanCharge__c' : 'zqu__QuoteCharge__c',
                            quoteRecord.Original_Record_Type_Name__c == 'Amendment' ? 'zqu__QuoteRatePlan__r.zqu__Quote__c' : 'zqu__Quote__c' });
            for (SObject charge : Database.query(chargeSoql)) {
                Decimal listPrice = (Decimal) charge.get('zqu__ListPrice__c');
                Decimal effectivePrice = (Decimal) charge.get('zqu__EffectivePrice__c');
                if (!fcApprovalSettings.Bypass_DBD_Approval__c && effectivePrice < listPrice) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Discounting not allowed on REE Product.'));
                    return false;
                }
            }
        }

        return true;
    }
    
    private PageReference redirect(String format) {
        URL zuoraInstanceUrl = null;
        String zuoraSessionId = '';
        if (!Test.isRunningTest()) {
            Zuora.zApi zApiInstance = new Zuora.zApi();
            Zuora.zApi.LoginResult loginResult = zApiInstance.zlogin();
            zuoraSessionId = loginResult.Session;
            zuoraInstanceUrl = new URL(loginResult.ServerUrl);
        } else {
            zuoraSessionId = 'abcdef123456';
            zuoraInstanceUrl = new URL('https://example.zuora.com');
        }
        String endpointUrl = zuoraInstanceUrl.getProtocol()+ '://' + zuoraInstanceUrl.getHost() + '/apps/servlet/GenerateQuote';
        Map<String, String> params = new Map<String, String> {
            'attachToOpportunity' => 'true',
            'format' => format,
            'locale' => 'en_US',
            'quoteId' => quoteRecord.Id,
            'serverUrl' => FC_InstanceUtils.getBaseUrlForInstance() + '/services/Soap/u/10.0/' + UserInfo.getOrganizationId(),
            'sessionId' => UserInfo.getSessionID(),
            'templateId' => quoteRecord.zqu__QuoteTemplate__r.zqu__Template_Id__c,
            'useSFDCLocale' => '1',
            'ZSession' => zuoraSessionId
        };
        String[] paramList = new List<String>();
        for (String key : params.keySet()) {
            paramList.add(String.join(new String[] { key, EncodingUtil.urlEncode(params.get(key), 'UTF-8') }, '='));
        }
        String paramString = String.join(paramList, '&');
        endpointUrl = String.join(new String[] { endpointUrl, paramString }, '?');
        System.debug('********* REQUEST 1: ' + endpointUrl);
        Http httpClient = new Http();
        HttpRequest request1 = new HttpRequest();
        request1.setEndpoint(endpointUrl);
        request1.setTimeout(120000);
        request1.setMethod('GET');
        request1.setHeader('Connection', 'close');
        HttpResponse response1 = httpClient.send(request1);
        System.debug('********* RESPONSE 1: ' + response1.getBody());

        if (response1.getStatusCode() != 200) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                                                           String.format('Request 1: {0} - {1}', 
                                                                         new String[] { String.valueOf(response1.getStatusCode()),
                                                                             response1.getStatus() })));
                return null;
        }
        return standardController.view();
    }
}