src/objects/FC_Billing_Instruction_Set__c.object
<CustomObject>
    <fields>
        <fullName>Instruction_Parameters__c</fullName>
        <label>Instruction Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Line Item ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Sets</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>FC_Billing_Instruction_Template__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Sets</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Sets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(FC) Billing Instruction Set</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Billing Instruction Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Billing_Instruction_Template__c.object
<CustomObject>
    <label>(FC) Billing Instruction Template</label>
    <nameField>
        <label>(FC) Billing Instruction Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Initial_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <label>(FC) Initial Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Term_End_Date__c</fullName>
        <label>(FC) Term End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FC_FcBillingInstructionSetCache.cls
public class FC_FcBillingInstructionSetCache {

    private static final String[] SELECT_FIELDS = new String[]{
            'Id', 'Opportunity__c', 'Opportunity__r.FC_Initial_Term__c', 'Opportunity__r.FC_Term_End_Date__c',
            'Opportunity_Line_Item_ID__c', 'Instruction_Parameters__c', 'Template__c', 'Template__r.Name'
    };

    private static final Map<ID, FC_Billing_Instruction_Set__c> BY_ID_MAP = new Map<ID, FC_Billing_Instruction_Set__c>();
    private static final Map<ID, FC_Billing_Instruction_Set__c> BY_OPPORTUNITY_LINE_ITEM_ID_MAP = new Map<ID, FC_Billing_Instruction_Set__c>();

    private static final String SOQL_BASE;

    static {
        SOQL_BASE = String.format('select {0} from FC_Billing_Instruction_Set__c',
                new String[]{
                        String.join(SELECT_FIELDS, ', ')
                });
    }

    public static void clearCache() {
        BY_ID_MAP.clear();
        BY_OPPORTUNITY_LINE_ITEM_ID_MAP.clear();
    }

    public static Map<ID, FC_Billing_Instruction_Set__c> findByIds(Set<ID> recordIds) {
        Map<ID, FC_Billing_Instruction_Set__c> results = new Map<ID, FC_Billing_Instruction_Set__c>();
        Set<ID> recordIdsToQuery = new Set<ID>();
        for (ID recordId : recordIds) {
            if (BY_ID_MAP.containsKey(recordId)) {
                results.put(recordId, BY_ID_MAP.get(recordId));
            } else {
                recordIdsToQuery.add(recordId);
            }
        }
        if (recordIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Id in :recordIdsToQuery';
            for (FC_Billing_Instruction_Set__c record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                results.put(record.Id, record);
            }
        }
        return results;
    }

    public static Map<ID, FC_Billing_Instruction_Set__c> findByOpportunityLineItemIds(Set<ID> opportunityLineItemIds) {
        Map<ID, FC_Billing_Instruction_Set__c> results = new Map<ID, FC_Billing_Instruction_Set__c>();
        Set<ID> opportunityLineItemIdsToQuery = new Set<ID>();
        for (ID opportunityLineItemId : opportunityLineItemIds) {
            if (BY_OPPORTUNITY_LINE_ITEM_ID_MAP.containsKey(opportunityLineItemId)) {
                results.put(opportunityLineItemId, BY_OPPORTUNITY_LINE_ITEM_ID_MAP.get(opportunityLineItemId));
            } else {
                opportunityLineItemIdsToQuery.add(opportunityLineItemId);
            }
        }
        if (opportunityLineItemIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Opportunity_Line_Item_ID__c in :opportunityLineItemIdsToQuery';
            for (FC_Billing_Instruction_Set__c record : Database.query(soql)) {
                try {
                    ID opportunityLineItemId = Id.valueOf(record.Opportunity_Line_Item_ID__c);
                    BY_OPPORTUNITY_LINE_ITEM_ID_MAP.put(opportunityLineItemId, record);
                    results.put(opportunityLineItemId, record);
                    BY_ID_MAP.put(record.Id, record);
                } catch (Exception e) {
                    // Do nothing
                }
            }
        }
        return results;
    }

}