src/objects/FC_Billing_Instruction_Set__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Sets</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>FC_Billing_Instruction_Template__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Sets</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Sets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(FC) Billing Instruction Set</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Billing Instruction Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Billing_Instruction_Step__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Instruction_Set__c</fullName>
        <label>Billing Instruction Set</label>
        <referenceTo>FC_Billing_Instruction_Set__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Steps</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <label>Billing Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Semi_Annual</fullName>
                    <label>Semi-Annual</label>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Eighteen_Months</fullName>
                    <label>Eighteen Months</label>
                </value>
                <value>
                    <fullName>Two_Years</fullName>
                    <label>Two Years</label>
                </value>
                <value>
                    <fullName>Three_Years</fullName>
                    <label>Three Years</label>
                </value>
                <value>
                    <fullName>Five_Years</fullName>
                    <label>Five Years</label>
                </value>
                <value>
                    <fullName>Specific_Months</fullName>
                    <label>Specific Months</label>
                </value>
                <value>
                    <fullName>Subscription_Term</fullName>
                    <label>Subscription Term</label>
                </value>
                <value>
                    <fullName>Week</fullName>
                </value>
                <value>
                    <fullName>Specific_Weeks</fullName>
                    <label>Specific Weeks</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Effective_Date__c</fullName>
        <label>Contract Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Execute_Immediately__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exec Now</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metadata_Is_Last__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Metadata - Is Last?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metadata_Number_of_Periods__c</fullName>
        <label>Metadata - Number of Periods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Metrostudy_Product_Geography_Seg3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metrostudy Product Geography Seg3</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Steps</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Up_To_Periods__c</fullName>
        <label>Up To Periods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>(FC) Billing Instruction Step</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Billing Instruction Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Billing_Instruction_Template__c.object
<CustomObject>
    <label>(FC) Billing Instruction Template</label>
    <nameField>
        <label>(FC) Billing Instruction Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Execute_Immediately__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Execute Immediately</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Initial_Term__c</fullName>
        <defaultValue>12</defaultValue>
        <label>(FC) Initial Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Notify_Accounting_Generate_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Notify Accounting Generate Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Term_End_Date__c</fullName>
        <label>(FC) Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proof_Of_Delivery_Delivered_Date__c</fullName>
        <label>Proof Of Delivery Delivered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proof_of_Delivery_attached__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Have you attached signed doc or email with deliverable and attached below?</inlineHelpText>
        <label>Proof of Delivery attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Skip_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Validation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Billing_Frequency__c</fullName>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Subscription_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Annually</fullName>
                    <default>true</default>
                    <label>Annually</label>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Billing_Instruction_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Billing Instruction Set</label>
        <referenceTo>FC_Billing_Instruction_Set__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Product_Geography_Seg3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Metrostudy Product Geography Seg3</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>TEXT(TotalPrice)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/FC_FcBillingInstructionStepHandler.cls
global without sharing class FC_FcBillingInstructionStepHandler extends fcf.TriggerAdapter {

    global static final String TRIGGER_RUN_STATUS_ID = 'FC_FcBillingInstructionStepHandler';

    // Before and after phase variables
    private static Map<Id, Set<String>> fcBillingInstructionStepToTagsMap = new Map<Id, Set<String>>();
    private static Map<Id, FC_Billing_Instruction_Set__c> fcBillingInstructionSetLookupMap = new Map<Id, FC_Billing_Instruction_Set__c>();
    private static Map<Id, OpportunityLineItem> fcBillingInstructionSetIdToOpportunityLineItemMap = new Map<Id, OpportunityLineItem>();

    // Before phase variables
    private Map<Id, FC_Billing_Instruction_Step__c> fcBillingInstructionStepLookupMap = new Map<Id, FC_Billing_Instruction_Step__c>();

    // After phase variables
    private Map<Id, FC_Metroclient_Product_Geography_Seg3__c> fcMetroclientProductGeographySeg3LookupMap = new Map<Id, FC_Metroclient_Product_Geography_Seg3__c>();
    private Map<Id, Set<String>> fcMetroclientProductGeographySeg3ToTagsMap = new Map<Id, Set<String>>();
    private Set<FC_Billing_Instruction_Step__Tag> fcBillingInstructionStepTagsToCreate = new Set<FC_Billing_Instruction_Step__Tag>();
    private Set<FC_Billing_Instruction_Step__c> fcBillingInstructionStepsToUpdate = new Set<FC_Billing_Instruction_Step__c>();
    private Set<Opportunity> opportunitiesToUpdate = new Set<Opportunity>();

    global override void bulkBefore() {

        if (Trigger.isUpdate) {

            fcBillingInstructionStepLookupMap.putAll(FC_FcBillingInstructionStepCache.findByIds(Trigger.newMap.keySet()));
            for (Id fcBillingInstructionStepRecordId : fcBillingInstructionStepLookupMap.keySet()) {
                Set<String> fcBillingInstructionSetTags = fcBillingInstructionStepToTagsMap.get(fcBillingInstructionStepRecordId);
                if (fcBillingInstructionSetTags == null) {
                    fcBillingInstructionSetTags = new Set<String>();
                    fcBillingInstructionStepToTagsMap.put(fcBillingInstructionStepRecordId, fcBillingInstructionSetTags);
                }
                for (FC_Billing_Instruction_Step__Tag tagRecord : fcBillingInstructionStepLookupMap.get(fcBillingInstructionStepRecordId).Tags) {
                    fcBillingInstructionSetTags.add(tagRecord.Name);
                }
            }

        }

        if (Trigger.isInsert || Trigger.isUpdate) {

            Set<Id> fcBillingInstructionSetIdsToLookup = new Set<Id>();
            for (SObject so : Trigger.new) {
                FC_Billing_Instruction_Step__c fcBillingInstructionStepRecord = (FC_Billing_Instruction_Step__c) so;
                fcBillingInstructionSetIdsToLookup.add(fcBillingInstructionStepRecord.Billing_Instruction_Set__c);
            }
            fcBillingInstructionSetLookupMap.putAll(FC_FcBillingInstructionSetCache.findByIds(fcBillingInstructionSetIdsToLookup));
            fcBillingInstructionSetIdToOpportunityLineItemMap.putAll(FC_OpportunityLineItemCache.findByBillingInstructionSetIds(fcBillingInstructionSetIdsToLookup));

        }

    }

    global override void beforeInsert(SObject so) {
        FC_Billing_Instruction_Step__c newFcBillingInstructionStepRecord = (FC_Billing_Instruction_Step__c) so;
        populateFields(newFcBillingInstructionStepRecord);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        FC_Billing_Instruction_Step__c newFcBillingInstructionStepRecord = (FC_Billing_Instruction_Step__c) so;
        populateFields(newFcBillingInstructionStepRecord);
    }

    global override void bulkAfter() {

        if (Trigger.isInsert) {

            Set<Id> fcMetroclientProductGeographySeg3IdsToLookup = new Set<Id>();
            for (SObject so : Trigger.new) {
                FC_Billing_Instruction_Step__c billingInstructionStepRecord = (FC_Billing_Instruction_Step__c) so;
                if (billingInstructionStepRecord.Metrostudy_Product_Geography_Seg3__c != null) {
                    fcMetroclientProductGeographySeg3IdsToLookup.add(billingInstructionStepRecord.Metrostudy_Product_Geography_Seg3__c);
                }
            }
            fcMetroclientProductGeographySeg3LookupMap.putAll(FC_FcMetroclientProductGeoSeg3Cache.findByIds(fcMetroclientProductGeographySeg3IdsToLookup));

            for (Id fcMetroclientProductGeographySeg3RecordId : fcMetroclientProductGeographySeg3LookupMap.keySet()) {
                Set<String> fcMetroclientProductGeographySeg3Tags = fcMetroclientProductGeographySeg3ToTagsMap.get(fcMetroclientProductGeographySeg3RecordId);
                if (fcMetroclientProductGeographySeg3Tags == null) {
                    fcMetroclientProductGeographySeg3Tags = new Set<String>();
                    fcMetroclientProductGeographySeg3ToTagsMap.put(fcMetroclientProductGeographySeg3RecordId, fcMetroclientProductGeographySeg3Tags);
                }
                for (FC_Metroclient_Product_Geography_Seg3__Tag tagRecord : fcMetroclientProductGeographySeg3LookupMap.get(fcMetroclientProductGeographySeg3RecordId).Tags) {
                    fcMetroclientProductGeographySeg3Tags.add(tagRecord.Name);
                }
            }

        }

    }

    global override void afterInsert(SObject so) {
        FC_Billing_Instruction_Step__c newFcBillingInstructionStepRecord = (FC_Billing_Instruction_Step__c) so;
        prepareTagRecordsForInsert(newFcBillingInstructionStepRecord);
//        prepareOpportunityRecordsForUpdate(null, newFcBillingInstructionStepRecord);
    }

    global override void afterUpdate(SObject oldSo, SObject so) {
        FC_Billing_Instruction_Step__c oldFcBillingInstructionStepRecord = (FC_Billing_Instruction_Step__c) oldSo;
        FC_Billing_Instruction_Step__c newFcBillingInstructionStepRecord = (FC_Billing_Instruction_Step__c) so;
//        prepareOpportunityRecordsForUpdate(oldFcBillingInstructionStepRecord, newFcBillingInstructionStepRecord);
    }

    global override void finallyAfter() {

        // Prevent after phase from recursively executing
        if (!fcf.TriggerRunStatus.isRunnable(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID))) {
            return;
        }
        fcf.TriggerRunStatus.block(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID));

        if (Trigger.isInsert) {

            if (!fcBillingInstructionStepTagsToCreate.isEmpty()) {
                insert new List<FC_Billing_Instruction_Step__Tag>(fcBillingInstructionStepTagsToCreate);
                fcBillingInstructionStepTagsToCreate.clear();
            }
            if (!fcBillingInstructionStepsToUpdate.isEmpty()) {
                update new List<FC_Billing_Instruction_Step__c>(fcBillingInstructionStepsToUpdate);
                fcBillingInstructionStepsToUpdate.clear();
            }

        }

        if (Trigger.isUpdate) {
            if (!opportunitiesToUpdate.isEmpty()) {
                update new List<Opportunity>(opportunitiesToUpdate);
                opportunitiesToUpdate.clear();
            }
        }

    }

//    private void prepareOpportunityRecordsForUpdate(FC_Billing_Instruction_Step__c oldFcBillingInstructionStepRecord,
//            FC_Billing_Instruction_Step__c newFcBillingInstructionStepRecord) {
//
//        Set<String> fcBillingInstructionStepTags =
//                fcBillingInstructionStepToTagsMap.get(newFcBillingInstructionStepRecord.Id);
//        FC_Billing_Instruction_Set__c fcBillingInstructionSetRecord =
//                fcBillingInstructionSetLookupMap.get(newFcBillingInstructionStepRecord.Billing_Instruction_Set__c);
//
//        if (fcBillingInstructionStepTags != null && fcBillingInstructionStepTags.contains('Expenses') &&
//                fcBillingInstructionSetRecord != null &&
//                (oldFcBillingInstructionStepRecord == null || oldFcBillingInstructionStepRecord.Status__c != 'Executed') &&
//                newFcBillingInstructionStepRecord.Status__c == 'Executed' &&
//                newFcBillingInstructionStepRecord.Price__c > 0) {
//
//            OpportunityLineItem opportunityLineItemRecord =
//                    fcBillingInstructionSetIdToOpportunityLineItemMap.get(fcBillingInstructionSetRecord.Id);
//
//            if (opportunityLineItemRecord != null &&
//                    opportunityLineItemRecord.FC_Product_Geography_Seg3__r.Seg3__c == 'CONS') {
//                opportunitiesToUpdate.add(new Opportunity(Id = fcBillingInstructionSetRecord.Opportunity__c,
//                        Skip_Validation__c = true, FC_Notify_Accounting_Generate_Invoice__c = true));
//            }
//
//        }
//
//    }

    private void prepareTagRecordsForInsert(FC_Billing_Instruction_Step__c fcBillingInstructionStepRecord) {
        if (fcBillingInstructionStepRecord.Metrostudy_Product_Geography_Seg3__c != null &&
                fcMetroclientProductGeographySeg3ToTagsMap.containsKey(fcBillingInstructionStepRecord.Metrostudy_Product_Geography_Seg3__c)) {
            Set<String> fcMetroclientProductGeographySeg3TagNames =
                    fcMetroclientProductGeographySeg3ToTagsMap.get(fcBillingInstructionStepRecord.Metrostudy_Product_Geography_Seg3__c);
            for (String fcMetroclientProductGeographySeg3TagName : fcMetroclientProductGeographySeg3TagNames) {
                fcBillingInstructionStepTagsToCreate.add(
                        new FC_Billing_Instruction_Step__Tag(ItemId = fcBillingInstructionStepRecord.Id,
                                Name = fcMetroclientProductGeographySeg3TagName, Type = 'Public'));
                fcBillingInstructionStepsToUpdate.add(new FC_Billing_Instruction_Step__c(Id = fcBillingInstructionStepRecord.Id));
            }
        }
    }

    private void populateFields(FC_Billing_Instruction_Step__c fcBillingInstructionStepRecord) {

        // Initialize tag set in a "before insert"-safe manner.
        Set<String> fcBillingInstructionStepTags = new Set<String>();
        if (fcBillingInstructionStepRecord.Id != null) {
            fcBillingInstructionStepTags.addAll(fcBillingInstructionStepToTagsMap.get(fcBillingInstructionStepRecord.Id));
        }

        FC_Billing_Instruction_Set__c fcBillingInstructionSetRecord = fcBillingInstructionSetLookupMap.get(fcBillingInstructionStepRecord.Billing_Instruction_Set__c);
        OpportunityLineItem opportunityLineItemRecord = fcBillingInstructionSetIdToOpportunityLineItemMap.get(fcBillingInstructionSetRecord.Id);

        Map<String, Integer> billingPeriodToMultiplerMap = new Map<String, Integer>{
                'Month' => 1, 'Monthly' => 1,
                'Quarter' => 3, 'Quarterly' => 3,
                'Semi_Annual' => 6, 'Semi-Annually' => 6,
                'Annual' => 12, 'Annually' => 12
        };

        // Populate End Date
        fcBillingInstructionStepRecord.End_Date__c = null;
        if (opportunityLineItemRecord != null) {

            if (fcBillingInstructionStepRecord.Contract_Effective_Date__c != null) {

                Integer billingPeriodMultiplier = 0;
                if ((String.isNotEmpty(fcBillingInstructionStepRecord.Billing_Period__c) &&
                        billingPeriodToMultiplerMap.containsKey(fcBillingInstructionStepRecord.Billing_Period__c)) ||
                        (String.isNotEmpty(opportunityLineItemRecord.Billing_Frequency__c) &&
                                billingPeriodToMultiplerMap.containsKey(opportunityLineItemRecord.Billing_Frequency__c))) {
                    billingPeriodMultiplier = String.isNotEmpty(fcBillingInstructionStepRecord.Billing_Period__c) ?
                            billingPeriodToMultiplerMap.get(fcBillingInstructionStepRecord.Billing_Period__c) :
                            billingPeriodToMultiplerMap.get(opportunityLineItemRecord.Billing_Frequency__c);
                }

                Integer upToPeriods = (fcBillingInstructionSetRecord.Opportunity__r.FC_Initial_Term__c != null ?
                        Integer.valueOf(fcBillingInstructionSetRecord.Opportunity__r.FC_Initial_Term__c) : 12) /
                        (billingPeriodMultiplier > 0 ? billingPeriodMultiplier : 1);
                if (fcBillingInstructionStepRecord.Up_To_Periods__c != null) {
                    upToPeriods = Integer.valueOf(fcBillingInstructionStepRecord.Up_To_Periods__c);
                }

                System.debug('******* TEMPLATE: ' + fcBillingInstructionSetRecord.Template__r.Name);
                if (fcBillingInstructionSetRecord.Template__r.Name == 'Ramp Up' || fcBillingInstructionSetRecord.Template__r.Name == 'Step Up') {
                    if (fcBillingInstructionStepRecord.Metadata_Is_Last__c) {
                        fcBillingInstructionStepRecord.End_Date__c = fcBillingInstructionSetRecord.Opportunity__r.FC_Term_End_Date__c;
                    } else {
                        Integer numberOfPeriods = 1;
                        if (fcBillingInstructionStepRecord.Metadata_Number_of_Periods__c != null) {
                            numberOfPeriods = Integer.valueOf(fcBillingInstructionStepRecord.Metadata_Number_of_Periods__c);
                        }
                        fcBillingInstructionStepRecord.End_Date__c = fcBillingInstructionStepRecord.Contract_Effective_Date__c.addMonths(
                                numberOfPeriods * billingPeriodMultiplier) - (billingPeriodMultiplier > 0 ? 1 : 0);
                    }
                } else {
                    fcBillingInstructionStepRecord.End_Date__c = fcBillingInstructionStepRecord.Contract_Effective_Date__c.addMonths(
                            upToPeriods * billingPeriodMultiplier) - (billingPeriodMultiplier > 0 ? 1 : 0);
                }

                if (fcBillingInstructionStepRecord.End_Date__c != null && fcBillingInstructionStepRecord.Price__c != null) {
                    fcBillingInstructionStepRecord.Total_Price__c = fcBillingInstructionStepRecord.Price__c *
                            (fcBillingInstructionStepRecord.Contract_Effective_Date__c.monthsBetween(fcBillingInstructionStepRecord.End_Date__c + (billingPeriodMultiplier > 0 ? 1 : 0))) /
                            (billingPeriodMultiplier > 0 ? billingPeriodMultiplier : 1);
                }
            }

            // Populate CONS specific data
            if (fcBillingInstructionStepRecord.Status__c == 'New' && opportunityLineItemRecord != null &&
                    opportunityLineItemRecord.FC_Product_Geography_Seg3__r.Seg3__c == 'CONS') {

                // Execute the CONS Balance Due instruction only if Proof of Delivery is attached.
                if (fcBillingInstructionStepTags.contains('Balance Due')) {
                    fcBillingInstructionStepRecord.Execute_Immediately__c = opportunityLineItemRecord.Opportunity.Proof_of_Delivery_attached__c;

                    if (opportunityLineItemRecord.Opportunity.Proof_Of_Delivery_Delivered_Date__c != null) {
                        fcBillingInstructionStepRecord.Contract_Effective_Date__c = opportunityLineItemRecord.Opportunity.Proof_Of_Delivery_Delivered_Date__c;
                    }
                }

                // Execute the CONS Expenses instruction only if the amount is a positive number.
                if (fcBillingInstructionStepTags.contains('Expenses')) {
                    fcBillingInstructionStepRecord.Execute_Immediately__c = fcBillingInstructionStepRecord.Price__c != null &&
                            fcBillingInstructionStepRecord.Price__c > 0;

                    if (opportunityLineItemRecord.Opportunity.Proof_Of_Delivery_Delivered_Date__c != null) {
                        fcBillingInstructionStepRecord.Contract_Effective_Date__c = opportunityLineItemRecord.Opportunity.Proof_Of_Delivery_Delivered_Date__c;
                    }
                }

            }

        }

    }

}