src/objects/FC_Billing_Instruction_Set__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Number__c</fullName>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Billing Instruction Set</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Billing Instruction Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Billing_Instruction_Step__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Cycle_Day__c</fullName>
        <label>Bill Cycle Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bill_Cycle_Type__c</fullName>
        <label>Bill Cycle Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultFromCustomer</fullName>
                    <label>Default From Customer</label>
                </value>
                <value>
                    <fullName>SpecificDayOfMonth</fullName>
                    <label>Specific Day Of Month</label>
                </value>
                <value>
                    <fullName>SubscriptionStartDay</fullName>
                    <label>Subscription Start Day</label>
                </value>
                <value>
                    <fullName>ChargeTriggerDay</fullName>
                    <label>Charge Trigger Day</label>
                </value>
                <value>
                    <fullName>SpecificDayOfWeek</fullName>
                    <label>Specific Day Of Week</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Instruction_Description__c</fullName>
        <label>Billing Instruction Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Instruction_Set__c</fullName>
        <label>Billing Instruction Set</label>
        <referenceTo>FC_Billing_Instruction_Set__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Steps</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Period_Alignment__c</fullName>
        <label>Billing Period Alignment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AlignToCharge</fullName>
                    <label>Align To Charge</label>
                </value>
                <value>
                    <fullName>AlignToSubscriptionStart</fullName>
                    <label>Align To Subscription Start</label>
                </value>
                <value>
                    <fullName>AlignToTermStart</fullName>
                    <label>Align To Term Start</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <label>Billing Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Semi_Annual</fullName>
                    <label>Semi-Annual</label>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Eighteen_Months</fullName>
                    <label>Eighteen Months</label>
                </value>
                <value>
                    <fullName>Two_Years</fullName>
                    <label>Two Years</label>
                </value>
                <value>
                    <fullName>Three_Years</fullName>
                    <label>Three Years</label>
                </value>
                <value>
                    <fullName>Five_Years</fullName>
                    <label>Five Years</label>
                </value>
                <value>
                    <fullName>Specific_Months</fullName>
                    <label>Specific Months</label>
                </value>
                <value>
                    <fullName>Subscription_Term</fullName>
                    <label>Subscription Term</label>
                </value>
                <value>
                    <fullName>Week</fullName>
                </value>
                <value>
                    <fullName>Specific_Weeks</fullName>
                    <label>Specific Weeks</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Effective_Date__c</fullName>
        <label>Contract Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Condition__c</fullName>
        <label>End Date Condition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscription_End</fullName>
                    <label>Subscription End</label>
                </value>
                <value>
                    <fullName>Fixed_Period</fullName>
                    <label>Fixed Period</label>
                </value>
                <value>
                    <fullName>Specific_End_Date</fullName>
                    <label>Specific End Date</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Execute_Immediately__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exec Now</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>IF(!ISBLANK(Metrostudy_Product_Geography_Seg3__c),
    IF(TEXT(Metrostudy_Product_Geography_Seg3__r.Charge_Type__c) == &apos;OneTime&apos;, Metrostudy_Product_Geography_Seg3__r.One_Time_List_Price__c,
        CASE(TEXT(Billing_Period__c), 
            &apos;Annual&apos;,  Metrostudy_Product_Geography_Seg3__r.Annual_List_Price__c,
            &apos;Semi_Annual&apos;,  Metrostudy_Product_Geography_Seg3__r.Semi_Annual_List_Price__c,
            &apos;Quarter&apos;,  Metrostudy_Product_Geography_Seg3__r.Quarterly_List_Price__c, 
            &apos;Month&apos;, Metrostudy_Product_Geography_Seg3__r.Monthly_List_Price__c, 
             NULL
        )
    ),
    NULL
)</formula>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Metrostudy_Product_Geography_Seg3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metrostudy Product Geography Seg3</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Steps</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>(FC) Billing Instruction Steps</relationshipLabel>
        <relationshipName>FC_Billing_Instruction_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(FC) Billing Instruction Step</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Billing Instruction Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Steps</pluralLabel>
    <recordTypes>
        <fullName>Amend_Add</fullName>
        <active>true</active>
        <label>Amend - Add</label>
    </recordTypes>
    <recordTypes>
        <fullName>Amend_Modify</fullName>
        <active>true</active>
        <label>Amend - Modify</label>
    </recordTypes>
    <recordTypes>
        <fullName>Amend_Remove</fullName>
        <active>true</active>
        <label>Amend - Remove</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>OneTime</fullName>
                    <label>One-Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Execute_Immediately__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Execute Immediately</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geography_Type__c</fullName>
        <formula>Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name</formula>
        <label>Geography Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <formula>Product_Geography__r.Geography__r.Name</formula>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Geography__c</fullName>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ZuoraAmendmentProcessorBatchable.cls
public class FC_ZuoraAmendmentProcessorBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts,
        Database.Stateful {

    private static final String SOQL = 'select Id, Bill_Cycle_Day__c, Bill_Cycle_Type__c,' +
            'Billing_Instruction_Description__c, Billing_Instruction_Set__c, ' +
            'Billing_Instruction_Set__r.Charge_Number__c, ' +
            'Billing_Period__c, Billing_Period_Alignment__c, Contract_Effective_Date__c, ' +
            'Description__c, End_Date_Condition__c, Execute_Immediately__c, List_Price__c, ' +
            'Metrostudy_Product_Geography_Seg3__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Charge_Type__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Geography__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Geography_Type__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Product_Geography__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Product_Geography__r.Geography__r.Seg2__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Product_Rate_Plan__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Product_Rate_Plan__r.zqu__ZuoraId__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Product_Rate_Plan__r.zqu__ZProduct__c, ' +
            'Metrostudy_Product_Geography_Seg3__r.Product_Rate_Plan__r.zqu__ZProduct__r.Name, ' +
            'Metrostudy_Product_Geography_Seg3__r.Seg3__c, Price__c, ' +
            'Product_Rate_Plan__c, Product_Rate_Plan__r.zqu__ZuoraId__c, Quantity__c, RecordTypeId, ' +
            'RecordType.DeveloperName, Specific_Billing_Period__c, Specific_End_Date__c, Status__c, Trigger_Date__c, ' +
            'Trigger_Event__c, Up_To_Periods__c, Up_To_Periods_Type__c, Weekly_Bill_Cycle_Day__c ' +
            'from FC_Billing_Instruction_Step__c ' +
            'where Billing_Instruction_Set__r.Opportunity__c = \'\'{0}\'\' ' +
            'and Status__c = \'\'Pending\'\' ' +
            'and RecordType.DeveloperName in (\'\'Amend_Add\'\', \'\'Amend_Modify\'\', \'\'Amend_Remove\'\') ' +
            'and Execute_Immediately__c = true';

    private Id opportunityId;

    private Boolean subscribeInvoked = false;

    private Boolean hasAmendAdd = false;

    private Boolean amendAddSuccess = false;

    private Opportunity opportunityRecord;

    private FC_ZuoraClient zuoraClient;

    public FC_ZuoraAmendmentProcessorBatchable(Id opportunityId, Boolean subscribeInvoked) {
        this.opportunityId = opportunityId;
        this.subscribeInvoked = subscribeInvoked;
        for (Opportunity queriedOpportunity : [
                select Id, AccountId, Name, CloseDate, ContractId, Contract.FC_Subscription_Number__c,
                        FC_Bill_Case__c, FC_Subscription_Notes__c, One_time_Sale_Type__c, Purchase_Type__c
                from Opportunity
                where Id = :opportunityId
                limit 1
        ]) {
            this.opportunityRecord = queriedOpportunity;
        }
        this.zuoraClient = new FC_ZuoraClient(this.opportunityId);
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(String.format(SOQL, new String[]{
                opportunityId
        }));
    }

    public void execute(Database.BatchableContext context, List<FC_Billing_Instruction_Step__c> scope) {
        if (scope != null && !scope.isEmpty()) {

            Boolean exceptionCaught = false;
            try {

                // Check if "Amend - Add" is present
                for (FC_Billing_Instruction_Step__c billingInstructionStepRecord : scope) {
                    if (billingInstructionStepRecord.RecordType.DeveloperName == 'Amend_Add') {
                        this.hasAmendAdd = true;
                    }
                }
                // Get base subscription version.
//                FC_ZuoraClient.GetSubscriptionResponse baseSubscriptionDetail =
//                        this.zuoraClient.getSubscriptionByKey(this.opportunityRecord.Contract.FC_Subscription_Number__c);
//                FC_ZuoraClient.Subscription baseSubscriptionObject = this.zuoraClient.getSubscriptionObject(baseSubscriptionDetail.id);

                FC_ZuoraClient.UpdateSubscriptionResponse response = this.zuoraClient.updateSubscription(
                        FC_ZuoraUtil.buildUpdateSubscriptionRequest(scope, this.opportunityRecord, false),
                        this.opportunityRecord.Contract.FC_Subscription_Number__c);
                if (response.Success) {

                    if (this.hasAmendAdd) {
                        this.amendAddSuccess = true;
                    }

                    FC_Billing_Instruction_Step__c[] billingInstructionStepsToUpdate = new List<FC_Billing_Instruction_Step__c>();
                    for (FC_Billing_Instruction_Step__c billingInstructionStepRecord : scope) {
                        billingInstructionStepsToUpdate.add(new FC_Billing_Instruction_Step__c(
                                Id = billingInstructionStepRecord.Id, Status__c = 'Executed'));
                    }
                    if (!billingInstructionStepsToUpdate.isEmpty()) {
                        update billingInstructionStepsToUpdate;
                    }

                    Opportunity opportunityRecordToUpdate = new Opportunity(Id = this.opportunityRecord.Id,
                            FC_Last_Sent_To_Zuora__c = DateTime.now(), Skip_Validation__c = true);
                    update opportunityRecordToUpdate;

                } else {

                    String[] errorReasons = new List<String>();
                    if (response.reasons != null && !response.reasons.isEmpty()) {
                        for (FC_ZuoraClient.ZuoraError error : response.reasons) {
                            errorReasons.add(String.format('{0} - {1}', new String[]{
                                    error.code, error.message
                            }));
                        }
                        throw new FC_Exception(String.join(errorReasons, '; '));
                    }
                }
            } catch (Exception e) {
                exceptionCaught = true;
                throw new FC_Exception(String.format('{0}: {1}: {2}',
                        new String []{
                                e.getTypeName(), e.getMessage(), e.getStackTraceString()
                        }));
            } finally {
                if (exceptionCaught) {
                    zuoraClient.flushTransactions();
                }
            }

        }
    }

    public void finish(Database.BatchableContext context) {
        if (this.opportunityRecord != null && !this.subscribeInvoked && this.hasAmendAdd && this.amendAddSuccess &&
                new Set<String>{
                        'Database Access', 'Internet Sales', 'Membership'
                }.contains(this.opportunityRecord.One_time_Sale_Type__c) &&
                this.opportunityRecord.Purchase_Type__c != 'Price Increase Only') {
            update new Opportunity(Id = this.opportunityRecord.Id, FC_Send_Provisioning_Notification__c = true, Skip_Validation__c = true);
        }

        zuoraClient.flushTransactions();

        FC_MetroclientAccountProvisionBatchable batchable = new FC_MetroclientAccountProvisionBatchable(new Set<Id>{
                this.opportunityRecord.AccountId
        });
        batchable.parentTransactionId = this.opportunityRecord.Id;
        Database.executeBatch(batchable);

    }

}