src/objects/FC_Billing_Instruction_Set__c.object
<CustomObject>
    <label>(FC) Billing Instruction Set</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Billing Instruction Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Billing Instruction Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Bill_Case__c</fullName>
        <label>(FC) Bill Case</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proof_Of_Delivery_Delivered_Date__c</fullName>
        <label>Proof Of Delivery Delivered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proof_of_Delivery_attached__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Have you attached signed doc or email with deliverable and attached below?</inlineHelpText>
        <label>Proof of Delivery attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scheduled_Delivery_Date__c</fullName>
        <description>Used for auditing purposes</description>
        <inlineHelpText>Enter the date the deliverable is scheduled to be presented to Client.  Once presented, attach the deliverable to opp.</inlineHelpText>
        <label>Scheduled Product Delivery Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Billing_Frequency__c</fullName>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Subscription_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Annually</fullName>
                    <default>true</default>
                    <label>Annually</label>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Bill_Case__c</fullName>
        <label>(FC) Bill Case</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Billing_Instruction_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Billing Instruction Set</label>
        <referenceTo>FC_Billing_Instruction_Set__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Product_Geography_Seg3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Metrostudy Product Geography Seg3</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_UUID__c</fullName>
        <externalId>true</externalId>
        <label>(FC) UUID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/FC_OpportunityLineItemCache.cls
public with sharing class FC_OpportunityLineItemCache {

    private static String[] OPPORTUNITY_LINE_ITEM_FIELDS = new String[]{
            'Id', 'Billing_Frequency__c', 'FC_Bill_Case__c', 'FC_Billing_Instruction_Set__c',
            'FC_Product_Geography_Seg3__c', 'FC_Product_Geography_Seg3__r.Seg3__c', 'FC_UUID__c', 'OpportunityId',
            'Opportunity.Proof_of_Delivery_attached__c', 'Opportunity.Proof_Of_Delivery_Delivered_Date__c',
            'Opportunity.Scheduled_Delivery_Date__c'
    };

    private static final Map<ID, OpportunityLineItem> BY_ID_MAP = new Map<ID, OpportunityLineItem>();
    private static final Map<ID, OpportunityLineItem> BY_BILLING_INSTRUCTION_SET_ID_MAP = new Map<ID, OpportunityLineItem>();
    private static final Map<String, OpportunityLineItem> BY_UUID_MAP = new Map<String, OpportunityLineItem>();
    private static final Map<Id, Set<OpportunityLineItem>> BY_OPPORTUNITY_ID_MAP = new Map<Id, Set<OpportunityLineItem>>();

    private static final String SOQL_BASE;

    static {
        SOQL_BASE = String.format('select {0} from OpportunityLineItem',
                new String[]{
                        String.join(OPPORTUNITY_LINE_ITEM_FIELDS, ', ')
                });
    }

    public static void clearCache() {
        BY_ID_MAP.clear();
        BY_BILLING_INSTRUCTION_SET_ID_MAP.clear();
        BY_UUID_MAP.clear();
        BY_OPPORTUNITY_ID_MAP.clear();
    }

    public static Map<ID, OpportunityLineItem> findByIds(Set<ID> opportunityLineItemIds) {
        Map<ID, OpportunityLineItem> results = new Map<ID, OpportunityLineItem>();
        Set<ID> opportunityLineItemIdsToQuery = new Set<ID>();
        for (ID opportunityLineItemId : opportunityLineItemIds) {
            if (BY_ID_MAP.containsKey(opportunityLineItemId)) {
                results.put(opportunityLineItemId, BY_ID_MAP.get(opportunityLineItemId));
            } else {
                opportunityLineItemIdsToQuery.add(opportunityLineItemId);
            }
        }
        if (opportunityLineItemIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Id in :opportunityLineItemIdsToQuery';
            for (OpportunityLineItem record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                results.put(record.Id, record);
            }
        }
        return results;
    }

    public static Map<String, OpportunityLineItem> findByUuids(Set<String> opportunityLineItemUuids) {
        Map<String, OpportunityLineItem> results = new Map<String, OpportunityLineItem>();
        Set<String> opportunityLineItemUuidsToQuery = new Set<STRING>();
        for (String opportunityLineItemUuid : opportunityLineItemUuids) {
            if (BY_UUID_MAP.containsKey(opportunityLineItemUuid)) {
                results.put(opportunityLineItemUuid, BY_UUID_MAP.get(opportunityLineItemUuid));
            } else {
                opportunityLineItemUuidsToQuery.add(opportunityLineItemUuid);
            }
        }
        if (opportunityLineItemUuidsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where FC_UUID__c in :opportunityLineItemUuidsToQuery';
            for (OpportunityLineItem record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                BY_UUID_MAP.put(record.FC_UUID__c, record);
                results.put(record.FC_UUID__c, record);
            }
        }
        return results;
    }

    public static Map<ID, OpportunityLineItem> findByBillingInstructionSetIds(Set<ID> billingInstructionSetIds) {
        Map<ID, OpportunityLineItem> results = new Map<ID, OpportunityLineItem>();
        Set<ID> billingInstructionSetIdsToQuery = new Set<ID>();
        for (ID billingInstructionSetId : billingInstructionSetIds) {
            if (BY_BILLING_INSTRUCTION_SET_ID_MAP.containsKey(billingInstructionSetId)) {
                results.put(billingInstructionSetId, BY_BILLING_INSTRUCTION_SET_ID_MAP.get(billingInstructionSetId));
            } else {
                billingInstructionSetIdsToQuery.add(billingInstructionSetId);
            }
        }
        if (billingInstructionSetIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where FC_Billing_Instruction_Set__c in :billingInstructionSetIdsToQuery';
            for (OpportunityLineItem record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                BY_BILLING_INSTRUCTION_SET_ID_MAP.put(record.FC_Billing_Instruction_Set__c, record);
                results.put(record.FC_Billing_Instruction_Set__c, record);
            }
        }
        return results;
    }

    public static Map<Id, Set<OpportunityLineItem>> findByOpportunityIds(Set<Id> opportunityIds) {
        Map<Id, Set<OpportunityLineItem>> results = new Map<Id, Set<OpportunityLineItem>>();
        Set<Id> opportunityIdsToQuery = new Set<Id>();
        for (Id opportunityId : opportunityIds) {
            if (BY_OPPORTUNITY_ID_MAP.containsKey(opportunityId)) {
                results.put(opportunityId, BY_OPPORTUNITY_ID_MAP.get(opportunityId));
            } else {
                opportunityIdsToQuery.add(opportunityId);
            }
        }
        if (opportunityIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where OpportunityId in :opportunityIdsToQuery';
            for (OpportunityLineItem record : Database.query(soql)) {
                Set<OpportunityLineItem> records = results.get(record.OpportunityId);
                if (records == null) {
                    records = new Set<OpportunityLineItem>();
                    results.put(record.OpportunityId, records);
                }
                records.add(record);
                BY_OPPORTUNITY_ID_MAP.put(record.OpportunityId, records);
                BY_ID_MAP.put(record.Id, record);
            }
        }
        return results;
    }

}