src/objects/FC_Charge_Monthly_Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Number__c</fullName>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Plan_Charge__c</fullName>
        <label>Rate Plan Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>(FC) Charge Monthly Revenues</relationshipLabel>
        <relationshipName>FC_Charge_Monthly_Revenues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>(FC) Charge Monthly Revenue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Charge Monthly Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Charge Monthly Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_FcChargeMonthlyRevenueHandler.cls
global without sharing class FC_FcChargeMonthlyRevenueHandler extends fcf.TriggerAdapter {

    private Map<String, Zuora__SubscriptionProductCharge__c> chargeLookupMap =
            new Map<String, Zuora__SubscriptionProductCharge__c>();

    global override void bulkBefore() {
        if (Trigger.isInsert || Trigger.isUpdate) {
            Set<String> chargeNumbersToLookup = new Set<String>();
            for (SObject so : Trigger.new) {
                FC_Charge_Monthly_Revenue__c chargeMonthlyRevenueRecord = (FC_Charge_Monthly_Revenue__c) so;
                if (String.isNotBlank(chargeMonthlyRevenueRecord.Charge_Number__c)) {
                    chargeNumbersToLookup.add(chargeMonthlyRevenueRecord.Charge_Number__c);
                }
            }
            if (!chargeNumbersToLookup.isEmpty()) {
                chargeLookupMap.putAll(FC_SubscriptionProductChargeCache.findByChargeNumbers(chargeNumbersToLookup));
            }
        }
    }

    global override void beforeInsert(SObject so) {
        FC_Charge_Monthly_Revenue__c newChargeMonthlyRevenueRecord = (FC_Charge_Monthly_Revenue__c) so;
        populateFields(newChargeMonthlyRevenueRecord);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        FC_Charge_Monthly_Revenue__c newChargeMonthlyRevenueRecord = (FC_Charge_Monthly_Revenue__c) so;
        populateFields(newChargeMonthlyRevenueRecord);
    }

    private void populateFields(FC_Charge_Monthly_Revenue__c chargeMonthlyRevenueRecord) {
        chargeMonthlyRevenueRecord.Rate_Plan_Charge__c = null;
        if (String.isNotBlank(chargeMonthlyRevenueRecord.Charge_Number__c) &&
                chargeLookupMap.containsKey(chargeMonthlyRevenueRecord.Charge_Number__c)) {
            chargeMonthlyRevenueRecord.Rate_Plan_Charge__c =
                    chargeLookupMap.get(chargeMonthlyRevenueRecord.Charge_Number__c).Id;
        }
    }

}