src/objects/FC_Charge_Revenue_Share__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Obsolete__c</fullName>
        <formula>Subscription_Product_Charge__r.LastModifiedDate != Charge_Last_Modified_Date__c</formula>
        <label>Obsolete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed_By_Batchable_On__c</fullName>
        <label>Processed By Batchable On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Charge Revenue Share</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Charge Revenue Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Charge Revenue Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Charge_Revenue_Share_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Last_Run_On__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Charge Revenue Share Settings</label>
</CustomObject>

src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <formula>Product_Geography__r.Geography__r.Name</formula>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Segment_2_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Market_Name__c</fullName>
        <label>Market Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>(FC) Segment 2 Assignment</label>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <fields>
        <fullName>GeographyTypeId__c</fullName>
        <label>Geography Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProduct__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Metrostudy Products</description>
    <fields>
        <fullName>ProductAbbreviation__c</fullName>
        <label>Product Abbreviation</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>This is a concatenation of the Product Name and marekt so that the Market displays on the Add Product to Opportunity window</description>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The deprecated Product SKU field.</description>
        <inlineHelpText>This field will be auto-generated if no value specified.</inlineHelpText>
        <label>SKU (Deprecated)</label>
        <length>70</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>Product__c</fullName>
        <formula>zqu__ProductRatePlan__r.zqu__Product__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__RecognizedRevenueAccount__c</fullName>
        <description>The name of the recognized revenue account for this charge.</description>
        <label>Recognized Revenue Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ZProducts</relationshipLabel>
        <relationshipName>ZProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestChargeRevenueShareCleanerBatch.cls
@isTest
private class FC_TestChargeRevenueShareCleanerBatch {

    @isTest
    private static void testDeleteAll() {

        FC_Charge_Revenue_Share__c[] testChargeRevenueShares = [
                select Id, Obsolete__c
                from FC_Charge_Revenue_Share__c
        ];
        System.assertEquals(2, testChargeRevenueShares.size());

        Test.startTest();
        FC_ChargeRevenueShareCleanerBatchable batchable = new FC_ChargeRevenueShareCleanerBatchable(null);
        Database.executeBatch(batchable);
        Test.stopTest();

        testChargeRevenueShares = [
                select Id, Obsolete__c
                from FC_Charge_Revenue_Share__c
        ];
        System.assertEquals(0, testChargeRevenueShares.size());

    }

    @isTest
    private static void testDeleteObsolete() {

        FC_Charge_Revenue_Share__c[] testChargeRevenueShares = [
                select Id, Obsolete__c
                from FC_Charge_Revenue_Share__c
                where Obsolete__c = true and Processed_By_Batchable_On__c < :DateTime.now()
        ];
        System.assertEquals(1, testChargeRevenueShares.size());
        System.assertEquals(true, testChargeRevenueShares[0].Obsolete__c);

        Test.startTest();
        FC_ChargeRevenueShareCleanerBatchable batchable = new FC_ChargeRevenueShareCleanerBatchable(DateTime.now());
        Database.executeBatch(batchable);
        Test.stopTest();

        testChargeRevenueShares = [
                select Id, Obsolete__c
                from FC_Charge_Revenue_Share__c
                where Obsolete__c = true and Processed_By_Batchable_On__c < :DateTime.now()
        ];
        System.assertEquals(0, testChargeRevenueShares.size());
    }

    @testSetup
    private static void setup() {

        FC_Charge_Revenue_Share_Settings__c testChargeRevenueShareSettings = new FC_Charge_Revenue_Share_Settings__c(
                SetupOwnerId = UserInfo.getOrganizationId(), Last_Run_On__c = Date.today().addYears(-1));
        insert testChargeRevenueShareSettings;

        FC_Segment_2_Assignment__c[] testSegment2Assignments = new FC_Segment_2_Assignment__c[]{
                new FC_Segment_2_Assignment__c(Name = '01', Market_Name__c = 'TEST MARKET 1', Allocation_Percentage__c = 10),
                new FC_Segment_2_Assignment__c(Name = '02', Market_Name__c = 'TEST MARKET 2', Allocation_Percentage__c = 20)
        };
        insert testSegment2Assignments;

        Product2 testProduct = new Product2(Name = 'Test Product', IsActive = true);
        insert testProduct;

        PricebookEntry testPricebookEntry = new PricebookEntry(IsActive = true,
                Pricebook2Id = Test.getStandardPricebookId(), Product2Id = testProduct.Id, UnitPrice = 100);
        insert testPricebookEntry;

        zqu__ZProduct__c testZProduct = new zqu__ZProduct__c(Name = 'Test ZProduct', zqu__Product__c = testProduct.Id,
                zqu__SKU__c = 'SKU-1', zqu__ZuoraId__c = 'P-1');
        insert testZProduct;

        zqu__ProductRatePlan__c testProductRatePlan = new zqu__ProductRatePlan__c(Name = 'Test Product Rate Plan',
                zqu__Product__c = testProduct.Id, zqu__ZuoraId__c = 'PRP-1', zqu__ZProduct__c = testZProduct.Id);
        insert testProductRatePlan;

        zqu__ProductRatePlanCharge__c testProductRatePlanCharge = new zqu__ProductRatePlanCharge__c(
                Name = 'Test Product Rate Plan Charge', zqu__ProductRatePlan__c = testProductRatePlan.Id,
                zqu__RecognizedRevenueAccount__c = 'AC-1', zqu__ZuoraId__c = 'PRPC-1');
        insert testProductRatePlanCharge;

        MetroclientProduct__c testMetroclientProduct = new MetroclientProduct__c(Name = 'Test Product',
                ProductAbbreviation__c = 'TEST');
        insert testMetroclientProduct;

        MetroclientGeographyType__c testGeographyType = new MetroclientGeographyType__c(Name = 'Test Geography Type',
                GeographyTypeId__c = 1);
        insert testGeographyType;

        MetroclientGeography__c[] testGeographies = new MetroclientGeography__c[]{
                new MetroclientGeography__c(Name = 'Test Geography 00', GeographyType__c = testGeographyType.Id, Seg2__c = '00'),
                new MetroclientGeography__c(Name = 'Test Geography 01', GeographyType__c = testGeographyType.Id, Seg2__c = '01')
        };
        insert testGeographies;

        MetroclientProductGeographyType__c testProductGeographyType =
                new MetroclientProductGeographyType__c(Name = 'Test Product Geography Type',
                        GeographyType__c = testGeographyType.Id, Product__c = testMetroclientProduct.Id);
        insert testProductGeographyType;

        MetroclientProductGeography__c[] testProductGeographies = new MetroclientProductGeography__c[]{
                new MetroclientProductGeography__c(
                        Name = 'Test Product Geography 00', Geography__c = testGeographies[0].Id,
                        ProductGeographyType__c = testProductGeographyType.Id),
                new MetroclientProductGeography__c(
                        Name = 'Test Product Geography 01', Geography__c = testGeographies[1].Id,
                        ProductGeographyType__c = testProductGeographyType.Id)
        };
        insert testProductGeographies;

        FC_Metroclient_Product_Geography_Seg3__c[] testProductGeographySeg3s =
                new FC_Metroclient_Product_Geography_Seg3__c[]{
                        new FC_Metroclient_Product_Geography_Seg3__c(Accounting_Code__c = 'AC-00', Charge_Type__c = 'Recurring',
                                Dependent_Seg3__c = null, Exclude_From_Product_Selector__c = false,
                                Execute_Immediately__c = true, Product__c = testProduct.Id,
                                Product_Geography__c = testProductGeographies[0].Id, Product_Rate_Plan__c = testProductRatePlan.Id,
                                Seg3__c = 'CONS'),
                        new FC_Metroclient_Product_Geography_Seg3__c(Accounting_Code__c = 'AC-01', Charge_Type__c = 'Recurring',
                                Dependent_Seg3__c = null, Exclude_From_Product_Selector__c = false,
                                Execute_Immediately__c = true, Product__c = testProduct.Id,
                                Product_Geography__c = testProductGeographies[1].Id, Product_Rate_Plan__c = testProductRatePlan.Id,
                                Seg3__c = 'CONS')
                };
        insert testProductGeographySeg3s;

        Account testAccount = new Account(Name = 'Test Account', BillingPostalCode = '12345');
        insert testAccount;

        Contact[] testContacts = new Contact[]{
                new Contact(AccountId = testAccount.Id, FirstName = 'Test First', LastName = 'Test Last',
                        MailingStreet = 'Test Addresss1\nTest Address2', MailingCity = 'Test City', MailingStateCode = 'NY',
                        MailingPostalCode = '12345', MailingCountryCode = 'US'),
                new Contact(AccountId = testAccount.Id, LastName = 'Test Last')
        };
        insert testContacts;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account',
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;

        Zuora__Subscription__c[] testSubscriptions = new List<Zuora__Subscription__c>{
                new Zuora__Subscription__c(Name = 'S-1', Zuora__Account__c = testAccount.Id,
                        Zuora__CustomerAccount__c = testCustomerAccount.Id, Zuora__External_Id__c = 'S-1',
                        Zuora__SubscriptionNumber__c = 'S-1', Zuora__Zuora_Id__c = 'S-1')
        };
        insert testSubscriptions;

        Zuora__SubscriptionProductCharge__c[] testCharges = new List<Zuora__SubscriptionProductCharge__c>{
                new Zuora__SubscriptionProductCharge__c(Name = 'SPC-1',
                        Seg3RecordID__c = testProductGeographySeg3s[0].Id,
                        Seg3_Record__c = testProductGeographySeg3s[0].Id,
                        Zuora__ChargeNumber__c = 'SPC-1', Zuora__External_Id__c = 'SPC-1',
                        Zuora__MonthlyRecurringRevenue__c = 100, Zuora__Subscription__c = testSubscriptions[0].Id,
                        Zuora__SubscriptionChargeNumber__c = 'SPC-1'),
                new Zuora__SubscriptionProductCharge__c(Name = 'SPC-2',
                        Seg3RecordID__c = testProductGeographySeg3s[1].Id,
                        Seg3_Record__c = testProductGeographySeg3s[1].Id,
                        Zuora__ChargeNumber__c = 'SPC-2', Zuora__External_Id__c = 'SPC-2',
                        Zuora__MonthlyRecurringRevenue__c = 100, Zuora__Subscription__c = testSubscriptions[0].Id,
                        Zuora__SubscriptionChargeNumber__c = 'SPC-2')
        };
        insert testCharges;

        FC_Charge_Revenue_Share__c[] testChargeRevenueShares = new FC_Charge_Revenue_Share__c[]{
                new FC_Charge_Revenue_Share__c(Subscription_Product_Charge__c = testCharges[0].Id,
                        Charge_Last_Modified_Date__c = testCharges[0].LastModifiedDate,
                        Processed_By_Batchable_On__c = DateTime.now().addDays(-1)),
                new FC_Charge_Revenue_Share__c(Subscription_Product_Charge__c = testCharges[0].Id,
                        Charge_Last_Modified_Date__c = DateTime.now().addDays(-1),
                        Processed_By_Batchable_On__c = DateTime.now().addDays(-1))
        };
        insert testChargeRevenueShares;

    }
}