src/objects/FC_Charge_Monthly_Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Number__c</fullName>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Import_Process_ID__c</fullName>
        <externalId>true</externalId>
        <label>Import Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Revenue__c</fullName>
        <label>Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Plan_Charge__c</fullName>
        <label>Rate Plan Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>(FC) Charge Monthly Revenues</relationshipLabel>
        <relationshipName>FC_Charge_Monthly_Revenues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>(FC) Charge Monthly Revenue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Charge Monthly Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Charge Monthly Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Charge_Monthly_Revenue_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Active_Import_Process_ID__c</fullName>
        <label>Active Import Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Charge Monthly Revenue Settings</label>
</CustomObject>

src/objects/FC_Charge_Monthly_Revenue_Share__c.object
<CustomObject>
    <fields>
        <fullName>Allocated_Amount__c</fullName>
        <label>Allocated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Allocated Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipLabel>(FC) Charge Monthly Revenue Shares</relationshipLabel>
        <relationshipName>FC_Charge_Monthly_Revenue_Shares</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Charge_Monthly_Revenue__c</fullName>
        <label>Charge Monthly Revenue</label>
        <referenceTo>FC_Charge_Monthly_Revenue__c</referenceTo>
        <relationshipLabel>(FC) Charge Monthly Revenue Shares</relationshipLabel>
        <relationshipName>FC_Charge_Monthly_Revenue_Shares</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RD_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RD Assignment</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>(FC) Charge Monthly Revenue Shares</relationshipLabel>
        <relationshipName>FC_Charge_Monthly_Revenue_Shares</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_2__c</fullName>
        <label>Segment 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Charge Monthly Revenue Share</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Charge Monthly Revenue Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Charge Monthly Revenue Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Segment_2_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Region_Assignment_ID__c</fullName>
        <label>Sales Region Assignment ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Segment 2 Assignment</label>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geography_FIPS__c</fullName>
        <label>Geography FIPS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seg2__c</fullName>
        <label>Seg2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Seg3_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seg3 Record</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ChargeMonthlyRevShareProcessorBatch.cls
public with sharing class FC_ChargeMonthlyRevShareProcessorBatch implements Database.Batchable<sObject> {

    public String importProcessId;

    public FC_ChargeMonthlyRevShareProcessorBatch(String importProcessId) {
        this.importProcessId = importProcessId;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
                select Id, Charge_Number__c, Date__c, Monthly_Revenue__c, Rate_Plan_Charge__c,
                        Rate_Plan_Charge__r.Seg3_Record__c,
                        Rate_Plan_Charge__r.Seg3_Record__r.Geography_Type__c,
                        Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__c,
                        Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__c,
                        Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Name,
                        Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Seg2__c,
                        Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.ProductGeographyType__c,
                        Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__c,
                        Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name
                from FC_Charge_Monthly_Revenue__c
                where Import_Process_ID__c = :this.importProcessId
        ]);
    }

    public void execute(Database.BatchableContext context, List<FC_Charge_Monthly_Revenue__c> scope) {
        Map<String, FC_Segment_2_Assignment__c> segment2AssignmentMap = FC_Segment_2_Assignment__c.getAll();

        Map<String, Id> segment2ToGeographyMap = new Map<String, Id>();
        for (MetroclientGeography__c geographyRecord : [
                select Id, Seg2__c
                from MetroclientGeography__c
                where Seg2__c != null
                and Seg2__c != '' and GeographyType__r.Name = 'Market' and (not Geography_FIPS__c like '%c%')
        ]) {
            if (String.isNotBlank(geographyRecord.Seg2__c)) {
                segment2ToGeographyMap.put(geographyRecord.Seg2__c, geographyRecord.Id);
            }
        }

        Map<String, Set<FC_Segment_2_Assignment__c>> stateToSegment2AssignmentsMap = new Map<String, Set<FC_Segment_2_Assignment__c>>();
        Map<String, Decimal> stateToSegment2TotalPercentAllocationMap = new Map<String, Decimal>();
        for (FC_Segment_2_Assignment__c segment2AssignmentRecord : segment2AssignmentMap.values()) {
            if (String.isNotBlank(segment2AssignmentRecord.State__c)) {

                Set<FC_Segment_2_Assignment__c> stateSegment2Assignments = stateToSegment2AssignmentsMap.get(segment2AssignmentRecord.State__c);
                if (stateSegment2Assignments == null) {
                    stateSegment2Assignments = new Set<FC_Segment_2_Assignment__c>();
                    stateToSegment2AssignmentsMap.put(segment2AssignmentRecord.State__c, stateSegment2Assignments);
                }
                stateSegment2Assignments.add(segment2AssignmentRecord);

                Decimal stateTotalPercentAllocation = stateToSegment2TotalPercentAllocationMap.get(segment2AssignmentRecord.State__c);
                if (stateTotalPercentAllocation == null) {
                    stateTotalPercentAllocation = 0;
                }
                stateToSegment2TotalPercentAllocationMap.put(segment2AssignmentRecord.State__c,
                        stateTotalPercentAllocation + segment2AssignmentRecord.Allocation_Percentage__c);

            }
        }

        FC_Charge_Monthly_Revenue_Share__c[] recordsToInsert = new List<FC_Charge_Monthly_Revenue_Share__c>();
        if (scope != null && !scope.isEmpty()) {
            for (FC_Charge_Monthly_Revenue__c record : scope) {
                Decimal mrr = record.Monthly_Revenue__c != null ? record.Monthly_Revenue__c : 0;
                if (record.Rate_Plan_Charge__c != null &&
                        record.Rate_Plan_Charge__r.Seg3_Record__c != null &&
                        record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__c != null &&
                        record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.ProductGeographyType__c != null &&
                        record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__c != null) {
                    if (record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name == 'State' &&
                            stateToSegment2AssignmentsMap.containsKey(record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Name) &&
                            stateToSegment2TotalPercentAllocationMap.containsKey(record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Name) &&
                            stateToSegment2TotalPercentAllocationMap.get(record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Name) != 0) {
                        for (FC_Segment_2_Assignment__c segment2AssignmentRecord : stateToSegment2AssignmentsMap.get(record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Name)) {
                            Decimal allocationPercentage = segment2AssignmentRecord.Allocation_Percentage__c /
                                    stateToSegment2TotalPercentAllocationMap.get(record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Name);
                            recordsToInsert.add(new FC_Charge_Monthly_Revenue_Share__c(
                                    Allocated_Amount__c = mrr * allocationPercentage,
                                    Allocated_Geography__c = segment2ToGeographyMap.get(segment2AssignmentRecord.Name),
                                    Allocation_Percentage__c = allocationPercentage * 100,
                                    Charge_Monthly_Revenue__c = record.Id,
                                    RD_Assignment__c = segment2AssignmentRecord.Sales_Region_Assignment_ID__c,
                                    Segment_2__c = segment2AssignmentRecord.Name
                            ));
                        }
                    } else if (record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name == 'Country') {
                        for (FC_Segment_2_Assignment__c segment2AssignmentRecord : segment2AssignmentMap.values()) {
                            Decimal allocationPercentage = segment2AssignmentRecord.Allocation_Percentage__c / Decimal.valueOf(100);
                            recordsToInsert.add(new FC_Charge_Monthly_Revenue_Share__c(
                                    Allocated_Amount__c = mrr * allocationPercentage,
                                    Allocated_Geography__c = segment2ToGeographyMap.get(segment2AssignmentRecord.Name),
                                    Allocation_Percentage__c = allocationPercentage * 100,
                                    Charge_Monthly_Revenue__c = record.Id,
                                    RD_Assignment__c = segment2AssignmentRecord.Sales_Region_Assignment_ID__c,
                                    Segment_2__c = segment2AssignmentRecord.Name
                            ));
                        }
                    } else {
                        FC_Segment_2_Assignment__c segment2AssignmentRecord =
                                segment2AssignmentMap.get(record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Seg2__c);
                        if (segment2AssignmentRecord != null) {
                            recordsToInsert.add(new FC_Charge_Monthly_Revenue_Share__c(
                                    Allocated_Amount__c = mrr,
                                    Allocated_Geography__c = segment2ToGeographyMap.get(segment2AssignmentRecord.Name),
                                    Allocation_Percentage__c = 100,
                                    Charge_Monthly_Revenue__c = record.Id,
                                    RD_Assignment__c = segment2AssignmentRecord != null ?
                                            segment2AssignmentRecord.Sales_Region_Assignment_ID__c : null,
                                    Segment_2__c = record.Rate_Plan_Charge__r.Seg3_Record__r.Product_Geography__r.Geography__r.Seg2__c
                            ));
                        }
                    }
                }
            }
        }

        if (!recordsToInsert.isEmpty()) {
            insert recordsToInsert;
        }
    }

    public void finish(Database.BatchableContext context) {
        FC_Charge_Monthly_Revenue_Settings__c config = FC_Charge_Monthly_Revenue_Settings__c.getOrgDefaults();
        config.Active_Import_Process_ID__c = this.importProcessId;
        upsert config;
        Database.executeBatch(new FC_ChargeMonthlyRevenueCleanerBatchable());
    }
}