src/objects/FC_Charge_Monthly_Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Import_Process_ID__c</fullName>
        <externalId>true</externalId>
        <label>Import Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Charge Monthly Revenue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Charge Monthly Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Charge Monthly Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Charge_Monthly_Revenue_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Active_Import_Process_ID__c</fullName>
        <label>Active Import Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Charge Monthly Revenue Settings</label>
</CustomObject>

src/classes/FC_ChargeMonthlyRevenueCleanerBatchable.cls
public without sharing class FC_ChargeMonthlyRevenueCleanerBatchable implements Database.Batchable<sObject> {

    public FC_ChargeMonthlyRevenueCleanerBatchable() {
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        FC_Charge_Monthly_Revenue_Settings__c config = FC_Charge_Monthly_Revenue_Settings__c.getOrgDefaults();
        return Database.getQueryLocator([
                select Id
                from FC_Charge_Monthly_Revenue__c
                where Import_Process_ID__c != :config.Active_Import_Process_ID__c
        ]);
    }

    public void execute(Database.BatchableContext context, List<FC_Charge_Monthly_Revenue__c> scope) {
        if (scope != null && !scope.isEmpty()) {
            delete scope;
        }
    }

    public void finish(Database.BatchableContext context) {
    }

}