src/objects/FC_Charge_Monthly_Revenue_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Active_Import_Process_ID__c</fullName>
        <label>Active Import Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Charge Monthly Revenue Settings</label>
</CustomObject>

src/classes/FC_TestChargeMonthlyRevShareProcessCtrl.cls
@IsTest
private class FC_TestChargeMonthlyRevShareProcessCtrl {

    @IsTest
    private static void testHttpPost() {
        FC_Charge_Monthly_Revenue_Settings__c testConfig = FC_Charge_Monthly_Revenue_Settings__c.getOrgDefaults();
        System.assert(String.isBlank(testConfig.Active_Import_Process_ID__c));
        Test.startTest();
        FC_ChargeMonthlyRevShareProcessorCtrl.runProcess('123456');
        Test.stopTest();
        testConfig = FC_Charge_Monthly_Revenue_Settings__c.getOrgDefaults();
        System.assertEquals('123456', testConfig.Active_Import_Process_ID__c);
    }

}