src/objects/FC_Charge_Revenue_Share__c.object
<CustomObject>
    <fields>
        <fullName>Allocated_ARR__c</fullName>
        <label>Allocated ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Allocated Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipLabel>(FC) Charge Revenue Shares</relationshipLabel>
        <relationshipName>FC_Charge_Revenue_Shares</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Charge_Last_Modified_Date__c</fullName>
        <label>Charge Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Obsolete__c</fullName>
        <formula>Subscription_Product_Charge__r.LastModifiedDate != Charge_Last_Modified_Date__c</formula>
        <label>Obsolete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed_By_Batchable_On__c</fullName>
        <label>Processed By Batchable On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RD_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RD Assignment</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>(FC) Charge Revenue Shares</relationshipLabel>
        <relationshipName>FC_Charge_Revenue_Shares</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_2__c</fullName>
        <label>Segment 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>(FC) Charge Revenue Shares</relationshipLabel>
        <relationshipName>FC_Charge_Revenue_Shares</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>(FC) Charge Revenue Share</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Charge Revenue Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Charge Revenue Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Charge_Revenue_Share_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Last_Run_On__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Charge Revenue Share Settings</label>
</CustomObject>

src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Geography_Type__c</fullName>
        <formula>Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name</formula>
        <label>Geography Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <formula>Product_Geography__r.Geography__r.Name</formula>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Geography__c</fullName>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Segment_2_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Region_Assignment_ID__c</fullName>
        <label>Sales Region Assignment ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Segment 2 Assignment</label>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geography_FIPS__c</fullName>
        <label>Geography FIPS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seg2__c</fullName>
        <label>Seg2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>ARR__c</fullName>
        <formula>Zuora__MonthlyRecurringRevenue__c  * 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Monthly Recurring Revenue value multiplied by 12</inlineHelpText>
        <label>ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Seg3_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seg3 Record</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ChargeRevenueShareProcessorBatchable.cls
public without sharing class FC_ChargeRevenueShareProcessorBatchable implements Database.Batchable<sObject>,
        Database.Stateful {

    public DateTime lastRunOn;
    public DateTime startTime;

    public Boolean processObsoletes;

    public FC_ChargeRevenueShareProcessorBatchable(Boolean processObsoletes) {
        this.processObsoletes = processObsoletes;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        FC_Charge_Revenue_Share_Settings__c config = FC_Charge_Revenue_Share_Settings__c.getOrgDefaults();
        DateTime currentTime = DateTime.now();
        this.startTime = currentTime;
        this.lastRunOn = config.Last_Run_On__c;
        String soqlTemplate = 'select Id, ARR__c, LastModifiedDate, Seg3_Record__c, ' +
                'Seg3_Record__r.Geography_Type__c, Seg3_Record__r.Product_Geography__c, ' +
                'Seg3_Record__r.Product_Geography__r.Geography__c, ' +
                'Seg3_Record__r.Product_Geography__r.Geography__r.Name, ' +
                'Seg3_Record__r.Product_Geography__r.Geography__r.Seg2__c, ' +
                'Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name ' +
                'from Zuora__SubscriptionProductCharge__c where {0}';
        String criteria = 'CreatedDate <= :currentTime';
        if (config.Last_Run_On__c != null) {
            criteria = '(CreatedDate > :lastRunOn and CreatedDate <= :currentTime)';
        }
        if (processObsoletes) {
            criteria = 'Id in (select Subscription_Product_Charge__c from FC_Charge_Revenue_Share__c where Obsolete__c = true)';
        }

        return Database.getQueryLocator(String.format(soqlTemplate, new String[]{
                criteria
        }));
    }

    public void execute(Database.BatchableContext context, List<Zuora__SubscriptionProductCharge__c> scope) {
        Map<String, FC_Segment_2_Assignment__c> segment2AssignmentMap = FC_Segment_2_Assignment__c.getAll();

        Map<String, Id> segment2ToGeographyMap = new Map<String, Id>();
        for (MetroclientGeography__c geographyRecord : [
                select Id, Seg2__c
                from MetroclientGeography__c
                where Seg2__c != null
                and Seg2__c != '' and GeographyType__r.Name = 'Market' and (not Geography_FIPS__c like '%c%')
        ]) {
            if (String.isNotBlank(geographyRecord.Seg2__c)) {
                segment2ToGeographyMap.put(geographyRecord.Seg2__c, geographyRecord.Id);
            }
        }

        Map<String, Set<FC_Segment_2_Assignment__c>> stateToSegment2AssignmentsMap = new Map<String, Set<FC_Segment_2_Assignment__c>>();
        Map<String, Decimal> stateToSegment2TotalPercentAllocationMap = new Map<String, Decimal>();
        for (FC_Segment_2_Assignment__c segment2AssignmentRecord : segment2AssignmentMap.values()) {
            if (String.isNotBlank(segment2AssignmentRecord.State__c)) {

                Set<FC_Segment_2_Assignment__c> stateSegment2Assignments = stateToSegment2AssignmentsMap.get(segment2AssignmentRecord.State__c);
                if (stateSegment2Assignments == null) {
                    stateSegment2Assignments = new Set<FC_Segment_2_Assignment__c>();
                    stateToSegment2AssignmentsMap.put(segment2AssignmentRecord.State__c, stateSegment2Assignments);
                }
                stateSegment2Assignments.add(segment2AssignmentRecord);

                Decimal stateTotalPercentAllocation = stateToSegment2TotalPercentAllocationMap.get(segment2AssignmentRecord.State__c);
                if (stateTotalPercentAllocation == null) {
                    stateTotalPercentAllocation = 0;
                }
                stateToSegment2TotalPercentAllocationMap.put(segment2AssignmentRecord.State__c,
                        stateTotalPercentAllocation + segment2AssignmentRecord.Allocation_Percentage__c);

            }
        }

        FC_Charge_Revenue_Share__c[] recordsToInsert = new List<FC_Charge_Revenue_Share__c>();
        if (scope != null && !scope.isEmpty()) {
            for (Zuora__SubscriptionProductCharge__c chargeRecord : scope) {
                Decimal arr = chargeRecord.ARR__c != null ? chargeRecord.ARR__c : 0;
                if (chargeRecord.Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name == 'State' &&
                        stateToSegment2AssignmentsMap.containsKey(chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Name) &&
                        stateToSegment2TotalPercentAllocationMap.containsKey(chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Name) &&
                        stateToSegment2TotalPercentAllocationMap.get(chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Name) != 0) {
                    for (FC_Segment_2_Assignment__c segment2AssignmentRecord : stateToSegment2AssignmentsMap.get(chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Name)) {
                        Decimal allocationPercentage = segment2AssignmentRecord.Allocation_Percentage__c /
                                stateToSegment2TotalPercentAllocationMap.get(chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Name);
                        recordsToInsert.add(new FC_Charge_Revenue_Share__c(
                                Allocated_ARR__c = arr * allocationPercentage,
                                Allocated_Geography__c = segment2ToGeographyMap.get(segment2AssignmentRecord.Name),
                                Allocation_Percentage__c = allocationPercentage * 100,
                                Charge_Last_Modified_Date__c = chargeRecord.LastModifiedDate,
                                Processed_By_Batchable_On__c = this.startTime,
                                RD_Assignment__c = segment2AssignmentRecord.Sales_Region_Assignment_ID__c,
                                Segment_2__c = segment2AssignmentRecord.Name,
                                Subscription_Product_Charge__c = chargeRecord.Id));
                    }
                } else if (chargeRecord.Seg3_Record__r.Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name == 'Country') {
                    for (FC_Segment_2_Assignment__c segment2AssignmentRecord : segment2AssignmentMap.values()) {
                        Decimal allocationPercentage = segment2AssignmentRecord.Allocation_Percentage__c / Decimal.valueOf(100);
                        recordsToInsert.add(new FC_Charge_Revenue_Share__c(
                                Allocated_ARR__c = arr * allocationPercentage,
                                Allocated_Geography__c = segment2ToGeographyMap.get(segment2AssignmentRecord.Name),
                                Allocation_Percentage__c = allocationPercentage * 100,
                                Charge_Last_Modified_Date__c = chargeRecord.LastModifiedDate,
                                Processed_By_Batchable_On__c = this.startTime,
                                RD_Assignment__c = segment2AssignmentRecord.Sales_Region_Assignment_ID__c,
                                Segment_2__c = segment2AssignmentRecord.Name,
                                Subscription_Product_Charge__c = chargeRecord.Id));
                    }
                } else {
                    FC_Segment_2_Assignment__c segment2AssignmentRecord =
                            segment2AssignmentMap.get(chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Seg2__c);
                    recordsToInsert.add(new FC_Charge_Revenue_Share__c(
                            Allocated_ARR__c = arr,
                            Allocated_Geography__c = segment2ToGeographyMap.get(chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Seg2__c),
                            Allocation_Percentage__c = 100,
                            Charge_Last_Modified_Date__c = chargeRecord.LastModifiedDate,
                            Processed_By_Batchable_On__c = this.startTime,
                            RD_Assignment__c = segment2AssignmentRecord != null ?
                                    segment2AssignmentRecord.Sales_Region_Assignment_ID__c : null,
                            Segment_2__c = chargeRecord.Seg3_Record__r.Product_Geography__r.Geography__r.Seg2__c,
                            Subscription_Product_Charge__c = chargeRecord.Id));
                }
            }
        }
        if (!recordsToInsert.isEmpty()) {
            insert recordsToInsert;
        }
    }

    public void finish(Database.BatchableContext context) {
        if (!processObsoletes) {
            FC_Charge_Revenue_Share_Settings__c config = FC_Charge_Revenue_Share_Settings__c.getOrgDefaults();
            config.Last_Run_On__c = this.startTime;
            upsert config;
            FC_ChargeRevenueShareProcessorBatchable processorBatchable = new FC_ChargeRevenueShareProcessorBatchable(true);
            Database.executeBatch(processorBatchable);
        } else {
            FC_ChargeRevenueShareCleanerBatchable cleanerBatchable = new FC_ChargeRevenueShareCleanerBatchable(this.startTime);
            Database.executeBatch(cleanerBatchable);
        }
    }

}