src/objects/FC_Invoice_Item_Revenue_Share__c.object
<CustomObject>
    <fields>
        <fullName>Obsolete__c</fullName>
        <formula>Invoice_Item__r.fziiss__UpdatedDate__c != Invoice_Item_Last_Modified_Date__c</formula>
        <label>Obsolete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed_By_Batchable_On__c</fullName>
        <label>Processed By Batchable On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Invoice Item Revenue Share</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Invoice Item Revenue Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Invoice Item Revenue Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Invoice_Item_Revenue_Share_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Last_Run_On__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Invoice Item Revenue Share Settings</label>
</CustomObject>

src/classes/FC_InvoiceItemRevenueShareCleanerBatch.cls
public without sharing class FC_InvoiceItemRevenueShareCleanerBatch implements Database.Batchable<sObject> {

    public DateTime latestBatchableProcessedOn;

    public FC_InvoiceItemRevenueShareCleanerBatch(DateTime latestBatchableProcessedOn) {
        this.latestBatchableProcessedOn = latestBatchableProcessedOn;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        String soql = 'select Id from FC_Invoice_Item_Revenue_Share__c ';
        DateTime latestBatchableProcessedOn = this.latestBatchableProcessedOn;
        if (latestBatchableProcessedOn != null) {
            soql += 'where Obsolete__c = true and Processed_By_Batchable_On__c < :latestBatchableProcessedOn';
        }
        return Database.getQueryLocator(soql);
    }

    public void execute(Database.BatchableContext context, List<FC_Invoice_Item_Revenue_Share__c> scope) {
        if (scope != null && !scope.isEmpty()) {
            delete scope;
        }
    }

    public void finish(Database.BatchableContext context) {
        if (this.latestBatchableProcessedOn == null) {
            FC_Invoice_Item_Revenue_Share_Settings__c config = FC_Invoice_Item_Revenue_Share_Settings__c.getOrgDefaults();
            config.Last_Run_On__c = null;
            upsert config;
        }
    }

}