src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <formula>Product_Geography__r.Geography__r.Name</formula>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Geography__c</fullName>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Segment_2_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Market_Name__c</fullName>
        <label>Market Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>(FC) Segment 2 Assignment</label>
</CustomObject>

src/objects/fziiss__Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Seg3RecordID__c</fullName>
        <label>Seg3RecordID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seg3_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seg3 Record</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment2_Market_Name__c</fullName>
        <label>Segment2 Market Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment2__c</fullName>
        <label>Segment2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fziiss__Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Plan Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fziiss__ServiceStartDate__c</fullName>
        <label>Service Start Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <label>Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <description>Zuora Subscription Charge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Charge Number (Zuora)</inlineHelpText>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>FC_Lookup_Key__c</fullName>
        <externalId>true</externalId>
        <label>FC Lookup Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>FC_Eligible_to_Cancel_End_Date__c</fullName>
        <label>(FC) Eligible to Cancel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Eligible_to_Cancel_Start_Date__c</fullName>
        <label>(FC) Eligible to Cancel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermSettingType__c</fullName>
        <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
        <label>Term Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>FC_Eligible_to_Cancel_End_Date__c</fullName>
        <label>(FC) Eligible to Cancel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Eligible_to_Cancel_Start_Date__c</fullName>
        <label>(FC) Eligible to Cancel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Lookup_Key__c</fullName>
        <externalId>true</externalId>
        <label>FC Lookup Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Most_Recent_Service_Start_Date__c</fullName>
        <label>(FC) Most Recent Service Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_RD_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) RD Assignment</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seg3RecordID__c</fullName>
        <label>Seg3 Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seg3_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seg3 Record</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment2_Market_Name__c</fullName>
        <label>Segment2 Market Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment2__c</fullName>
        <label>Segment2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__ProductSKU__c</fullName>
        <label>Product SKU (Deprecated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__RatePlanName__c</fullName>
        <label>Rate Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_SubscriptionProductChargeHandler.cls
global without sharing class FC_SubscriptionProductChargeHandler extends fcf.TriggerAdapter {

    global static final String TRIGGER_RUN_STATUS_ID = 'FC_SubscriptionProductChargeHandler';

    // Before and after phases
    private static Map<ID, Zuora__Subscription__c> subscriptionLookupMap = new Map<ID, Zuora__Subscription__c>();

    // Before phase
    private Map<ID, FC_Metroclient_Product_Geography_Seg3__c> productGeographySeg3LookupMap = new Map<ID, FC_Metroclient_Product_Geography_Seg3__c>();
    private Map<Id, Set<MetrostudySalesRegionAssignment__c>> salesRegionIdToSalesRegionAssignmentsMap =
            new Map<Id, Set<MetrostudySalesRegionAssignment__c>>();
    private Map<String, FC_Segment_2_Assignment__c> fcSegment2AssignmentLookupMap = FC_Segment_2_Assignment__c.getAll();

    // After phase
    private Set<String> ratePlanChargeZuoraIdsToLookup = new Set<String>();
    private Set<String> fcLookupKeysToLookup = new Set<String>();
    private Set<String> chargeNumbersToLookup = new Set<String>();
    private Set<ID> billingAccountIdsToUpdate = new Set<ID>();
    private Set<ID> subscriptionIdsToUpdate = new Set<ID>();


    global override void bulkBefore() {
        if (Trigger.isInsert || Trigger.isUpdate) {

            Set<ID> seg3RecordIdsToLookup = new Set<ID>();
            for (SObject so : Trigger.new) {
                Zuora__SubscriptionProductCharge__c chargeRecord = (Zuora__SubscriptionProductCharge__c) so;
                if (String.isNotBlank(chargeRecord.Seg3RecordID__c)) {
                    try {
                        seg3RecordIdsToLookup.add(Id.valueOf(chargeRecord.Seg3RecordID__c));
                    } catch (Exception e) {
                        // Do nothing.
                    }
                }
            }
            productGeographySeg3LookupMap.putAll(FC_FcMetroclientProductGeoSeg3Cache.findByIds(seg3RecordIdsToLookup));

            Set<Id> salesRegionIdsToLookup = new Set<Id>();
            for (FC_Metroclient_Product_Geography_Seg3__c seg3Record : productGeographySeg3LookupMap.values()) {
                if (seg3Record.Product_Geography__r.Geography__r.SalesRegion__c != null) {
                    salesRegionIdsToLookup.add(seg3Record.Product_Geography__r.Geography__r.SalesRegion__c);
                }
            }
            salesRegionIdToSalesRegionAssignmentsMap.putAll(FC_MetrostudySalesRegionAssignmentCache.findBySalesRegionIds(salesRegionIdsToLookup));

            Set<ID> subscriptionIdsToLookup = new Set<ID>();
            for (SObject so : Trigger.new) {
                Zuora__SubscriptionProductCharge__c subscriptionProductChargeRecord = (Zuora__SubscriptionProductCharge__c) so;
                if (subscriptionProductChargeRecord.Zuora__Subscription__c != null) {
                    subscriptionIdsToLookup.add(subscriptionProductChargeRecord.Zuora__Subscription__c);
                }
            }
            subscriptionLookupMap.putAll(FC_SubscriptionCache.findByIds(subscriptionIdsToLookup));
        }
    }

    global override void beforeInsert(SObject so) {
        Zuora__SubscriptionProductCharge__c newCharge = (Zuora__SubscriptionProductCharge__c) so;
        populateFields(newCharge);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        Zuora__SubscriptionProductCharge__c newCharge = (Zuora__SubscriptionProductCharge__c) so;
        newCharge.FC_Most_Recent_Service_Start_Date__c = null;
        populateFields(newCharge);
    }

    global override void finallyBefore() {

        if (Trigger.isInsert || Trigger.isUpdate) {

            Map<String, zqu__ProductRatePlanCharge__c> productRatePlanChargeMap = FC_ProductRatePlanChargeCache.findByFcLookupKeys(fcLookupKeysToLookup);
            for (SObject so : Trigger.new) {
                Zuora__SubscriptionProductCharge__c newCharge = (Zuora__SubscriptionProductCharge__c) so;
                if (String.isNotBlank(newCharge.FC_Lookup_Key__c) && productRatePlanChargeMap.containsKey(newCharge.FC_Lookup_Key__c)) {
                    newCharge.Product_Rate_Plan_Charge__c = productRatePlanChargeMap.get(newCharge.FC_Lookup_Key__c).Id;
                }
            }

        }

        if (Trigger.isUpdate) {
            for (AggregateResult ar : [
                    select fziiss__Rate_Plan_Charge__c,
                            max(fziiss__ServiceStartDate__c) latestServiceStartDate
                    from fziiss__Invoice_Item__c
                    where fziiss__Rate_Plan_Charge__c in :Trigger.new
                    group by fziiss__Rate_Plan_Charge__c
            ]) {
                Zuora__SubscriptionProductCharge__c subscriptionProductChargeRecord =
                        (Zuora__SubscriptionProductCharge__c) Trigger.newMap.get((Id) ar.get('fziiss__Rate_Plan_Charge__c'));
                if (subscriptionProductChargeRecord != null) {
                    subscriptionProductChargeRecord.FC_Most_Recent_Service_Start_Date__c =
                            (Date) ar.get('latestServiceStartDate');
                }
            }
        }

    }


    global override void bulkAfter() {

        Set<ID> subscriptionIdsToLookup = new Set<ID>();
        if (Trigger.isInsert || Trigger.isUpdate || Trigger.isUndelete) {
            for (SObject so : Trigger.new) {
                Zuora__SubscriptionProductCharge__c subscriptionProductChargeRecord = (Zuora__SubscriptionProductCharge__c) so;
                if (subscriptionProductChargeRecord.Zuora__Subscription__c != null) {
                    subscriptionIdsToLookup.add(subscriptionProductChargeRecord.Zuora__Subscription__c);
                }
            }
        }
        if (Trigger.isUpdate || Trigger.isDelete) {
            for (SObject so : Trigger.old) {
                Zuora__SubscriptionProductCharge__c subscriptionProductChargeRecord = (Zuora__SubscriptionProductCharge__c) so;
                if (subscriptionProductChargeRecord.Zuora__Subscription__c != null) {
                    subscriptionIdsToLookup.add(subscriptionProductChargeRecord.Zuora__Subscription__c);
                }
            }
        }
        subscriptionLookupMap.putAll(FC_SubscriptionCache.findByIds(subscriptionIdsToLookup));

    }

    global override void afterInsert(SObject so) {
        Zuora__SubscriptionProductCharge__c newCharge = (Zuora__SubscriptionProductCharge__c) so;

        if (String.isNotBlank(newCharge.Zuora__External_Id__c)) {
            ratePlanChargeZuoraIdsToLookup.add(newCharge.Zuora__External_Id__c);
            chargeNumbersToLookup.add(newCharge.Zuora__ChargeNumber__c);
        }

        markSubscriptionAndBillingAccountForUpdate(newCharge);
    }

    global override void afterUpdate(SObject oldSo, SObject so) {
        Zuora__SubscriptionProductCharge__c newCharge = (Zuora__SubscriptionProductCharge__c) so;
        Zuora__SubscriptionProductCharge__c oldCharge = (Zuora__SubscriptionProductCharge__c) oldSo;

        if (String.isNotBlank(newCharge.Zuora__External_Id__c)) {
            ratePlanChargeZuoraIdsToLookup.add(newCharge.Zuora__External_Id__c);
            chargeNumbersToLookup.add(newCharge.Zuora__ChargeNumber__c);
        }

        markSubscriptionAndBillingAccountForUpdate(newCharge);
        markSubscriptionAndBillingAccountForUpdate(oldCharge);
    }

    global override void afterDelete(SObject oldSo) {
        Zuora__SubscriptionProductCharge__c oldCharge = (Zuora__SubscriptionProductCharge__c) oldSo;

        markSubscriptionAndBillingAccountForUpdate(oldCharge);
    }

    global override void afterUndelete(SObject so) {
        Zuora__SubscriptionProductCharge__c newCharge = (Zuora__SubscriptionProductCharge__c) so;

        markSubscriptionAndBillingAccountForUpdate(newCharge);
    }

    global override void finallyAfter() {

        // Prevent after phase from recursively executing
        if (!fcf.TriggerRunStatus.isRunnable(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID))) {
            return;
        }
        fcf.TriggerRunStatus.block(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID));

        if (Trigger.isInsert || Trigger.isUpdate) {

            if (!chargeNumbersToLookup.isEmpty()) {
                List<MetroclientAccountProductGeography__c> metroclientAccountProductGeographiesToUpdate = new List<MetroclientAccountProductGeography__c>();
                for (MetroclientAccountProductGeography__c record : [
                        select Id
                        from MetroclientAccountProductGeography__c
                        where ChargeNumber__c in :chargeNumbersToLookup
                ]) {
                    metroclientAccountProductGeographiesToUpdate.add(new MetroclientAccountProductGeography__c(Id = record.Id));
                }
                if (!metroclientAccountProductGeographiesToUpdate.isEmpty()) {
                    update metroclientAccountProductGeographiesToUpdate;
                }
                chargeNumbersToLookup.clear();
            }

        }

        if (!billingAccountIdsToUpdate.isEmpty()) {
            Zuora__CustomerAccount__c[] billingAccountsToUpdate = new List<Zuora__CustomerAccount__c>();
            for (ID billingAccountIdToUpdate : billingAccountIdsToUpdate) {
                billingAccountsToUpdate.add(new Zuora__CustomerAccount__c(Id = billingAccountIdToUpdate));
            }
            update billingAccountsToUpdate;
            billingAccountIdsToUpdate.clear();
        }

        if (!subscriptionIdsToUpdate.isEmpty()) {
            Zuora__Subscription__c[] subscriptionsToUpdate = new List<Zuora__Subscription__c>();
            for (Id subscriptionIdToUpdate : subscriptionIdsToUpdate) {
                subscriptionsToUpdate.add(new Zuora__Subscription__c(Id = subscriptionIdToUpdate));
            }
            update subscriptionsToUpdate;
            subscriptionIdsToUpdate.clear();
        }

    }

    private void markSubscriptionAndBillingAccountForUpdate(Zuora__SubscriptionProductCharge__c charge) {
        if (charge.Zuora__Subscription__c != null && subscriptionLookupMap.containsKey(charge.Zuora__Subscription__c)) {
            if (subscriptionLookupMap.get(charge.Zuora__Subscription__c).Zuora__CustomerAccount__c != null) {
                billingAccountIdsToUpdate.add(subscriptionLookupMap.get(charge.Zuora__Subscription__c).Zuora__CustomerAccount__c);
            }
            subscriptionIdsToUpdate.add(charge.Zuora__Subscription__c);
        }
    }

    private void populateFields(Zuora__SubscriptionProductCharge__c chargeRecord) {

        // Populate FC Lookup Key
        String fcLookupKey = String.join(new String[]{
                chargeRecord.Zuora__ProductSKU__c,
                chargeRecord.Zuora__RatePlanName__c, chargeRecord.Name
        }, '^');
        chargeRecord.FC_Lookup_Key__c = fcLookupKey;
        fcLookupKeysToLookup.add(fcLookupKey);

        // Populate Segment2 Market Name
        String segment2 = chargeRecord.Segment2__c == null ? '' : chargeRecord.Segment2__c;
        if (segment2.trim().length() == 1) {
            segment2 = '0' + segment2;
        }

        FC_Segment_2_Assignment__c assignment = fcSegment2AssignmentLookupMap.get(segment2);
        chargeRecord.Segment2_Market_Name__c = '';
        if (assignment != null) {
            chargeRecord.Segment2_Market_Name__c = assignment.Market_Name__c;
        }

        // Populate Seg3 Record
        chargeRecord.Seg3_Record__c = null;
        try {
            if (String.isNotBlank(chargeRecord.Seg3RecordID__c) &&
                    productGeographySeg3LookupMap.containsKey(Id.valueOf(chargeRecord.Seg3RecordID__c))) {
                chargeRecord.Seg3_Record__c = Id.valueOf(chargeRecord.Seg3RecordID__c);
            }
        } catch (Exception e) {
            // Do nothing.
        }

        // Populate RD Assignment
        try {
            chargeRecord.FC_RD_Assignment__c = null;
            FC_Metroclient_Product_Geography_Seg3__c seg3Record = productGeographySeg3LookupMap.get(Id.valueOf(chargeRecord.Seg3RecordID__c));
            if (seg3Record != null) {
                Set<MetrostudySalesRegionAssignment__c> possibleSalesRegionAssignments =
                        salesRegionIdToSalesRegionAssignmentsMap.get(seg3Record.Product_Geography__r.Geography__r.SalesRegion__c);
                if (possibleSalesRegionAssignments != null) {
                    for (MetrostudySalesRegionAssignment__c salesRegionAssignmentRecord : possibleSalesRegionAssignments) {
                        if (salesRegionAssignmentRecord.Role__c == 'RD') {
                            chargeRecord.FC_RD_Assignment__c = salesRegionAssignmentRecord.Id;
                            break;
                        }
                    }
                }
            }
        } catch (Exception e) {
            // Do nothing.
        }

        // Populate Eligible to Cancel Start and End Dates
        chargeRecord.FC_Eligible_to_Cancel_Start_Date__c = null;
        chargeRecord.FC_Eligible_to_Cancel_End_Date__c = null;
        Zuora__Subscription__c subscriptionRecord = subscriptionLookupMap.get(chargeRecord.Zuora__Subscription__c);
        if (subscriptionRecord != null && subscriptionRecord.Zuora__TermSettingType__c == 'EVERGREEN' &&
                subscriptionRecord.Zuora__SubscriptionStartDate__c != null &&
                subscriptionRecord.Zuora__NextChargeDate__c != null &&
                subscriptionRecord.Zuora__TermStartDate__c != null) {
            Date todaysDate = Date.today();
            Date endOfFirstYear = subscriptionRecord.Zuora__SubscriptionStartDate__c.addYears(1).addDays(-1);
            Boolean isFirstYear = todaysDate >= subscriptionRecord.Zuora__SubscriptionStartDate__c &&
                    todaysDate <= endOfFirstYear;

            // Assume charge is in the first year
            chargeRecord.FC_Eligible_to_Cancel_Start_Date__c = endOfFirstYear.addDays(-90);
            chargeRecord.FC_Eligible_to_Cancel_End_Date__c = endOfFirstYear.addDays(-30);

            // Calculate dates if not in first year
            if (!isFirstYear) {

                // Assume billing period is not monthly
                chargeRecord.FC_Eligible_to_Cancel_Start_Date__c = subscriptionRecord.Zuora__NextChargeDate__c.addDays(-90);
                chargeRecord.FC_Eligible_to_Cancel_End_Date__c = subscriptionRecord.Zuora__NextChargeDate__c.addDays(-30);

                // Calculate dates if billing period is monthly
                if (chargeRecord.Zuora__BillingPeriod__c == 'Month') {

                    // Calculate quarter
                    Date quarterStartDate = Date.newInstance(todaysDate.year() - 1, subscriptionRecord.Zuora__TermStartDate__c.month(), subscriptionRecord.Zuora__TermStartDate__c.day());


                    /* If the quarter ends on the last day of the month, assume that each quarter will end on the last
                     * day of the month. This is to prevent an infinite loop from occurring when todays date's month
                     * has more days than the quarter end date's month.
                     */
                    Boolean useLastDayOfMonthForQuarterEnd = false;
                    Date quarterEndDate = Date.newInstance(todaysDate.year() - 1, subscriptionRecord.Zuora__TermStartDate__c.month(), subscriptionRecord.Zuora__TermStartDate__c.day()).addMonths(3).addDays(-1);
                    Integer quarterEndDay = quarterEndDate.day();
                    if (quarterEndDay == Date.daysInMonth(quarterEndDate.year(), quarterEndDate.month())) {
                        useLastDayOfMonthForQuarterEnd = true;
                    }
                    while (todaysDate < quarterStartDate || quarterEndDate < todaysDate) {
                        quarterStartDate = quarterStartDate.addMonths(3);
                        quarterEndDate = quarterEndDate.addMonths(3);
                        if (useLastDayOfMonthForQuarterEnd) {
                            quarterEndDate = getLastDateForMonth(quarterEndDate.year(), quarterEndDate.month());
                        }
                    }
                    chargeRecord.FC_Eligible_to_Cancel_Start_Date__c = quarterEndDate.addDays(-90);
                    chargeRecord.FC_Eligible_to_Cancel_End_Date__c = quarterEndDate.addDays(-30);
                }

            }
        }
    }

    private Date getLastDateForMonth(Integer year, Integer month) {
        return Date.newInstance(year, month, Date.daysInMonth(year, month));
    }

}