src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Code__c</fullName>
        <externalId>true</externalId>
        <label>Accounting Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>OneTime</fullName>
                    <label>One-Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography_Type__c</fullName>
        <formula>Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name</formula>
        <label>Geography Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <formula>Product_Geography__r.Geography__r.Name</formula>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Geography__c</fullName>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_FcMetroclientProductGeoSeg3Cache.cls
public class FC_FcMetroclientProductGeoSeg3Cache {

    private static String[] SELECT_FIELDS = new String[]{
            'Id', 'Accounting_Code__c', 'Charge_Type__c', 'Geography__c', 'Geography_Type__c', 'Product_Geography__c',
            'Product_Geography__r.Geography__c', 'Product_Geography__r.Geography__r.SalesRegion__c', 'Seg3__c',
            '(select Name, Type from Tags where Type = \'Public\') Tags'
    };

    private static final Map<Id, FC_Metroclient_Product_Geography_Seg3__c> BY_ID_MAP =
            new Map<Id, FC_Metroclient_Product_Geography_Seg3__c>();
    private static final Map<String, Set<FC_Metroclient_Product_Geography_Seg3__c>> BY_ACCOUNTING_CODE_MAP =
            new Map<String, Set<FC_Metroclient_Product_Geography_Seg3__c>>();
    private static final String SOQL_BASE;

    static {
        SOQL_BASE = String.format('select {0} from FC_Metroclient_Product_Geography_Seg3__c',
                new String[]{
                        String.join(SELECT_FIELDS, ', ')
                });
    }

    public static void clearCache() {
        BY_ID_MAP.clear();
        BY_ACCOUNTING_CODE_MAP.clear();
    }

    public static Map<ID, FC_Metroclient_Product_Geography_Seg3__c> findByIds(Set<ID> recordIds) {
        Map<ID, FC_Metroclient_Product_Geography_Seg3__c> results = new Map<ID, FC_Metroclient_Product_Geography_Seg3__c>();
        Set<ID> recordIdsToQuery = new Set<ID>();
        for (ID recordId : recordIds) {
            if (BY_ID_MAP.containsKey(recordId)) {
                results.put(recordId, BY_ID_MAP.get(recordId));
            } else {
                recordIdsToQuery.add(recordId);
            }
        }
        if (recordIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Id in :recordIdsToQuery';
            FC_Metroclient_Product_Geography_Seg3__c[] records = Database.query(soql);
            BY_ID_MAP.putAll(records);
            results.putAll(records);
        }
        return results;
    }

    public static Map<String, Set<FC_Metroclient_Product_Geography_Seg3__c>> findByAccountingCodes(Set<String> accountingCodes) {
        Map<String, Set<FC_Metroclient_Product_Geography_Seg3__c>> results = new Map<String, Set<FC_Metroclient_Product_Geography_Seg3__c>>();
        Set<String> accountingCodesToQuery = new Set<String>();
        for (String accountingCode : accountingCodes) {
            if (BY_ACCOUNTING_CODE_MAP.containsKey(accountingCode)) {
                results.put(accountingCode, BY_ACCOUNTING_CODE_MAP.get(accountingCode));
            } else {
                accountingCodesToQuery.add(accountingCode);
            }
        }
        if (accountingCodesToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Accounting_Code__c in :accountingCodesToQuery';
            FC_Metroclient_Product_Geography_Seg3__c[] records = Database.query(soql);
            Integer recordCount = records.size();
            for (Integer i = 0; i < recordCount; i++) {
                FC_Metroclient_Product_Geography_Seg3__c record = records[i];
                Set<FC_Metroclient_Product_Geography_Seg3__c> recordsForAccountingCode = BY_ACCOUNTING_CODE_MAP.get(record.Accounting_Code__c);
                if (recordsForAccountingCode == null) {
                    recordsForAccountingCode = new Set<FC_Metroclient_Product_Geography_Seg3__c>();
                    BY_ACCOUNTING_CODE_MAP.put(record.Accounting_Code__c, recordsForAccountingCode);
                    results.put(record.Accounting_Code__c, recordsForAccountingCode);
                }
                recordsForAccountingCode.add(record);
                BY_ID_MAP.put(record.Id, record);
            }
        }
        return results;
    }

}