src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Code__c</fullName>
        <externalId>true</externalId>
        <label>Accounting Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>OneTime</fullName>
                    <label>One-Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependent_Seg3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Seg3</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Dependent Seg3&apos;s</relationshipLabel>
        <relationshipName>Dependent_Seg3s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude_From_Product_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude From Product Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Execute_Immediately__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Execute Immediately</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <formula>Product_Geography__r.Geography__r.Name</formula>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Geography__c</fullName>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ProductRatePlan__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <label>Geography</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Albuquerque-37</fullName>
                </value>
                <value>
                    <fullName>Atlanta-79</fullName>
                </value>
                <value>
                    <fullName>Austin-45</fullName>
                </value>
                <value>
                    <fullName>Bay Area-07</fullName>
                </value>
                <value>
                    <fullName>Boise-36</fullName>
                </value>
                <value>
                    <fullName>California-Full State-09</fullName>
                </value>
                <value>
                    <fullName>Carolinas-74</fullName>
                </value>
                <value>
                    <fullName>Central California-05</fullName>
                </value>
                <value>
                    <fullName>Central Florida-81</fullName>
                </value>
                <value>
                    <fullName>Charlotte-75</fullName>
                </value>
                <value>
                    <fullName>Chicago-71</fullName>
                </value>
                <value>
                    <fullName>Cincinnati-91</fullName>
                </value>
                <value>
                    <fullName>Cleveland-92</fullName>
                </value>
                <value>
                    <fullName>Colorado Springs-12</fullName>
                </value>
                <value>
                    <fullName>Columbus-93</fullName>
                </value>
                <value>
                    <fullName>Dallas Fort Worth-47</fullName>
                </value>
                <value>
                    <fullName>Denver-11</fullName>
                </value>
                <value>
                    <fullName>Desert / Mountain-10</fullName>
                </value>
                <value>
                    <fullName>Detroit-66</fullName>
                </value>
                <value>
                    <fullName>Florida-80</fullName>
                </value>
                <value>
                    <fullName>Hawaii-15</fullName>
                </value>
                <value>
                    <fullName>Houston-48</fullName>
                </value>
                <value>
                    <fullName>Indianapolis-72</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-04</fullName>
                </value>
                <value>
                    <fullName>LA Coastal-02</fullName>
                </value>
                <value>
                    <fullName>Las Vegas-21</fullName>
                </value>
                <value>
                    <fullName>Louisville-70</fullName>
                </value>
                <value>
                    <fullName>MidAtlantic-50</fullName>
                </value>
                <value>
                    <fullName>Midwest-64</fullName>
                </value>
                <value>
                    <fullName>Naples/Ft. Meyers-86</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>This is a concatenation of the Product Name and marekt so that the Market displays on the Add Product to Opportunity window</description>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>Product__c</fullName>
        <formula>zqu__ProductRatePlan__r.zqu__Product__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestFcMetroclientProdGeoSeg3Handler.cls
@isTest
private class FC_TestFcMetroclientProdGeoSeg3Handler {

    @isTest
    private static void testInsert() {

        MetroclientProductGeography__c testProductGeography = [
                select Id
                from MetroclientProductGeography__c
                where Name = 'Test Product Geography'
                limit 1
        ];

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_FcMetroclientProductGeoSeg3Handler'
        });

        Test.startTest();

        FC_Metroclient_Product_Geography_Seg3__c testProductGeographySeg3 =
                new FC_Metroclient_Product_Geography_Seg3__c(Accounting_Code__c = 'AC-1',
                        Dependent_Seg3__c = null, Exclude_From_Product_Selector__c = false,
                        Execute_Immediately__c = true,
                        Product_Geography__c = testProductGeography.Id);
        insert testProductGeographySeg3;

        Test.stopTest();

        testProductGeographySeg3 = [
                select Id, Product__c, Product_Rate_Plan__c, Charge_Type__c, Seg3__c
                from FC_Metroclient_Product_Geography_Seg3__c
                where Id = :testProductGeographySeg3.Id
                limit 1
        ];

        Product2 testProduct = [select Id from Product2 where Name = 'Test Product' limit 1];
        zqu__ProductRatePlan__c testProductRatePlan = [
                select Id
                from zqu__ProductRatePlan__c
                where zqu__ZuoraId__c = 'PRP-1'
                limit 1
        ];
        System.assertEquals(testProduct.Id, testProductGeographySeg3.Product__c);
        System.assertEquals(testProductRatePlan.Id, testProductGeographySeg3.Product_Rate_Plan__c);
        System.assertEquals('Recurring', testProductGeographySeg3.Charge_Type__c);
        System.assertEquals('CONS', testProductGeographySeg3.Seg3__c);

    }

    @isTest
    private static void testUpdate() {

        FC_Metroclient_Product_Geography_Seg3__c testProductGeographySeg3 = [
                select Id, Product__c, Product_Rate_Plan__c, Charge_Type__c, Seg3__c
                from FC_Metroclient_Product_Geography_Seg3__c
                where Accounting_Code__c = 'AC-1'
                limit 1
        ];

        System.assertEquals(null, testProductGeographySeg3.Product__c);
        System.assertEquals(null, testProductGeographySeg3.Product_Rate_Plan__c);
        System.assert(String.isBlank(testProductGeographySeg3.Charge_Type__c));
        System.assert(String.isBlank(testProductGeographySeg3.Seg3__c));

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'FC_FcMetroclientProductGeoSeg3Handler'
        });

        Test.startTest();

        update testProductGeographySeg3;

        Test.stopTest();

        testProductGeographySeg3 = [
                select Id, Product__c, Product_Rate_Plan__c, Charge_Type__c, Seg3__c
                from FC_Metroclient_Product_Geography_Seg3__c
                where Accounting_Code__c = 'AC-1'
                limit 1
        ];

        Product2 testProduct = [select Id from Product2 where Name = 'Test Product' limit 1];
        zqu__ProductRatePlan__c testProductRatePlan = [
                select Id
                from zqu__ProductRatePlan__c
                where zqu__ZuoraId__c = 'PRP-1'
                limit 1
        ];
        System.assertEquals(testProduct.Id, testProductGeographySeg3.Product__c);
        System.assertEquals(testProductRatePlan.Id, testProductGeographySeg3.Product_Rate_Plan__c);
        System.assertEquals('Recurring', testProductGeographySeg3.Charge_Type__c);
        System.assertEquals('CONS', testProductGeographySeg3.Seg3__c);

    }

    @testSetup
    private static void setup() {

        Product2 testProduct = new Product2(Name = 'Test Product', IsActive = true);
        insert testProduct;

        PricebookEntry testPricebookEntry = new PricebookEntry(IsActive = true,
                Pricebook2Id = Test.getStandardPricebookId(), Product2Id = testProduct.Id, UnitPrice = 100);
        insert testPricebookEntry;

        zqu__ZProduct__c testZProduct = new zqu__ZProduct__c(Name = 'Test ZProduct', zqu__Product__c = testProduct.Id,
                zqu__SKU__c = 'SKU-1', zqu__ZuoraId__c = 'P-1');
        insert testZProduct;

        zqu__ProductRatePlan__c testProductRatePlan = new zqu__ProductRatePlan__c(Name = 'Test Product Rate Plan',
                Segment3__c = 'CONS', zqu__Product__c = testProduct.Id, zqu__ZuoraId__c = 'PRP-1',
                zqu__ZProduct__c = testZProduct.Id, zqu__EffectiveStartDate__c = Date.today() - 30,
                zqu__EffectiveEndDate__c = Date.today() + 30, zqu__Deleted__c = false);
        insert testProductRatePlan;

        zqu__ProductRatePlanCharge__c testProductRatePlanCharge = new zqu__ProductRatePlanCharge__c(
                Name = 'Test Product Rate Plan Charge', zqu__ProductRatePlan__c = testProductRatePlan.Id,
                zqu__RecognizedRevenueAccount__c = 'AC-1', FC_Recognized_Revenue_Account__c = 'AC-1',
                zqu__ZuoraId__c = 'PRPC-1', zqu__Type__c = 'Recurring',
                zqu__Deleted__c = false);
        insert testProductRatePlanCharge;

        MetroclientProduct__c testMetroclientProduct = new MetroclientProduct__c(Name = 'Test Product',
                ProductAbbreviation__c = 'TEST', ZuoraSku__c = 'SKU-1');
        insert testMetroclientProduct;

        MetroclientGeographyType__c testGeographyType = new MetroclientGeographyType__c(Name = 'Test Geography Type',
                GeographyTypeId__c = 1);
        insert testGeographyType;

        MetroclientGeography__c testGeography = new MetroclientGeography__c(Name = 'Test Geography',
                GeographyType__c = testGeographyType.Id);
        insert testGeography;

        MetroclientProductGeographyType__c testProductGeographyType =
                new MetroclientProductGeographyType__c(Name = 'Test Product Geography Type',
                        GeographyType__c = testGeographyType.Id, Product__c = testMetroclientProduct.Id);
        insert testProductGeographyType;

        MetroclientProductGeography__c testProductGeography = new MetroclientProductGeography__c(
                Name = 'Test Product Geography', Geography__c = testGeography.Id,
                ProductGeographyType__c = testProductGeographyType.Id);
        insert testProductGeography;

        FC_Metroclient_Product_Geography_Seg3__c testProductGeographySeg3 =
                new FC_Metroclient_Product_Geography_Seg3__c(Accounting_Code__c = 'AC-1',
                        Dependent_Seg3__c = null, Exclude_From_Product_Selector__c = false,
                        Execute_Immediately__c = true,
                        Product_Geography__c = testProductGeography.Id);
        insert testProductGeographySeg3;
    }

}