src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Code__c</fullName>
        <externalId>true</externalId>
        <label>Accounting Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>OneTime</fullName>
                    <label>One-Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Geography__c</fullName>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Rate_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ProductRatePlan__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetroclientProduct__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Metrostudy Products</description>
    <label>Metrostudy Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>ProductGeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography Type</label>
        <referenceTo>MetroclientProductGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>This is a concatenation of the Product Name and marekt so that the Market displays on the Add Product to Opportunity window</description>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The deprecated Product SKU field.</description>
        <inlineHelpText>This field will be auto-generated if no value specified.</inlineHelpText>
        <label>SKU (Deprecated)</label>
        <length>70</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>zqu__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Segment3__c</fullName>
        <label>Segment3</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>Product__c</fullName>
        <formula>zqu__ProductRatePlan__r.zqu__Product__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Type__c</fullName>
        <description>The Type of the Rate Plan Charge.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>Seg3__c</fullName>
        <label>Seg3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ZProducts</relationshipLabel>
        <relationshipName>ZProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_FcMetroclientProductGeoSeg3Handler.cls
global without sharing class FC_FcMetroclientProductGeoSeg3Handler extends fcf.TriggerAdapter {

    private Map<String, Set<zqu__ProductRatePlanCharge__c>> accountingCodeToProductRatePlanChargesMap = new Map<String, Set<zqu__ProductRatePlanCharge__c>>();
    private Map<Id, MetroclientProductGeography__c> metroclientProductGeographyLookupMap = new Map<Id, MetroclientProductGeography__c>();

    global override void bulkBefore() {
        if (Trigger.isInsert || Trigger.isUpdate) {

            Set<String> accountingCodesToLookup = new Set<String>();
            Set<Id> metroclientProductGeographyIdsToLookup = new Set<Id>();

            for (SObject so : Trigger.new) {
                FC_Metroclient_Product_Geography_Seg3__c seg3Record = (FC_Metroclient_Product_Geography_Seg3__c) so;
                if (String.isNotBlank(seg3Record.Accounting_Code__c)) {
                    accountingCodesToLookup.add(seg3Record.Accounting_Code__c.toUpperCase());
                }
                if (seg3Record.Product_Geography__c != null) {
                    metroclientProductGeographyIdsToLookup.add(seg3Record.Product_Geography__c);
                }
            }
            accountingCodeToProductRatePlanChargesMap.putAll(FC_ProductRatePlanChargeCache.findWithActiveRatePlanByRecognizedRevenueAccount(accountingCodesToLookup));
            metroclientProductGeographyLookupMap.putAll(FC_MetroclientProductGeographyCache.findByIds(metroclientProductGeographyIdsToLookup));

        }
    }

    global override void beforeInsert(SObject so) {
        FC_Metroclient_Product_Geography_Seg3__c newSeg3Record = (FC_Metroclient_Product_Geography_Seg3__c) so;
        populateFields(newSeg3Record);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        FC_Metroclient_Product_Geography_Seg3__c newSeg3Record = (FC_Metroclient_Product_Geography_Seg3__c) so;
        populateFields(newSeg3Record);
    }

    private void populateFields(FC_Metroclient_Product_Geography_Seg3__c seg3Record) {
        seg3Record.Charge_Type__c = null;
        seg3Record.Seg3__c = null;
        seg3Record.Product__c = null;
        seg3Record.Product_Rate_Plan__c = null;
        MetroclientProductGeography__c metroclientProductGeographyRecord = metroclientProductGeographyLookupMap.get(seg3Record.Product_Geography__c);
        if (metroclientProductGeographyRecord != null &&
                String.isNotBlank(metroclientProductGeographyRecord.ProductGeographyType__r.Product__r.ZuoraSku__c) &&
                String.isNotBlank(seg3Record.Accounting_Code__c) &&
                accountingCodeToProductRatePlanChargesMap.containsKey(seg3Record.Accounting_Code__c.toUpperCase())) {
            for (zqu__ProductRatePlanCharge__c productRatePlanChargeRecord : accountingCodeToProductRatePlanChargesMap.get(seg3Record.Accounting_Code__c.toUpperCase())) {
                if (metroclientProductGeographyRecord.ProductGeographyType__r.Product__r.ZuoraSku__c ==
                        productRatePlanChargeRecord.zqu__ProductRatePlan__r.zqu__ZProduct__r.zqu__SKU__c) {
                    seg3Record.Product__c = productRatePlanChargeRecord.zqu__ProductRatePlan__r.zqu__Product__c;
                    seg3Record.Product_Rate_Plan__c = productRatePlanChargeRecord.zqu__ProductRatePlan__c;
                    seg3Record.Charge_Type__c = productRatePlanChargeRecord.zqu__Type__c == 'One-Time' ? 'OneTime' : productRatePlanChargeRecord.zqu__Type__c;
                    seg3Record.Seg3__c = productRatePlanChargeRecord.zqu__ProductRatePlan__r.Segment3__c;
                    break;
                }
            }
        }
    }

}