src/objects/FC_Metroclient_Product_Geography_Seg3__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>(FC) Metrostudy Product Geography Seg3&apos;s</relationshipLabel>
        <relationshipName>FC_Metrostudy_Product_Geography_Seg3s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>(FC) Metrostudy Product Geography Seg3</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Metrostudy Product Geography Seg3 N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Metrostudy Product Geography Seg3&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Segment_2_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Market_Name__c</fullName>
        <label>Market Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>(FC) Segment 2 Assignment</label>
</CustomObject>

src/objects/fziiss__Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Frequency__c</fullName>
        <inlineHelpText>Blank if no account link available.</inlineHelpText>
        <label>Billing Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment2_Market_Name__c</fullName>
        <label>Segment2 Market Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment2__c</fullName>
        <label>Segment2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fziiss__ChargeNumber__c</fullName>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fziiss__Rate_Plan_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Plan Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fziiss__ServiceStartDate__c</fullName>
        <label>Service Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>fziiss__SubscriptionNumber__c</fullName>
        <label>Subscription Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fziiss__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <label>Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>This is a concatenation of the Product Name and marekt so that the Market displays on the Add Product to Opportunity window</description>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The deprecated Product SKU field.</description>
        <inlineHelpText>This field will be auto-generated if no value specified.</inlineHelpText>
        <label>SKU (Deprecated)</label>
        <length>70</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Segment2__c</fullName>
        <label>Segment2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>Product__c</fullName>
        <formula>zqu__ProductRatePlan__r.zqu__Product__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ZProducts</relationshipLabel>
        <relationshipName>ZProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>FC_Most_Recent_Service_Start_Date__c</fullName>
        <label>(FC) Most Recent Service Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment2_Market_Name__c</fullName>
        <label>Segment2 Market Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment2__c</fullName>
        <label>Segment2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingPeriod__c</fullName>
        <description>e.g. monthly, quarterly, annually</description>
        <label>Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestFziissInvoiceItemHandler.cls
@isTest
private class FC_TestFziissInvoiceItemHandler {

    @isTest
    private static void testInsert() {

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'fziiss.InvoiceItemHandler', 'FC_SubscriptionProductChargeHandler'
        });

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [
                select Id, Zuora__BillingPeriod__c, Zuora__External_Id__c, Zuora__Subscription__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];

        Test.startTest();
        fziiss__Invoice_Item__c testInvoiceItem = new fziiss__Invoice_Item__c(Name = 'II-1', Segment2__c = '00',
                fziiss__SubscriptionNumber__c = 'S-1', fziiss__ChargeNumber__c = 'SPC-1',
                fziiss__Subscription__c = testSubscriptionProductCharge.Zuora__Subscription__c,
                fziiss__Rate_Plan_Charge__c = testSubscriptionProductCharge.Id);
        insert testInvoiceItem;

        Test.stopTest();

        testInvoiceItem = [
                select Id, Name, Billing_Frequency__c, Segment2_Market_Name__c
                from fziiss__Invoice_Item__c
                where Id = :testInvoiceItem.Id
        ];
        System.assertEquals('TEST MARKET', testInvoiceItem.Segment2_Market_Name__c);
        System.assertEquals(testSubscriptionProductCharge.Zuora__BillingPeriod__c, testInvoiceItem.Billing_Frequency__c);
    }

    @isTest
    private static void testUpdate() {

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(null, testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);

        fziiss__Invoice_Item__c testInvoiceItem = new fziiss__Invoice_Item__c(Name = 'II-1',
                fziiss__SubscriptionNumber__c = 'S-1',
                fziiss__ChargeNumber__c = 'SPC-1',
                fziiss__Rate_Plan_Charge__c = testSubscriptionProductCharge.Id,
                fziiss__ServiceStartDate__c = Date.today());
        insert testInvoiceItem;

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'fziiss.InvoiceItemHandler', 'FC_SubscriptionProductChargeHandler'
        });

        fcf.TriggerRunStatus.unblockAll();
        Test.startTest();
        testInvoiceItem.Name = 'II-1';
        testInvoiceItem.Segment2__c = '00';
        testInvoiceItem.fziiss__SubscriptionNumber__c = 'S-1';
        testInvoiceItem.fziiss__ChargeNumber__c = 'SPC-1';
        update testInvoiceItem;
        Test.stopTest();

        testInvoiceItem = [
                select Id, Name, Billing_Frequency__c, Segment2_Market_Name__c
                from fziiss__Invoice_Item__c
                where Id = :testInvoiceItem.Id
        ];
        System.assertEquals('TEST MARKET', testInvoiceItem.Segment2_Market_Name__c);
        System.assertEquals(testSubscriptionProductCharge.Zuora__BillingPeriod__c, testInvoiceItem.Billing_Frequency__c);

        testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(Date.today(), testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);

    }

    @isTest
    private static void testDelete() {

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'fziiss.InvoiceItemHandler', 'FC_SubscriptionProductChargeHandler'
        });

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(null, testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);

        fcf.TriggerRunStatus.unblockAll();
        fziiss__Invoice_Item__c testInvoiceItem = new fziiss__Invoice_Item__c(Name = 'II-1',
                fziiss__SubscriptionNumber__c = 'S-1',
                fziiss__ChargeNumber__c = 'SPC-1',
                fziiss__Rate_Plan_Charge__c = testSubscriptionProductCharge.Id,
                fziiss__ServiceStartDate__c = Date.today());
        insert testInvoiceItem;

        testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(Date.today(), testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);

        fcf.TriggerRunStatus.unblockAll();
        Test.startTest();
        delete testInvoiceItem;
        Test.stopTest();

        testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(null, testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);
    }

    @isTest
    private static void testUndelete() {

        fcf.TriggerHandlerSettings.enable(new Set<String>{
                'fziiss.InvoiceItemHandler', 'FC_SubscriptionProductChargeHandler'
        });

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(null, testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);

        fcf.TriggerRunStatus.unblockAll();
        fziiss__Invoice_Item__c testInvoiceItem = new fziiss__Invoice_Item__c(Name = 'II-1',
                fziiss__SubscriptionNumber__c = 'S-1',
                fziiss__ChargeNumber__c = 'SPC-1',
                fziiss__Rate_Plan_Charge__c = testSubscriptionProductCharge.Id,
                fziiss__ServiceStartDate__c = Date.today());
        insert testInvoiceItem;

        testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(Date.today(), testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);

        fcf.TriggerRunStatus.unblockAll();
        delete testInvoiceItem;

        testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(null, testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);

        fcf.TriggerRunStatus.unblockAll();
        Test.startTest();
        undelete testInvoiceItem;
        Test.stopTest();

        testSubscriptionProductCharge = [
                select Id, FC_Most_Recent_Service_Start_Date__c, Zuora__BillingPeriod__c, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c
                where Zuora__External_Id__c = 'SPC-1'
        ];
        System.assertEquals(Date.today(), testSubscriptionProductCharge.FC_Most_Recent_Service_Start_Date__c);
    }

    @testSetup
    private static void setup() {
        FC_Segment_2_Assignment__c testFcSegment2Assignment = new FC_Segment_2_Assignment__c(Name = '00',
                Market_Name__c = 'TEST MARKET');
        insert testFcSegment2Assignment;

        Product2 testProduct = new Product2(Name = 'Test Product', IsActive = true);
        insert testProduct;

        PricebookEntry testPricebookEntry = new PricebookEntry(IsActive = true,
                Pricebook2Id = Test.getStandardPricebookId(), Product2Id = testProduct.Id, UnitPrice = 100);
        insert testPricebookEntry;

        zqu__ZProduct__c testZProduct = new zqu__ZProduct__c(Name = 'Test ZProduct', zqu__Product__c = testProduct.Id,
                zqu__SKU__c = 'SKU-1', zqu__ZuoraId__c = 'P-1');
        insert testZProduct;

        zqu__ProductRatePlan__c testProductRatePlan = new zqu__ProductRatePlan__c(Name = 'Test Product Rate Plan',
                zqu__Product__c = testProduct.Id, zqu__ZuoraId__c = 'PRP-1', zqu__ZProduct__c = testZProduct.Id);
        insert testProductRatePlan;

        zqu__ProductRatePlanCharge__c testProductRatePlanCharge = new zqu__ProductRatePlanCharge__c(
                Name = 'Test Product Rate Plan Charge', zqu__ProductRatePlan__c = testProductRatePlan.Id,
                zqu__RecognizedRevenueAccount__c = 'AC-1', zqu__ZuoraId__c = 'PRPC-1');
        insert testProductRatePlanCharge;

        MetroclientProduct__c testMetroclientProduct = new MetroclientProduct__c(Name = 'Test Product',
                ProductAbbreviation__c = 'TEST');
        insert testMetroclientProduct;

        MetroclientGeographyType__c testGeographyType = new MetroclientGeographyType__c(Name = 'Test Geography Type',
                GeographyTypeId__c = 1);
        insert testGeographyType;

        MetroclientGeography__c testGeography = new MetroclientGeography__c(Name = 'Test Geography',
                GeographyType__c = testGeographyType.Id);
        insert testGeography;

        MetroclientProductGeographyType__c testProductGeographyType =
                new MetroclientProductGeographyType__c(Name = 'Test Product Geography Type',
                        GeographyType__c = testGeographyType.Id, Product__c = testMetroclientProduct.Id);
        insert testProductGeographyType;

        MetroclientProductGeography__c testProductGeography = new MetroclientProductGeography__c(
                Name = 'Test Product Geography', Geography__c = testGeography.Id,
                ProductGeographyType__c = testProductGeographyType.Id);
        insert testProductGeography;

        FC_Metroclient_Product_Geography_Seg3__c testProductGeographySeg3 =
                new FC_Metroclient_Product_Geography_Seg3__c(Accounting_Code__c = 'AC-1', Charge_Type__c = 'Recurring',
                        Dependent_Seg3__c = null, Exclude_From_Product_Selector__c = false,
                        Execute_Immediately__c = true, Product__c = testProduct.Id,
                        Product_Geography__c = testProductGeography.Id, Product_Rate_Plan__c = testProductRatePlan.Id,
                        Seg3__c = 'CONS');
        insert testProductGeographySeg3;

        Account testAccount = new Account(Name = 'Test Account', BillingPostalCode = '12345');
        insert testAccount;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account',
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;

        Zuora__Subscription__c testSubscription = new Zuora__Subscription__c(Name = 'S-1',
                Zuora__Account__c = testAccount.Id, Zuora__CustomerAccount__c = testCustomerAccount.Id,
                Zuora__External_Id__c = 'S-1', Zuora__SubscriptionNumber__c = 'S-1');
        insert testSubscription;

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = new Zuora__SubscriptionProductCharge__c(
                Name = 'SPC-1', Zuora__Account__c = testAccount.Id, Zuora__Subscription__c = testSubscription.Id,
                Zuora__BillingPeriod__c = 'Month', Zuora__SubscriptionChargeNumber__c = 'SPC-1',
                Zuora__External_Id__c = 'SPC-1', Seg3_Record__c = testProductGeographySeg3.Id);
        insert testSubscriptionProductCharge;

        fcf.TriggerHandlerSettings.enable('FC_FziissInvoiceItemHandler');
    }

}