src/objects/FC_Revenue_Share__c.object
<CustomObject>
    <fields>
        <fullName>Allocated_Cancellation_Revenue__c</fullName>
        <label>Allocated Cancellation Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Delta_Revenue__c</fullName>
        <label>Allocated Delta Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Allocated Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipLabel>(FC) Revenue Shares</relationshipLabel>
        <relationshipName>FC_Revenue_Shares</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_New_Revenue__c</fullName>
        <label>Allocated New Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Renewal_Revenue__c</fullName>
        <label>Allocated Renewal Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Total_Revenue__c</fullName>
        <label>Allocated Total Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Obsolete__c</fullName>
        <formula>!(Opportunity__r.LastModifiedDate == Opportunity_Last_Modified_Date__c &amp;&amp;  Opportunity__r.FC_Most_Recent_OLI_Last_Modified_Date__c == Recent_Opp_Line_Item_Last_Modified_Date__c)</formula>
        <label>Obsolete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Last_Modified_Date__c</fullName>
        <label>Opportunity Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Line Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>(FC) Revenue Shares</relationshipLabel>
        <relationshipName>FC_Revenue_Shares</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processed_By_Batchable_On__c</fullName>
        <label>Processed By Batchable On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Purchase_Type__c</fullName>
        <label>Purchase Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RD_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RD Assignment</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>(FC) Revenue Shares</relationshipLabel>
        <relationshipName>FC_Revenue_Shares</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recent_Opp_Line_Item_Last_Modified_Date__c</fullName>
        <label>Recent Opp. Line Item Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Seg3_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seg3 Record</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>(FC) Revenue Shares</relationshipLabel>
        <relationshipName>FC_Revenue_Shares</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_2__c</fullName>
        <label>Segment 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>(FC) Revenue Share</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Revenue Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Revenue Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Revenue_Share_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Last_Run_On__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Revenue Share Settings</label>
</CustomObject>

src/objects/FC_Segment_2_Assignment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Allocation_Percentage__c</fullName>
        <label>Allocation %</label>
        <precision>18</precision>
        <scale>14</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Region_Assignment_ID__c</fullName>
        <label>Sales Region Assignment ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>(FC) Segment 2 Assignment</label>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geography_FIPS__c</fullName>
        <label>Geography FIPS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seg2__c</fullName>
        <label>Seg2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Bypass_Revenue_Share_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Bypass Revenue Share Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Most_Recent_OLI_Last_Modified_Date__c</fullName>
        <label>(FC) Most Recent OLI Last Modified Date</label>
        <summarizedField>OpportunityLineItem.LastModifiedDate</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Purchase_Type__c</fullName>
        <label>Purchase Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>One-time</fullName>
                </value>
                <value>
                    <fullName>Price Increase Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Marketing_Group</fullName>
        <active>true</active>
        <businessProcess>Marketing</businessProcess>
        <label>HW_Marketing Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Media</fullName>
        <active>true</active>
        <businessProcess>Media</businessProcess>
        <label>HW_Media</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>FC_Cancellation_Revenue_Formula__c</fullName>
        <formula>IF(ISPICKVAL(FC_Purchase_Type__c , &quot;Cancellation&quot;) &amp;&amp; ISPICKVAL(Billing_Frequency__c , &quot;One-Time&quot;), FC_Original_Sale_Price__c * -1,

IF(ISPICKVAL(FC_Purchase_Type__c , &quot;Cancellation&quot;) , TotalPrice, 

IF(ISPICKVAL(FC_Purchase_Type__c , &quot;Cancellation - Reversal&quot;), TotalPrice, 0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) Cancellation Revenue*</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_Effective_Date__c</fullName>
        <label>Eff. Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_End_Date__c</fullName>
        <label>(FC) End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Geography_Type__c</fullName>
        <formula>FC_Product_Geography_Seg3__r.Product_Geography__r.ProductGeographyType__r.GeographyType__r.Name</formula>
        <label>Geo Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Geography__c</fullName>
        <formula>FC_Product_Geography_Seg3__r.Product_Geography__r.Geography__r.Name</formula>
        <label>(FC) Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_New_Revenue_Formula__c</fullName>
        <formula>IF(ISPICKVAL(FC_Purchase_Type__c , &quot;New&quot;), 
    IF(FC_Annualize_New_Revenue__c, 
        FC_Annualized_Amount__c, TotalPrice), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) New Revenue*</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_Price_Increase_Decrease_Formula__c</fullName>
        <formula>IF(ISPICKVAL(FC_Purchase_Type__c , &quot;Renewal&quot;) || ISPICKVAL(FC_Purchase_Type__c , &quot;Price Change&quot;), FC_Sale_Price__c - FC_Original_Sale_Price__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) Price Increase/Decrease*</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_Product_Geography_Seg3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Metrostudy Product Geography Seg3</label>
        <referenceTo>FC_Metroclient_Product_Geography_Seg3__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Purchase_Type__c</fullName>
        <label>(FC) Purchase Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Renewal Upsell</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancellation - Reversal</fullName>
                </value>
                <value>
                    <fullName>Restructure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_RD_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) RD Assignment</label>
        <referenceTo>MetrostudySalesRegionAssignment__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Renewal_Revenue_Formula__c</fullName>
        <formula>IF(ISPICKVAL(FC_Purchase_Type__c, &quot;Renewal&quot;) || (ISPICKVAL(FC_Purchase_Type__c, &quot;Price Change&quot;) &amp;&amp; FC_Sale_Price__c != 0 &amp;&amp; FC_Opportunity_Renewal__c),
    IF(FC_Do_Not_Annualize__c,
        CASE(TEXT(Billing_Frequency__c), 
             &quot;Monthly&quot;, FC_Sale_Price__c / 12, 
             &quot;Quarterly&quot;, FC_Sale_Price__c / 4, 
             &quot;Semi-Annually&quot;, FC_Sale_Price__c / 2,
             FC_Sale_Price__c),
        FC_Sale_Price__c),
    IF(ISPICKVAL(FC_Purchase_Type__c, &quot;Renewal Upsell&quot;),
        FC_Original_Sale_Price__c,
        0)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) Renewal Revenue*</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_Seg2__c</fullName>
        <formula>FC_Product_Geography_Seg3__r.Product_Geography__r.Geography__r.Seg2__c</formula>
        <label>(FC) Seg2</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/FC_RevenueShareProcessorBatchable.cls
public without sharing class FC_RevenueShareProcessorBatchable implements Database.Batchable<sObject>,
        Database.Stateful {

    public DateTime lastRunOn;
    public DateTime startTime;

    public Boolean processObsoletes;

    public FC_RevenueShareProcessorBatchable(Boolean processObsoletes) {
        this.processObsoletes = processObsoletes;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        FC_Revenue_Share_Settings__c config = FC_Revenue_Share_Settings__c.getOrgDefaults();
        DateTime currentTime = DateTime.now();
        this.startTime = currentTime;
        this.lastRunOn = config.Last_Run_On__c;
        String soqlTemplate = 'select Id, FC_Cancellation_Revenue_Formula__c, FC_Effective_Date__c, ' +
                'FC_End_Date__c, FC_Geography__c, FC_Geography_Type__c, FC_New_Revenue_Formula__c, ' +
                'FC_Price_Increase_Decrease_Formula__c, FC_Product_Geography_Seg3__c, FC_Purchase_Type__c, ' +
                'FC_RD_Assignment__c, FC_Renewal_Revenue_Formula__c, FC_Seg2__c, OpportunityId, Opportunity.LastModifiedDate, ' +
                'Opportunity.FC_Most_Recent_OLI_Last_Modified_Date__c, TotalPrice ' +
                'from OpportunityLineItem where {0} and (not Opportunity.RecordType.DeveloperName in (\'\'Marketing_Group\'\', \'\'Media\'\')) ' +
                'and Opportunity.FC_Bypass_Revenue_Share_Calculation__c = false';

        String criteria = 'Opportunity.CreatedDate <= :currentTime';
        if (config.Last_Run_On__c != null) {
            criteria = '(Opportunity.CreatedDate > :lastRunOn and Opportunity.CreatedDate <= :currentTime)';
        }
        if (processObsoletes) {
            criteria = 'OpportunityId in (select Opportunity__c from FC_Revenue_Share__c where Obsolete__c = true)';
        }

        return Database.getQueryLocator(String.format(soqlTemplate, new String[]{
                criteria
        }));
    }

    public void execute(Database.BatchableContext context, List<OpportunityLineItem> scope) {
        Map<String, FC_Segment_2_Assignment__c> segment2AssignmentMap = FC_Segment_2_Assignment__c.getAll();

        Map<String, Id> segment2ToGeographyMap = new Map<String, Id>();
        for (MetroclientGeography__c geographyRecord : [
                select Id, Seg2__c
                from MetroclientGeography__c
                where Seg2__c != null
                and Seg2__c != '' and GeographyType__r.Name = 'Market' and (not Geography_FIPS__c like '%c%')
        ]) {
            if (String.isNotBlank(geographyRecord.Seg2__c)) {
                segment2ToGeographyMap.put(geographyRecord.Seg2__c, geographyRecord.Id);
            }
        }

        Map<String, Set<FC_Segment_2_Assignment__c>> stateToSegment2AssignmentsMap = new Map<String, Set<FC_Segment_2_Assignment__c>>();
        Map<String, Decimal> stateToSegment2TotalPercentAllocationMap = new Map<String, Decimal>();
        for (FC_Segment_2_Assignment__c segment2AssignmentRecord : segment2AssignmentMap.values()) {
            if (String.isNotBlank(segment2AssignmentRecord.State__c)) {

                Set<FC_Segment_2_Assignment__c> stateSegment2Assignments = stateToSegment2AssignmentsMap.get(segment2AssignmentRecord.State__c);
                if (stateSegment2Assignments == null) {
                    stateSegment2Assignments = new Set<FC_Segment_2_Assignment__c>();
                    stateToSegment2AssignmentsMap.put(segment2AssignmentRecord.State__c, stateSegment2Assignments);
                }
                stateSegment2Assignments.add(segment2AssignmentRecord);

                Decimal stateTotalPercentAllocation = stateToSegment2TotalPercentAllocationMap.get(segment2AssignmentRecord.State__c);
                if (stateTotalPercentAllocation == null) {
                    stateTotalPercentAllocation = 0;
                }
                stateToSegment2TotalPercentAllocationMap.put(segment2AssignmentRecord.State__c,
                        stateTotalPercentAllocation + segment2AssignmentRecord.Allocation_Percentage__c);

            }
        }

        FC_Revenue_Share__c[] recordsToInsert = new List<FC_Revenue_Share__c>();
        if (scope != null && !scope.isEmpty()) {
            for (OpportunityLineItem opportunityLineItemRecord : scope) {
                Decimal cancellationRevenue = opportunityLineItemRecord.FC_Cancellation_Revenue_Formula__c != null ? opportunityLineItemRecord.FC_Cancellation_Revenue_Formula__c : 0;
                Decimal deltaRevenue = opportunityLineItemRecord.FC_Price_Increase_Decrease_Formula__c != null ? opportunityLineItemRecord.FC_Price_Increase_Decrease_Formula__c : 0;
                Decimal newRevenue = opportunityLineItemRecord.FC_New_Revenue_Formula__c != null ? opportunityLineItemRecord.FC_New_Revenue_Formula__c : 0;
                Decimal renewalRevenue = opportunityLineItemRecord.FC_Renewal_Revenue_Formula__c != null ? opportunityLineItemRecord.FC_Renewal_Revenue_Formula__c : 0;
                Decimal totalRevenue = opportunityLineItemRecord.TotalPrice != null ? opportunityLineItemRecord.TotalPrice : 0;
                if (opportunityLineItemRecord.FC_Geography_Type__c == 'State' &&
                        stateToSegment2AssignmentsMap.containsKey(opportunityLineItemRecord.FC_Geography__c) &&
                        stateToSegment2TotalPercentAllocationMap.containsKey(opportunityLineItemRecord.FC_Geography__c) &&
                        stateToSegment2TotalPercentAllocationMap.get(opportunityLineItemRecord.FC_Geography__c) != 0) {
                    for (FC_Segment_2_Assignment__c segment2AssignmentRecord : stateToSegment2AssignmentsMap.get(opportunityLineItemRecord.FC_Geography__c)) {
                        Decimal allocationPercentage = segment2AssignmentRecord.Allocation_Percentage__c /
                                stateToSegment2TotalPercentAllocationMap.get(opportunityLineItemRecord.FC_Geography__c);
                        recordsToInsert.add(new FC_Revenue_Share__c(
                                Allocated_Cancellation_Revenue__c = cancellationRevenue * allocationPercentage,
                                Allocated_Delta_Revenue__c = deltaRevenue * allocationPercentage,
                                Allocated_Geography__c = segment2ToGeographyMap.get(segment2AssignmentRecord.Name),
                                Allocated_New_Revenue__c = newRevenue * allocationPercentage,
                                Allocated_Renewal_Revenue__c = renewalRevenue * allocationPercentage,
                                Allocated_Total_Revenue__c = totalRevenue * allocationPercentage,
                                Allocation_Percentage__c = allocationPercentage * 100,
                                End_Date__c = opportunityLineItemRecord.FC_End_Date__c,
                                Opportunity__c = opportunityLineItemRecord.OpportunityId,
                                Opportunity_Last_Modified_Date__c = opportunityLineItemRecord.Opportunity.LastModifiedDate,
                                Opportunity_Line_Item_ID__c = opportunityLineItemRecord.Id,
                                Processed_By_Batchable_On__c = this.startTime,
                                Purchase_Type__c = opportunityLineItemRecord.FC_Purchase_Type__c,
                                RD_Assignment__c = segment2AssignmentRecord.Sales_Region_Assignment_ID__c,
                                Recent_Opp_Line_Item_Last_Modified_Date__c = opportunityLineItemRecord.Opportunity.FC_Most_Recent_OLI_Last_Modified_Date__c,
                                Seg3_Record__c = opportunityLineItemRecord.FC_Product_Geography_Seg3__c,
                                Segment_2__c = segment2AssignmentRecord.Name,
                                Start_Date__c = opportunityLineItemRecord.FC_Effective_Date__c));
                    }
                } else if (opportunityLineItemRecord.FC_Geography_Type__c == 'Country') {
                    for (FC_Segment_2_Assignment__c segment2AssignmentRecord : segment2AssignmentMap.values()) {
                        Decimal allocationPercentage = segment2AssignmentRecord.Allocation_Percentage__c / Decimal.valueOf(100);
                        recordsToInsert.add(new FC_Revenue_Share__c(
                                Allocated_Cancellation_Revenue__c = cancellationRevenue * allocationPercentage,
                                Allocated_Delta_Revenue__c = deltaRevenue * allocationPercentage,
                                Allocated_Geography__c = segment2ToGeographyMap.get(segment2AssignmentRecord.Name),
                                Allocated_New_Revenue__c = newRevenue * allocationPercentage,
                                Allocated_Renewal_Revenue__c = renewalRevenue * allocationPercentage,
                                Allocated_Total_Revenue__c = totalRevenue * allocationPercentage,
                                Allocation_Percentage__c = allocationPercentage * 100,
                                End_Date__c = opportunityLineItemRecord.FC_End_Date__c,
                                Opportunity__c = opportunityLineItemRecord.OpportunityId,
                                Opportunity_Last_Modified_Date__c = opportunityLineItemRecord.Opportunity.LastModifiedDate,
                                Opportunity_Line_Item_ID__c = opportunityLineItemRecord.Id,
                                Processed_By_Batchable_On__c = this.startTime,
                                Purchase_Type__c = opportunityLineItemRecord.FC_Purchase_Type__c,
                                RD_Assignment__c = segment2AssignmentRecord.Sales_Region_Assignment_ID__c,
                                Recent_Opp_Line_Item_Last_Modified_Date__c = opportunityLineItemRecord.Opportunity.FC_Most_Recent_OLI_Last_Modified_Date__c,
                                Seg3_Record__c = opportunityLineItemRecord.FC_Product_Geography_Seg3__c,
                                Segment_2__c = segment2AssignmentRecord.Name,
                                Start_Date__c = opportunityLineItemRecord.FC_Effective_Date__c));
                    }
                } else {
                    recordsToInsert.add(new FC_Revenue_Share__c(
                            Allocated_Cancellation_Revenue__c = cancellationRevenue,
                            Allocated_Delta_Revenue__c = deltaRevenue,
                            Allocated_Geography__c = segment2ToGeographyMap.get(opportunityLineItemRecord.FC_Seg2__c),
                            Allocated_New_Revenue__c = newRevenue,
                            Allocated_Renewal_Revenue__c = renewalRevenue,
                            Allocated_Total_Revenue__c = totalRevenue,
                            Allocation_Percentage__c = 100,
                            End_Date__c = opportunityLineItemRecord.FC_End_Date__c,
                            Opportunity__c = opportunityLineItemRecord.OpportunityId,
                            Opportunity_Last_Modified_Date__c = opportunityLineItemRecord.Opportunity.LastModifiedDate,
                            Opportunity_Line_Item_ID__c = opportunityLineItemRecord.Id,
                            Processed_By_Batchable_On__c = this.startTime,
                            Purchase_Type__c = opportunityLineItemRecord.FC_Purchase_Type__c,
                            RD_Assignment__c = opportunityLineItemRecord.FC_RD_Assignment__c,
                            Recent_Opp_Line_Item_Last_Modified_Date__c = opportunityLineItemRecord.Opportunity.FC_Most_Recent_OLI_Last_Modified_Date__c,
                            Seg3_Record__c = opportunityLineItemRecord.FC_Product_Geography_Seg3__c,
                            Segment_2__c = opportunityLineItemRecord.FC_Seg2__c,
                            Start_Date__c = opportunityLineItemRecord.FC_Effective_Date__c));
                }
            }
        }

        if (!recordsToInsert.isEmpty()) {
            insert recordsToInsert;
        }
    }

    public void finish(Database.BatchableContext context) {
        FC_Revenue_Share_Settings__c config = FC_Revenue_Share_Settings__c.getOrgDefaults();
        config.Last_Run_On__c = this.startTime;
        upsert config;
        if (!processObsoletes) {
            FC_RevenueShareProcessorBatchable processorBatchable = new FC_RevenueShareProcessorBatchable(true);
            Database.executeBatch(processorBatchable);
        } else {
            FC_RevenueShareCleanerBatchable cleanerBatchable = new FC_RevenueShareCleanerBatchable(this.startTime);
            Database.executeBatch(cleanerBatchable);
        }
    }

}