src/objects/FC_Revenue_Share__c.object
<CustomObject>
    <fields>
        <fullName>Obsolete__c</fullName>
        <formula>!(Opportunity__r.LastModifiedDate == Opportunity_Last_Modified_Date__c &amp;&amp;  Opportunity__r.FC_Most_Recent_OLI_Last_Modified_Date__c == Recent_Opp_Line_Item_Last_Modified_Date__c)</formula>
        <label>Obsolete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>(FC) Revenue Shares</relationshipLabel>
        <relationshipName>FC_Revenue_Shares</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processed_By_Batchable_On__c</fullName>
        <label>Processed By Batchable On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Revenue Share</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>(FC) Revenue Share Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>(FC) Revenue Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FC_Revenue_Share_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Last_Run_On__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <label>(FC) Revenue Share Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Bypass_Revenue_Share_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Bypass Revenue Share Calculation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FC_RevenueShareCleanerBatchable.cls
public without sharing class FC_RevenueShareCleanerBatchable implements Database.Batchable<sObject> {

    public DateTime latestBatchableProcessedOn;

    public FC_RevenueShareCleanerBatchable(DateTime latestBatchableProcessedOn) {
        this.latestBatchableProcessedOn = latestBatchableProcessedOn;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        String soql = 'select Id from FC_Revenue_Share__c where Opportunity__r.FC_Bypass_Revenue_Share_Calculation__c = false ';
        DateTime latestBatchableProcessedOn = this.latestBatchableProcessedOn;
        if (latestBatchableProcessedOn != null) {
            soql += 'and Obsolete__c = true and Processed_By_Batchable_On__c < :latestBatchableProcessedOn';
        }
        return Database.getQueryLocator(soql);
    }

    public void execute(Database.BatchableContext context, List<FC_Revenue_Share__c> scope) {
        if (scope != null && !scope.isEmpty()) {
            delete scope;
        }
    }

    public void finish(Database.BatchableContext context) {
        if (this.latestBatchableProcessedOn == null) {
            FC_Revenue_Share_Settings__c config = FC_Revenue_Share_Settings__c.getOrgDefaults();
            config.Last_Run_On__c = null;
            upsert config;
        }
    }

}