src/objects/fcf__Exception_Log__c.object
<CustomObject>
    <description>The Exception Log object stores exception data caught in real-time by the ExceptionLogUtil class.</description>
    <fields>
        <fullName>fcf__Message__c</fullName>
        <description>The error message that displays for the user.</description>
        <inlineHelpText>The error message that displays for the user.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fcf__Related_To_ID__c</fullName>
        <description>This ID can be used to relate this exception log to a specific object or job ID.</description>
        <externalId>true</externalId>
        <label>Related To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fcf__Type__c</fullName>
        <description>The type of exception, such as DmlException, ListException, MathException, and so on.</description>
        <inlineHelpText>The type of exception, such as DmlException, ListException, MathException, and so on.</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_AmendmentJobStatusController.cls
public without sharing class FC_AmendmentJobStatusController {

    public Id amendmentJobId { get; set; }

    public AsyncApexJob job {

        get {
            if (job == null && amendmentJobId != null) {
                for (AsyncApexJob asyncApexJobRecord : [
                        select Id, Status, ExtendedStatus
                        from AsyncApexJob
                        where Id = :amendmentJobId
                        limit 1
                ]) {
                    job = asyncApexJobRecord;
                }
            }
            return job;
        }

        private set;

    }

    public String jobStatus {

        get {
            return job != null ? (String.isBlank(jobExtendedStatus) ? job.Status : 'Error') : '';
        }

        private set;

    }

    public String jobExtendedStatus {

        get {
            jobExtendedStatus = '';
            if (job != null) {
                jobExtendedStatus = job.ExtendedStatus;
                if (String.isBlank(jobExtendedStatus)) {
                    for (fcf__Exception_Log__c exceptionLogRecord : [
                            select Id, fcf__Type__c, fcf__Message__c
                            from fcf__Exception_Log__c
                            where fcf__Related_To_ID__c = :job.Id
                            limit 1
                    ]) {
                        jobExtendedStatus = String.format('{0}: {1}', new String[]{
                                exceptionLogRecord.fcf__Type__c,
                                exceptionLogRecord.fcf__Message__c
                        });
                    }
                }
            }
            return jobExtendedStatus;
        }

        private set;

    }

    public Boolean isJobRunning {

        get {
            return job != null && (new Set<String>{
                    'Queued', 'Processing', 'Preparing', 'Holding'
            }).contains(job.Status);
        }

        private set;

    }

    public FC_AmendmentJobStatusController() {
    }

    public void refresh() {
        this.job = null;
    }

}