src/objects/GoogleIntegrationHelperSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GoogleIntegrationHelperSettings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Last_Updated_Date_Sales__c</fullName>
        <label>Last Updated Date (Sales)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sold_Out_Date__c</fullName>
        <label>Sold Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Snapshot__c.object
<CustomObject>
    <description>MG_Project Snapshot</description>
    <fields>
        <fullName>Last_Updated_Date_Sales__c</fullName>
        <label>Last Updated Date (Sales)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Snapshots</relationshipLabel>
        <relationshipName>Project_Snapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sold_Out_Date__c</fullName>
        <label>Sold Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Snapshot</label>
    <nameField>
        <displayFormat>PS{0} {MM}-{DD}-{YYYY}</displayFormat>
        <label>Project Snapshot Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestMaintClasses.cls
@isTest
private class TestMaintClasses {
	@isTest static void TestBatchDeleteSubscriberActivity() {
		BatchDeleteSubscriberActivity theBatch = new BatchDeleteSubscriberActivity();
		Database.executeBatch(theBatch);
	}

	@isTest static void TestBatchMaintProjectFields() {
		BatchMaintProjectFields theBatch2 = new BatchMaintProjectFields();
		Database.executeBatch(theBatch2);
	}

	@isTest static void TestBasicGoogleStuff() {
		GoogleIntegrationHelper.BuildSignedUrl('foo');
		GoogleIntegrationHelperSetting__c crypto = new GoogleIntegrationHelperSetting__c(Name='CryptoKey', Value__c = 'bar');
		insert crypto;
		GoogleIntegrationHelper.BuildSignedUrl('foo');
	}

	@isTest static void TestScheduleBatchMaint() {
		System.schedule('ScheduleApexClassTest',
                        '0 0 0 15 3 ? 2022', 
                        new BatchMaintProjectFields());
	}

	@isTest static void TestScheduledBatchDeleteSubscriberActivity_scheduler() {
		System.schedule('ScheduleApexClassTest',
                        '0 0 0 15 3 ? 2022', 
                        new BatchDeleteSubscriberActivity_scheduler());
	}

	@isTest static void TestMaintProjectFields() {
		List<Project__c> projectsToInsert = new List<Project__c>();
		projectsToInsert.add(new Project__c(Name = 'Test 1', Total_Units_Planned__c = 20, Total_Units_Sold__c = 10, Sold_Out_Date__c = System.today()));
		projectsToInsert.add(new Project__c(Name = 'Test 2', Total_Units_Planned__c = 40, Total_Units_Sold__c = 0, Last_Updated_Date_Sales__c = System.today()));
		projectsToInsert.add(new Project__c(Name = 'Test 3', Total_Units_Planned__c = 60, Total_Units_Sold__c = 20));

		insert projectsToInsert;

		List<Project_Snapshot__c> snapsToInsert = new List<Project_Snapshot__c>();
		for (Project__c p : projectsToInsert) {
			snapsToInsert.add(new Project_Snapshot__c(Project__c = p.Id, Total_Units_Planned__c = p.Total_Units_Planned__c, Total_Units_Sold__c = p.Total_Units_Sold__c + 1));
			snapsToInsert.add(new Project_Snapshot__c(Project__c = p.Id, Total_Units_Planned__c = p.Total_Units_Planned__c, Total_Units_Sold__c = p.Total_Units_Sold__c + 2));
		}
		insert snapsToInsert;

		MaintProjectFields.updateThreeMonthSalesRate(projectsToInsert);
	}
}