src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>How_may_we_help_you__c</fullName>
        <label>How may we help you?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Become a Member</fullName>
                </value>
                <value>
                    <fullName>Purchase Information/Reports</fullName>
                </value>
                <value>
                    <fullName>Consulting/Market Study</fullName>
                </value>
                <value>
                    <fullName>Training Request</fullName>
                </value>
                <value>
                    <fullName>Media Request</fullName>
                </value>
                <value>
                    <fullName>Customer Support/Training Request</fullName>
                </value>
                <value>
                    <fullName>Billing Questions</fullName>
                </value>
                <value>
                    <fullName>General Information</fullName>
                </value>
                <value>
                    <fullName>Join eList</fullName>
                </value>
                <value>
                    <fullName>Download White Paper</fullName>
                </value>
                <value>
                    <fullName>Speakers Bureau Information</fullName>
                </value>
                <value>
                    <fullName>Contact a Local Market Expert</fullName>
                </value>
                <value>
                    <fullName>Technical Support</fullName>
                </value>
                <value>
                    <fullName>Have a Sales Representative Contact Me</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Key Influencer</fullName>
                </value>
                <value>
                    <fullName>Purchaser</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Purchasing Agent</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipName>MetroclientGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <fields>
        <fullName>GeographyTypeId__c</fullName>
        <label>Geography Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metrostudy_ZIP_Code__c.object
<CustomObject>
    <fields>
        <fullName>Metrostudy_Market__c</fullName>
        <label>Metrostudy Market</label>
        <referenceTo>MetrostudyMarket__c</referenceTo>
        <relationshipLabel>Metrostudy ZIP Codes</relationshipLabel>
        <relationshipName>Metrostudy_ZIP_Codes1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Metrostudy ZIP Code</label>
    <nameField>
        <label>Metrostudy ZIP Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy ZIP Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MetrostudyMarket__c.object
<CustomObject>
    <description>Metrostudy Survey Markets</description>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metroclient Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Markets</relationshipLabel>
        <relationshipName>MetrostudyMarkets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegion__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Available sales regions to assign to geographies</description>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_DNU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Emp DNU</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MetroStudyLeadAssignmentTH_test.cls
/*******************************************************************************************************************
** Module Name   : MetroStudyLeadAssignmentTH_test
** Description   : Test class for MetroStudyLeadAssignmentTriggerHandler
** Throws        : NA
** Calls         : NA
** 
** Organization  : Rainmaker
**
** Revision History:-
** Version             Date            Author           Description of Action
** 1.0                 06/28/16        Rainmaker             
******************************************************************************************************************/
@isTest
private class MetroStudyLeadAssignmentTH_test{
    @testSetup static void testData() {
        MetrostudySalesRegion__c msr=new MetrostudySalesRegion__c(Abbreviation__c='test',User_DNU__c=userinfo.getUserId());
        insert msr;
        system.assert(msr.id != null);
        
        MetrostudySalesRegionAssignment__c msra=new MetrostudySalesRegionAssignment__c(SalesRegion__c=msr.id, Role__c = 'DBD', User__c=UserInfo.getuserId());
        insert msra;
        system.assert(msra.id != null);
        
        MetrostudySalesRegionAssignment__c msra2=new MetrostudySalesRegionAssignment__c(SalesRegion__c=msr.id, Role__c = 'RD', User__c=UserInfo.getuserId());
        insert msra2;
        system.assert(msra2.id != null);
        
        MetroclientGeographyType__c MGType = new MetroclientGeographyType__c(GeographyTypeId__c=12345);
        Insert MGType;
        system.assert(MGType.Id != null);
        
        MetroclientGeography__c MGObj = new MetroclientGeography__c(Name='Test Geo', SalesRegion__c=msr.Id,GeographyType__c=MGType.Id);
        Insert MGObj;
        System.assert(MGObj.Id != null);
        
        MetrostudyMarket__c MMObj = new MetrostudyMarket__c(Name='Test Market', Geography__c=MGObj.Id);
        Insert MMObj;
        System.assert(MMObj.id != null);
        
        Metrostudy_ZIP_Code__c ZCObj = new Metrostudy_ZIP_Code__c(Name='12345', Metrostudy_Market__c=MMObj.id);
        Insert ZCObj;
        System.assert(ZCObj.Id != null);
        
        Lead L = new Lead(Firstname='Test', LastName='Lead', Email='Test@lead.com', Company='Test',PostalCode='12345',
                          How_may_we_help_you__c='Training Request', Industry = 'Accounting', LeadSource = 'MS_BriefingAttendee');
        Insert L;
        System.assert(L.Id != null);
    }
    
    static testMethod void testMethod1(){
        Lead L = [select Id, FirstName FROM Lead LIMIT 1];
        L.FirstName = 'Test1';
        update L;
        delete L;
        
        Lead L2 = new Lead(Firstname='Test2', LastName='Lead2', Email='Test@lead.com', Company='Test',PostalCode='12345',
                          How_may_we_help_you__c='Download White Paper', Industry = 'Accounting', LeadSource = 'MS_BriefingAttendee');
        Insert L2;
        System.assert(L2.Id != null);
        
        L2.Firstname='Test3';
        update L2;
        delete L2;
    }
}