src/objects/MetrostudySalesRegion__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Available sales regions to assign to geographies</description>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of included geographies</inlineHelpText>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Sales Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FC_TestRegionalDirectorListController.cls
@isTest
private class FC_TestRegionalDirectorListController {

    @isTest
    private static void testRegionalDirectorList() {
        Test.startTest();
        FC_RegionalDirectorListController controller = new FC_RegionalDirectorListController();
        String[] testResult = controller.regionalDirectorNames;
        System.assertEquals(1, testResult.size());
        System.assertEquals('Test Sales', testResult[0]);
        Test.stopTest();
    }

    @testSetup
    private static void setup() {
        Profile testSalesProfile = [select Id from Profile where Name = 'Media - Sales Rep' limit 1];

        User testSalesUser = new User(FirstName = 'Test', LastName = 'Sales', ProfileId = testSalesProfile.Id,
                Username = FC_UuidUtil.uuidV4() + '@example.com', Email = FC_UuidUtil.uuidV4() + '@example.com',
                Alias = FC_UuidUtil.uuidV4().left(8), CommunityNickname = FC_UuidUtil.uuidV4(),
                TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US');
        insert testSalesUser;

        MetrostudySalesRegion__c testSalesRegion = new MetrostudySalesRegion__c(Abbreviation__c = 'TEST',
                Description__c = 'Test Sales Region', Name = 'Test Sales Region');
        insert testSalesRegion;

        MetrostudySalesRegionAssignment__c testSalesRegionAssignment = new MetrostudySalesRegionAssignment__c(
                Name = 'Test Sales Region Assignment', Role__c = 'RD', SalesRegion__c = testSalesRegion.Id,
                User__c = testSalesUser.Id);
        insert testSalesRegionAssignment;
    }

}