src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientSubscriptionAmendmentLog__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Remove Product Ammendment log. Tracks the removal of products from a subscription.</description>
    <label>Metrostudy Subscription Amendment Log</label>
    <nameField>
        <label>Amendment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Subscription Amendment Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MetroclientApplyRemovalAmendmentsTest.cls
@isTest
public class MetroclientApplyRemovalAmendmentsTest{
 @isTest static void MetroclientApplyRemovalAmendmentsTest()   
    {
       test.startTest(); 
        
        Account acc = TestFactoryMetroclient.makeAccount('Account 1');
        Account acc2 = TestFactoryMetroclient.makeAccount('Account 2');
          
        TestFactoryMetroclient.ProductGeographyFactory();        
        MetroclientProductGeography__c  prodGeo=  [SELECT Id FROM MetroclientProductGeography__c  where name = 'TestProdGeo1' Limit 1 ];
        MetroclientProductGeography__c  prodGeo2=  [SELECT Id FROM MetroclientProductGeography__c  where name = 'TestProdGeo2' Limit 1 ];
        MetroclientProductGeography__c  prodGeo3=  [SELECT Id FROM MetroclientProductGeography__c  where name = 'TestProdGeo3' Limit 1 ];
        
        Zuora__Subscription__c testSub =  TestFactoryMetroclient.makeSubscription(acc, 'Test Subscription A',System.Today(), System.Today(),'Active' );
        Zuora__SubscriptionProductCharge__c testSubProdCharge =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo,'Test Charge A',System.Today(), System.Today(),'Reocurring');
        Zuora__SubscriptionProductCharge__c testSubProdChargeB =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo, 'Test Charge b',System.Today(), System.Today(),'OneTime'); //will flag different Record Id and different Account
        Zuora__SubscriptionProductCharge__c testSubProdChargeC =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo2, 'Test Charge c',System.Today(), System.Today(),'Reocurring'); //will flag new provisioning
        Zuora__SubscriptionProductCharge__c testSubProdChargeD =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo, 'Test Charge d',System.Today(), System.Today(),'Reocurring'); 
        Zuora__SubscriptionProductCharge__c testSubProdChargeE =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo, 'Test Charge e',System.Today(), System.Today(),'Reocurring'); 
       
        Zuora__Subscription__c testSubB =  TestFactoryMetroclient.makeSubscription(acc2, 'Test Subscription B',System.Today(), System.Today(),'Active' );
        Zuora__SubscriptionProductCharge__c testSubProdChargeB1 =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSubB,prodGeo,'Test Charge B-1',System.Today(), System.Today(),'Reocurring');
        
        MetroclientAccountProductGeography__c testAccPG = TestFactoryMetroclient.makeAccountProductGeography(acc,prodGeo, testSub, testSubProdCharge, false, false );
        MetroclientAccountProductGeography__c testAccPG2 = TestFactoryMetroclient.makeAccountProductGeography(acc2,prodGeo2, testSub, testSubProdChargeB, true, false );
        MetroclientAccountProductGeography__c testAccPG4 = TestFactoryMetroclient.makeAccountProductGeographySameDates(acc,prodGeo, testSub, testSubProdChargeD, false, false );
        MetroclientAccountProductGeography__c testAccPG5 = TestFactoryMetroclient.makeAccountProductGeographySameDates(acc2,prodGeo2, testSub, testSubProdChargeE, false, false );
        MetroclientAccountProductGeography__c testAccPG6 = TestFactoryMetroclient.makeAccountProductGeography(acc2,prodGeo2, testSub, testSubProdChargeB, false, false );
        
        
        MetroclientSubscriptionAmendmentLog__c testAmdLog = TestFactoryMetroclient.makeAmendmentLog('MS-A0001', testSub, testSubProdCharge, 'RemoveProduct', System.Today());
        MetroclientSubscriptionAmendmentLog__c testAmdLog2 = TestFactoryMetroclient.makeAmendmentLog('MS-A0002', testSub, testSubProdChargeB, 'RemoveProduct', System.Today());
       
        //Zuora__CustomerAccount__c testBillAcc= TestFactoryMetroclient.makeBillingAccount(acc);
        
        
      
       SchedulableContext sc = null;
       MetroclientApplyRemovalAmendments b = new MetroclientApplyRemovalAmendments ();
       b.execute(sc);              
       test.stopTest(); 
    }   
}