src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MetroclientAccountProvisionBatchDeltTest.cls
@isTest(SeeAllData=true)
public class MetroclientAccountProvisionBatchDeltTest{
 @isTest static void MetroclientAccountProvisionBatchDeltTest()   
    {
    	GoogleIntegrationHelper.disableAsync = true;
        test.startTest(); 
        Account acc = TestFactoryMetroclient.makeAccount('Account 1');
        TestFactoryMetroclient.ProductGeographyFactory();        
        MetroclientProductGeography__c  prodGeo=  [SELECT Id FROM MetroclientProductGeography__c  where name = 'TestProdGeo1' Limit 1 ];
         
        Zuora__Subscription__c testSub =  TestFactoryMetroclient.makeSubscription(acc, 'Test Subscription 9',System.Today(), System.Today(),'Active' );
        Zuora__SubscriptionProductCharge__c testSubProdCharge =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo,'Test Charge 1',System.Today(), System.Today(),'Reocurring');
        Zuora__SubscriptionProductCharge__c testSubProdChargeB =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo, 'Test Charge 2',System.Today(), System.Today(),'OneTime'); 
        Zuora__SubscriptionProductCharge__c testSubProdChargeC =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo, 'Test Charge 3',System.Today(), System.Today(),'Reocurring'); 
        Zuora__SubscriptionProductCharge__c testSubProdChargeD =  TestFactoryMetroclient.makeSubscriptionProductCharge(testSub,prodGeo, 'Test Charge 4',System.Today(), System.Today(),'Reocurring'); 
     
        MetroclientAccountProductGeography__c testAccPG = TestFactoryMetroclient.makeAccountProductGeography(acc,prodGeo, testSub, testSubProdCharge, false, false );
        MetroclientAccountProductGeography__c testAccPG2 = TestFactoryMetroclient.makeAccountProductGeography(acc,prodGeo, testSub, testSubProdChargeB, true, false );
        MetroclientAccountProductGeography__c testAccPG3 = TestFactoryMetroclient.makeAccountProductGeography(acc,prodGeo, testSub, testSubProdChargeC, true, false );
        MetroclientAccountProductGeography__c testAccPG4 = TestFactoryMetroclient.makeAccountProductGeographySameDates(acc,prodGeo, testSub, testSubProdChargeD, false, false );
         
        SchedulableContext sc = null;
        MetroclientAccountProvisionBatchDelete b = new MetroclientAccountProvisionBatchDelete();
        b.execute(sc);              
        test.stopTest(); 
    }   
}