src/objects/MetrostudySalesRegion__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Available sales regions to assign to geographies</description>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of included geographies</inlineHelpText>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Sales Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRegion__c</fullName>
        <label>Sales Region</label>
        <referenceTo>MetrostudySalesRegion__c</referenceTo>
        <relationshipLabel>Sales Region Assignments</relationshipLabel>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FC_TestMetrostudySalesRegionAssignCache.cls
@isTest
private class FC_TestMetrostudySalesRegionAssignCache {

    @isTest
    private static void testClearCache() {

        MetrostudySalesRegionAssignment__c testSalesRegionAssignment = [
                select Id
                from MetrostudySalesRegionAssignment__c
                where Name = 'Test Sales Region Assignment'
                limit 1
        ];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<Id, MetrostudySalesRegionAssignment__c> results = FC_MetrostudySalesRegionAssignmentCache.findByIds(
                new Set<Id>{
                        testSalesRegionAssignment.Id
                });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        results = FC_MetrostudySalesRegionAssignmentCache.findByIds(new Set<Id>{
                testSalesRegionAssignment.Id
        });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        FC_MetrostudySalesRegionAssignmentCache.clearCache();
        results = FC_MetrostudySalesRegionAssignmentCache.findByIds(new Set<Id>{
                testSalesRegionAssignment.Id
        });
        System.assertEquals(1, results.size());
        System.assertEquals(2, Limits.getQueries());
        Test.stopTest();

    }

    @isTest
    private static void testFindByIds() {

        MetrostudySalesRegionAssignment__c testSalesRegionAssignment = [
                select Id
                from MetrostudySalesRegionAssignment__c
                where Name = 'Test Sales Region Assignment'
                limit 1
        ];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<Id, MetrostudySalesRegionAssignment__c> results = FC_MetrostudySalesRegionAssignmentCache.findByIds(
                new Set<Id>{
                        testSalesRegionAssignment.Id
                });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        results = FC_MetrostudySalesRegionAssignmentCache.findByIds(new Set<Id>{
                testSalesRegionAssignment.Id
        });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        Test.stopTest();

    }

    @isTest
    private static void testFindBySalesRegionIds() {

        MetrostudySalesRegionAssignment__c testSalesRegionAssignment = [
                select Id, SalesRegion__c
                from MetrostudySalesRegionAssignment__c
                where Name = 'Test Sales Region Assignment'
                limit 1
        ];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<Id, Set<MetrostudySalesRegionAssignment__c>> results = FC_MetrostudySalesRegionAssignmentCache.findBySalesRegionIds(
                new Set<Id>{
                        testSalesRegionAssignment.SalesRegion__c
                });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        results = FC_MetrostudySalesRegionAssignmentCache.findBySalesRegionIds(new Set<Id>{
                testSalesRegionAssignment.SalesRegion__c
        });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        Test.stopTest();

    }

    @testSetup
    private static void setup() {

        MetrostudySalesRegion__c testSalesRegion = new MetrostudySalesRegion__c(Abbreviation__c = 'TEST',
                Description__c = 'Test Sales Region', Name = 'Test Sales Region');
        insert testSalesRegion;

        MetrostudySalesRegionAssignment__c testSalesRegionAssignment = new MetrostudySalesRegionAssignment__c(
                Name = 'Test Sales Region Assignment', Role__c = 'Test', SalesRegion__c = testSalesRegion.Id,
                User__c = UserInfo.getUserId());
        insert testSalesRegionAssignment;

    }

}