src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <description>Zuora Subscription Charge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Charge Number (Zuora)</inlineHelpText>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Subscription is no longer active and product cannot be accessed. Record exists for reference only.</description>
        <inlineHelpText>When checked, product cannot be accessed. Record exists for reference only.</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date the subscription ends  (SubscriptionEndDate).  This value is blank (NULL) for evergreen subscriptions.</description>
        <inlineHelpText>The date access to the product expires and can no longer be accessed.  This field is blank when a subscription is evergreen.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manual override.  When this box is checked, the job that updates this object based on the subscriptions from Zuora will ignore this record and not update it.  To be used when the Start Date, End Date or Deleted status need to be Manually overridden.
Check box when a manual override is required. Start Date, End Date, and/or Delete status has been manually overridden and should not be updated based on the subscription dates/status in Zuora.</description>
        <inlineHelpText>When checked, a manual override for this record is in effect.</inlineHelpText>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date that the subscription starts (SubscriptionStartDate)</description>
        <inlineHelpText>The date that the access to the product starts.  This date is determined by the subscription or amendment start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubscriptionName__c</fullName>
        <description>Zuora Subscription Name</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Name (Zuora)</inlineHelpText>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geographies</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geography_FIPS__c</fullName>
        <label>Geography FIPS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Geography</label>
    <nameField>
        <label>Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Types of geographies (County,State,etc)</description>
    <fields>
        <fullName>GeographyTypeId__c</fullName>
        <label>Geography Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Metrostudy Geography Type</label>
    <nameField>
        <label>Geography Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProduct__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Metrostudy Products</description>
    <fields>
        <fullName>ProductAbbreviation__c</fullName>
        <label>Product Abbreviation</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SubscriptionOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box when product can only be delivered as a subscription and a One-Time sale should still be provisioned as a subscription.</description>
        <inlineHelpText>Product is delivered as a subscription and a One-Time sale must be provisioned as a subscription.  When this box is unchecked, a One-Time sale of the product is not provisioned.</inlineHelpText>
        <label>Subscription Only?</label>
        <type>Checkbox</type>
    </fields>
    <label>Metrostudy Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if the product-geography is currently available for sale.</description>
        <inlineHelpText>Indicates if the product-geography is currently available for sale. Inactive product geographies will not be included in the product selector&apos;s tiered selections (when applicable).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography</label>
        <referenceTo>MetroclientGeography__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductGeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography Type</label>
        <referenceTo>MetroclientProductGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>GeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geography Type</label>
        <referenceTo>MetroclientGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientSubscriptionAmendmentLog__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Remove Product Ammendment log. Tracks the removal of products from a subscription.</description>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubscriptionName__c</fullName>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Subscription Amendment Log</label>
    <nameField>
        <label>Amendment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Subscription Amendment Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <description>The date when the (segmented) charge ends (or ended).</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveStartDate__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFactoryMetroclient.cls
@isTest
public class TestFactoryMetroclient {

  
  public static Account makeAccount(string aName) {

    Account testAcc = new Account();
    testAcc.Name = aName;
    testAcc.BillingCity = 'Houston';
    testAcc.BillingState = 'TX';
    testAcc.BillingPostalCode = '12345';
    testAcc.ShippingStreet ='123 Main St.';
    testAcc.ShippingCity = 'Houston';
    testAcc.ShippingState = 'TX';  
    testAcc.ShippingPostalCode='77002';
    testAcc.ShippingCountry ='United States';
    insert testAcc;
    return testAcc;
  }
  
  public static MetroclientGeographyType__c makeGeographyType(string sName, Decimal sId) {
    MetroclientGeographyType__c  testGeoType = new MetroclientGeographyType__c();
    testGeoType.Name = sName;
    testGeoType.GeographyTypeId__c= sId;  
    insert testGeoType ;
    return testGeoType ;    
  }
  public static MetroclientGeography__c makeGeography(MetroclientGeographyType__c geoType, string GeoName, string GeoFIPS) {

    MetroclientGeography__c testGeo = new MetroclientGeography__c();
    testGeo.Name = GeoName;
    testGeo.Geography_FIPS__c= GeoFIPS;  
    testGeo.GeographyType__c  =geoType.Id;
    insert testGeo;
    return testGeo;    
  }
  
  
  public static MetroclientProduct__c makeProduct(string pName, boolean pSubscrpitionOnly) {

    MetroclientProduct__c testProd = new MetroclientProduct__c();
    testProd.Name = pName;
    if(pName.length()>20)
        pName=pName.SubString(0,20);
    testProd.ProductAbbreviation__c =pName;
    testProd.SubscriptionOnly__c  = pSubscrpitionOnly;    
    insert testProd;
    return testProd;    
  }
  
  public static MetroclientProductGeographyType__c makeProductGeographyType(MetroclientProduct__c  prod, MetroclientGeographyType__c  geoType) {

    MetroclientProductGeographyType__c testProdGeoType = new MetroclientProductGeographyType__c();
    testProdGeoType.Name = 'Test Product Geography Type';
    testProdGeoType.GeographyType__c= geoType.Id ;
    testProdGeoType.Product__c= prod.Id;      
    insert testProdGeoType ;
    return testProdGeoType ;    
  }  
  
   public static MetroclientProductGeography__c makeProductGeography(MetroclientProductGeographyType__c prodGeoType, MetroclientGeography__c  geo, string sName) {

    MetroclientProductGeography__c testProdGeo = new MetroclientProductGeography__c();
    testProdGeo.Name = sName;
    testProdGeo.Active__c= True;
    testProdGeo.ProductGeographyType__c =prodGeoType.Id;
    testProdGeo.Geography__c= geo.ID; 
    insert testProdGeo ;
    return testProdGeo ;    
  }
  
  
  public static MetroclientAccountProductGeography__c  makeAccountProductGeography(Account testAcc, MetroclientProductGeography__c prodGeo, Zuora__Subscription__c  testSub, Zuora__SubscriptionProductCharge__c  testCharge, boolean bOrr, boolean bDel ) { 
  
     MetroclientAccountProductGeography__c testAccPG = new MetroclientAccountProductGeography__c ();
     testAccPG.Account__c= testAcc.Id;
     testAccPG.Deleted__c = bDel;
     testAccPG.Override__c= bOrr;
     testAccPG.StartDate__c=testCharge.Zuora__EffectiveStartDate__c.AddDays(-1);
     testAccPG.MetroclientProductGeography__c = prodGeo.ID;
     testAccPG.ChargeNumber__c = testCharge.Name;
     testAccPG.SubscriptionName__c = testSub.Name;
     insert testAccPG;
     return testAccPG;
   }
   
    
  public static MetroclientAccountProductGeography__c  makeAccountProductGeographySameDates(Account testAcc, MetroclientProductGeography__c prodGeo, Zuora__Subscription__c  testSub, Zuora__SubscriptionProductCharge__c  testCharge, boolean bOrr, boolean bDel ) { 
  
     MetroclientAccountProductGeography__c testAccPG = new MetroclientAccountProductGeography__c ();
     testAccPG.Account__c= testAcc.Id;
     testAccPG.Deleted__c = bDel;
     testAccPG.Override__c= bOrr;
     testAccPG.StartDate__c=testCharge.Zuora__EffectiveStartDate__c;
     testAccPG.EndDate__c=testCharge.Zuora__EffectiveEndDate__c;
     testAccPG.MetroclientProductGeography__c = prodGeo.ID;
     testAccPG.ChargeNumber__c = testCharge.Name;
     testAccPG.SubscriptionName__c = testSub.Name;
     insert testAccPG;
     return testAccPG;
   }
   
   
   
   public static Zuora__SubscriptionProductCharge__c makeSubscriptionProductCharge (Zuora__Subscription__c  testSub,MetroclientProductGeography__c prodGeo,string sName, date dStart, date dEnd, string sFreq){
        Zuora__SubscriptionProductCharge__c testSubProdCharge = new Zuora__SubscriptionProductCharge__c ();
        testSubProdCharge.Name = sName;
        testSubProdCharge.Zuora__ChargeNumber__c = sName;
        testSubProdCharge.CreatedDate = System.Now();
        testSubProdCharge.LastModifiedDate = System.Now();
        testSubProdCharge.Zuora__Type__c = sFreq;
        testSubProdCharge.Zuora__Subscription__c = testSub.Id;
        testSubProdCharge.Record_Id__c = prodGeo.Id;
        testSubProdCharge.Zuora__EffectiveEndDate__c = dStart;
        testSubProdCharge.Zuora__EffectiveStartDate__c = dEnd;
       insert testSubProdCharge;
       return testSubProdCharge; 
   }
   
     public static Zuora__SubscriptionProductCharge__c makeSubscriptionProductCharge_BadRecordId (Zuora__Subscription__c  testSub,string sName, date dStart, date dEnd, string sFreq){
        Zuora__SubscriptionProductCharge__c testSubProdCharge = new Zuora__SubscriptionProductCharge__c ();
        testSubProdCharge.Name = sName;
        testSubProdCharge.Zuora__ChargeNumber__c = sName;
        testSubProdCharge.CreatedDate = System.Now();
        testSubProdCharge.LastModifiedDate = System.Now();
        testSubProdCharge.Zuora__Type__c = sFreq;
        testSubProdCharge.Zuora__Subscription__c = testSub.Id;
        testSubProdCharge.Record_Id__c = 'I-am-A-bad-RecordId';
        testSubProdCharge.Zuora__EffectiveEndDate__c = dStart;
        testSubProdCharge.Zuora__EffectiveStartDate__c = dEnd;
       insert testSubProdCharge;
       return testSubProdCharge; 
   }
   
   
  
   
   public static Zuora__Subscription__c makeSubscription (Account acc, string sName, date dStart, date dEnd, string sStatus){
       Zuora__Subscription__c testSub = new Zuora__Subscription__c ();
       testSub.Name = sName;
       testSub.Zuora__SubscriptionStartDate__c = dStart;
       testSub.Zuora__SubscriptionEndDate__c = dEnd;
       testSub.Zuora__Status__c= sStatus;
       testSub.Zuora__Account__c = acc.Id;
       insert testSub;
       return testSub;  
   }
   
   
    public static MetroclientSubscriptionAmendmentLog__c makeAmendmentLog(string sName, Zuora__Subscription__c  testSub, Zuora__SubscriptionProductCharge__c  testCharge, string sAmendmentType, date dEffectiveDate){
       MetroclientSubscriptionAmendmentLog__c testAmdLog = new MetroclientSubscriptionAmendmentLog__c();
       testAmdLog.Name = sName;
       testAmdLog.EffectiveDate__c = dEffectiveDate;
       testAmdLog.AmendmentType__c = sAmendmentType;
       testAmdLog.SubscriptionName__c = testSub.Name;
       testAmdLog.ChargeNumber__c =  testCharge.Name;
       testAmdLog.UniqueName__c = sName + ' | ' + testSub.Name + ' | ' +  testCharge.Name;
       testAmdLog.ProvisioningUpdated__c = false;
       insert testAmdLog ;
       return testAmdLog ;  
   }
   
   
   
    public static void ProductGeographyFactory() {

    MetroclientProduct__c prodMM = TestFactoryMetroclient.makeProduct('Metrostudy Membership (Test)',true);
    MetroclientProduct__c prodHBD = TestFactoryMetroclient.makeProduct('Home Builder Database Package (Test)',false);
    
    MetroclientGeographyType__c geoTypeMkt = TestFactoryMetroclient.makeGeographyType('Market',20);
    MetroclientGeographyType__c geoTypeCBSA = TestFactoryMetroclient.makeGeographyType('CBSA',30);
    
    MetroclientGeography__c geoMkt1= TestFactoryMetroclient.makeGeography(geoTypeMkt,'Test Market 1','T1');
    MetroclientGeography__c geoMkt2= TestFactoryMetroclient.makeGeography(geoTypeMkt,'Test Market 2','T2');
    MetroclientGeography__c geoCBSA1= TestFactoryMetroclient.makeGeography(geoTypeMkt,'Test CBSA 1','T0001');
    MetroclientGeography__c geoCBSA2= TestFactoryMetroclient.makeGeography(geoTypeMkt,'Test CBSA 2','T0002');
    
    
    MetroclientProductGeographyType__c prodGeoTypeMmMkt= TestFactoryMetroclient.makeProductGeographyType(prodMM,geoTypeMkt );    
    MetroclientProductGeographyType__c prodGeoTypeHbdCBSA= TestFactoryMetroclient.makeProductGeographyType(prodHBD ,geoTypeCBSA); 
    MetroclientProductGeography__c testProdGeo = new MetroclientProductGeography__c();
    
     makeProductGeography(prodGeoTypeMmMkt, geoMkt1 , 'TestProdGeo1');
     makeProductGeography(prodGeoTypeMmMkt, geoMkt2 , 'TestProdGeo2');
     makeProductGeography(prodGeoTypeHbdCBSA, geoCBSA1, 'TestProdGeo3');
     makeProductGeography(prodGeoTypeHbdCBSA, geoCBSA2, 'TestProdGeo4');

    
 }
  
   
 /* public static Zuora__CustomerAccount__c makeBillingAccount (Account acc){  
       Zuora__CustomerAccount__c testBillAcct  =new Zuora__CustomerAccount__c();
       testBillAcct.Name='Test Billing Account';
       testBillAcct.Zuora__BillToState__c='TX';
       testBillAcct.Zuora__Account__c = acc.Id;
       insert testBillAcct;
       return testBillAcct;
   
   }*/   

  
 }