src/objects/MetrostudySalesRegionAssignment__c.object
<CustomObject>
    <description>Metrostudy Sales Region - Assigns employees to Metrostudy Sales Regions.</description>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Commission Role
RD = Regional Director
DBD =Director of Business Development
SAMA = Strategic Account Member Advisor
MA = Member Advisor
RAM = Regional Account Manager
Other = Other roles (ex: Consultants)</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>DBD</fullName>
                </value>
                <value>
                    <fullName>SAMA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MetrostudySalesRegionAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Sales Region Assignment</label>
    <nameField>
        <label>Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Sales Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FC_RegionalDirectorListController.cls
public with sharing class FC_RegionalDirectorListController {

    public String[] regionalDirectorNames {

        get {
            if (regionalDirectorNames == null) {
                regionalDirectorNames = new List<String>();
                for (AggregateResult ar : [
                        select User__r.Name employeeName
                        from MetrostudySalesRegionAssignment__c
                        where Role__c = 'RD'
                        group by User__r.Name
                        order by User__r.Name asc
                ]) {
                    String employeeName = (String) ar.get('employeeName');
                    if (String.isNotBlank(employeeName)) {
                        regionalDirectorNames.add(employeeName);
                    }
                }
                regionalDirectorNames.sort();
            }
            return regionalDirectorNames;
        }

        private set;

    }

    public FC_RegionalDirectorListController() {
    }

}