src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <description>Zuora Subscription Charge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Charge Number (Zuora)</inlineHelpText>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Subscription is no longer active and product cannot be accessed. Record exists for reference only.</description>
        <inlineHelpText>When checked, product cannot be accessed. Record exists for reference only.</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date the subscription ends  (SubscriptionEndDate).  This value is blank (NULL) for evergreen subscriptions.</description>
        <inlineHelpText>The date access to the product expires and can no longer be accessed.  This field is blank when a subscription is evergreen.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manual override.  When this box is checked, the job that updates this object based on the subscriptions from Zuora will ignore this record and not update it.  To be used when the Start Date, End Date or Deleted status need to be Manually overridden.
Check box when a manual override is required. Start Date, End Date, and/or Delete status has been manually overridden and should not be updated based on the subscription dates/status in Zuora.</description>
        <inlineHelpText>When checked, a manual override for this record is in effect.</inlineHelpText>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RemovalAmendment__c</fullName>
        <description>Name of Removal Amendment that removed a product.  Products can be removed without a Removal Amendment if the subscription simply expired or was cancelled.  Products that are not in Subscription &amp; Charges object AND don&apos;t have a Removal Amendment should have the delete flag turned on.</description>
        <label>Removal Amendment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubscriptionName__c</fullName>
        <description>Zuora Subscription Name</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Name (Zuora)</inlineHelpText>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientSubscriptionAmendmentLog__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Remove Product Ammendment log. Tracks the removal of products from a subscription.</description>
    <fields>
        <fullName>AmendmentType__c</fullName>
        <label>Amendment Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProvisioningUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Provisioning has been updated for this change?</description>
        <label>Provisioning Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubscriptionName__c</fullName>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Subscription Amendment Log</label>
    <nameField>
        <label>Amendment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Subscription Amendment Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudyProvisionSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Metrostudy Account provisioning settings</description>
    <fields>
        <fullName>ApplyRemovalAmendmentsLastRun__c</fullName>
        <label>Apply Removal Amendments Last Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SendEmailCc__c</fullName>
        <label>Send Email Cc</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SendEmailTo__c</fullName>
        <label>Send Email To</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>UpdateProvisioning__c</fullName>
        <defaultValue>true</defaultValue>
        <label>UpdateProvisioning</label>
        <type>Checkbox</type>
    </fields>
    <label>Metrostudy Provisioning Settings</label>
</CustomObject>

src/classes/MetroclientApplyRemovalAmendments.cls
global class MetroclientApplyRemovalAmendments implements Schedulable {
 
global void execute(SchedulableContext ctx) { 
     /*  SchedulableContext sc = null;
         MetroclientApplyRemovalAmendments b = new MetroclientApplyRemovalAmendments ();
         b.execute(sc);    */
     

    boolean bFailed=false; 
    boolean bFound=false;
    date AmendmentEffectiveDate;
    string SubscriptionName;
    string ChargeNumber;    
    string AmendmentCode; 
    string whereCharges  = '\'PreventEmpty\'';
    string sMailMessage ='';      
    
     MetrostudyProvisionSettings__c mps = MetrostudyProvisionSettings__c.getOrgDefaults();
        string  sTo=mps.SendEmailTo__c;
        string  sCc=mps.SendEmailCc__c;
        boolean bUpdateProvisioning=mps.UpdateProvisioning__c;
        if (Test.isRunningTest()) 
             bUpdateProvisioning=true;
             
  
    try{    
   
       
            
        List<MetroclientAccountProductGeography__c>  ListUpdateProv = new List<MetroclientAccountProductGeography__c>(); 
        List<MetroclientSubscriptionAmendmentLog__c> ListUpdateLog= new List<MetroclientSubscriptionAmendmentLog__c>();         
        
        /* 
        1) Get everything from MetroclientSubscriptionAmendmentLog__c where ProvisioningUpdated__c = False ; Populate string with charge numbers */    
              
                
        List<MetroclientSubscriptionAmendmentLog__c >  ListLog = [Select Name, SubscriptionName__c, ChargeNumber__c , EffectiveDate__c from MetroclientSubscriptionAmendmentLog__c where
        AmendmentType__c = 'RemoveProduct' and ProvisioningUpdated__c=False ];
          
        System.debug('Get string of charge numbers to narrow down queries and avoid reaching limits');       
           
        for(MetroclientSubscriptionAmendmentLog__c item: ListLog )
        {
             ChargeNumber= item.ChargeNumber__c ;
             if( ChargeNumber!= null && ChargeNumber!='')                     
                     whereCharges  =  whereCharges  +   ',\'' + ChargeNumber + '\'';          
                                  
        }            
        System.debug('whereCharges   = ' + whereCharges  );
                
        
          /*   2) get all account provisioning from those charge numbers ; Compare end date.  Update end date and ammendment field if needed.   */
          
         List<MetroclientAccountProductGeography__c> AccountProvision = Database.query('Select Name, ChargeNumber__c , SubscriptionName__c, EndDate__c , RemovalAmendment__c FROM  MetroclientAccountProductGeography__c Where  Deleted__c=false  and Override__c=false AND ChargeNumber__c in (' + whereCharges  +')');
         Map<string, MetroclientAccountProductGeography__c> mapAccountProvision = new Map<string, MetroclientAccountProductGeography__c>(AccountProvision);        
       
         for(MetroclientSubscriptionAmendmentLog__c item: ListLog )
         {
                ChargeNumber= item.ChargeNumber__c ;
                SubscriptionName = item.SubscriptionName__c;
                AmendmentEffectiveDate = item.EffectiveDate__c ;
                AmendmentCode=  item.Name;
                bFound = false;                
                System.debug('Loop Log:' + item.Name + '....SubscriptionName=' + SubscriptionName  + '...ChargeNumber=' + ChargeNumber);
                
                For(MetroclientAccountProductGeography__c  a: mapAccountProvision.values())
                {                
                   
                    if(a.ChargeNumber__c ==ChargeNumber  && a.SubscriptionName__c==SubscriptionName )
                    {
                          bFound = true;
                          if(a.EndDate__c!=AmendmentEffectiveDate|| a.RemovalAmendment__c != AmendmentCode )
                          {  
                             System.debug(' -Update EndDate__c from ' + a.EndDate__c + ' ....to: ' +  AmendmentEffectiveDate);                   
                             System.debug(' -Update RemovalAmendment__c from ' + a.RemovalAmendment__c  + ' ....to: ' +  AmendmentCode ); 
                             a.EndDate__c=AmendmentEffectiveDate ;  
                             a.RemovalAmendment__c =AmendmentCode;                  
                             ListUpdateProv.add(a);     
                          }else{
                               System.debug('End date already matches removal amendment');
                          }               
                          
                          item.ProvisioningUpdated__c = true;
                          ListUpdateLog.add(item);
                          break;
                    }                   
                
                }  // end loop of Account Provisioning 
                
                if(!bFound )
                    System.debug(' ............................  Provisioning could not be found ');                
                
            
         }   // end loop of Remove Product Amendment Log      
            
        
             
         
           try{      
              if (!ListUpdateProv.isEmpty()) 
                    Database.update(ListUpdateProv); 
               if (!ListUpdateLog.isEmpty()) 
                    Database.update(ListUpdateLog);  
            }catch (Exception ex) {
                 
                 sMailMessage += '<br /><br />' + 'Exception Line#'+ ex.getLineNumber() + ' Details:' + ex;      
                 System.debug('Exception: ' + ex + '....Line # ' + ex.getLineNumber()); 
                 bFailed=true;
            }           
        
        
         if(!bFailed && bUpdateProvisioning)
         {      
              DateTime LastRun =  mps.ApplyRemovalAmendmentsLastRun__c;
              DateTime NewDate = System.now();
              mps.ApplyRemovalAmendmentsLastRun__c= NewDate;  /**  Update date of last run **/
              update mps;
              System.Debug('ApplyRemovalAmendmentsLastRun__c changed from ' + LastRun +  '  to:  ' + NewDate);
         }
            
    }
    catch (Exception ex) {            
         System.debug('Exception: ' + ex + '....Line # ' + ex.getLineNumber()); 
         bFailed= true;  
         sMailMessage += '<br /><br />' + 'Exception Line#'+ ex.getLineNumber() + ' Details:' + ex;      
    }  
           
   
   
    
    if(bFailed)
    {
       SendEmail('**MetroclientApplyRemovalAmendments',sMailMessage, sTo, sCc);
    }
           
}   

 private void SendEmail(string sSubject, string sBody, string sTo, string sCc){
      
         try{  
            
            sBody='<body style="font-family:arial;font-size:10pt">' + sBody  +'</body>' ;        
                      
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[] {sTo});
            mail.setToAddresses(new String[] {sCc});
            mail.setSubject(sSubject);
            String messageBody = sBody;
            mail.setHtmlBody(messageBody); 
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            
         }catch (Exception ex) {
                System.debug('EMAIL Error -Line#'+ ex.getLineNumber() + '-----' + ex );
         } 
    
   }
    
}