src/objects/MetroclientAccountProductGeography__c.object
<CustomObject>
    <description>Metrostudy Provisioning - Account Level.  Populated when a quote is sent to Z-billing.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargeNumber__c</fullName>
        <description>Zuora Subscription Charge Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Charge Number (Zuora)</inlineHelpText>
        <label>Charge Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Subscription is no longer active and product cannot be accessed. Record exists for reference only.</description>
        <inlineHelpText>When checked, product cannot be accessed. Record exists for reference only.</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date the subscription ends  (SubscriptionEndDate).  This value is blank (NULL) for evergreen subscriptions.</description>
        <inlineHelpText>The date access to the product expires and can no longer be accessed.  This field is blank when a subscription is evergreen.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MetroclientProductGeography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography</label>
        <referenceTo>MetroclientProductGeography__c</referenceTo>
        <relationshipLabel>Metrostudy Account Product Geographies</relationshipLabel>
        <relationshipName>MetroclientAccountProductGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manual override.  When this box is checked, the job that updates this object based on the subscriptions from Zuora will ignore this record and not update it.  To be used when the Start Date, End Date or Deleted status need to be Manually overridden.
Check box when a manual override is required. Start Date, End Date, and/or Delete status has been manually overridden and should not be updated based on the subscription dates/status in Zuora.</description>
        <inlineHelpText>When checked, a manual override for this record is in effect.</inlineHelpText>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date that the subscription starts (SubscriptionStartDate)</description>
        <inlineHelpText>The date that the access to the product starts.  This date is determined by the subscription or amendment start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubscriptionName__c</fullName>
        <description>Zuora Subscription Name</description>
        <externalId>true</externalId>
        <inlineHelpText>Subscription Name (Zuora)</inlineHelpText>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Metrostudy Account Product Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Account Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProduct__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Metrostudy Products</description>
    <label>Metrostudy Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeography__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Associates products with the geographies they are offered in.</description>
    <fields>
        <fullName>ProductCatalogRecordId__c</fullName>
        <description>18 character version of the SFDC Id.  Used by Zuora to associate subscription rate plan charges / product rate plan charges with a product geography.</description>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>18 character unique id used by Zuora as the &quot;Record Id&quot; that associates subscription rate plan charges / product rate plan charges with a product geography.</inlineHelpText>
        <label>Product Catalog Record Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductGeographyType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Geography Type</label>
        <referenceTo>MetroclientProductGeographyType__c</referenceTo>
        <relationshipName>MetroclientProductGeographies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography</label>
    <nameField>
        <label>Product Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetroclientProductGeographyType__c.object
<CustomObject>
    <description>Metroclient Product Catalog - Geography types associated with products</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>MetroclientProduct__c</referenceTo>
        <relationshipName>MetroclientProductGeographyTypes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Metrostudy Product Geography Type</label>
    <nameField>
        <label>Product Geography Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrostudy Product Geography Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MetrostudyProvisionSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Metrostudy Account provisioning settings</description>
    <fields>
        <fullName>SendEmailCc__c</fullName>
        <label>Send Email Cc</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SendEmailTo__c</fullName>
        <label>Send Email To</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SubscriptionUpdateLastCheck__c</fullName>
        <description>Last time the APEX class ran to batch update Account Provisioning</description>
        <inlineHelpText>Last time the APEX class ran to batch update Account Provisioning</inlineHelpText>
        <label>Subscription Update Last Check</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SubscriptionUpdateMaxCheck__c</fullName>
        <description>The max date and time the APEX class with look at for changes.  If blank, the class will include up 25 hours in the date/time range.</description>
        <inlineHelpText>The max date and time the APEX class with look at for changes.  If blank, the class will include up 25 hours in the date/time range.</inlineHelpText>
        <label>Subscription Update Max Check</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UpdateProvisioning__c</fullName>
        <defaultValue>true</defaultValue>
        <label>UpdateProvisioning</label>
        <type>Checkbox</type>
    </fields>
    <label>Metrostudy Provisioning Settings</label>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <description>The date when the (segmented) charge ends (or ended).</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveStartDate__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MetroclientAccountProvisionBatchUpdate.cls
global class MetroclientAccountProvisionBatchUpdate implements Schedulable {
 
     /*  SchedulableContext sc = null;
         MetroclientAccountProvisionBatchUpdate b = new MetroclientAccountProvisionBatchUpdate();
         b.execute(sc);    */       
    
  
     
    global void execute(SchedulableContext ctx) {
    
         boolean bFailed=false;  
         string sMailMessage='';
         string sMailMessageEnd='';
        string Subscription;
        string SubscriptionName;
        string Account;
        string AccountName;
        string ChargeNumber;
        string ChargeType;
        string Record_Id;
        string status;
        boolean bValid;
        boolean bFound;
        boolean SubscriptionOnly;
        date startDate;
        date endDate; 
        date subStartDate;   
        string queryRid = '\'PreventEmpty\'';
        string queryAcc= '\'PreventEmpty\'';
        string ProdGeoName;
        boolean bHighP = false; 
        boolean bUpdate;
        string lastSub = ''; 
        string sLastCheck;
        string sNewCheck;
        
        integer z = 0;
        Map<String, String> mapRecName = new Map<String ,String>();
        Map<String, boolean> mapRecSubOnly = new Map<String ,boolean>();              
   
        MetrostudyProvisionSettings__c mps = MetrostudyProvisionSettings__c.getOrgDefaults();
        DateTime LastCheck =  mps.SubscriptionUpdateLastCheck__c;
        DateTime NewDate  =  mps.SubscriptionUpdateMaxCheck__c; 
        string  sTo =mps.SendEmailTo__c;
        string  sCc= mps.SendEmailCc__c;
        boolean bUpdateProvisioning=mps.UpdateProvisioning__c;
        System.Debug('bUpdateProvisioning:' + bUpdateProvisioning+ '....sTo :' + sTo );
        if (Test.isRunningTest()) {
            bUpdateProvisioning=true;
        }
      
      try{ 
            if(LastCheck==null)
                LastCheck =System.now().addHours(-24);
            if(NewDate==null || NewDate < LastCheck  )    
                 NewDate = System.now(); 
            if(LastCheck.addHours(25)< NewDate)//don't go over a day
            {
                NewDate = LastCheck.addHours(25);
                sMailMessage+='*** Job looks for records updated during a maximum time period of a 24 hours. Running this job again is needed to get changes that occurred after ' + NewDate  + '.<br /><br />';
                bHighP = true;  
            }
    
            sLastCheck = LastCheck.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS+0000');
            sNewCheck = NewDate.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS+0000');
            
            System.Debug('LastCheck:' + LastCheck + '....sLastCheck :' + sLastCheck );
           
            string spcQuery = 'select Id, Name, CreatedDate,  LastModifiedDate , Zuora__Type__c, Zuora__Subscription__c, Record_Id__c, Zuora__ChargeNumber__c,';
            spcQuery +=' Zuora__Subscription__r.Zuora__Account__r.Name,Zuora__Subscription__r.Zuora__Account__c ,Zuora__Subscription__r.Zuora__Status__c,Zuora__Subscription__r.Name,';
            spcQuery +=' Zuora__EffectiveEndDate__c, Zuora__EffectiveStartDate__c, Zuora__Subscription__r.Zuora__SubscriptionStartDate__c, Zuora__Subscription__r.Zuora__SubscriptionEndDate__c ';
            spcQuery +=' from Zuora__SubscriptionProductCharge__c where Record_Id__c != null and ((LastModifiedDate >=' +sLastCheck + ' and LastModifiedDate <=' +sNewCheck + ') or (Zuora__Subscription__r.LastModifiedDate >=' + sLastCheck +' and Zuora__Subscription__r.LastModifiedDate <=' + sNewCheck +'))';
            spcQuery +=' order by Zuora__Subscription__r.Zuora__Account__r.Name, Zuora__Subscription__r.Name, Zuora__ChargeNumber__c';     
            System.Debug('spcQuery::::  ' + spcQuery  );
            
            List<MetroclientAccountProductGeography__c> InsertList = new List<MetroclientAccountProductGeography__c>();
            List<MetroclientAccountProductGeography__c> UpdateList = new List<MetroclientAccountProductGeography__c>();  
            List<Zuora__SubscriptionProductCharge__c>  SubProdCharge = Database.query(spcQuery);
           // Map<string, Zuora__SubscriptionProductCharge__c> mapSubProdCharge = new Map<string, Zuora__SubscriptionProductCharge__c>(SubProdCharge);
           
           System.debug('Get string of record ids and string of accounts to narrow down queries and avoid reaching limits');
           for(Zuora__SubscriptionProductCharge__c item: SubProdCharge)
           {
                Record_Id = item.Record_Id__c;
                System.debug('Record_Id=' + Record_Id + '....Account=' + item.Zuora__Subscription__r.Zuora__Account__c  + '...SubscriptionName=' +  item.Zuora__Subscription__r.Name );
                
                if( Record_Id != null && Record_Id !=''){        
                   if(!queryRid .contains('\'' + Record_Id + '\''))
                    {
                        if(queryRid!='')
                            queryRid = queryRid + ',';
                        queryRid =  queryRid +   '\'' + Record_Id + '\'';     
                    }     
                }  
               if(!queryAcc.contains('\'' + item.Zuora__Subscription__r.Name + '\''))  
               {
                    if(queryAcc!='')
                        queryAcc = queryAcc + ',';
                    queryAcc =  queryAcc +   '\'' + item.Zuora__Subscription__r.Name + '\'';  
               }
            }
            
            System.debug('Record_Ids to include: ' + queryRid ); 
            System.debug('Subscriptions to include: ' + queryAcc );
             
            string queryVRI= 'Select Name, ProductGeographyType__r.Name,ProductGeographyType__r.Product__r.SubscriptionOnly__c FROM  MetroclientProductGeography__c where ProductCatalogRecordId__c in (' + queryRid +')';
            string queryAP= 'Select Id,Account__r.Name, Account__c, MetroclientProductGeography__r.Name, Deleted__c, Override__c, SubscriptionName__c,ChargeNumber__c, StartDate__c, EndDate__c,MetroclientProductGeography__c';
            queryAP+=' from MetroclientAccountProductGeography__c where Deleted__c = false and SubscriptionName__c in ('+ queryAcc +')';
            System.debug('queryRecordId::::' + queryVRI);   
            System.debug('queryAccountProv::::'+ queryAP);  
             List<MetroclientProductGeography__c >   ValidRecordIdList = Database.query(queryVRI);
             for(MetroclientProductGeography__c r: ValidRecordIdList)
            {            
                 mapRecName.put(r.Id,r.Name); 
                 mapRecSubOnly.put(r.Id, r.ProductGeographyType__r.Product__r.SubscriptionOnly__c );        
                
            }           
    
           
            List<MetroclientAccountProductGeography__c> AccountProvision =  Database.query(queryAP);             
            //Map<string, MetroclientAccountProductGeography__c> mapAccountProvision = new Map<string, MetroclientAccountProductGeography__c>(AccountProvision);       
            
            for(Zuora__SubscriptionProductCharge__c item: SubProdCharge)
            {
                z+=1;
                System.debug('Start z:' + z);
                bValid = false;
                bFound = false;
                ProdGeoName='';
                SubscriptionOnly = false;
                Record_Id = item.Record_Id__c;
                ChargeType = item.Zuora__Type__c; 
                AccountName = item.Zuora__Subscription__r.Zuora__Account__r.Name;    
                ChargeNumber  =  item.Zuora__ChargeNumber__c;
                SubscriptionName  = item.Zuora__Subscription__r.Name;
                
                
                
                try{ 
                    ProdGeoName = mapRecName.get(Record_Id);
                    SubscriptionOnly = mapRecSubOnly.get(Record_Id);
                    System.debug('--- ProductGeo Name: ' + ProdGeoName + '  . . . . . . . .  SubscriptionOnly=' + SubscriptionOnly);
                    bValid = true;
               }catch(Exception ex) {            
                    System.debug('Exception: ' + ex + '....Line # ' + ex.getLineNumber()); 
                    sMailMessage += '<br /><br />Exception: ' + ex + '....Line # ' + ex.getLineNumber();
                    bValid = false;               
               }
                
               if(ProdGeoName ==null)
               {
                   bValid = false;
                   System.debug('** -- ** __ ** __ Bad Record ID....' + Record_Id + '.......'+AccountName  + ' ' + SubscriptionName   + '-' + ChargeNumber   );
                   sMailMessage += '<br /><br /><strong>Invalid RECORD ID Found</strong> The Subscription Charge had to be skipped.  Please correct.<br />';
                   sMailMessage += AccountName  + ' ' + SubscriptionName   + '-' + ChargeNumber  + ' Invalid Record Id: ' + Record_Id + '<br /><br />';
                   bHighP = true;               
                   
               }
               
                Account = item.Zuora__Subscription__r.Zuora__Account__c ;  
                Subscription = item.Zuora__Subscription__c;
                status = item.Zuora__Subscription__r.Zuora__Status__c;
                startDate = item.Zuora__EffectiveStartDate__c;  // Rate Charge Effective Date
                subStartDate = item.Zuora__Subscription__r.Zuora__SubscriptionStartDate__c;   // Subscription Start Date
                      
                if(status=='Cancelled'|| ChargeType=='OneTime' || ChargeType=='One-Time')
                {
                    endDate =  item.Zuora__Subscription__r.Zuora__SubscriptionEndDate__c;
                    
                }else{    
                    
                    endDate = item.Zuora__EffectiveEndDate__c;                
                }    
                System.debug('----- Account: ' + Account + ' . . SubscriptionName  : ' + SubscriptionName+ ' . . ChargeNumber  : ' + ChargeNumber  + '. . Record_Id: ' + Record_Id);
                System.debug('Name: ' + item.Name );
                System.debug('CreatedDate: ' + item.CreatedDate);System.debug('LastModifiedDate: ' + item.LastModifiedDate);System.debug('ChargeType: ' + ChargeType);
                System.debug('status: ' + status + '..startDate: ' + startDate + '...endDate: ' + endDate);    
                
                bFound = false;    
                For(MetroclientAccountProductGeography__c  a: AccountProvision)
                {
                      if(a.ChargeNumber__c==ChargeNumber  && a.SubscriptionName__c==SubscriptionName )
                      {
                        bFound = true;
                        bUpdate = false;
                        System.debug('Already exists in Account Provisioning: ' + a.ChargeNumber__c);
                        if(a.StartDate__c!=startDate || a.EndDate__c!=endDate || a.Account__c != Account ||  a.MetroclientProductGeography__c !=Record_Id)
                        {
                            System.debug('...................   Update Account Provisioning:  ..................................................................');
                            
                            
                            if(AccountName + SubscriptionName!=lastSub )
                            {
                                  if(lastSub!='')
                                     sMailMessage += '<br /><hr style="color:gray;width:100%;size:1pt;" />';
                                  sMailMessage += '<br /><br /><strong>' + AccountName + '</strong>';                                  
                            }      
                            lastSub =AccountName + SubscriptionName;
                            
                            sMailMessage += '<br /><br />' + SubscriptionName+ ' | ' + ChargeNumber ;
                            sMailMessage += '<br />'  + ProdGeoName +'';
                           
                            if(a.StartDate__c!=startDate && !a.Override__c){
                                    
                                  sMailMessage +=  '<br /><strong>Start Date Changed</strong>&nbsp; &nbsp;Before: ' + formatDateString(a.StartDate__c)+ ' &nbsp; After: ' + formatDateString(startDate);   
                                  if(startDate < a.StartDate__c ||startDate  == subStartDate )
                                  { 
                                       sMailMessage +=  ' &nbsp; <i>Provisioning Start Date was updated</i>';
                                       a.StartDate__c=startDate;
                                       bUpdate =true;
                                    
                                }else{
                                
                                    sMailMessage +=  ' &nbsp; <i>Provisioning date not changed - most likely a price increase</i>';
                                }
                            }
                                    
                            if(a.EndDate__c!=endDate) { 
                                sMailMessage +=  '<br /><strong>End Date Changed</strong>&nbsp; &nbsp; Before: '  + formatDateString(a.EndDate__c) + ' &nbsp;  After: '  + formatDateString(endDate);  
                                if(!a.Override__c) 
                                {            
                                    sMailMessage +=  ' &nbsp; <i>Provisioning End Date was updated</i>';
                                    a.EndDate__c=endDate;
                                    bUpdate =true;
                                }
                                
                                
                            }
                            
                            if( a.Account__c != Account){                        
                              
                                 sMailMessage +=  '<br /><strong>Account Changed</strong>';
                                 if( !a.Override__c)
                                 {
                                     sMailMessage += '<font style="color:red"> ***</font>';
                                     bHighP = true;
                                 }
                                 sMailMessage +=  '  &nbsp; In SFDC: &nbsp;'+ a.Account__r.Name;//  +  ' &nbsp; &nbsp; (Id=' + a.Account__c + ')<br />After: &nbsp; &nbsp; ' + AccountName + ' &nbsp; &nbsp; (Id='+ Account+ ')'; 
                                 //a.Account__c = Account;
                                 
                            }
                            
                            if( a.MetroclientProductGeography__c !=Record_Id ){
                               
                                sMailMessage +=  '<br /><strong>Product Geography Changed</strong>';
                                if( !a.Override__c)
                                {
                                    sMailMessage += '<font style="color:red"> *** </font>';
                                    bHighP = true;  
                                }
                                sMailMessage +=  ' &nbsp; In SFDC: &nbsp;'+ a.MetroclientProductGeography__r.Name;  //  +' &nbsp; &nbsp; (Id=' + a.MetroclientProductGeography__c + ')' + '<br />After:  &nbsp; &nbsp; ' + ProdGeoName + ' &nbsp; &nbsp; (Id=' + Record_Id +')' ; 
                                                                                        
                             } 
                          
                            if( !a.Override__c && bUpdate)
                                UpdateList.add(a);                           
                            
                            if(a.Override__c)
                                 sMailMessage +=  '<br />Override set to TRUE. No update to provisioning was made.';
                                                                
                        } else{
                            sMailMessageEnd += '<br />' + SubscriptionName+ ' | ' + ChargeNumber;
                        }                       
                                  
                        break;             
                      }
                } 
                if(bFound==false &&   bValid == true  && ((ChargeType!='OneTime' && ChargeType!='One-Time')|| SubscriptionOnly==true))
                {                  
                    
                    if(AccountName + SubscriptionName!=lastSub )
                    {
                          if(lastSub!='')
                             sMailMessage += '<hr style="color:gray;width:100%;size:1pt;" />';
                          sMailMessage += '<br /><br /><strong>' + AccountName + '</strong>';                                  
                    }      
                    lastSub =AccountName + SubscriptionName;
                    
                    System.debug('*** *** *** *** *** *** *** *** *** Insert Account Provisioning *** *** *** *** *** *** *** *** ***' + ProdGeoName ); 
                    sMailMessage +='<br /><br />' + SubscriptionName + ' | ' + ChargeNumber  + ' <strong>- New Provisioning</strong>';
                    sMailMessage +='<br />' + ProdGeoName + '<br />Dates: &nbsp; ' + formatDateString(startDate)+ ' - ' + formatDateString(endDate);
                    MetroclientAccountProductGeography__c newRecord = new MetroclientAccountProductGeography__c();
                    newRecord.Name = SubscriptionName + ' | ' + ChargeNumber;
                    newRecord.Account__c = Account;
                    newRecord.StartDate__c = startDate;
                    newRecord.EndDate__c = endDate;
                    newRecord.MetroclientProductGeography__c = Record_Id;
                    newRecord.ChargeNumber__c = ChargeNumber;
                    newRecord.SubscriptionName__c= SubscriptionName;
                    InsertList.add(newRecord);  
                }  
            }
       
        if(sMailMessage =='' && sMailMessageEnd =='')
                sMailMessage = '<br />No modified subscriptions were found.';
                
                        
         if(!bUpdateProvisioning)
         {
             sMailMessage = '<br /><br />* * * Provisioning set to not update.  No changes were made to Provisioning. * * *<br /><br />' + sMailMessage;
            
         }else{
            try{      
               if (InsertList.isEmpty() == false)
                    Database.insert(InsertList);                
            }catch (Exception ex) {
               
                 System.debug('Insert Exception' + ex);
                 sMailMessage += '<br /><br />' + 'Insert Exception' + ex;
                 bFailed=true;
            
            }
            
            try{      
              if (UpdateList.isEmpty() == false) 
                    Database.update(UpdateList); 
                
            }catch (Exception ex) {
                 
                  System.debug('Update Exception' + ex);
                  sMailMessage += '<br /><br />' + 'Update Exception' + ex;
                     bFailed=true;
            }           
       }   
        
    }catch (Exception ex) {         
         System.debug('Exception Line#'+ ex.getLineNumber() + ' Details:' + ex);
         sMailMessage += '<br /><br />' + 'Exception Line#'+ ex.getLineNumber() + ' Details:' + ex;
         bFailed=true;
    }
    
    sMailMessage += '<br /><hr style="color:gray;width:100%;size:1pt;" />';
    string Subject = 'Results: SubscriptionUpdateLastCheck';
    if(bHighP==true)
     {
         Subject = '***' + Subject;         
         sMailMessage+='<br /><br /><font style="color:red">*** When a subscription account or product geography is changed, provisioning is not automatically updated.';
         sMailMessage+=' Please manually update provisioning where needed.</font></br>';
     }
     
     
      sMailMessage='Account Provisioning Changes between ' + LastCheck.formatLong() + ' and '+NewDate.formatLong()  + '<br />' + sMailMessage;
      
      
      if(sMailMessageEnd!='')
            sMailMessageEnd='<br /><br />Subscriptions modified but provisioning not changed:' + sMailMessageEnd;
            
    sMailMessageEnd +='<br /><br /><br /><i>Automated email sent from SFDC Class MetroclientAccountProvisionBatchUpdate</i>.';
           
    sMailMessage=sMailMessage+ sMailMessageEnd;
         
    SendEmail(Subject,sMailMessage, sTo, sCc);
        
    if(bFailed==false && bUpdateProvisioning && !Test.isRunningTest())
    {
            mps.SubscriptionUpdateLastCheck__c = NewDate ;
            update mps;
            System.Debug('SubscriptionUpdateLastCheck__c updated to:  ' + NewDate );
     }
     
   }

    private string formatDateString(Date d)
    {
        if(d==null)
            return '[blank]';
        else
            return d.format();       }

   


    private void SendEmail(string sSubject, string sBody, string sTo, string sCc){
      
         try{  
            
            sBody='<body style="font-family:arial;font-size:10pt">' + sBody  +'</body>' ;        
                      
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[] {sTo});
            mail.setToAddresses(new String[] {sCc});
            mail.setSubject(sSubject);
            String messageBody = sBody;
            mail.setHtmlBody(messageBody); 
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            
         }catch (Exception ex) {
                System.debug('EMAIL Error -Line#'+ ex.getLineNumber() + '-----' + ex  );
                 System.debug('email message: ' + sBody);
         } 
    
   }
}