src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FC_Bill_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities ((FC) Bill To Contact)</relationshipLabel>
        <relationshipName>Opportunities6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FC_Last_Sent_To_Zuora__c</fullName>
        <label>(FC) Last Sent To Zuora</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FC_Sold_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>(FC) Sold To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities ((FC) Sold To Contact)</relationshipLabel>
        <relationshipName>Opportunities7</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__AccountNumber__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Balance__c</fullName>
        <label>Bill To Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToAddress1__c</fullName>
        <label>Bill To Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToAddress2__c</fullName>
        <label>Bill To Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCity__c</fullName>
        <label>Bill To Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToCountry__c</fullName>
        <label>Bill To Address Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToName__c</fullName>
        <label>Bill To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToPostalCode__c</fullName>
        <label>Bill To Address Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__BillToState__c</fullName>
        <label>Bill To Address State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToAddress1__c</fullName>
        <label>Sold To Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToAddress2__c</fullName>
        <label>Sold To Address2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToCity__c</fullName>
        <label>Sold To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToCountry__c</fullName>
        <label>Sold To Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToName__c</fullName>
        <label>Sold To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToPostalCode__c</fullName>
        <label>Sold To Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SoldToState__c</fullName>
        <label>Sold To State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FC_OpportunityBillingAccountFormCtrl.cls
public with sharing class FC_OpportunityBillingAccountFormCtrl {

    private final Opportunity OPPORTUNITY_RECORD;
    private final ApexPages.StandardController STANDARD_CONTROLLER;

    public Id selectedBillingAccountId { get; set; }

    public String selectedBillingAccountAction { get; set; }

    public SelectOption[] billingAccountContactOptions {

        get {
            if (billingAccountContactOptions == null) {
                billingAccountContactOptions = new List<SelectOption>();
                billingAccountContactOptions.add(new SelectOption('', '-- Select One --'));
                Set<Id> visitedContactIds = new Set<Id>();
                for (OpportunityContactRole opportunityContactRoleRecord : [
                        select Id, ContactId, Contact.Name
                        from OpportunityContactRole
                        where OpportunityId = :this.OPPORTUNITY_RECORD.Id
                        order by Contact.LastName asc
                ]) {
                    if (!visitedContactIds.contains(opportunityContactRoleRecord.ContactId)) {
                        billingAccountContactOptions.add(new SelectOption(opportunityContactRoleRecord.ContactId,
                                opportunityContactRoleRecord.Contact.Name));
                        visitedContactIds.add(opportunityContactRoleRecord.ContactId);
                    }
                }
            }
            return billingAccountContactOptions;
        }

        private set;

    }

    public Zuora__CustomerAccount__c[] billingAccounts {

        get {
            if (billingAccounts == null) {
                billingAccounts = [
                        select Id, Name, Zuora__AccountNumber__c, Zuora__Balance__c, Zuora__BillToCity__c,
                                Zuora__BillToCountry__c, Zuora__BillToAddress1__c, Zuora__BillToAddress2__c,
                                Zuora__BillToState__c, Zuora__BillToPostalCode__c, Zuora__BillToName__c,
                                Zuora__SoldToAddress1__c, Zuora__SoldToAddress2__c, Zuora__SoldToCity__c,
                                Zuora__SoldToCountry__c,Zuora__SoldToName__c,Zuora__SoldToPostalCode__c,
                                Zuora__SoldToState__c
                        from Zuora__CustomerAccount__c
                        where Zuora__Account__c = :this.OPPORTUNITY_RECORD.AccountId
                ];
            }
            return billingAccounts;
        }

        private set;

    }

    public FC_OpportunityBillingAccountFormCtrl(ApexPages.StandardController standardController) {
        this.OPPORTUNITY_RECORD = (Opportunity) standardController.getRecord();
        this.STANDARD_CONTROLLER = standardController;
    }

    public void refreshUi() {
        this.billingAccountContactOptions = null;
        this.billingAccounts = null;
        this.selectedBillingAccountId = null;
        this.OPPORTUNITY_RECORD.FC_Bill_To_Contact__c = null;
        this.OPPORTUNITY_RECORD.FC_Sold_To_Contact__c = null;
        this.OPPORTUNITY_RECORD.FC_Billing_Account__c = null;
    }

    public PageReference saveOpportunity() {

        if (!isValid()) {
            return null;
        }

        if (selectedBillingAccountAction == 'USE_EXISTING') {
            this.OPPORTUNITY_RECORD.FC_Billing_Account__c = selectedBillingAccountId;
        }

        update this.OPPORTUNITY_RECORD;

        return this.STANDARD_CONTROLLER.view();
    }

    private Boolean isValid() {
        Boolean valid = true;

        if (selectedBillingAccountAction == 'USE_EXISTING' && String.isBlank(selectedBillingAccountId)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                    'You must select a billing account.'));
            valid = false;
        }

        if (this.OPPORTUNITY_RECORD.FC_Last_Sent_To_Zuora__c != null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                    'You cannot change the billing account or contacts since this opportunity was sent to Zuora.'));
            valid = false;
        }

        return valid;
    }

}