src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>IncludeInCancelDigest__c</fullName>
        <description>Include in Cancel Digest</description>
        <formula>/*

 @Description Returns true if Opportunity is cancelled today and the Record Type is MS or Metro
 @changelog  MG/10K 18/11 Changed to new criteria
 @changelog BE 6/7/18 Added criteria for record type MS Opportunity

Old Code

AND (  
    Stage_Changed_On__c = TODAY(),
    RecordType.Name = &quot;Metrostudy Renewal Oppty Record Type&quot;, 
     NOT (CONTAINS (Text(Cancellation_Status__c), &quot;Green&quot;)) 
    )

*/

AND( 
Stage_Changed_On__c = TODAY(), 
OR( 
AND( 
RecordType.Name = &quot;Metrostudy Renewal Oppty Record Type&quot;, 
NOT(CONTAINS(TEXT(Cancellation_Status__c), &quot;Green&quot;)) 
), 
AND( 
RecordType.Name = &quot;MS Opportunity&quot;, 
FC_Cancellation_Revenue__c &lt; 0 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Include in Cancel Digest</inlineHelpText>
        <label>Include in Cancel Digest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeInRenewalDigest__c</fullName>
        <description>Include In Renewal Digest</description>
        <formula>/* 
 @Description  Returns true if Opportunity is cancelled today and the Record Type is MS or Metro
 @changelog   MG/10K 18/11 Changed to new criteria 
*/ 

AND (
   Stage_Changed_On__c = TODAY(),
   IsClosed,
   Renewal__c,
  OR ( 
        ISPICKVAL(StageName, &quot;Closed Won&quot;), 
        ISPICKVAL(StageName, &quot;Active&quot;) 
        )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Include In Renewal Digest</inlineHelpText>
        <label>Include In Renewal Digest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeInWinDigest__c</fullName>
        <description>Include in Win Digest</description>
        <formula>/*

 @Description Returns true if Opportunity is Won today and the Record Type is MS or Metro
 @changelog MG/10K 18/11 Changed to new criteria 
 

*/
    AND (
           Stage_Changed_On__c = TODAY(),
           OR ( 
                  ISPICKVAL(StageName, &quot;Closed Won&quot;), 
                  ISPICKVAL(StageName, &quot;Active&quot;) 
                  ),                      
           OR (
                  CONTAINS(RecordType.Name, &quot;MS&quot;),
                  CONTAINS(RecordType.Name, &quot;Metrostudy&quot;),
                  RecordType.Name = &quot;Record Lock&quot;,
                  AND(CONTAINS(RecordType.Name, &quot;Network&quot;),  FC_DBD_Revenue__c &gt; 0)
                  
                  
                ),
           OR(
                 TEXT(Channel_Type__c) = &quot;Direct&quot;,
                 TEXT(Channel_Type__c) = &quot;Inside Sales&quot;,
                 TEXT(Channel_Type__c) = &quot;Strategic Account&quot;,
                 TEXT(Channel_Type__c) = &quot;Templeton&quot;,
                 TEXT(Channel_Type__c) = &quot;BPM&quot;,
                 TEXT(Channel_Type__c) = &quot;Consulting&quot;
                 ),
           OR(
                                    
                                    NOT(Renewal__c)
                                    )
                 
               
        )
                      
                      /*                           
             AND(       
                            ISPICKVAL(StageName, &quot;Closed Won&quot;), 
                            OR (
                            CONTAINS(RecordType.Name, &quot;MS&quot;),
                            RecordType.Name = &quot;Metrostudy Opportunity Record Type Admin&quot;, 
                            RecordType.Name = &quot;Record Lock&quot;,
                             FC_DBD_Revenue__c &gt; 0
                            ),
                           OR(
                           TEXT(Channel_Type__c) = &quot;Direct&quot;,
                           TEXT(Channel_Type__c) = &quot;Inside Sales&quot;,
                           TEXT(Channel_Type__c) = &quot;Strategic Account&quot;,
                           TEXT(Channel_Type__c) = &quot;Templeton&quot;
                           TEXT(Channel_Type__c) = &quot;BPM&quot;,
                           TEXT)Channel_Type__c) = &quot;Consulting&quot;
                           ),
                           NOT(Closed_Won_Checkbox__c),
                               OR(
                                     TEXT(Channel_Type__c) = &quot;Templeton&quot;,
                                     RecordType.Name = &quot;Metrostudy Opportunity Record Type Consult&quot;
                                    ),
                                OR(
                                  
                                    NOT(Renewal__c)
                                    )
                                                                            
                    )
           )
           
    
)
                      /*                           
             AND(       
                            ISPICKVAL(StageName, &quot;Closed Won&quot;), 
                            OR (
                            CONTAINS(RecordType.Name, &quot;MS&quot;),
                            RecordType.Name = &quot;Metrostudy Opportunity Record Type Admin&quot;, 
                            RecordType.Name = &quot;Record Lock&quot;,
                             FC_DBD_Revenue__c &gt; 0
                            ),
                           OR(
                           TEXT( Purchase_Type__c)   &lt;&gt;  &quot;Price Increase Only&quot;,
                           ),
                           NOT(Closed_Won_Checkbox__c),
                               OR(
                                     TEXT(Channel_Type__c) = &quot;Templeton&quot;,
                                     RecordType.Name = &quot;Metrostudy Opportunity Record Type Consult&quot;
), 
OR(  
NOT(Renewal__c) 
) 
  
*/</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Include in Win Digest</inlineHelpText>
        <label>Include in Win Digest</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DailyDigestController.cls
/**
 * Created by mikegill on 05/10/2017
 */

public class DailyDigestController {

    public String digestFilter {get;set;}
    public String query {get;set;}
    String soqlString = ApexUtils.getObjectFields('Opportunity');

    public List<Opportunity> getopptys()

    {
        List<Opportunity> oppty;

        if (digestFilter == 'cancel'){
            query = 'SELECT ' + soqlString + ' ,Owner.Name FROM Opportunity where IncludeInCancelDigest__c = true';
        }


        else if (digestFilter == 'win'){
            query = 'SELECT ' + soqlString + ' ,Owner.Name FROM Opportunity where IncludeInWinDigest__c = true';
        }


        else if (digestFilter == 'renewal'){
            query = 'SELECT ' + soqlString + ' ,Owner.Name FROM Opportunity where IncludeInRenewalDigest__c = true';
        }

        oppty = Database.query(query); // Fetch my data

        return oppty; // return my data
    }



}