src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Skip_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Validation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>FC_Eligible_to_Cancel_End_Date__c</fullName>
        <label>(FC) Eligible to Cancel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Eligible_to_Cancel_Start_Date__c</fullName>
        <label>(FC) Eligible to Cancel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Latest_Charge_Effective_Date__c</fullName>
        <label>(FC) Latest Charge Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_One_Time_Charge_Count__c</fullName>
        <label>(FC) One-Time Charge Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Override_Eligible_to_Cancel_Dates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Override Eligible to Cancel Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Recurring_Charge_Count__c</fullName>
        <label>(FC) Recurring Charge Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpportunityID__c</fullName>
        <label>Opportunity ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>FC_Eligible_to_Cancel_End_Date__c</fullName>
        <label>(FC) Eligible to Cancel End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_Eligible_to_Cancel_Start_Date__c</fullName>
        <label>(FC) Eligible to Cancel Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FC_One_If_One_Time_Charge__c</fullName>
        <formula>IF(TEXT(Zuora__Type__c) == &quot;One-Time&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) One If One-Time Charge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_One_If_Recurring_Charge__c</fullName>
        <formula>IF(TEXT(Zuora__Type__c) == &quot;Recurring&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) One If Recurring Charge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveStartDate__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ZuoraSubscriptionHandler.cls
global without sharing class FC_ZuoraSubscriptionHandler extends fcf.TriggerAdapter {

    private static final String TRIGGER_RUN_STATUS_ID = 'FC_ZuoraSubscriptionHandler';

    // Before phase
    private Map<String, Contract> subscriptionNumberToContractMap = new Map<String, Contract>();
    private Map<ID, Opportunity> opportunityLookupMap = new Map<ID, Opportunity>();

    // After phase
    private Map<ID, Account> accountsToUpdateMap = new Map<ID, Account>();
    //private Map<ID, Opportunity> opportunitiesToUpdateMap = new Map<ID, Opportunity>();
    private Map<ID, Contract> contractsToUpdateMap = new Map<ID, Contract>();

    global override void bulkBefore() {

        if (Trigger.isInsert || Trigger.isUpdate) {

            Set<Id> opportunityIdsToLookup = new Set<Id>();

            for (SObject so : Trigger.new) {
                Zuora__Subscription__c subscriptionRecord = (Zuora__Subscription__c) so;
                if (String.isNotBlank(subscriptionRecord.OpportunityID__c)) {
                    try {
                        opportunityIdsToLookup.add(Id.valueOf(subscriptionRecord.OpportunityID__c));
                    } catch (Exception e) {
                        // Ignore invalid opportunity IDs
                    }
                }
            }

            opportunityLookupMap.putAll(FC_OpportunityCache.findByIds(opportunityIdsToLookup));

        }

    }

    global override void beforeInsert(SObject so) {
        Zuora__Subscription__c newSubscriptionRecord = (Zuora__Subscription__c) so;

        populateFields(newSubscriptionRecord);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        Zuora__Subscription__c newSubscriptionRecord = (Zuora__Subscription__c) so;

        populateFields(newSubscriptionRecord);
    }

    global override void finallyBefore() {

        // Initialize aggregate fields
        for (SObject so : Trigger.new) {
            Zuora__Subscription__c subscriptionRecord = (Zuora__Subscription__c) so;
            subscriptionRecord.FC_One_Time_Charge_Count__c = 0;
            subscriptionRecord.FC_Recurring_Charge_Count__c = 0;
            subscriptionRecord.FC_Latest_Charge_Effective_Date__c = null;
            if (!subscriptionRecord.FC_Override_Eligible_to_Cancel_Dates__c) {
                subscriptionRecord.FC_Eligible_to_Cancel_Start_Date__c = null;
                subscriptionRecord.FC_Eligible_to_Cancel_End_Date__c = null;
            }
        }

        // Aggregate charge records
        if (Trigger.isUpdate) {

            for (AggregateResult ar : [
                    select Zuora__Subscription__c,
                            sum(FC_One_If_One_Time_Charge__c) countOneTimeCharges,
                            sum(FC_One_If_Recurring_Charge__c) countRecurringCharges,
                            max(Zuora__EffectiveStartDate__c) latestEffectiveStartDate,
                            min(FC_Eligible_to_Cancel_Start_Date__c) earliestEligibleToCancelDate,
                            max(FC_Eligible_to_Cancel_End_Date__c) latestEligibleToCancelDate
                    from Zuora__SubscriptionProductCharge__c
                    where Zuora__Subscription__c in :Trigger.newMap.keySet()
                    group by Zuora__Subscription__c
            ]) {
                Zuora__Subscription__c subscriptionRecord =
                        (Zuora__Subscription__c) Trigger.newMap.get((Id) ar.get('Zuora__Subscription__c'));
                subscriptionRecord.FC_One_Time_Charge_Count__c = (Decimal) ar.get('countOneTimeCharges');
                subscriptionRecord.FC_Recurring_Charge_Count__c = (Decimal) ar.get('countRecurringCharges');
                subscriptionRecord.FC_Latest_Charge_Effective_Date__c = (Date) ar.get('latestEffectiveStartDate');
                if (!subscriptionRecord.FC_Override_Eligible_to_Cancel_Dates__c) {
                    subscriptionRecord.FC_Eligible_to_Cancel_Start_Date__c = (Date) ar.get('earliestEligibleToCancelDate');
                    subscriptionRecord.FC_Eligible_to_Cancel_End_Date__c = (Date) ar.get('latestEligibleToCancelDate');
                }
            }

        }

    }

    global override void bulkAfter() {
        if (Trigger.isInsert || Trigger.isUpdate || Trigger.isUndelete) {

            Set<String> subscriptionNumberToLookup = new Set<String>();
            for (SObject so : Trigger.new) {
                Zuora__Subscription__c subscriptionRecord = (Zuora__Subscription__c) so;
                subscriptionNumberToLookup.add(subscriptionRecord.Name);
            }
            subscriptionNumberToContractMap.putAll(FC_ContractCache.findBySubscriptionNumbers(subscriptionNumberToLookup));
        }
    }

    global override void afterInsert(SObject so) {
        Zuora__Subscription__c newSubscriptionRecord = (Zuora__Subscription__c) so;

        includeAccountForUpdate(newSubscriptionRecord);
        includeContractForUpdate(newSubscriptionRecord);
        //includeOpportunityForUpdate(newSubscriptionRecord);
    }

    global override void afterUpdate(SObject oldSo, SObject so) {
        Zuora__Subscription__c newSubscriptionRecord = (Zuora__Subscription__c) so;

        includeAccountForUpdate(newSubscriptionRecord);
        includeContractForUpdate(newSubscriptionRecord);
        //includeOpportunityForUpdate(newSubscriptionRecord);
    }

    global override void afterDelete(SObject so) {
        Zuora__Subscription__c oldSubscriptionRecord = (Zuora__Subscription__c) so;

        includeAccountForUpdate(oldSubscriptionRecord);
    }

    global override void afterUndelete(SObject so) {
        Zuora__Subscription__c newSubscriptionRecord = (Zuora__Subscription__c) so;

        includeAccountForUpdate(newSubscriptionRecord);
        includeContractForUpdate(newSubscriptionRecord);
        //includeOpportunityForUpdate(newSubscriptionRecord);
    }

    global override void finallyAfter() {

        fcf.TriggerRunStatusItem fcfTriggerRunStatusItem =
                new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID);
        if (!fcf.TriggerRunStatus.isRunnable(fcfTriggerRunStatusItem)) {
            return;
        }
        fcf.TriggerRunStatus.block(fcfTriggerRunStatusItem);

        if (!accountsToUpdateMap.isEmpty()) {
            update accountsToUpdateMap.values();
            accountsToUpdateMap.clear();
        }

        if (!contractsToUpdateMap.isEmpty()) {
            update contractsToUpdateMap.values();
            contractsToUpdateMap.clear();
        }

//        if (!opportunitiesToUpdateMap.isEmpty()) {
//            update opportunitiesToUpdateMap.values();
//            opportunitiesToUpdateMap.clear();
//        }

    }

    private void populateFields(Zuora__Subscription__c subscriptionRecord) {

        // Populate Opportunity
        subscriptionRecord.Opportunity__c = null;
        try {
            if (String.isNotBlank(subscriptionRecord.OpportunityID__c) &&
                    opportunityLookupMap.containsKey(Id.valueOf(subscriptionRecord.OpportunityID__c))) {
                subscriptionRecord.Opportunity__c = Id.valueOf(subscriptionRecord.OpportunityID__c);
            }
        } catch (Exception e) {
            // Ignore invalid opportunity IDs
        }

    }

    private void includeAccountForUpdate(Zuora__Subscription__c subscriptionRecord) {
        if (subscriptionRecord.Zuora__Account__c != null) {
            accountsToUpdateMap.put(subscriptionRecord.Zuora__Account__c,
                    new Account(Id = subscriptionRecord.Zuora__Account__c));
        }
    }

//    private void includeOpportunityForUpdate(Zuora__Subscription__c subscriptionRecord) {
//        if (subscriptionRecord.Opportunity__c != null) {
//            opportunitiesToUpdateMap.put(subscriptionRecord.Opportunity__c,
//                    new Opportunity(Id = subscriptionRecord.Opportunity__c, Skip_Validation__c = true));
//        }
//    }

    private void includeContractForUpdate(Zuora__Subscription__c subscriptionRecord) {
        if (subscriptionNumberToContractMap.containsKey(subscriptionRecord.Name)) {
            contractsToUpdateMap.put(subscriptionNumberToContractMap.get(subscriptionRecord.Name).Id,
                    new Contract(Id = subscriptionNumberToContractMap.get(subscriptionRecord.Name).Id));
        }
    }

}