src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>What channel does the deal belong to?</description>
        <inlineHelpText>What channel does the deal belong to?</inlineHelpText>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BPM</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>REE</fullName>
                </value>
                <value>
                    <fullName>Strategic Account</fullName>
                </value>
                <value>
                    <fullName>Templeton</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_DBD_Revenue__c</fullName>
        <formula>IF(FC_Opportunity_Line_Item_Count__c == 0, 
    Amount, 
    IF(FC_Pay_DBD_Rollup__c == 0,
        FC_New_Revenue__c + FC_Upsell_Revenue__c + FC_Price_Increase_Decrease__c + 
            IF(FC_New_Revenue__c &gt; 0 || FC_Upsell_Revenue__c &gt; 0 || FC_Price_Increase_Decrease__c &gt; 0, 
                FC_Cancellation_Revenue__c, 0),
        DBD_Override_Roll_Up__c
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DBD Revenue Summary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_New_Revenue__c</fullName>
        <label>(FC) New Revenue</label>
        <summarizedField>OpportunityLineItem.FC_New_Revenue_Formula__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>MS_Territory_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MS Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>One_time_Sale_Type__c</fullName>
        <label>Sale Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Briefing Attendance</fullName>
                </value>
                <value>
                    <fullName>Briefing Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Consulting/Engagement</fullName>
                </value>
                <value>
                    <fullName>Consumer Segmentation</fullName>
                </value>
                <value>
                    <fullName>Custom Export/Report</fullName>
                </value>
                <value>
                    <fullName>Database Access</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Internet Sales</fullName>
                </value>
                <value>
                    <fullName>Land Planning Optimization</fullName>
                </value>
                <value>
                    <fullName>Mailing List</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Private Consult</fullName>
                </value>
                <value>
                    <fullName>Speaking Engagement</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Type__c</fullName>
        <label>Purchase Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>One-time</fullName>
                </value>
                <value>
                    <fullName>Price Increase Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a renewal?</description>
        <label>Renewal?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Media</fullName>
        <active>true</active>
        <businessProcess>Media</businessProcess>
        <label>HW_Media</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>FC_DBD_Revenue__c</fullName>
        <formula>IF(FC_Pay_DBD__c &amp;&amp; !ISBLANK(FC_DBD_Percentage__c), TotalPrice * FC_DBD_Percentage__c, TotalPrice)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) DBD Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_New_Revenue_Formula__c</fullName>
        <formula>IF(ISPICKVAL(FC_Purchase_Type__c , &quot;New&quot;), 
    IF(FC_Annualize_New_Revenue__c, 
        FC_Annualized_Amount__c, TotalPrice), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>(FC) New Revenue*</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FC_New_Revenue__c</fullName>
        <label>xx_(FC) New Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FC_Pay_DBD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(FC) Pay DBD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Purchase_Type__c</fullName>
        <label>(FC) Purchase Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Renewal Upsell</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancellation - Reversal</fullName>
                </value>
                <value>
                    <fullName>Restructure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FC_Seg3__c</fullName>
        <formula>TEXT(FC_Product_Geography_Seg3__r.Seg3__c)</formula>
        <label>Seg3</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>MetrostudyIncludeOnWebsite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include On Website</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GaugeChartControllerQTD_User.cls
public class GaugeChartControllerQTD_User {
    public String ExecId {get;set;}
    public String UserId {get;set;}
    public String UserName {get;set;}
    public String dashboardId {get;set;}
    public String dateRange {get;set;}
    
    public List<SelectOption> UserOptions { get;set; }
    
    public Integer minVal = 0;
    public Integer maxVal = 1000;   // real value calculated in code
    
    public Double salesVal = 0;
    public Double percentVal = 0;
    
    public Object objQuota;
    public Object UserResult;
    public Object objOpportunityRollupClosed;
    public Dashboard dashboardResults;
    public Dashboard runAs;
    
    public GaugeChartControllerQTD_User(){
        getData();
        }
        
    public void getData() {
       dashboardId = '01Z34000001CFZm';
         
       Map<String, String> family = new Map<String, String>{'INFO' => 'Direct', 'BPMS' => 'BPM', 'CONS' => 'Consultant'};
       
       Integer thisMonth = date.Today().month();
       Integer thisYear = date.Today().Year();
       
       Date qryEndDate = date.newinstance(thisYear, 12, 31);
       Date qryBegDate = date.newinstance(thisYear, 1, 1);
       
      if(thisMonth <= 3){
        qryEndDate = date.newinstance(thisYear, 3, 31);
        qryBegDate = date.newinstance(thisYear, 1, 1);
       }
      else if(thisMonth <= 6){
        qryEndDate = date.newinstance(thisYear, 6, 30);
        qryBegDate = date.newinstance(thisYear, 4, 1);
            }
      else if(thisMonth <= 9){
        qryEndDate = date.newinstance(thisYear, 9, 30);
        qryBegDate = date.newinstance(thisYear, 7, 1);
            }
      else if(thisMonth <= 12){
        qryEndDate = date.newinstance(thisYear, 12, 31);
        qryBegDate = date.newinstance(thisYear, 10, 1);
            }
            
       
       ExecId = (ExecId == null) ? 'All' : ExecId;    // default to 'All'
       
       Dashboard[] dashboardResults = [
               SELECT Id, runningUser.id, runningUser.name 
               FROM Dashboard 
               WHERE id = :dashboardId
               ];
       
       UserId = (dashboardResults == null || dashboardResults.size() == 0) ? UserInfo.getUserId() : dashboardResults[0].runningUser.id;    // default to current user (need to have a valid user ID)
       UserName = (dashboardResults == null || dashboardResults.size() == 0) ? UserInfo.getUserName() : dashboardResults[0].runningUser.name;
       
       //overwrite them for the logged in user
       //UserId = UserInfo.getUserId();    // default to current user (need to have a valid user ID)
       //UserName = UserInfo.getUserName();
       
       ///////////////////////////////////////////////////////////////
       //Grab the opty totals or actuals
       if(ExecId.containsIgnoreCase('All')) {   // all was implicitly selected
            //Act Values
            AggregateResult[] groupedResults = [Select SUM(Opportunity.FC_DBD_Revenue__c) TotalPrice
            FROM Opportunity WHERE Id IN (SELECT opportunityId
            FROM OpportunityLineItem 
           WHERE 
            Opportunity.One_time_Sale_Type__c != ''
            AND Opportunity.Amount != 0
            AND Opportunity.StageName NOT IN ('Renewal','Price Increase')
            AND Opportunity.Purchase_Type__c != 'Price Increase Only'
            AND (Opportunity.Renewal__c = False
            OR  (Opportunity.Renewal__c = True
            AND FC_Pay_DBD__c = True))
            AND Opportunity.One_time_Sale_Type__c NOT IN ('Consulting/Engagement','Land Planning Optimization') 
            AND (FC_New_Revenue__c != 0
            OR (FC_Pay_DBD__c = True
            AND FC_New_Revenue__c = 0))
            AND Opportunity.Purchase_Type__c != 'Restructure'
            
            AND ((Opportunity.Probability = 100
            AND Opportunity.RecordType.Name NOT IN ('Metrostudy Renewal Oppty Record Type'))
            
            OR (Opportunity.Probability IN (0,100)
            AND Opportunity.RecordType.Name IN ('Metrostudy Renewal Oppty Record Type')))
            
            AND Opportunity.MS_Territory_Owner__c = :UserId
            AND Opportunity.CloseDate >= :qryBegDate
            AND Opportunity.CloseDate <= :qryEndDate
            )            
            
            ];       
            objOpportunityRollupClosed = groupedResults[0].get('TotalPrice');
            
            //Max Values
            AggregateResult[] quotaResults = [
            SELECT SUM(QuotaAmount) Quota 
            FROM ForecastingQuota 
            WHERE QuotaOwnerId = :UserId 
            AND StartDate >= :qryBegDate 
            AND StartDate <= :qryEndDate
            AND (ProductFamily = :family.get('INFO')
            OR ProductFamily = :family.get('BPM')
            OR ProductFamily = :family.get('Consultant'))
            
            ];
            objQuota = quotaResults[0].get('Quota');
            maxVal = Integer.valueOf(objQuota);      
            
            }
       else {   // A Dept Was Selected
            AggregateResult[] groupedResults = [Select SUM(FC_DBD_Revenue__c)  TotalPrice
            FROM OpportunityLineItem 
            WHERE 
            Opportunity.Amount != 0
            AND Opportunity.StageName IN ('Active','Closed Won','Rev Reversal')
            AND Opportunity.Channel_Type__c != ''
            AND Opportunity.RecordType.Name IN ('MS Opportunity', 'Metrostudy Opportunity Record Type Admin',
                'Metrostudy Opportunity Record Type Consult','MS - Opportunity BPM','Metrostudy Opportunity - REE',
                'Media - Network')
            
            AND (NOT Opportunity.Purchase_Type__c LIKE '%Price Increase Only%')
            AND Opportunity.MS_Territory_Owner__c = :UserId
            AND FC_Seg3__c = :ExecId

            AND Opportunity.CloseDate >= :qryBegDate 
            AND Opportunity.CloseDate <= :qryEndDate 
            
            //Added 5/9/18 per Howard
            AND (FC_New_Revenue_Formula__c != 0
            OR (FC_New_Revenue_Formula__c = 0
            AND FC_Pay_DBD__c = True))
            //End 5/9/18
            
            AND FC_Purchase_Type__c != 'Restructure'
            AND (Opportunity.Renewal__c = False
            OR  (Opportunity.Renewal__c = True
            AND FC_Pay_DBD__c = True))
            
            ];       
            objOpportunityRollupClosed = groupedResults[0].get('TotalPrice');
            
            String f = family.get(ExecId);

            //Max Values
            AggregateResult[] quotaResults = [
            SELECT SUM(QuotaAmount) Quota 
            FROM ForecastingQuota 
            WHERE QuotaOwnerId = :UserId 
            AND StartDate >= :qryBegDate 
            AND StartDate <= :qryEndDate
            AND ProductFamily = :f
            
            ];
            objQuota = quotaResults[0].get('Quota');
            maxVal = Integer.valueOf(objQuota);      
            
            }
            
            
       salesVal = Integer.valueOf(objOpportunityRollupClosed);    
       salesVal = (salesVal  == null) ? 0 : salesVal ;   
       
       maxVal = (maxVal  == null) ? 0 : maxVal ;   
       
       If(maxVal != 0)
       {
           percentVal = Double.valueOf((salesVal / maxVal) * 100 ).round();
           //percentVal = maxVal;
       }else
       {
           percentVal = 0;
       }
       
    }
    
    
    public void setExecId(String sExecId) {
        ExecId = sExecId;        
        }    

    public Double getSalesVal() {
        return salesVal;
        }
        
    public Integer getMaxValue() {
        return maxVal;
        }
    public Double getPercentVal() {
        return percentVal;
        }


    public void autoRun()
    {          
        UserOptions = new list<SelectOption>();
            
        
        for (User u : [
            SELECT ID,name 
            FROM user 
            WHERE (Username LIKE '%metrostudy%' 
            OR Email LIKE '%metrostudy%')
            AND Profile.Name LIKE '%sales%' 
            AND IsActive = True
            AND Title NOT IN ('Regional Director','Director of Published Research')
            AND MetrostudyIncludeOnWebsite__c = True
            AND (NOT Profile.Name LIKE '%consulting%')
            AND (NOT Profile.Name LIKE '%bpm%')
            AND (NOT Profile.Name LIKE '%management%')
           
            ])
        {
            UserOptions.add(new SelectOption(u.ID,u.Name ) );
        }
    }
    
    public void checkValue()
    {
        System.debug('----------------'+UserId);
    }

 
}