src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Metrostudy_Opportunity_REE</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <label>MS_Metrostudy Opportunity - REE</label>
    </recordTypes>
    <recordTypes>
        <fullName>Metrostudy_Opportunity_Record_Type_Consult</fullName>
        <active>true</active>
        <businessProcess>CPQ Sales Process</businessProcess>
        <description>Use for MS Consulting Opps</description>
        <label>MS_Metrostudy Opportunity Record Type Consult</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Status__c</fullName>
        <description>The Status of the Quote.</description>
        <inlineHelpText>The Status of the Quote.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent to Z-Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_NewQuoteController.cls
public class FC_NewQuoteController {

    private static final Set<String> MULTI_QUOTE_RECORD_TYPE_DEVELOPER_NAMES = new Set<String> {
            'Metrostudy_Opportunity_Record_Type_Consult', 'Metrostudy_Opportunity_REE' };
        
    private final Opportunity record;
    
    public FC_NewQuoteController(ApexPages.StandardController standardController) {
        this.record = (Opportunity) standardController.getRecord();
    }

    public PageReference redirect() {
        PageReference prResult = null;
        Integer sentToZBillingQuoteCount = [select count() from zqu__Quote__c 
                                            where zqu__Opportunity__c = :record.Id 
                                            and zqu__Status__c = 'Sent to Z-Billing'];    
        if ((record.RecordTypeId != null && MULTI_QUOTE_RECORD_TYPE_DEVELOPER_NAMES.contains(record.RecordType.DeveloperName)) || 
                sentToZBillingQuoteCount == 0) {
            prResult = Page.zqu__QuoteOption;
            prResult.getParameters().put('id', record.Id);
            prResult.setRedirect(true);
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                                                       'A quote on this opportunity has already been sent to Z-Billing.'));
        }
        return prResult;
    }
    
}