src/objects/Plan__c.object
<CustomObject>
    <description>MG_Plan</description>
    <fields>
        <fullName>Display_in_Zonda__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display in Zonda</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Garage__c</fullName>
        <label>Garage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Baths__c</fullName>
        <label># of Baths</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Beds__c</fullName>
        <label># of Beds</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Floors__c</fullName>
        <label># of Floors</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Full_Baths__c</fullName>
        <label># of Full Baths</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Half_Baths__c</fullName>
        <label># of Half Baths</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Market__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Off-Market</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Notes__c</fullName>
        <label>Plan Notes</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Unchanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Price Unchanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Update_Request__c.object
<CustomObject>
    <description>MG_Plan Update Request</description>
    <fields>
        <fullName>Display_in_Zonda__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display in Zonda</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Garage__c</fullName>
        <label>Garage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Baths__c</fullName>
        <label># of Baths</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Beds__c</fullName>
        <label># of Beds</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Floors__c</fullName>
        <label># of Floors</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Full_Baths__c</fullName>
        <label># of Full Baths</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Half_Baths__c</fullName>
        <label># of Half Baths</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Market__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Off-Market</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>New Plan Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Notes__c</fullName>
        <label>Plan Notes</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Update Requests</relationshipLabel>
        <relationshipName>Plan_Update_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Price_Unchanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Price Unchanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Request_Status__c</fullName>
        <label>Update Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plan Update Request</label>
    <nameField>
        <displayFormat>PLUR-{0000000}</displayFormat>
        <label>Plan Update Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Update Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrgPlanUpdateRequestsHandler.cls
public with sharing class TrgPlanUpdateRequestsHandler {
	/**
	// 		this method will analyze the Plan Update Requests received and if they're in an approved state [and weren't before], it'll go update the corresponding
	// 		Plans -- this is very likely to be called as part of a cascading update when a Project Update Request gets approved
	*/
	public static void ApprovePlanUpdateRequests(String triggerContext, List<Plan_Update_Request__c> triggerNew, Map<Id, Plan_Update_Request__c> triggerNewMap, List<Plan_Update_Request__c> triggerOld, Map<Id, Plan_Update_Request__c> triggerOldMap) {
		Set<Id> planIdsToUpdate = new Set<Id>();
		Map<Id, Plan__c> mapPlanIdsToPlans = new Map<Id, Plan__c>();
		List<Plan__c> plansToUpdate = new List<Plan__c>();
		Set<Id> planIdsGettingUpdated = new Set<Id>();
		List<Plan_Update_Request__c> plursToApprove = new List<Plan_Update_Request__c>();
		// check each plan update request to see if it's approved now and wasn't before
		for (Plan_Update_Request__c plur : triggerNew) {
			if (plur.Update_Request_Status__c == 'Approved') {
				if (Trigger.isInsert) {
					plursToApprove.add(plur);
					planIdsToUpdate.add(plur.Plan__c);
				} else if (Trigger.isUpdate) {
					if (triggerOldMap.get(plur.Id).Update_Request_Status__c != 'Approved') {
						plursToApprove.add(plur);
						planIdsToUpdate.add(plur.Plan__c);
					}
				}
			}
		}
		// get all the plans in a map
		mapPlanIdsToPlans = new Map<Id, Plan__c>([SELECT Id, Num_of_Beds__c, Off_Market__c, Num_of_Baths__c, Num_of_Full_Baths__c, Num_of_Half_Baths__c, Name, Price__c, Square_Footage__c, Plan_Notes__c, Num_of_Floors__c, Garage__c, Price_Unchanged__c FROM Plan__c WHERE Id IN :planIdsToUpdate]);
		// loop through the plan update requests and set the fields on the plans with the updated values, then add them to plansToUpdate
		for (Plan_Update_Request__c plur : plursToApprove) {
			if (null != mapPlanIdsToPlans.get(plur.Plan__c)) {
				Plan__c thePlan = mapPlanIdsToPlans.get(plur.Plan__c);
				thePlan.Num_of_Baths__c = plur.Num_of_Baths__c;
				thePlan.Num_of_Full_Baths__c = plur.Num_of_Full_Baths__c;
				thePlan.Num_of_Half_Baths__c = plur.Num_of_Half_Baths__c;
				thePlan.Num_of_Beds__c = plur.Num_of_Beds__c;
				thePlan.Price__c = plur.Price__c;
				thePlan.Square_Footage__c = plur.Square_Footage__c;
				thePlan.Name = plur.Plan_Name__c;
				thePlan.Plan_Notes__c = plur.Plan_Notes__c;
				thePlan.Num_of_Floors__c = plur.Num_of_Floors__c;
				thePlan.Garage__c = plur.Garage__c;
				thePlan.Price_Unchanged__c = plur.Price_Unchanged__c;
				thePlan.Display_in_Zonda__c = plur.Display_in_Zonda__c;
				thePlan.Off_Market__c = plur.Off_Market__c;
				//thePlan.Display_in_Zonda__c = true;
				if (!planIdsGettingUpdated.contains(thePlan.Id)) {
					planIdsGettingUpdated.add(thePlan.Id);
					plansToUpdate.add(thePlan);
				}
			}
		}
		// update the plansToUpdate collection
		update plansToUpdate;
	}
}