src/objects/Plan__c.object
<CustomObject>
    <description>MG_Plan</description>
    <fields>
        <fullName>Num_of_Baths__c</fullName>
        <label># of Baths</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Beds__c</fullName>
        <label># of Beds</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Unchanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Price Unchanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Snapshot__c.object
<CustomObject>
    <description>MG_Plan Snapshot</description>
    <fields>
        <fullName>Num_of_Baths__c</fullName>
        <label># of Baths</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Num_of_Beds__c</fullName>
        <label># of Beds</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Snapshots</relationshipLabel>
        <relationshipName>Plan_Snapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Plan Snapshots</relationshipLabel>
        <relationshipName>Plan_Snapshots</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Plan Snapshot</label>
    <nameField>
        <displayFormat>PLS{0000} {MM}-{DD}-{YYYY}</displayFormat>
        <label>Plan Snapshot Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrgPlansHandler.cls
public with sharing class TrgPlansHandler {
	public static void CreatePlanSnapshots(String triggerContext, List<Plan__c> triggerNew, Map<Id, Plan__c> triggerNewMap, List<Plan__c> triggerOld, Map<Id, Plan__c> triggerOldMap) {
		List<Plan_Snapshot__c> snapshotsToInsert = new List<Plan_Snapshot__c>();
		for (Plan__c oldPlan : triggerOld) {
			if (oldPlan.Price__c != triggerNewMap.get(oldPlan.Id).Price__c || triggerNewMap.get(oldPlan.Id).Price_Unchanged__c) {
				Plan_Snapshot__c newSnap = new Plan_Snapshot__c(
					Num_of_Baths__c = oldPlan.Num_of_Baths__c
				,	Num_of_Beds__c = oldPlan.Num_of_Beds__c
				,	Price__c = oldPlan.Price__c
				,	Plan__c = oldPlan.Id
				,	Project__c = oldPlan.Project__c
				,	Square_Footage__c = oldPlan.Square_Footage__c
					);
				snapshotsToInsert.add(newSnap);
			}
		}
		insert snapshotsToInsert;
	}
}