src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Alternate_Phone_Number__c</fullName>
        <label>Alternate Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City (legacy)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County (legacy)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Do_Not_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Special__c</fullName>
        <label>Email/Special</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIPS__c</fullName>
        <label>FIPS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <label>Monthly HOA #1</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Master_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Plan</label>
        <referenceTo>Master_Plan__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Price__c</fullName>
        <label>Max Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Unit_Size__c</fullName>
        <label>Max Unit Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Price__c</fullName>
        <label>Min Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Unit_Size__c</fullName>
        <label>Min Unit Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attached</fullName>
                </value>
                <value>
                    <fullName>Detached</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Characteristics__c</fullName>
        <label>Project Characteristics</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Adult</fullName>
                </value>
                <value>
                    <fullName>Gated</fullName>
                </value>
                <value>
                    <fullName>High Rise (12+ Floors)</fullName>
                </value>
                <value>
                    <fullName>Mid-Rise (5-11 Floors)</fullName>
                </value>
                <value>
                    <fullName>Low Rise (1-4 Floors)</fullName>
                </value>
                <value>
                    <fullName>Affordable</fullName>
                </value>
                <value>
                    <fullName>Basement</fullName>
                </value>
                <value>
                    <fullName>Golf</fullName>
                </value>
                <value>
                    <fullName>LEED Certified</fullName>
                </value>
                <value>
                    <fullName>Mixed-Use</fullName>
                </value>
                <value>
                    <fullName>Ocean Views</fullName>
                </value>
                <value>
                    <fullName>Transit Oriented Development</fullName>
                </value>
                <value>
                    <fullName>Alley Load SFD</fullName>
                </value>
                <value>
                    <fullName>Carriage Homes</fullName>
                </value>
                <value>
                    <fullName>Cluster Detached</fullName>
                </value>
                <value>
                    <fullName>Condo Conversion</fullName>
                </value>
                <value>
                    <fullName>Condo Hotel</fullName>
                </value>
                <value>
                    <fullName>Condominiums</fullName>
                </value>
                <value>
                    <fullName>Detached Condo</fullName>
                </value>
                <value>
                    <fullName>Duplex/Duet</fullName>
                </value>
                <value>
                    <fullName>Elevator</fullName>
                </value>
                <value>
                    <fullName>Live-Work</fullName>
                </value>
                <value>
                    <fullName>Loft</fullName>
                </value>
                <value>
                    <fullName>Motorcourts</fullName>
                </value>
                <value>
                    <fullName>Multi-Builder Community</fullName>
                </value>
                <value>
                    <fullName>MultiGen</fullName>
                </value>
                <value>
                    <fullName>Net Zero Building</fullName>
                </value>
                <value>
                    <fullName>Paired Homes</fullName>
                </value>
                <value>
                    <fullName>Passive House Construction</fullName>
                </value>
                <value>
                    <fullName>Resort</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_ID__c</fullName>
        <label>Region ID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Office_Notes__c</fullName>
        <label>Sales Office Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Person_2__c</fullName>
        <label>Sales Person #2</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Person_Name__c</fullName>
        <label>Sales Person Name #1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rate__c</fullName>
        <label>Sales Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_and_Marketing_Firm__c</fullName>
        <label>Sales and Marketing Firm</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Update_Request__c.object
<CustomObject>
    <description>MG_Project Update Request</description>
    <fields>
        <fullName>Alternate_Phone_Number__c</fullName>
        <inlineHelpText>Alternate Phone Number</inlineHelpText>
        <label>Alternate Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Do_Not_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Special__c</fullName>
        <label>Email/Special</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIPS__c</fullName>
        <label>FIPS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HOA__c</fullName>
        <label>Monthly HOA #1</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Master_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Plan</label>
        <referenceTo>Master_Plan__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Price__c</fullName>
        <label>Max Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Unit_Size__c</fullName>
        <label>Max Unit Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Price__c</fullName>
        <label>Min Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Unit_Size__c</fullName>
        <label>Min Unit Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attached</fullName>
                </value>
                <value>
                    <fullName>Detached</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Characteristics__c</fullName>
        <label>Project Characteristics</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Adult</fullName>
                </value>
                <value>
                    <fullName>Gated</fullName>
                </value>
                <value>
                    <fullName>High Rise</fullName>
                </value>
                <value>
                    <fullName>Mid Rise</fullName>
                </value>
                <value>
                    <fullName>Riverside</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Update Requests</relationshipLabel>
        <relationshipName>Project_Update_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region_ID__c</fullName>
        <label>Region ID</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Office_Notes__c</fullName>
        <label>Sales Office Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Person_2__c</fullName>
        <label>Sales Person #2</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Person_Name__c</fullName>
        <label>Sales Person Name #1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_and_Marketing_Firm__c</fullName>
        <label>Sales and Marketing Firm</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Project Update Request</label>
    <nameField>
        <displayFormat>PUR-{000000}</displayFormat>
        <label>Project Update Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Update Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BuilderProjectMgmtApprovalExt.cls
public with sharing class BuilderProjectMgmtApprovalExt {

	private final Project_Update_Request__c theProjectUpdateRequest;

    public BuilderProjectMgmtApprovalExt(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest())
            stdController.addFields( new list<string>( Project_Update_Request__c.sobjecttype.getdescribe().fields.getmap().keyset() ) );
        this.theProjectUpdateRequest = (Project_Update_Request__c)stdController.getRecord();
    }

    public PageReference updateProject() {
        Project__c theProject = [SELECT City__c,
                                County__c,
                                Do_Not_Call__c,
                                Email_Special__c,
                                FIPS__c,
                                HOA__c,
                                Location__Longitude__s,
                                Location__Latitude__s,
                                Master_Plan__c,
                                Max_Price__c,
                                Max_Unit_Size__c,
                                Min_Price__c,
                                Min_Unit_Size__c,
                                Open_Date__c,
                                Phone_Number__c,
                                Product_Type__c,
                                Alternate_Phone_Number__c,
                                Sales_Office_Notes__c,
             //                 Email_Special__c,
                                Project_Characteristics__c,
                                Region_ID__c,
                                Sales_and_Marketing_Firm__c,
                                Sales_Person_2__c,
                                Sales_Person_Name__c,
                                Sales_Rate__c,
                                Sold_Out_Date__c,
                                State__c,
                                Status__c,
                                Total_Remaining__c,
                                Total_Units_Planned__c,
                                Total_Units_Sold__c,
                                Typical_Lot_Size__c,
                                Website__c,
                                Last_Updated_Date_Price__c,
                                Last_Update_User_Price__c,
                                Last_Updated_Date_Sales__c,
                                Last_Update_User_Sales__c,
                                Prices_Verified__c,
                                Sales_Verified__c,
                                Meyers_Notes__c
                                FROM Project__c WHERE Id = :theProjectUpdateRequest.Project__c];
        theProject.City__c = theProjectUpdateRequest.City__c;
        theProject.County__c = theProjectUpdateRequest.County__c;
        theProject.Do_Not_Call__c = theProjectUpdateRequest.Do_Not_Call__c;
        theProject.Email_Special__c = theProjectUpdateRequest.Email_Special__c;
        theProject.Alternate_Phone_Number__c = theProjectUpdateRequest.Alternate_Phone_Number__c;
        theProject.Sales_Office_Notes__c = theProjectUpdateRequest.Sales_Office_Notes__c;
        theProject.FIPS__c = theProjectUpdateRequest.FIPS__c;
        theProject.HOA__c = theProjectUpdateRequest.HOA__c;
        theProject.Location__Longitude__s = theProjectUpdateRequest.Location__Longitude__s;
        theProject.Location__Latitude__s = theProjectUpdateRequest.Location__Latitude__s;
        theProject.Master_Plan__c = theProjectUpdateRequest.Master_Plan__c;
        theProject.Max_Price__c = theProjectUpdateRequest.Max_Price__c;
        theProject.Max_Unit_Size__c = theProjectUpdateRequest.Max_Unit_Size__c;
        theProject.Min_Price__c = theProjectUpdateRequest.Min_Price__c;
        theProject.Min_Unit_Size__c = theProjectUpdateRequest.Min_Unit_Size__c;
        theProject.Open_Date__c = theProjectUpdateRequest.Open_Date__c;
        theProject.Phone_Number__c = theProjectUpdateRequest.Phone_Number__c;
        theProject.Product_Type__c = theProjectUpdateRequest.Product_Type__c;
        theProject.Project_Characteristics__c = theProjectUpdateRequest.Project_Characteristics__c;
        theProject.Region_ID__c = theProjectUpdateRequest.Region_ID__c;
        theProject.Sales_and_Marketing_Firm__c = theProjectUpdateRequest.Sales_and_Marketing_Firm__c;
        theProject.Sales_Person_2__c = theProjectUpdateRequest.Sales_Person_2__c;
        theProject.Sales_Person_Name__c = theProjectUpdateRequest.Sales_Person_Name__c;
        theProject.Sales_Rate__c = theProjectUpdateRequest.Sales_Rate__c;
        theProject.Sold_Out_Date__c = theProjectUpdateRequest.Sold_Out_Date__c;
        theProject.State__c = theProjectUpdateRequest.State__c;
        theProject.Status__c = theProjectUpdateRequest.Status__c;
        theProject.Total_Remaining__c = theProjectUpdateRequest.Total_Remaining__c;
        theProject.Total_Units_Planned__c = theProjectUpdateRequest.Total_Units_Planned__c;
        theProject.Total_Units_Sold__c = theProjectUpdateRequest.Total_Units_Sold__c;
        theProject.Typical_Lot_Size__c = theProjectUpdateRequest.Typical_Lot_Size__c;
        theProject.Website__c = theProjectUpdateRequest.Website__c;
        theProject.Prices_Verified__c = theProjectUpdateRequest.Prices_Verified__c;
        theProject.Sales_Verified__c = theProjectUpdateRequest.Sales_Verified__c;
        theProject.Meyers_Notes__c = theProjectUpdateRequest.Meyers_Notes__c;
        //theProject.Last_Updated_Date_Price__c = theProjectUpdateRequest.Last_Updated_Date_Price__c;
        //theProject.Last_Update_User_Price__c = theProjectUpdateRequest.Last_Update_User_Price__c;
        //theProject.Last_Updated_Date_Sales__c = theProjectUpdateRequest.Last_Updated_Date_Sales__c;
        //theProject.Last_Update_User_Sales__c = theProjectUpdateRequest.Last_Update_User_Sales__c;

        update theProject;

        theProjectUpdateRequest.Update_Request_Status__c = 'Approved';
        update theProjectUpdateRequest;

        ApexPages.PageReference whereToGo = new ApexPages.PageReference('/'+theProject.Id);
        return whereToGo;
    }
}