src/objects/Project__c.object
<CustomObject>
    <description>MG_Project</description>
    <fields>
        <fullName>Last_Updated_Date_Sales__c</fullName>
        <label>Last Updated Date (Sales)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Rate_Last_3_Months_calc__c</fullName>
        <inlineHelpText>This is calculated by the system nightly based on Project Snapshot records</inlineHelpText>
        <label>Sales Rate Last 3 Months (calc)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold_Out_Date__c</fullName>
        <label>Sold Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Units_Planned__c</fullName>
        <label>Total Units Planned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units_Sold__c</fullName>
        <label>Total Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchMaintProjectFields.cls
global class BatchMaintProjectFields implements Database.Batchable<sObject>, Schedulable {
	
	String query;

	// Schedulable Bit:
	global void execute(SchedulableContext SC) {
		BatchMaintProjectFields theBatch = new BatchMaintProjectFields();
		Database.executeBatch(theBatch);
	}

	// Batchable Bits:
	global BatchMaintProjectFields() {
		query = 'SELECT Id, Total_Units_Sold__c, Total_Units_Planned__c, Sales_Rate_Last_3_Months_calc__c, Open_Date__c, Sold_Out_Date__c, CreatedDate, Last_Updated_Date_Sales__c FROM Project__c';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Project__c> scope) {
   		List<Project__c> projectsToUpdate = MaintProjectFields.updateThreeMonthSalesRate(scope);
		if (null != projectsToUpdate && !projectsToUpdate.isEmpty()) {
			update projectsToUpdate;
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}