src/objects/WF_Archived_Project__c.object
<CustomObject>
    <fields>
        <fullName>Process_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to remove the record once Project Archived</description>
        <label>Process Done</label>
        <type>Checkbox</type>
    </fields>
    <label>WF Archived Project</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>WF Project Archive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF Archived Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WF_ArchivedProjectTriggerHandler.cls
/**
** Created Date : 27 June 2016
** Author : Mohit Gupta (Rainmaker)
*/
public class WF_ArchivedProjectTriggerHandler {
    
    public static void onAfterUpdate(list<WF_Archived_Project__c> newArchivedProjectList) {
        List<String> listProjectsIdsToDelete= new List<String>();
        for(WF_Archived_Project__c archivedProject : newArchivedProjectList) {
            if(archivedProject.Process_Done__c) {
                listProjectsIdsToDelete.add(archivedProject.Id);
            }
        }   
        deleteRecords(listProjectsIdsToDelete);
    }
    
    @future(callout=true)
    public static void deleteRecords(list<String> listProjectsIdsToDelete) {
        List<WF_Archived_Project__c> listProjectsToDelete= new List<WF_Archived_Project__c>();
        for(String archivedProject : listProjectsIdsToDelete) {
            listProjectsToDelete.add(new WF_Archived_Project__c(Id = archivedProject));
        }
        delete listProjectsToDelete;
    }
    
}