src/objects/WF_Archived_Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>WF_Project_Archives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to remove the record once Project Archived</description>
        <label>Process Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WF_Project_Id__c</fullName>
        <label>WF Project ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WF Archived Project</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>WF Project Archive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WF Archived Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WF_ArchivedProjectTriggerTest.cls
@isTest

private class WF_ArchivedProjectTriggerTest{

    static testMethod void testAfterUpdate(){
            
         
         Opportunity oppt = new Opportunity(Name ='New opp',StageName = 'Customer Won',Amount = 3000,CloseDate = System.today());
         insert oppt;
            
         WF_Archived_Project__c wf = new WF_Archived_Project__c();
         wf.Process_Done__c=true;
         wf.WF_Project_Id__c='2';
         wf.Opportunity__c=oppt.Id;
         insert wf;
         
         
         wf.WF_Project_Id__c='21';
         
         update wf;
   }

}