src/objects/Zonda_Contract__c.object
<CustomObject>
    <description>MG_Zonda Contract</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Zonda Contracts</relationshipLabel>
        <relationshipName>Zonda_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Creation_Date__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                    <isActive>false</isActive>
                    <label>A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RSD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Zonda_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_s__c</fullName>
        <label>Role(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Land Acquisition</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_End_Date__c</fullName>
        <defaultValue>DATE(2999,12,31)</defaultValue>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <label>Zonda Contract</label>
    <nameField>
        <label>Zonda Contract</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zonda Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAccounttype.cls
@isTest
private class TestAccounttype {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        
        Account accnt = new Account();
        accnt.name='test1';
        accnt.type='prospect';
        accnt.Industry='Banking';
        accnt.BillingPostalCode='590009';
        insert accnt;
        
        Zonda_Contract__c zoncon = new Zonda_Contract__c();
        zoncon.Name='contracttest';
        zoncon.Subscription_End_Date__c = date.today()+30;
        zoncon.RSD__c=u.id;
        zoncon.Contract_Creation_Date__c = date.today()-5;
        zoncon.Account__c=accnt.id;
        zoncon.Role_s__c='Sales & Marketing';
        zoncon.contract_status__c='Expired';
        insert zoncon;
        
        zoncon.contract_status__c='Active';
       update zoncon;
    }
}