src/objects/Zonda_User_Group__c.object
<CustomObject>
    <description>MG_Zonda User Group: This object links with m_customer_master</description>
    <fields>
        <fullName>Coverage_String__c</fullName>
        <description>All coverage strings from related contracts combined</description>
        <label>Coverage String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Zonda User Group</label>
    <nameField>
        <label>Zonda User Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zonda User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZondaContractCoverageManagerViewOnlyExt.cls
public with sharing class ZondaContractCoverageManagerViewOnlyExt {

    private Zonda_User_Group__c theCoverage;
    public String updatedCoverage {get; set;}

    public ZondaContractCoverageManagerViewOnlyExt(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new String[]{'Coverage_String__c'});
        }
        theCoverage = (Zonda_User_Group__c)stdController.getRecord();
        system.debug('Test'+theCoverage);
        updatedCoverage = theCoverage.Coverage_String__c;
        system.debug(updatedCoverage);
    }

    public PageReference apexUpdateCoverage() {
        system.debug('theCoverage.Coverage_String__c: '+theCoverage.Coverage_String__c);
        system.debug('updatedCoverage: '+updatedCoverage);
        theCoverage.Coverage_String__c = updatedCoverage;
        update theCoverage;
        //return new PageReference('/'+theCoverage.Id);
        return null;
    }
}