src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>FC_Lookup_Key__c</fullName>
        <externalId>true</externalId>
        <label>FC Lookup Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ProductRatePlanChargeHandler.cls
global without sharing class FC_ProductRatePlanChargeHandler extends fcf.TriggerAdapter {

    private Map<ID, zqu__ProductRatePlan__c> productRatePlanMap = new Map<ID, zqu__ProductRatePlan__c>();
    
    global override void bulkBefore() {
   	
    	Set<ID> productRatePlanIds = new Set<ID>();
        for (SObject so : Trigger.new) {
            zqu__ProductRatePlanCharge__c newCharge = (zqu__ProductRatePlanCharge__c) so;
            if (newCharge.zqu__ProductRatePlan__c != null) {
                productRatePlanIds.add(newCharge.zqu__ProductRatePlan__c);
            }
        }
        productRatePlanMap = new Map<ID, zqu__ProductRatePlan__c>([select Id, Name, zqu__ZProduct__r.zqu__SKU__c 
				from zqu__ProductRatePlan__c where Id in :productRatePlanIds]);
        
    }
    
    global override void beforeInsert(SObject so) {
	   	zqu__ProductRatePlanCharge__c newCharge = (zqu__ProductRatePlanCharge__c) so;
    	populateFcLookupKey(newCharge);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
	   	zqu__ProductRatePlanCharge__c newCharge = (zqu__ProductRatePlanCharge__c) so;
    	populateFcLookupKey(newCharge);
    }
    
    private void populateFcLookupKey(zqu__ProductRatePlanCharge__c charge) {
        zqu__ProductRatePlan__c ratePlan = productRatePlanMap.get(charge.zqu__ProductRatePlan__c);
        if (ratePlan != null) {
        	charge.FC_Lookup_Key__c = String.join(new String[] { ratePlan.zqu__ZProduct__r.zqu__SKU__c,
	            	rateplan.Name, charge.Name }, '^');
        }
    }
    
}