src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>AppStage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote template that is used to generate the Quote PDF or Word document.</description>
        <inlineHelpText>The Quote template that will be used to generate the Quote PDF or Word document.  If not selected, the user will select a quote template from a list of available quote templates when creating Quote PDF or Word document.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>zqu__Quote_Template__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Status__c</fullName>
        <description>The Status of the Quote.</description>
        <inlineHelpText>The Status of the Quote.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent to Z-Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Signed</fullName>
        <active>true</active>
        <label>Signed</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote_Template__c.object
<CustomObject>
    <description>Quote template for generate PDF or WORD</description>
    <fields>
        <fullName>zqu__IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate this template is the default one of the refer quote type</description>
        <inlineHelpText>Indicate this template is the default one of the refer quote type</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Quote_Type__c</fullName>
        <description>Quote types.</description>
        <inlineHelpText>Quote Type</inlineHelpText>
        <label>Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Subscription</fullName>
                    <default>true</default>
                    <label>New Subscription</label>
                </value>
                <value>
                    <fullName>Amend Subscription</fullName>
                </value>
                <value>
                    <fullName>Renew Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Template_Id__c</fullName>
        <description>The template Id in Zuora</description>
        <inlineHelpText>The template Id in Zuora</inlineHelpText>
        <label>Template Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Quote Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestNewManualAgreementController.cls
@isTest
private class FC_TestNewManualAgreementController {
    private static final String QUOTE_TEMPLATE_NAME = 'Test Quote Template';

    @testSetup
    static void setup(){
         Account testAccount = new Account(Name = 'TestAccount', BillingPostalCode = '12345');
        insert testAccount;
        
        Opportunity[] testOpportunities = new Opportunity[] {
                new Opportunity(Name = 'TestOpportunity', AccountId = testAccount.Id, 
                                StageName = 'New', CloseDate = Date.today())};
        insert testOpportunities;
        
        zqu__Quote_Template__c[] testQuoteTemplates = new zqu__Quote_Template__c[] {
                new zqu__Quote_Template__c(Name = QUOTE_TEMPLATE_NAME, zqu__IsDefault__c = true, 
                                           zqu__Quote_Type__c = 'New Subscription', zqu__Template_Id__c = '12345') };
        upsert testQuoteTemplates;

        zqu__Quote__c[] testQuotes = new zqu__Quote__c[] { 
                new zqu__Quote__c(Name = 'TestQuote', RecordTypeId = fcf.RecordTypeUtil.findByName('zqu__Quote__c.Default').Id, Approval_Status__c = '', 
                                  zqu__QuoteTemplate__c = testQuoteTemplates[0].Id, zqu__QuoteTemplate__r = testQuoteTemplates[0], zqu__Status__c = 'New',
                                  zqu__Opportunity__c = testOpportunities[0].Id)};
        insert testQuotes;
        
    }

    @isTest 
    static void test_OppAgreement() {

        test.startTest();

        List<Opportunity> oppList = [Select Id from Opportunity where name ='TestOpportunity'];

        System.assertEquals(1, oppList.size(), 'Opportunity Exists');

        PageReference  pageRef = Page.FC_NewManualAgreement;
         pageRef.getparameters().put('opportunityId',oppList[0].id);
        test.setCurrentPageReference(pageRef);

        FC_NewManualAgreementController mAgreement = new FC_NewManualAgreementController();

        mAgreement.clientAgreement.Name = 'Test';
        mAgreement.clientAgreement.echosign_dev1__Status__c = 'Signed';
        mAgreement.clientAgreement.echosign_dev1__Opportunity__c = oppList[0].id;
        mAgreement.clientAgreement.echosign_dev1__SignatureType__c = 'Written Signature';
        mAgreement.clientAgreement.echosign_dev1__DateSigned__c = Date.today();
        mAgreement.clientAgreement.Quote__c = null;

        mAgreement.CreateDocument();
        mAgreement.AgreementDocument.body = Blob.valueOf('Test');
        mAgreement.AgreementDocument.Name = 'TEts';

        PageReference pr = mAgreement.Save();

        System.assertNotEquals(null, pr);

        test.stopTest();


    }

    @isTest 
    static void test_QuoteAgreement() {

        test.startTest();

        List<zqu__Quote__c> quotesList = [Select Id from zqu__Quote__c where name ='TestQuote'];

        System.assertEquals(1, quotesList.size(), 'Quote Exists');

        PageReference  pageRef = Page.FC_NewManualAgreement;
         pageRef.getparameters().put('quoteId',quotesList[0].id);
        test.setCurrentPageReference(pageRef);

        FC_NewManualAgreementController mAgreement = new FC_NewManualAgreementController();

        mAgreement.clientAgreement.Name = 'Test';
        mAgreement.clientAgreement.echosign_dev1__Status__c = 'Signed';
        mAgreement.clientAgreement.echosign_dev1__Opportunity__c =null;
        mAgreement.clientAgreement.echosign_dev1__SignatureType__c = 'Written Signature';
        mAgreement.clientAgreement.echosign_dev1__DateSigned__c = Date.today();
        mAgreement.clientAgreement.Quote__c = quotesList[0].id;

        mAgreement.CreateDocument();
        mAgreement.AgreementDocument.body = Blob.valueOf('Test');
        mAgreement.AgreementDocument.Name = 'TEts';

        PageReference pr = mAgreement.Save();

        System.assertNotEquals(null, pr);

        test.stopTest();

        
    }
    
}