src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>FC_Lookup_Key__c</fullName>
        <externalId>true</externalId>
        <label>FC Lookup Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Type__c</fullName>
        <description>The Type of the Rate Plan Charge.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestProductRatePlanChargeHandler.cls
@isTest
public class FC_TestProductRatePlanChargeHandler {
    
    private static final String SIMPLE_PRODUCT_NAME = 'Test Simple Product';
    private static final String SIMPLE_PRODUCT_RATE_PLAN_NAME = 'Test Simple Product Rate Plan';
    private static final String SIMPLE_PRODUCT_RATE_PLAN_CHARGE_NAME = 'Test Simple Product Rate Plan Charge';
    private static final String CONSULTING_PRODUCT_NAME = 'Test Consulting Product';
    private static final String CONSULTING_PRODUCT_RATE_PLAN_NAME = 'Test Consulting Product Rate Plan';
    private static final String CONSULTING_PRODUCT_RATE_PLAN_CHARGE_NAME = 'Test Consulting Product Rate Plan Charge';
    private static final String ONE_TIME_CHARGE_PRODUCT_NAME = 'Test One-Time Charge Product';
    private static final String ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_NAME = 'Test One-Time Charge Product Rate Plan';
    private static final String ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_CHARGE_NAME = 'Test One-Time Charge Product Rate Plan Charge';
    
    private static testmethod void testInsert() {
        TestDataStruct testData = setup();
        enableTriggerHandlers();
        Test.startTest();
        Map<String, zqu__ProductRatePlanCharge__c> testProductRatePlanChargesMap = new Map<String, zqu__ProductRatePlanCharge__c> {
                SIMPLE_PRODUCT_RATE_PLAN_CHARGE_NAME => new zqu__ProductRatePlanCharge__c(Name = SIMPLE_PRODUCT_RATE_PLAN_CHARGE_NAME, 
                        zqu__ProductRatePlan__c = testData.productRatePlansMap.get(SIMPLE_PRODUCT_RATE_PLAN_NAME).Id, zqu__Type__c = 'Recurring', 
                        zqu__ZuoraId__c = '0'),
                CONSULTING_PRODUCT_RATE_PLAN_CHARGE_NAME => new zqu__ProductRatePlanCharge__c(Name = CONSULTING_PRODUCT_RATE_PLAN_CHARGE_NAME, 
                        zqu__ProductRatePlan__c = testData.productRatePlansMap.get(CONSULTING_PRODUCT_RATE_PLAN_NAME).Id, zqu__Type__c = 'Recurring', 
                        zqu__ZuoraId__c = '1'),
                ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_CHARGE_NAME => new zqu__ProductRatePlanCharge__c(Name = ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_CHARGE_NAME, 
                        zqu__ProductRatePlan__c = testData.productRatePlansMap.get(ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_NAME).Id, zqu__Type__c = 'One-Time',
                        zqu__ZuoraId__c = '2') };
        insert testProductRatePlanChargesMap.values();
        Test.stopTest();
        zqu__ProductRatePlanCharge__c[] testProductRatePlanCharges = [select Id, FC_Lookup_Key__c, Name, zqu__ProductRatePlan__r.Name, 
                                                                      zqu__ProductRatePlan__r.zqu__ZProduct__r.zqu__SKU__c 
                                                                      from zqu__ProductRatePlanCharge__c where Id in :testProductRatePlanChargesMap.values()];
        for (zqu__ProductRatePlanCharge__c testProductRatePlanCharge : testProductRatePlanCharges) {
            System.assertEquals(testProductRatePlanCharge.zqu__ProductRatePlan__r.zqu__ZProduct__r.zqu__SKU__c + '^' + 
                                testProductRatePlanCharge.zqu__ProductRatePlan__r.Name + '^' +
                                testProductRatePlanCharge.Name, testProductRatePlanCharge.FC_Lookup_Key__c);
        }
    }
    
    private static testmethod void testUpdate() {
        TestDataStruct testData = setup();
        enableTriggerHandlers();
        Map<String, zqu__ProductRatePlanCharge__c> testProductRatePlanChargesMap = new Map<String, zqu__ProductRatePlanCharge__c> {
                SIMPLE_PRODUCT_RATE_PLAN_CHARGE_NAME => new zqu__ProductRatePlanCharge__c(Name = SIMPLE_PRODUCT_RATE_PLAN_CHARGE_NAME, 
                        zqu__ProductRatePlan__c = testData.productRatePlansMap.get(SIMPLE_PRODUCT_RATE_PLAN_NAME).Id, zqu__Type__c = 'Recurring', 
                        zqu__ZuoraId__c = '0'),
                CONSULTING_PRODUCT_RATE_PLAN_CHARGE_NAME => new zqu__ProductRatePlanCharge__c(Name = CONSULTING_PRODUCT_RATE_PLAN_CHARGE_NAME, 
                        zqu__ProductRatePlan__c = testData.productRatePlansMap.get(CONSULTING_PRODUCT_RATE_PLAN_NAME).Id, zqu__Type__c = 'Recurring', 
                        zqu__ZuoraId__c = '1'),
                ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_CHARGE_NAME => new zqu__ProductRatePlanCharge__c(Name = ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_CHARGE_NAME, 
                        zqu__ProductRatePlan__c = testData.productRatePlansMap.get(ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_NAME).Id, zqu__Type__c = 'One-Time',
                        zqu__ZuoraId__c = '2') };
        insert testProductRatePlanChargesMap.values();
        Test.startTest();
        for (zqu__ProductRatePlanCharge__c testProductRatePlanCharge : testProductRatePlanChargesMap.values()) {
            testProductRatePlanCharge.zqu__ZuoraId__c = testProductRatePlanCharge.zqu__ZuoraId__c + 'TEST';
        }
        update testProductRatePlanChargesMap.values();
        Test.stopTest();
        zqu__ProductRatePlanCharge__c[] testProductRatePlanCharges = [select Id, FC_Lookup_Key__c, Name, zqu__ProductRatePlan__r.Name, 
                                                                      zqu__ProductRatePlan__r.zqu__ZProduct__r.zqu__SKU__c 
                                                                      from zqu__ProductRatePlanCharge__c where Id in :testProductRatePlanChargesMap.values()];
        for (zqu__ProductRatePlanCharge__c testProductRatePlanCharge : testProductRatePlanCharges) {
            System.assertEquals(testProductRatePlanCharge.zqu__ProductRatePlan__r.zqu__ZProduct__r.zqu__SKU__c + '^' + 
                                testProductRatePlanCharge.zqu__ProductRatePlan__r.Name + '^' +
                                testProductRatePlanCharge.Name, testProductRatePlanCharge.FC_Lookup_Key__c);
        }
    }
    
    private static void enableTriggerHandlers() {
        fcf.TriggerHandlerSettings.enable('FC_ProductRatePlanChargeHandler');
    }
    
    private static TestDataStruct setup() {
        
        Map<String, zqu__ZProduct__c> testProductsMap = new Map<String, zqu__ZProduct__c> {
                SIMPLE_PRODUCT_NAME => new zqu__ZProduct__c(Name = SIMPLE_PRODUCT_NAME, zqu__SKU__c = 'SKU-0', zqu__ZuoraId__c = '0'),
                CONSULTING_PRODUCT_NAME => new zqu__ZProduct__c(Name = CONSULTING_PRODUCT_NAME, zqu__SKU__c = 'SKU-1', zqu__ZuoraId__c = '1'),
                ONE_TIME_CHARGE_PRODUCT_NAME => new zqu__ZProduct__c(Name = ONE_TIME_CHARGE_PRODUCT_NAME, zqu__SKU__c = 'SKU-2', zqu__ZuoraId__c = '2') };
        upsert testProductsMap.values();
        
        Map<String, zqu__ProductRatePlan__c> testProductRatePlanMap = new Map<String, zqu__ProductRatePlan__c> {
                SIMPLE_PRODUCT_RATE_PLAN_NAME => new zqu__ProductRatePlan__c(Name = SIMPLE_PRODUCT_RATE_PLAN_NAME,
                        zqu__ZProduct__c = testProductsMap.get(SIMPLE_PRODUCT_NAME).Id, zqu__ZuoraId__c = '0'),
                CONSULTING_PRODUCT_RATE_PLAN_NAME => new zqu__ProductRatePlan__c(Name = CONSULTING_PRODUCT_RATE_PLAN_NAME,
                        zqu__ZProduct__c = testProductsMap.get(CONSULTING_PRODUCT_NAME).Id, zqu__ZuoraId__c = '1'),
                ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_NAME => new zqu__ProductRatePlan__c(Name = ONE_TIME_CHARGE_PRODUCT_RATE_PLAN_NAME,
                        zqu__ZProduct__c = testProductsMap.get(ONE_TIME_CHARGE_PRODUCT_NAME).Id,  zqu__ZuoraId__c = '2')};
        upsert testProductRatePlanMap.values();
        
        TestDataStruct result = new TestDataStruct();
        result.productsMap.putAll(testProductsMap);
        result.productRatePlansMap.putAll(testProductRatePlanMap);
        return result;
    }
    
    private class TestDataStruct {
        public Map<String, zqu__ZProduct__c> productsMap = new Map<String, zqu__ZProduct__c>();
        public Map<String, zqu__ProductRatePlan__c> productRatePlansMap = new Map<String, zqu__ProductRatePlan__c>();
    }
    
}