src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__ZuoraSubscriptionID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Zuora Subscription ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZuoraSubIdUpdate.cls
public with sharing class ZuoraSubIdUpdate {

    @future(callout = true)
    public static void updateSubId(Id quoteId, String zuoraSubName) {
    
        Zuora.zApi zuoraApi = new Zuora.zApi();
            
        zuoraApi.zlogin();
            
        List<Zuora.zObject> Sub = zuoraApi.zQuery('Select Id from Subscription Where Name = \'' + zuoraSubName + '\' AND status = \'Active\'');
    
        String SubId = (String)Sub[0].getValue('Id');
        
        zqu__Quote__c LocalQuote = [Select Id from zqu__Quote__c where Id = :quoteId];
        
        LocalQuote.zqu__ZuoraSubscriptionID__c = SubId;
    
        update LocalQuote;
    }
}