src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>zqu__Description__c</fullName>
        <description>A description of the amendment.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>zqu__QuoteTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Quote template that is used to generate the Quote PDF or Word document.</description>
        <inlineHelpText>The Quote template that will be used to generate the Quote PDF or Word document.  If not selected, the user will select a quote template from a list of available quote templates when creating Quote PDF or Word document.</inlineHelpText>
        <label>Quote Template</label>
        <referenceTo>zqu__Quote_Template__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Subscription</fullName>
                </value>
                <value>
                    <fullName>Amend Subscription</fullName>
                </value>
                <value>
                    <fullName>Renew Subscription</fullName>
                </value>
                <value>
                    <fullName>Cancel Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__Quote_Template__c.object
<CustomObject>
    <description>Quote template for generate PDF or WORD</description>
    <fields>
        <fullName>zqu__Description__c</fullName>
        <description>Description of this item.</description>
        <inlineHelpText>Description of this item.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>zqu__IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate this template is the default one of the refer quote type</description>
        <inlineHelpText>Indicate this template is the default one of the refer quote type</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Quote_Type__c</fullName>
        <description>Quote types.</description>
        <inlineHelpText>Quote Type</inlineHelpText>
        <label>Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Subscription</fullName>
                    <default>true</default>
                    <label>New Subscription</label>
                </value>
                <value>
                    <fullName>Amend Subscription</fullName>
                </value>
                <value>
                    <fullName>Renew Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Template_Id__c</fullName>
        <description>The template Id in Zuora</description>
        <inlineHelpText>The template Id in Zuora</inlineHelpText>
        <label>Template Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Quote Template</label>
    <nameField>
        <label>Quote Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/z_generate_quote_pdf.cls
public with sharing class z_generate_quote_pdf {

  public String defaultQuoteTemplateId {get;set;}
  public String attachmentId {get;set;}

  public zqu__Quote__c quote {get;set;}

  /**
   * Constructor
   */
  public z_generate_quote_pdf(ApexPages.StandardController controller) {
    ID recordId = controller.getRecord().Id;
    quote = getQuoteId(recordId);
  }

  /**
   * Queries for the Quote Object associated with this Record ID
   */
  public zqu__Quote__c getQuoteId(ID recordId) {
    List<zqu__Quote__c> quoteList = [
      SELECT
        Name, zqu__QuoteTemplate__r.zqu__Template_Id__c,
        zqu__SubscriptionType__c
      FROM
        zqu__Quote__c
      WHERE
        Id =: recordId];

    if (quoteList.size() == 0) {
      System.debug('Error: No quotes found with Id: ' + recordId);
      return null;
    } else {
      quote = quoteList[0];
      return quote;
    }
  }

  /**
   * Queries the Default Template for this SubscriptionType.
   */
  public void getDefaultQuoteTemplateId() {
    List<zqu__Quote_Template__c> quoteTemplateList = [
      SELECT 
        Name,zqu__IsDefault__c, zqu__Description__c, 
        zqu__Quote_Type__c, zqu__Template_Id__c 
      FROM
        zqu__Quote_Template__c
      WHERE
        zqu__Quote_Type__c = :quote.zqu__SubscriptionType__c];

    if (quoteTemplateList.size() == 0) {
      System.debug('No Quote Templates are setup');
      return;
    }
    
    this.defaultQuoteTemplateId = quote.zqu__QuoteTemplate__r.zqu__Template_Id__c;
    /*
    for (zqu__Quote_Template__c template : quoteTemplateList) {
      if (template.zqu__IsDefault__c) {
        this.defaultQuoteTemplateId = template.zqu__Template_Id__c;
        System.debug('Default Quote Template found with ID: ' 
          + this.defaultQuoteTemplateId);
      }
    }*/
  }

  /**
   * Generates PDF and attaches to Quote's parent Opportunity Object.
   */
  public PageReference generate() {
    // NOTE(chudy): Process Flow.
    if (quote != null) {
      /* TODO(chudy): No way to currently determine if this failed 
       * or not. */
      getDefaultQuoteTemplateId();

      // TODO(sandesh): Update Revenue Lines
      // TODO(sandesh): Update Taxes

      // NOTE(chudy): Generate Quote and attach to Opportunity
      if (defaultQuoteTemplateId == null) {
        return null;
        //generate();
      }
    }

    Map<String,Object> zuoraConfigInfo = 
      zqu.zQuoteUtil.getZuoraConfigInformation();

    Zuora.ZApi zApi = new Zuora.ZApi();

    Zuora.ZApi.LoginResult loginResult = zApi.zLogin();
    System.debug(loginResult.serverUrl);
    String quoteServletUrl = loginResult.serverUrl.contains('apisandbox') ?
      'https://apisandbox.zuora.com/apps/servlet/GenerateQuote' :
      'https://zuora.com/apps/servlet/GenerateQuote';

    String sessionId = UserInfo.getSessionId();

    String sfdcUrl = URL.getSalesforceBaseUrl().toExternalForm() 
      + '/services/Soap/u/10.0/' + UserInfo.getOrganizationId();

    PageReference generatePage = new PageReference(quoteServletUrl);
    generatePage.getParameters().put('templateId', defaultQuoteTemplateId);
    generatePage.getParameters().put('serverUrl', sfdcUrl);
    generatePage.getParameters().put('sessionId', sessionId);
    generatePage.getParameters().put('quoteId', quote.Id);
    generatePage.getParameters().put('attachToOpportunity', 'true');
    generatePage.getParameters().put('format', 'pdf');
    generatePage.getParameters().put('ZSession', loginResult.session);
    generatePage.getParameters().put('useSFDCLocale', '1');
    generatePage.getParameters().put('locale', UserInfo.getLocale());

    Http h = new Http();

    System.debug('Quote PDF URL = ' + generatePage.getUrl());

    HttpRequest req = new HttpRequest();
    req.setEndpoint(generatePage.getUrl());
    req.setMethod('GET');
	req.setTimeout(120000);
    HttpResponse res = h.send(req);

    if (res.getStatusCode() != 200) {
      appendMessage(ApexPages.Severity.ERROR, 'Error contacting Zuora');
      return null;
    }

    /* NOTE(chudy): I think Zuora handles the attaching it to the
     * opportunity through the https callout. We just check for success
     * here. */
    String zuoraResponse = res.getBody();
    String successMessage = 'Quote PDF document has been successfully';
    if (zuoraResponse.contains(successMessage)) {
      appendMessage(ApexPages.Severity.CONFIRM, 'Response Body: ' + zuoraResponse);
      attachmentId = zuoraResponse.split('AttachmentID:', 0)[1];
      // Not sure what happened here but the above split includes a +
      System.debug('Attachment ID Post Regex: ' + attachmentId);
      if (attachmentId.length() > 19) {
        attachmentId = attachmentId.substring(1,19);
      }
      
      // NOTE(chudy): The following will 
      String echoSignTemplate = 'a0qn00000008hYT';
      String quoteId = quote.Id;
      

      PageReference redirect = new PageReference('/apex/echosign_dev1__AgreementTemplateProcess?masterId='
        +quoteId+'&AttachmentId='+attachmentId);//+'&retURL=/'+quoteId);
      redirect.setRedirect(true);
      return redirect;
    } else {
      appendMessage(ApexPages.Severity.ERROR, 'Response Body: ' + zuoraResponse);
    }
    return null;
  }

  /**
   *  Display a message on the VF page
   */
  private static void appendMessage(ApexPages.Severity severity, 
      String message) {
    ApexPages.addMessage(new ApexPages.Message(severity, message));
  }

}