src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <fields>
        <fullName>Is_Retainer_Rate_Plan__c</fullName>
        <formula>CONTAINS(Name, &quot;Retainer&quot;)</formula>
        <label>Is Retainer Rate Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment3__c</fullName>
        <label>Segment3</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>BPMS</fullName>
                </value>
                <value>
                    <fullName>PUBR</fullName>
                </value>
                <value>
                    <fullName>CONS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Rate Plan.</description>
        <inlineHelpText>The Effective End Date of the Rate Plan.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Rate Plan.</description>
        <inlineHelpText>The Effective Start Date of the Rate Plan.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Rate Plans</relationshipLabel>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__ZProduct__c</fullName>
        <description>The ZProduct associated with this Rate Plan.</description>
        <inlineHelpText>The ZProduct associated with this Rate Plan.</inlineHelpText>
        <label>ZProduct</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>zqu__ZProduct__c.zqu__Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.zqu__Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>zqu__ZProduct__c</referenceTo>
        <relationshipLabel>Product Rate Plan</relationshipLabel>
        <relationshipName>ProductRatePlan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan.</inlineHelpText>
        <label>ZuoraId</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>FC_Lookup_Key__c</fullName>
        <externalId>true</externalId>
        <label>FC Lookup Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FC_Recognized_Revenue_Account__c</fullName>
        <externalId>true</externalId>
        <label>(FC) Recognized Revenue Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__ListPrice__c</fullName>
        <description>The List Price of the Rate Plan Charge.</description>
        <inlineHelpText>The List Price of the Rate Plan Charge.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__ProductRatePlan__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Rate Plan associated with this Rate Plan Charge.</description>
        <inlineHelpText>The Rate Plan associated with this Rate Plan Charge.</inlineHelpText>
        <label>Product Rate Plan</label>
        <referenceTo>zqu__ProductRatePlan__c</referenceTo>
        <relationshipLabel>Product Rate Plan Charges</relationshipLabel>
        <relationshipName>R00N40000001mFVKEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__RecurringPeriod__c</fullName>
        <description>The Recurring Period of the Rate Plan Charge.</description>
        <inlineHelpText>The Recurring Period of the Rate Plan Charge.</inlineHelpText>
        <label>Billing Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Quarter</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__Type__c</fullName>
        <description>The Type of the Rate Plan Charge.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Rate Plan Charge.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Rate Plan Charge.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>Is_BPM_Product__c</fullName>
        <formula>CONTAINS(Name, &apos;BPM&apos;)</formula>
        <label>Is BPM Product?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Consulting_Product__c</fullName>
        <formula>CONTAINS( Name , &quot;Consulting&quot; )</formula>
        <label>Is Consulting Product?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag for soft deletion</description>
        <inlineHelpText>Flag for soft deletion</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveEndDate__c</fullName>
        <description>The Effective End Date of the Product.</description>
        <inlineHelpText>The Effective End Date of the Product.</inlineHelpText>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__EffectiveStartDate__c</fullName>
        <description>The Effective Start Date of the Product.</description>
        <inlineHelpText>The Effective Start Date of the Product.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ZProducts</relationshipLabel>
        <relationshipName>ZProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ProductRatePlanChargeCache.cls
public class FC_ProductRatePlanChargeCache {

    private static String[] PRODUCT_RATE_PLAN_CHARGE_FIELDS = new String[]{
            'Id', 'FC_Lookup_Key__c', 'FC_Recognized_Revenue_Account__c', 'zqu__ListPrice__c',
            'zqu__ProductRatePlan__c', 'zqu__RecurringPeriod__c', 'zqu__Type__c', 'zqu__ZuoraId__c',
            'zqu__ProductRatePlan__r.Is_Retainer_Rate_Plan__c',
            'zqu__ProductRatePlan__r.Record_Id__c', 'zqu__ProductRatePlan__r.Segment3__c',
            'zqu__ProductRatePlan__r.zqu__EffectiveEndDate__c',
            'zqu__ProductRatePlan__r.zqu__EffectiveStartDate__c',
            'zqu__ProductRatePlan__r.zqu__Product__c',
            'zqu__ProductRatePlan__r.zqu__ZProduct__r.Is_BPM_Product__c',
            'zqu__ProductRatePlan__r.zqu__ZProduct__r.Is_Consulting_Product__c',
            'zqu__ProductRatePlan__r.zqu__ZProduct__r.zqu__SKU__c',
            'zqu__ProductRatePlan__r.zqu__ZuoraId__c'
    };

    private static final Map<ID, zqu__ProductRatePlanCharge__c> BY_ID_MAP = new Map<ID, zqu__ProductRatePlanCharge__c>();
    private static final Map<String, zqu__ProductRatePlanCharge__c> BY_ZUORA_ID_MAP = new Map<String, zqu__ProductRatePlanCharge__c>();
    private static final Map<String, zqu__ProductRatePlanCharge__c> BY_FC_LOOKUP_KEY_MAP = new Map<String, zqu__ProductRatePlanCharge__c>();
    private static final Map<String, Set<zqu__ProductRatePlanCharge__c>> BY_RECOGNIZED_REVENUE_ACCOUNT_MAP = new Map<String, Set<zqu__ProductRatePlanCharge__c>>();
    private static final String SOQL_BASE;

    static {
        SOQL_BASE = String.format('select {0} from zqu__ProductRatePlanCharge__c',
                new String[]{
                        String.join(PRODUCT_RATE_PLAN_CHARGE_FIELDS, ', ')
                });
    }

    public static void clearCache() {
        BY_ID_MAP.clear();
        BY_ZUORA_ID_MAP.clear();
        BY_FC_LOOKUP_KEY_MAP.clear();
        BY_RECOGNIZED_REVENUE_ACCOUNT_MAP.clear();
    }

    public static Map<ID, zqu__ProductRatePlanCharge__c> findByIds(Set<ID> productRatePlanChargeIds) {
        Map<ID, zqu__ProductRatePlanCharge__c> results = new Map<ID, zqu__ProductRatePlanCharge__c>();
        Set<ID> productRatePlanChargeIdsToQuery = new Set<ID>();
        for (ID productRatePlanChargeId : productRatePlanChargeIds) {
            if (BY_ID_MAP.containsKey(productRatePlanChargeId)) {
                results.put(productRatePlanChargeId, BY_ID_MAP.get(productRatePlanChargeId));
            } else {
                productRatePlanChargeIdsToQuery.add(productRatePlanChargeId);
            }
        }
        if (productRatePlanChargeIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Id in :productRatePlanChargeIdsToQuery';
            for (zqu__ProductRatePlanCharge__c productRatePlanChargeRecord : Database.query(soql)) {
                BY_FC_LOOKUP_KEY_MAP.put(productRatePlanChargeRecord.FC_Lookup_Key__c, productRatePlanChargeRecord);
                BY_ZUORA_ID_MAP.put(productRatePlanChargeRecord.zqu__ZuoraId__c, productRatePlanChargeRecord);
                BY_ID_MAP.put(productRatePlanChargeRecord.Id, productRatePlanChargeRecord);
                results.put(productRatePlanChargeRecord.Id, productRatePlanChargeRecord);
            }
        }
        return results;
    }

    public static Map<String, Set<zqu__ProductRatePlanCharge__c>> findWithActiveRatePlanByRecognizedRevenueAccount(Set<String> recognizedRevenueAccounts) {
        Map<String, Set<zqu__ProductRatePlanCharge__c>> results = new Map<String, Set<zqu__ProductRatePlanCharge__c>>();
        Set<String> recognizedRevenueAccountsToQuery = new Set<String>();
        for (String recognizedRevenueAccount : recognizedRevenueAccounts) {
            if (BY_RECOGNIZED_REVENUE_ACCOUNT_MAP.containsKey(recognizedRevenueAccount)) {
                results.put(recognizedRevenueAccount, BY_RECOGNIZED_REVENUE_ACCOUNT_MAP.get(recognizedRevenueAccount));
            } else {
                recognizedRevenueAccountsToQuery.add(recognizedRevenueAccount);
            }
        }
        if (recognizedRevenueAccountsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where FC_Recognized_Revenue_Account__c in :recognizedRevenueAccountsToQuery ' +
                    'and zqu__ProductRatePlan__r.zqu__EffectiveStartDate__c <= TODAY ' +
                    'and zqu__ProductRatePlan__r.zqu__EffectiveEndDate__c >= TODAY ' +
                    'and zqu__ProductRatePlan__r.zqu__Deleted__c = false and zqu__Deleted__c = false';
            for (zqu__ProductRatePlanCharge__c productRatePlanChargeRecord : Database.query(soql)) {
                Set<zqu__ProductRatePlanCharge__c> productRatePlanCharges = BY_RECOGNIZED_REVENUE_ACCOUNT_MAP.get(productRatePlanChargeRecord.FC_Recognized_Revenue_Account__c);
                if (productRatePlanCharges == null) {
                    productRatePlanCharges = new Set<zqu__ProductRatePlanCharge__c>();
                    BY_RECOGNIZED_REVENUE_ACCOUNT_MAP.put(productRatePlanChargeRecord.FC_Recognized_Revenue_Account__c, productRatePlanCharges);
                    results.put(productRatePlanChargeRecord.FC_Recognized_Revenue_Account__c, productRatePlanCharges);
                }
                productRatePlanCharges.add(productRatePlanChargeRecord);
                BY_FC_LOOKUP_KEY_MAP.put(productRatePlanChargeRecord.FC_Lookup_Key__c, productRatePlanChargeRecord);
                BY_ZUORA_ID_MAP.put(productRatePlanChargeRecord.zqu__ZuoraId__c, productRatePlanChargeRecord);
                BY_ID_MAP.put(productRatePlanChargeRecord.Id, productRatePlanChargeRecord);
            }
        }
        return results;
    }


    public static Map<String, zqu__ProductRatePlanCharge__c> findByFcLookupKeys(Set<String> fcLookupKeys) {
        Map<String, zqu__ProductRatePlanCharge__c> results = new Map<String, zqu__ProductRatePlanCharge__c>();
        Set<String> fcLookupKeysToQuery = new Set<String>();
        for (String fcLookupKey : fcLookupKeys) {
            if (BY_FC_LOOKUP_KEY_MAP.containsKey(fcLookupKey)) {
                results.put(fcLookupKey, BY_FC_LOOKUP_KEY_MAP.get(fcLookupKey));
            } else {
                fcLookupKeysToQuery.add(fcLookupKey);
            }
        }
        if (fcLookupKeysToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where FC_Lookup_Key__c in :fcLookupKeysToQuery';
            for (zqu__ProductRatePlanCharge__c productRatePlanChargeRecord : Database.query(soql)) {
                results.put(productRatePlanChargeRecord.FC_Lookup_Key__c, productRatePlanChargeRecord);
                BY_FC_LOOKUP_KEY_MAP.put(productRatePlanChargeRecord.FC_Lookup_Key__c, productRatePlanChargeRecord);
                BY_ZUORA_ID_MAP.put(productRatePlanChargeRecord.zqu__ZuoraId__c, productRatePlanChargeRecord);
                BY_ID_MAP.put(productRatePlanChargeRecord.Id, productRatePlanChargeRecord);
            }
        }
        return results;
    }

    public static Map<String, zqu__ProductRatePlanCharge__c> findByZuoraIds(Set<String> zuoraIds) {
        Map<String, zqu__ProductRatePlanCharge__c> results = new Map<String, zqu__ProductRatePlanCharge__c>();
        Set<String> zuoraIdsToQuery = new Set<String>();
        for (String zuoraId : zuoraIds) {
            if (BY_ZUORA_ID_MAP.containsKey(zuoraId)) {
                results.put(zuoraId, BY_ZUORA_ID_MAP.get(zuoraId));
            } else {
                zuoraIdsToQuery.add(zuoraId);
            }
        }
        if (zuoraIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where zqu__ZuoraId__c in :zuoraIdsToQuery';
            for (zqu__ProductRatePlanCharge__c productRatePlanChargeRecord : Database.query(soql)) {
                results.put(productRatePlanChargeRecord.zqu__ZuoraId__c, productRatePlanChargeRecord);
                BY_FC_LOOKUP_KEY_MAP.put(productRatePlanChargeRecord.FC_Lookup_Key__c, productRatePlanChargeRecord);
                BY_ZUORA_ID_MAP.put(productRatePlanChargeRecord.zqu__ZuoraId__c, productRatePlanChargeRecord);
                BY_ID_MAP.put(productRatePlanChargeRecord.Id, productRatePlanChargeRecord);
            }
        }
        return results;
    }

}