src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <description>The Charges associated with a Rate Plan.</description>
    <fields>
        <fullName>FC_Recognized_Revenue_Account__c</fullName>
        <externalId>true</externalId>
        <label>(FC) Recognized Revenue Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__RecognizedRevenueAccount__c</fullName>
        <description>The name of the recognized revenue account for this charge.</description>
        <label>Recognized Revenue Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Rate Plan Charge</label>
    <nameField>
        <label>Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plan Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ZquProductRatePlanChargeHandler.cls
global without sharing class FC_ZquProductRatePlanChargeHandler extends fcf.TriggerAdapter {

    global override void beforeInsert(SObject so) {
        zqu__ProductRatePlanCharge__c newProductRatePlanChargeRecord = (zqu__ProductRatePlanCharge__c) so;
        populateFields(newProductRatePlanChargeRecord);
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        zqu__ProductRatePlanCharge__c newProductRatePlanChargeRecord = (zqu__ProductRatePlanCharge__c) so;
        populateFields(newProductRatePlanChargeRecord);
    }

    private void populateFields(zqu__ProductRatePlanCharge__c productRatePlanChargeRecord) {
        productRatePlanChargeRecord.FC_Recognized_Revenue_Account__c = null;
        if (String.isNotBlank(productRatePlanChargeRecord.zqu__RecognizedRevenueAccount__c)) {
            productRatePlanChargeRecord.FC_Recognized_Revenue_Account__c = productRatePlanChargeRecord.zqu__RecognizedRevenueAccount__c.toUpperCase();
        }
    }

}