src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Seg2_Description__c</fullName>
        <label>Seg2 Description</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>61 - Philadelphia</fullName>
                </value>
                <value>
                    <fullName>61 - Philadelphia, 62 - New Jersey - New York</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Seg2_Description__c</fullName>
        <formula>IF(NOT(ISBLANK(Segment2__c)), LPAD(Segment2__c, 2, &quot;0&quot;) + &quot; - &quot; + Segment2_Market_Name__c, &quot;&quot;)</formula>
        <label>Seg2 Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ZuoraCustomerAccountHandler.cls
global without sharing class FC_ZuoraCustomerAccountHandler extends fcf.TriggerAdapter {

//    private static final String TRIGGER_RUN_STATUS_ID = 'FC_ZuoraCustomerAccountHandler';

    // Before-phase variables
    private Map<ID, Set<Zuora__SubscriptionProductCharge__c>> billingAccountIdToSubscriptionProductChargesMap =
            new Map<ID, Set<Zuora__SubscriptionProductCharge__c>>();

//    // After-phase variables
//    private Set<String> customerAccountZuoraIds = new Set<String>();

    global override void bulkBefore() {
        if (Trigger.isUpdate) {
            billingAccountIdToSubscriptionProductChargesMap.putAll(
                    FC_SubscriptionProductChargeCache.findByBillingAccountIds(Trigger.newMap.keySet()));
        }
    }

    global override void beforeUpdate(SObject oldSo, SObject so) {
        Zuora__CustomerAccount__c newCustomerAccount = (Zuora__CustomerAccount__c) so;

        populateFields(newCustomerAccount);
    }

//    global override void afterInsert(SObject so) {
//        Zuora__CustomerAccount__c newCustomerAccount = (Zuora__CustomerAccount__c) so;
//
//        if (String.isNotBlank(newCustomerAccount.Zuora__External_Id__c)) {
//            customerAccountZuoraIds.add(newCustomerAccount.Zuora__External_Id__c);
//        }
//    }
//
//    global override void afterUpdate(SObject oldSo, SObject so) {
//        Zuora__CustomerAccount__c newCustomerAccount = (Zuora__CustomerAccount__c) so;
//
//        if (String.isNotBlank(newCustomerAccount.Zuora__External_Id__c)) {
//            customerAccountZuoraIds.add(newCustomerAccount.Zuora__External_Id__c);
//        }
//    }
//
//    global override void finallyAfter() {
//
//        // Prevent after phase from recursively executing
//        if (!fcf.TriggerRunStatus.isRunnable(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID))) {
//            return;
//        }
//        fcf.TriggerRunStatus.block(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID));
//
//        if (Trigger.isInsert || Trigger.isUpdate) {
//
//            // Update related quotes
//            zqu__Quote__c[] quotesToUpdate = new List<zqu__Quote__c>();
//            Map<String, Set<zqu__Quote__c>> customerAccountZuoraIdsToQuotesMap = FC_ZquQuoteCache.findByZuoraAccountIds(customerAccountZuoraIds);
//            for (String customerAccountZuoraId : customerAccountZuoraIdsToQuotesMap.keySet()) {
//                for (zqu__Quote__c quoteRecord : customerAccountZuoraIdsToQuotesMap.get(customerAccountZuoraId)) {
//                    quotesToUpdate.add(new zqu__Quote__c(Id = quoteRecord.Id));
//                }
//            }
//            if (!quotesToUpdate.isEmpty()) {
//                update quotesToUpdate;
//            }
//
//        }
//
//    }

    private void populateFields(Zuora__CustomerAccount__c customerAccountRecord) {
        if (billingAccountIdToSubscriptionProductChargesMap.containsKey(customerAccountRecord.Id)) {
            Set<Zuora__SubscriptionProductCharge__c> subscriptionProductCharges =
                    billingAccountIdToSubscriptionProductChargesMap.get(customerAccountRecord.Id);
            Set<String> seg2DescriptionSet = new Set<String>();
            for (Zuora__SubscriptionProductCharge__c subscriptionProductCharge : subscriptionProductCharges) {
                if (String.isNotBlank(subscriptionProductCharge.Seg2_Description__c)) {
                    seg2DescriptionSet.add(subscriptionProductCharge.Seg2_Description__c);
                }
            }
            customerAccountRecord.Seg2_Description__c = String.join(new List<String>(seg2DescriptionSet), ';');
        }
    }

}