src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionChargeNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestSubscriptionProductChargeCache.cls
@isTest
private class FC_TestSubscriptionProductChargeCache {

    @isTest
    private static void testFindByIds() {
        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [select Id, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c where Zuora__External_Id__c = 'SPC-1'];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<ID, Zuora__SubscriptionProductCharge__c> results = FC_SubscriptionProductChargeCache.findByIds(new Set<ID> { testSubscriptionProductCharge.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, results.get(testSubscriptionProductCharge.Id).Zuora__External_Id__c);
        System.assertEquals(1, Limits.getQueries());
        results = FC_SubscriptionProductChargeCache.findByIds(new Set<ID> { testSubscriptionProductCharge.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, results.get(testSubscriptionProductCharge.Id).Zuora__External_Id__c);
        System.assertEquals(1, Limits.getQueries());

        FC_SubscriptionProductChargeCache.clearCache();
        results = FC_SubscriptionProductChargeCache.findByIds(new Set<ID> { testSubscriptionProductCharge.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, results.get(testSubscriptionProductCharge.Id).Zuora__External_Id__c);
        System.assertEquals(2, Limits.getQueries());

        Test.stopTest();
    }

    @isTest
    private static void testFindByChargeNumbers() {
        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [select Id, Zuora__ChargeNumber__c
                from Zuora__SubscriptionProductCharge__c where Zuora__ChargeNumber__c = 'SPC-1'];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<String, Zuora__SubscriptionProductCharge__c> results = FC_SubscriptionProductChargeCache.findByChargeNumbers(new Set<String> { testSubscriptionProductCharge.Zuora__ChargeNumber__c });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Id, results.get(testSubscriptionProductCharge.Zuora__ChargeNumber__c).Id);
        System.assertEquals(1, Limits.getQueries());
        results = FC_SubscriptionProductChargeCache.findByChargeNumbers(new Set<String> { testSubscriptionProductCharge.Zuora__ChargeNumber__c });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Id, results.get(testSubscriptionProductCharge.Zuora__ChargeNumber__c).Id);
        System.assertEquals(1, Limits.getQueries());

        FC_SubscriptionProductChargeCache.clearCache();
        results = FC_SubscriptionProductChargeCache.findByChargeNumbers(new Set<String> { testSubscriptionProductCharge.Zuora__ChargeNumber__c });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Id, results.get(testSubscriptionProductCharge.Zuora__ChargeNumber__c).Id);
        System.assertEquals(2, Limits.getQueries());

        Test.stopTest();
    }

    @isTest
    private static void testFindBySubscriptionZuoraIds() {
        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [select Id, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c where Zuora__External_Id__c = 'SPC-1'];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<String, Set<Zuora__SubscriptionProductCharge__c>> results = FC_SubscriptionProductChargeCache.findBySubscriptionZuoraIds(new Set<String> { 'S-1' });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, new List<Zuora__SubscriptionProductCharge__c>(results.get('S-1'))[0].Zuora__External_Id__c);
        System.assertEquals(1, Limits.getQueries());
        results = FC_SubscriptionProductChargeCache.findBySubscriptionZuoraIds(new Set<String> { 'S-1' });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, new List<Zuora__SubscriptionProductCharge__c>(results.get('S-1'))[0].Zuora__External_Id__c);
        System.assertEquals(1, Limits.getQueries());

        FC_SubscriptionProductChargeCache.clearCache();
        results = FC_SubscriptionProductChargeCache.findBySubscriptionZuoraIds(new Set<String> { 'S-1' });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, new List<Zuora__SubscriptionProductCharge__c>(results.get('S-1'))[0].Zuora__External_Id__c);
        System.assertEquals(2, Limits.getQueries());
        Test.stopTest();
    }

    @isTest
    private static void testFindBySubscriptionIds() {
        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [select Id, Zuora__Subscription__c
                from Zuora__SubscriptionProductCharge__c where Zuora__External_Id__c = 'SPC-1'];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<Id, Set<Zuora__SubscriptionProductCharge__c>> results = FC_SubscriptionProductChargeCache.findBySubscriptionIds(new Set<Id> { testSubscriptionProductCharge.Zuora__Subscription__c });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__Subscription__c, new List<Zuora__SubscriptionProductCharge__c>(results.get(testSubscriptionProductCharge.Zuora__Subscription__c))[0].Zuora__Subscription__c);
        System.assertEquals(1, Limits.getQueries());
        results = FC_SubscriptionProductChargeCache.findBySubscriptionIds(new Set<Id> { testSubscriptionProductCharge.Zuora__Subscription__c });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__Subscription__c, new List<Zuora__SubscriptionProductCharge__c>(results.get(testSubscriptionProductCharge.Zuora__Subscription__c))[0].Zuora__Subscription__c);
        System.assertEquals(1, Limits.getQueries());

        FC_SubscriptionProductChargeCache.clearCache();
        results = FC_SubscriptionProductChargeCache.findBySubscriptionIds(new Set<Id> { testSubscriptionProductCharge.Zuora__Subscription__c});
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__Subscription__c, new List<Zuora__SubscriptionProductCharge__c>(results.get(testSubscriptionProductCharge.Zuora__Subscription__c))[0].Zuora__Subscription__c);
        System.assertEquals(2, Limits.getQueries());
        Test.stopTest();
    }
    
    @isTest
    private static void testFindByBillingAccountIds() {
        Zuora__CustomerAccount__c testCustomerAccount = [select Id, Zuora__External_Id__c from Zuora__CustomerAccount__c
                where Zuora__External_Id__c = 'A-1' limit 1];
        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = [select Id, Zuora__External_Id__c
                from Zuora__SubscriptionProductCharge__c where Zuora__External_Id__c = 'SPC-1'];

        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<Id, Set<Zuora__SubscriptionProductCharge__c>> results = FC_SubscriptionProductChargeCache.findByBillingAccountIds(new Set<Id> { testCustomerAccount.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, new List<Zuora__SubscriptionProductCharge__c>(results.get(testCustomerAccount.Id))[0].Zuora__External_Id__c);
        System.assertEquals(1, Limits.getQueries());
        results = FC_SubscriptionProductChargeCache.findByBillingAccountIds(new Set<Id> { testCustomerAccount.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, new List<Zuora__SubscriptionProductCharge__c>(results.get(testCustomerAccount.Id))[0].Zuora__External_Id__c);
        System.assertEquals(1, Limits.getQueries());

        FC_SubscriptionProductChargeCache.clearCache();
        results = FC_SubscriptionProductChargeCache.findByBillingAccountIds(new Set<Id> { testCustomerAccount.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(testSubscriptionProductCharge.Zuora__External_Id__c, new List<Zuora__SubscriptionProductCharge__c>(results.get(testCustomerAccount.Id))[0].Zuora__External_Id__c);
        System.assertEquals(2, Limits.getQueries());
        Test.stopTest();
    }

    @testSetup
    private static void setup() {
        Account testAccount = new Account(Name = 'Test Account', BillingPostalCode = '12345');
        insert testAccount;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account', 
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;

        Zuora__Subscription__c testSubscription = new Zuora__Subscription__c(Name = 'S-1', 
                Zuora__Account__c = testAccount.Id, Zuora__CustomerAccount__c = testCustomerAccount.Id,
                Zuora__External_Id__c = 'S-1');
        insert testSubscription;

        Zuora__SubscriptionProductCharge__c testSubscriptionProductCharge = new Zuora__SubscriptionProductCharge__c(
                Name = 'SPC-1', Zuora__Account__c = testAccount.Id, Zuora__Subscription__c = testSubscription.Id,
                Zuora__ChargeNumber__c = 'SPC-1', Zuora__SubscriptionChargeNumber__c = 'SPC-1', Zuora__External_Id__c = 'SPC-1');
        insert testSubscriptionProductCharge;
    }

}