src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__NextChargeDate__c</fullName>
        <label>Next Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermSettingType__c</fullName>
        <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
        <label>Term Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TERMED</fullName>
                </value>
                <value>
                    <fullName>EVERGREEN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_SubscriptionCache.cls
public class FC_SubscriptionCache {

    private static String[] SUBSCRIPTION_FIELDS = new String[]{
            'Id', 'Opportunity__c', 'Zuora__Account__c', 'Zuora__CustomerAccount__c', 'Zuora__NextChargeDate__c',
            'Zuora__SubscriptionNumber__c', 'Zuora__SubscriptionStartDate__c', 'Zuora__TermSettingType__c', 'Zuora__TermStartDate__c'
    };

    private static final Map<ID, Zuora__Subscription__c> BY_ID_MAP = new Map<ID, Zuora__Subscription__c>();
    private static final Map<ID, Set<Zuora__Subscription__c>> BY_ACCOUNT_ID_MAP = new Map<ID, Set<Zuora__Subscription__c>>();
    private static final Map<String, Zuora__Subscription__c> BY_SUBSCRIPTION_NUMBER_MAP = new Map<String, Zuora__Subscription__c>();

    private static final String SOQL_BASE;

    static {
        SOQL_BASE = String.format('select {0} from Zuora__Subscription__c',
                new String[]{
                        String.join(SUBSCRIPTION_FIELDS, ', ')
                });
    }

    public static void clearCache() {
        BY_ID_MAP.clear();
        BY_ACCOUNT_ID_MAP.clear();
        BY_SUBSCRIPTION_NUMBER_MAP.clear();
    }

    public static Map<ID, Zuora__Subscription__c> findByIds(Set<ID> recordIds) {
        Map<ID, Zuora__Subscription__c> results = new Map<ID, Zuora__Subscription__c>();
        Set<ID> recordIdsToQuery = new Set<ID>();
        for (ID recordId : recordIds) {
            if (BY_ID_MAP.containsKey(recordId)) {
                results.put(recordId, BY_ID_MAP.get(recordId));
            } else {
                recordIdsToQuery.add(recordId);
            }
        }
        if (!recordIdsToQuery.isEmpty()) {
            String soql = SOQL_BASE + ' where Id in :recordIdsToQuery';
            for (Zuora__Subscription__c record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                results.put(record.Id, record);
            }
        }
        return results;
    }

    public static Map<String, Zuora__Subscription__c> findBySubscriptionNumber(Set<String> subscriptionNumbers) {
        Map<String, Zuora__Subscription__c> results = new Map<String, Zuora__Subscription__c>();
        Set<String> recordNumbersToQuery = new Set<String>();
        for (String subscriptionNumber : subscriptionNumbers) {
            if (BY_SUBSCRIPTION_NUMBER_MAP.containsKey(subscriptionNumber)) {
                results.put(subscriptionNumber, BY_SUBSCRIPTION_NUMBER_MAP.get(subscriptionNumber));
            } else {
                recordNumbersToQuery.add(subscriptionNumber);
            }
        }
        if (!recordNumbersToQuery.isEmpty()) {
            String soql = SOQL_BASE + ' where Zuora__SubscriptionNumber__c in :recordNumbersToQuery';
            for (Zuora__Subscription__c record : Database.query(soql)) {
                BY_ID_MAP.put(record.Id, record);
                BY_SUBSCRIPTION_NUMBER_MAP.put(record.Zuora__SubscriptionNumber__c, record);
                results.put(record.Zuora__SubscriptionNumber__c, record);
            }
        }
        return results;
    }


    public static Map<ID, Set<Zuora__Subscription__c>> findByAccountIds(Set<ID> accountIds) {
        Map<ID, Set<Zuora__Subscription__c>> results = new Map<ID, Set<Zuora__Subscription__c>>();
        Set<ID> accountIdsToQuery = new Set<ID>();
        for (String accountId : accountIds) {
            if (BY_ACCOUNT_ID_MAP.containsKey(accountId)) {
                results.put(accountId, BY_ACCOUNT_ID_MAP.get(accountId));
            } else {
                accountIdsToQuery.add(accountId);
            }
        }
        if (accountIdsToQuery.size() > 0) {
            String soql = SOQL_BASE + ' where Zuora__Account__c in :accountIdsToQuery';
            for (Zuora__Subscription__c subscriptionRecord : Database.query(soql)) {
                Set<Zuora__Subscription__c> subscriptions = results.get(subscriptionRecord.Zuora__Account__c);
                if (subscriptions == null) {
                    subscriptions = new Set<Zuora__Subscription__c>();
                    results.put(subscriptionRecord.Zuora__Account__c, subscriptions);
                }
                subscriptions.add(subscriptionRecord);
                BY_ACCOUNT_ID_MAP.put(subscriptionRecord.Zuora__Account__c, subscriptions);
                BY_ID_MAP.put(subscriptionRecord.Id, subscriptionRecord);
            }
        }
        return results;
    }

}