src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FC_TestZuoraCustomerAccountCache.cls
@isTest
private class FC_TestZuoraCustomerAccountCache {

    @isTest
    private static void testFindByIds() {
        
        Zuora__CustomerAccount__c testCustomerAccount = [select Id, Zuora__External_Id__c 
                from Zuora__CustomerAccount__c where Zuora__External_Id__c = 'A-1' limit 1];    
        
        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<ID, Zuora__CustomerAccount__c> results = FC_ZuoraCustomerAccountCache.findByIds(new Set<Id> { testCustomerAccount.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        results = FC_ZuoraCustomerAccountCache.findByIds(new Set<Id> { testCustomerAccount.Id });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        Test.stopTest();
        
    }
    
    @isTest
    private static void testFindByZuoraIds() {
        
        Zuora__CustomerAccount__c testCustomerAccount = [select Id, Zuora__External_Id__c 
                from Zuora__CustomerAccount__c where Zuora__External_Id__c = 'A-1' limit 1];    
        
        Test.startTest();
        System.assertEquals(0, Limits.getQueries());
        Map<String, Zuora__CustomerAccount__c> results = FC_ZuoraCustomerAccountCache.findByZuoraIds(new Set<String> { testCustomerAccount.Zuora__External_Id__c });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        results = FC_ZuoraCustomerAccountCache.findByZuoraIds(new Set<String> { testCustomerAccount.Zuora__External_Id__c });
        System.assertEquals(1, results.size());
        System.assertEquals(1, Limits.getQueries());
        Test.stopTest();
        
    }
    
    @testSetup
    private static void setup() {
        
        Account testAccount = new Account(Name = 'Test Account', BillingPostalCode = '12345');
        insert testAccount;
        
        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'Test Account', 
                Zuora__Account__c = testAccount.Id, Zuora__External_Id__c = 'A-1');
        insert testCustomerAccount;
        
    }
    
}