src/objects/Zuora__PaymentInvoice__c.object
<CustomObject>
    <description>Zuora Invoice Payment object.  An Invoice Payment is a mechanism to tie a payment to an invoice and indicate how much of the payment to apply to the invoice.  PaymentInvoice has Master-Detail relationship to Payment object and Lookup relationship to Invoice.</description>
    <fields>
        <fullName>Zuora__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The invoice associated with this Invoice Payment object.</description>
        <inlineHelpText>The invoice associated with this Invoice Payment object.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>Zuora__ZInvoice__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>PaymentInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_ZuoraPaymentInvoiceHandler.cls
global without sharing class FC_ZuoraPaymentInvoiceHandler extends fcf.TriggerAdapter {

    private static final String TRIGGER_RUN_STATUS_ID = 'FC_ZuoraPaymentInvoiceHandler';

    // After phase
    private Set<Id> invoiceIdsToUpdate = new Set<Id>();

    global override void afterInsert(SObject so) {
        Zuora__PaymentInvoice__c newPaymentInvoice = (Zuora__PaymentInvoice__c) so;
        prepareInvoiceForUpdate(newPaymentInvoice);
    }

    global override void afterUpdate(SObject oldSo, SObject so) {
        Zuora__PaymentInvoice__c newPaymentInvoice = (Zuora__PaymentInvoice__c) so;
        prepareInvoiceForUpdate(newPaymentInvoice);
    }

    global override void afterDelete(SObject oldSo) {
        Zuora__PaymentInvoice__c oldPaymentInvoice = (Zuora__PaymentInvoice__c) oldSo;
        prepareInvoiceForUpdate(oldPaymentInvoice);
    }

    global override void afterUndelete(SObject so) {
        Zuora__PaymentInvoice__c newPaymentInvoice = (Zuora__PaymentInvoice__c) so;
        prepareInvoiceForUpdate(newPaymentInvoice);
    }

    global override void finallyAfter() {

        // Prevent after phase from recursively executing
        if (!fcf.TriggerRunStatus.isRunnable(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID))) {
            return;
        }
        fcf.TriggerRunStatus.block(new fcf.TriggerRunStatusItem(TRIGGER_RUN_STATUS_ID));

        if (!invoiceIdsToUpdate.isEmpty()) {
            Zuora__ZInvoice__c[] invoicesToUpdate = new List<Zuora__ZInvoice__c>();
            for (Id invoiceIdToUpdate : invoiceIdsToUpdate) {
                invoicesToUpdate.add(new Zuora__ZInvoice__c(Id = invoiceIdToUpdate));
            }
            update invoicesToUpdate;
            invoicesToUpdate.clear();
        }

    }

    private void prepareInvoiceForUpdate(Zuora__PaymentInvoice__c paymentInvoiceRecord) {
        if (paymentInvoiceRecord.Zuora__Invoice__c != null) {
            invoiceIdsToUpdate.add(paymentInvoiceRecord.Zuora__Invoice__c);
        }
    }

}