src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>R00N40000001kyLcEAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__Payment__c.object
<CustomObject>
    <description>Zuora Payment object.  A payment is the money that customers send to pay for charges related to their subscriptions. 
The Payment object holds all of the information about an individual payment, including the payment amount and to which invoices the payment is applied.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM Account that this payment is related to.</description>
        <inlineHelpText>The CRM Account that this payment is related to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <description>The billing account that the payment is for.</description>
        <inlineHelpText>The billing account that the payment is for.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora__Effective_Date__c</fullName>
        <description>The date when the payment takes effect.</description>
        <inlineHelpText>The date when the payment takes effect.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The invoice that the payment is applied to.</description>
        <label>Invoice</label>
        <referenceTo>Zuora__ZInvoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the payment in the Zuora system. The value depends on the type of payment.</description>
        <inlineHelpText>The status of the payment in the Zuora system. The value depends on the type of payment.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__PaymentInvoice__c.object
<CustomObject>
    <description>Zuora Invoice Payment object.  An Invoice Payment is a mechanism to tie a payment to an invoice and indicate how much of the payment to apply to the invoice.  PaymentInvoice has Master-Detail relationship to Payment object and Lookup relationship to Invoice.</description>
    <fields>
        <fullName>Zuora__ApplyAmount__c</fullName>
        <description>The amount of the payment.</description>
        <label>Applied Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zuora__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The invoice associated with this Invoice Payment object.</description>
        <inlineHelpText>The invoice associated with this Invoice Payment object.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>Zuora__ZInvoice__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>PaymentInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Payment__c</fullName>
        <description>The payment associated with this Invoice Payment object.</description>
        <inlineHelpText>The payment associated with this Invoice Payment object.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Zuora__Payment__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>PaymentInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zuora__ZInvoice__c.object
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <fields>
        <fullName>FC_Most_Recent_Payment_Processed_On__c</fullName>
        <label>(FC) Most Recent Payment Processed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CRM account that the invoice is associated to.</description>
        <inlineHelpText>The CRM account that the invoice is associated to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__BillingAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The Zuora billing account that the invoice is for.</description>
        <inlineHelpText>The Zuora billing account that the invoice is for.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>ZInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <description>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</description>
        <inlineHelpText>The status of the invoice in the system. This status is not the status of the payment of the invoice, just the status of the invoice itself.</inlineHelpText>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FC_TestZuoraZInvoiceHandler.cls
@isTest
private class FC_TestZuoraZInvoiceHandler {

    @isTest
    private static void testUpdate() {

        Zuora__ZInvoice__c testInvoice = [select Id, FC_Most_Recent_Payment_Processed_On__c from Zuora__ZInvoice__c where Name = 'TEST INVOICE' limit 1];

        System.assertEquals(null, testInvoice.FC_Most_Recent_Payment_Processed_On__c);

        fcf.TriggerHandlerSettings.enable('FC_ZuoraZInvoiceHandler');

        Test.startTest();
        update testInvoice;
        Test.stopTest();

        testInvoice = [select Id, FC_Most_Recent_Payment_Processed_On__c from Zuora__ZInvoice__c where Name = 'TEST INVOICE' limit 1];
        System.assertEquals(Date.today() - 2, testInvoice.FC_Most_Recent_Payment_Processed_On__c);

    }

    @testSetup
    private static void setup() {

        Account testAccount = new Account(Name = 'TEST ACCOUNT', BillingPostalCode = '12345');
        insert testAccount;

        Zuora__CustomerAccount__c testCustomerAccount = new Zuora__CustomerAccount__c(Name = 'TEST ACCOUNT', Zuora__Account__c = testAccount.Id);
        insert testCustomerAccount;

        Zuora__ZInvoice__c testInvoice = new Zuora__ZInvoice__c(Name = 'TEST INVOICE',
                Zuora__BillingAccount__c = testCustomerAccount.Id);
        insert testInvoice;

        Zuora__Payment__c[] testPayments = new Zuora__Payment__c[]{
                new Zuora__Payment__c(Name = 'TEST PROCESSED PAYMENT', Zuora__BillingAccount__c = testCustomerAccount.Id,
                        Zuora__Effective_Date__c = Date.today() - 2, Zuora__Status__c = 'Processed'),
                new Zuora__Payment__c(Name = 'TEST ERROR PAYMENT', Zuora__BillingAccount__c = testCustomerAccount.Id,
                        Zuora__Effective_Date__c = Date.today(), Zuora__Status__c = 'ERROR')
        };
        insert testPayments;

        Zuora__PaymentInvoice__c[] testPaymentInvoices = new Zuora__PaymentInvoice__c[]{
                new Zuora__PaymentInvoice__c(Zuora__ApplyAmount__c = 100, Zuora__Invoice__c = testInvoice.Id, Zuora__Payment__c = testPayments[0].Id),
                new Zuora__PaymentInvoice__c(Zuora__ApplyAmount__c = 100, Zuora__Invoice__c = testInvoice.Id, Zuora__Payment__c = testPayments[1].Id)
        };
        insert testPaymentInvoices;

    }

}